Repository daos-stack/daos, pull requests merged in 2022-05, with the labels that each got.

#8997 DAOS-10400 test: Supporting ucx testing in network/zero_config.py (#8…
  src/tests/ftest/network/zero_config.py
Labels: clean-cherry-pick

#8991 DAOS-9919, CORCI-1170, CORCI-1171 ci: Use Artifactory
  Jenkinsfile
  ci/junit.sh
  ci/provisioning/post_provision_config.sh
  ci/provisioning/post_provision_config_common.sh
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes.sh
  ci/provisioning/post_provision_config_nodes_EL_7.sh
  ci/provisioning/post_provision_config_nodes_EL_8.sh
  ci/provisioning/post_provision_config_nodes_LEAP_15.sh
  ci/rpm/build_unsuccessful.sh
  ci/rpm/test_daos_node.sh
  ci/stacktrace.sh
  utils/docker/Dockerfile.centos.7
  utils/docker/Dockerfile.el.8
  utils/docker/Dockerfile.leap.15
  utils/rpms/packaging/Dockerfile.centos.7
  utils/rpms/packaging/Dockerfile.mockbuild
  utils/rpms/packaging/Makefile_packaging.mk
  utils/rpms/packaging/rpm_chrootbuild
  utils/scripts/install-centos7.sh
  utils/scripts/install-leap15.sh
Labels: unclean-cherry-pick

#8813 DAOS-9592 pool: Introduce ds_pool_check_svc_clues
  src/include/daos_srv/pool.h
  src/pool/srv_pool_check.c
Labels: CR

#9075 DAOS-10526 control: Add block devices to topology scan (#8970)
  src/control/lib/hardware/hwloc/bindings.go
  src/control/lib/hardware/hwloc/provider.go
  src/control/lib/hardware/hwloc/provider_test.go
  src/control/lib/hardware/pci.go
  src/control/lib/hardware/pci_test.go
  src/control/lib/hardware/pretty.go
  src/control/lib/hardware/pretty_test.go
  src/control/lib/hardware/topology.go
Labels: clean-cherry-pick

#9023 DAOS-10465 vos: Avoid using aggregation optimization on v2.0 pool (#8953)
  src/container/srv_target.c
  src/include/daos_srv/pool.h
  src/include/daos_srv/vos.h
  src/include/daos_srv/vos_types.h
  src/object/obj_internal.h
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
  src/tests/vos_engine.c
  src/vos/tests/vts_common.c
  src/vos/vos_container.c
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_layout.h
  src/vos/vos_obj.c
  src/vos/vos_pool.c
  src/vos/vos_tree.c
Labels: unclean-cherry-pick

#9041 DAOS-9583 chk: interface for vos operations to trace check process
  src/chk/SConscript
  src/chk/chk_internal.h
  src/chk/chk_srv.c
  src/chk/chk_vos.c
  src/include/daos_srv/daos_chk.h
Labels: CR

#9095 DAOS-8495 test: Increase test timeout for pool/svc.py (#9012)
  src/tests/ftest/pool/svc.yaml
Labels: clean-cherry-pick

#9094 DAOS-10609 test: fix usage of time (#9049)
  src/tests/ftest/util/apricot/apricot/test.py
Labels: clean-cherry-pick

#9093 DAOS-623 pylint: disable consider-using-f-string (#9022)
  utils/sl/pylint3.rc
Labels: clean-cherry-pick

#9096 DAOS-8495 test: Increase test timeout for pool/svc.py (#9012)
  src/tests/ftest/pool/svc.yaml
Labels: clean-cherry-pick

#9113 DAOS-10397 test: Add ucx provider support to dmg_network_scan.py (#9025)
  src/tests/ftest/control/dmg_network_scan.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/network_utils.py
Labels: clean-cherry-pick

#9005 DAOS-10416 ddb: Processing and Clearing ilog and dtx
  src/ddb/ddb_cmd_options.c
  src/ddb/ddb_cmd_options.h
  src/ddb/ddb_commands.c
  src/ddb/ddb_main.c
  src/ddb/ddb_printer.c
  src/ddb/ddb_vos.c
  src/ddb/ddb_vos.h
  src/ddb/tests/ddb_cmd_options_tests.c
  src/ddb/tests/ddb_cmocka.h
  src/ddb/tests/ddb_commands_print_tests.c
  src/ddb/tests/ddb_commands_tests.c
  src/ddb/tests/ddb_smoke_tests.sh
  src/ddb/tests/ddb_test_driver.c
  src/ddb/tests/ddb_vos_tests.c
Labels: CR

#8470 DAOS-9592 rdb: Add rdb_dictate and its rsvc APIs
  src/include/daos_srv/rdb.h
  src/include/daos_srv/rsvc.h
  src/pool/srv_pool.c
  src/rdb/rdb.c
  src/rdb/rdb_internal.h
  src/rdb/rdb_raft.c
  src/rdb/tests/rdb_test.c
  src/rdb/tests/rdbt.c
  src/rdb/tests/rpc.c
  src/rdb/tests/rpc.h
  src/rsvc/rpc.h
  src/rsvc/srv.c
Labels: CR

#9134 DAOS-10500 test: nvme/health.py: increase pool capacity (#9066)
  src/tests/ftest/nvme/health.py
  src/tests/ftest/nvme/health.yaml
Labels: clean-cherry-pick

#9047 DAOS-9583 chk: DAOS check engine logic
  src/chk/SConscript
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_iv.c
  src/chk/chk_srv.c
  src/include/daos_errno.h
  src/include/daos_srv/daos_mgmt_srv.h
  src/include/daos_srv/vos_types.h
  src/mgmt/srv_target.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
Labels: CR

#9046 DAOS-9583 chk: DAOS check leader logic
  src/chk/SConscript
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_iv.c
  src/chk/chk_leader.c
  src/chk/chk_srv.c
  src/include/daos_errno.h
  src/include/daos_srv/daos_chk.h
  src/include/daos_srv/daos_mgmt_srv.h
  src/include/daos_srv/vos_types.h
  src/mgmt/srv_target.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
Labels: CR

#9045 DAOS-9583 chk: common logic for DAOS check
  src/chk/SConscript
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_iv.c
  src/chk/chk_leader.c
  src/chk/chk_srv.c
  src/include/daos/btree_class.h
  src/include/daos_errno.h
  src/include/daos_srv/daos_chk.h
  src/include/daos_srv/daos_mgmt_srv.h
  src/include/daos_srv/vos_types.h
  src/mgmt/srv_target.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
Labels: CR

#9044 DAOS-9589 chk: DAOS check IV
  src/chk/SConscript
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_iv.c
  src/chk/chk_leader.c
  src/chk/chk_srv.c
  src/include/daos/btree_class.h
  src/include/daos_errno.h
  src/include/daos_srv/daos_chk.h
  src/include/daos_srv/daos_mgmt_srv.h
  src/include/daos_srv/iv.h
  src/include/daos_srv/vos_types.h
  src/mgmt/srv_target.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
Labels: CR

#9043 DAOS-9583 chk: DAOS check dRPC upcall
  Jenkinsfile
  src/chk/SConscript
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_iv.c
  src/chk/chk_leader.c
  src/chk/chk_srv.c
  src/chk/chk_upcall.c
  src/engine/drpc_ras.c
  src/include/daos/btree_class.h
  src/include/daos_errno.h
  src/include/daos_srv/daos_chk.h
  src/include/daos_srv/daos_mgmt_srv.h
  src/include/daos_srv/iv.h
  src/include/daos_srv/ras.h
  src/include/daos_srv/vos_types.h
  src/include/daos_types.h
  src/mgmt/srv_target.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
Labels: CR

#9042 DAOS-9583 chk: DAOS check RPC
  src/chk/SConscript
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_iv.c
  src/chk/chk_leader.c
  src/chk/chk_rpc.c
  src/chk/chk_srv.c
  src/chk/chk_upcall.c
  src/common/proc.c
  src/engine/drpc_ras.c
  src/include/daos/btree_class.h
  src/include/daos/common.h
  src/include/daos/rpc.h
  src/include/daos_errno.h
  src/include/daos_srv/daos_chk.h
  src/include/daos_srv/daos_mgmt_srv.h
  src/include/daos_srv/iv.h
  src/include/daos_srv/pool.h
  src/include/daos_srv/ras.h
  src/include/daos_srv/vos_types.h
  src/include/daos_types.h
  src/mgmt/srv_target.c
  src/object/obj_rpc.c
  src/pool/srv_pool_check.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
Labels: CR

#9048 DAOS-9583 mgmt: dRPC downcall interfaces for DAOS check
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_iv.c
  src/chk/chk_leader.c
  src/chk/chk_rpc.c
  src/chk/chk_srv.c
  src/chk/chk_vos.c
  src/engine/drpc_ras.c
  src/engine/init.c
  src/engine/server_iv.c
  src/include/daos_srv/daos_chk.h
  src/include/daos_srv/daos_engine.h
  src/include/daos_srv/daos_mgmt_srv.h
  src/include/daos_srv/iv.h
  src/include/daos_srv/vos_types.h
  src/mgmt/SConscript
  src/mgmt/srv_chk.c
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_target.c
  src/mgmt/tests/mocks.c
  src/mgmt/tests/srv_drpc_tests.c
  src/pool/srv_pool.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
Labels: CR

#9122 DAOS-9592 chk: pool list consolidation
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_leader.c
  src/dtx/dtx_srv.c
  src/engine/init.c
  src/include/daos_srv/daos_mgmt_srv.h
  src/mgmt/srv_pool.c
  src/pool/srv.c
  src/pool/srv_pool_check.c
  src/vos/vos_layout.h
Labels: CR

#9206 DAOS-10677 test: Backport for #9173 to suppress MPI leak
  utils/test_memcheck.supp
Labels: unclean-cherry-pick

#9205 DAOS-10677 test: Backport for #9173 to suppress MPI leak
  utils/test_memcheck.supp
Labels: unclean-cherry-pick
