Repository daos-stack/daos, pull requests merged in 2022-12, with the labels that each got.

#10936 DAOS-12079 test: Move HW Small tests to HW Medium (#10851)
  src/tests/ftest/aggregation/dfuse_space_check.py
  src/tests/ftest/container/fill_destroy_loop.py
  src/tests/ftest/container/full_pool_container_create.py
  src/tests/ftest/control/config_generate_output.py
  src/tests/ftest/control/config_generate_run.py
  src/tests/ftest/control/daos_admin_privileged.py
  src/tests/ftest/control/dmg_network_scan.py
  src/tests/ftest/control/dmg_pool_query_test.py
  src/tests/ftest/control/dmg_storage_query.py
  src/tests/ftest/control/dmg_storage_scan_scm.py
  src/tests/ftest/control/dmg_system_reformat.py
  src/tests/ftest/control/dmg_telemetry_io_basic.py
  src/tests/ftest/control/dmg_telemetry_nvme.py
  src/tests/ftest/control/ssd_socket.py
  src/tests/ftest/daos_perf/small.py
  src/tests/ftest/daos_vol/bigio.py
  src/tests/ftest/daos_vol/h5_suite.py
  src/tests/ftest/datamover/copy_procs.py
  src/tests/ftest/datamover/negative_space.py
  src/tests/ftest/dfuse/bash.py
  src/tests/ftest/dfuse/daos_build.py
  src/tests/ftest/dfuse/root_container.py
  src/tests/ftest/dfuse/sparse_file.py
  src/tests/ftest/harness/advanced.py
  src/tests/ftest/harness/basic.py
  src/tests/ftest/harness/config.py
  src/tests/ftest/harness/setup.py
  src/tests/ftest/harness/setup_hw.py
  src/tests/ftest/harness/slurm.py
  src/tests/ftest/harness/timeout.py
  src/tests/ftest/ior/intercept_basic.py
  src/tests/ftest/ior/intercept_messages.py
  src/tests/ftest/mpiio/hdf5.py
  src/tests/ftest/mpiio/romio.py
  src/tests/ftest/server/cpu_usage.py
  src/tests/ftest/server/daos_server_config.py
Labels: unclean-cherry-pick, release-2.4

#10875 DAOS-12081 test: Removing HW Small stage.
  Jenkinsfile
Labels: release-2.4, priority

#10723 DAOS-11466 test: performance test improvements (#10110)
  src/tests/ftest/deployment/basic_checkout.py
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/ior_hard.yaml
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/performance/mdtest_hard.yaml
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/mdtest_utils.py
  src/tests/ftest/util/oclass_utils.py
  src/tests/ftest/util/performance_test_base.py
Labels: unclean-cherry-pick, priority, forced-landing

#10942 DAOS-12167 test: remove ftest/ior/intercept_verify_data_integrity (#1…
  src/tests/ftest/ior/intercept_verify_data_integrity.py
  src/tests/ftest/ior/intercept_verify_data_integrity.yaml
Labels: clean-cherry-pick, priority, forced-landing

#10951 DAOS-12058 common: Integrating BMEM with WAL
  src/common/dav/dav.h
  src/common/dav/dav_iface.c
  src/common/dav/dav_internal.h
  src/common/dav/memblock.c
  src/common/dav/mo_wal.h
  src/common/dav/tx.c
  src/common/dav/wal_tx.c
  src/common/dav/wal_tx.h
  src/common/mem.c
  utils/run_test.sh
Labels: release-2.4, priority

#10938 DAOS-12084 test: Removing HW Small stage
  Jenkinsfile
Labels: release-2.4

#10954 DAOS-12119 control: Handle ErrPoolNotFound on retried PoolDestroy (#10873)
  src/control/common/proto/error.go
  src/control/common/proto/error_test.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/control/response.go
  src/control/lib/control/rpc.go
  src/control/server/mgmt_pool.go
  src/control/system/database.go
  src/control/system/errors.go
Labels: unclean-cherry-pick

#10335 DAOS-10659 test: Remove extra container created by ior/hard_rebuild.p…
  src/tests/ftest/ior/hard_rebuild.py
Labels: priority

#10171 DAOS-11265 test: Wait 1 min after bringing up the network in deployme…
  src/tests/ftest/deployment/network_failure.py
Labels: clean-cherry-pick, priority

#10843 DAOS-10602 build,bio,control: Enable engine to emulate VMD hotplug via SPDK RPC
  debian/changelog
  debian/control
  src/bio/bio_config.c
  src/bio/bio_device.c
  src/bio/bio_internal.h
  src/bio/bio_xstream.c
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/common/proto/ctl/smd.pb.go
  src/control/server/engine/config.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend_class.go
  src/control/server/storage/bdev/backend_class_test.go
  src/control/server/storage/bdev/backend_json.go
  src/control/server/storage/bdev/backend_json_test.go
  src/control/server/storage/config.go
  src/control/server/storage/provider.go
  src/control/server/storage/provider_test.go
  src/include/daos_srv/control.h
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_query.c
  src/proto/ctl/smd.proto
  utils/build.config
  utils/rpms/daos.spec
Labels: vmd

#10792 DAOS-7821 build: Add a gofmt githook
  utils/githooks/pre-commit.d/40-gofmt.sh
Labels: forced-landing

#10963 DAOS-12063 object: reset kds and recxs for each shard (#10834)
  src/object/cli_obj.c
Labels: release-2.4

#10947 DAOS-11880 engine: Scale size of metrics shmem region
  src/engine/init.c
  src/include/gurt/telemetry_common.h
Labels: forced-landing

#10956 DAOS-12155 cart: Fix iv test cleanup stage (#10932)
  src/tests/ftest/cart/iv/iv_one_node.py
  src/tests/ftest/cart/iv/iv_two_node.py
  src/tests/ftest/cart/util/cart_utils.py
Labels: priority

#10927 DAOS-11605 ad_mem: fix a bug in free space tracking
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
  src/common/tests/ad_mem_tests.c
  src/include/daos_srv/ad_mem.h
Labels: release-2.4, priority

#10886 DAOS-12060 doc: Describe daos_server.yml changes for MD on SSD
  docs/admin/deployment.md
  utils/config/daos_server.yml
  utils/config/examples/daos_server_mdonssd.yml
Labels: release-2.4, priority

#10832 DAOS-12031 client: checking access mode for root object open
  src/client/dfs/dfs.c
  src/client/pydaos/raw/daos_api.py
  src/object/cli_obj.c
  src/object/obj_rpc.h
  src/pool/cli.c
  src/tests/suite/daos_aggregate_ec.c
  src/tests/suite/daos_capa.c
  src/tests/suite/daos_checksum.c
  src/tests/suite/daos_container.c
  src/tests/suite/daos_dedup.c
  src/tests/suite/daos_dist_tx.c
  src/tests/suite/daos_kv.c
  src/tests/suite/daos_obj.c
  src/tests/suite/daos_obj_array.c
  src/tests/suite/daos_obj_ec.c
  src/utils/daos_autotest.c
  src/utils/daos_hdlr.c
Labels: release-2.4, priority

#10948 DAOS-12113 pool: hold dp_map_lock when access pool map (#10887)
  src/container/cli.c
  src/object/obj_tx.c
  src/pool/cli.c
Labels: clean-cherry-pick, release-2.2

#10971 DAOS-12185 cart: Disable CRT_CTX_SHARE_ADDR=1 for UCX.
  src/cart/crt_init.c
Labels: release-2.4, priority

#10914 DAOS-11605 common: some bug fixes for AD IO test
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
  src/vos/tests/vts_common.c
  src/vos/tests/vts_common.h
  src/vos/tests/vts_io.c
  src/vos/tests/vts_pool.c
Labels: release-2.4, priority, meta-on-ssd

#10008 DAOS-9218 test: data-mover erasure code support
  src/gurt/tests/test_gurt.c
  src/include/gurt/list.h
  src/object/cli_obj.c
  src/tests/ftest/deployment/io_sys_admin.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/file_count_test_base.py
  src/tests/suite/daos_obj.c
  src/tests/suite/daos_obj_ec.c
  utils/ansible/ftest/templates/daos-make.sh.j2
  utils/ansible/ftest/vars/Rocky8.yml
Labels: release-2.4, priority

#11020 DAOS-12253 packaging: Update packaging/ subdir
  utils/rpms/packaging/Dockerfile.mockbuild
  utils/rpms/packaging/Dockerfile.ubuntu.20.04
  utils/rpms/packaging/Makefile_packaging.mk
  utils/rpms/packaging/debian_chrootbuild
  utils/rpms/packaging/rpm_chrootbuild
Labels: forced-landing

#10998 DAOS-7420 test: Enable two online reintegration test.
  src/tests/ftest/osa/online_reintegration.py
Labels: release-2.4, priority

#10980 DAOS-11401 vos: complete umem_store callbacks
  src/bio/bio_wal.c
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/include/daos/mem.h
  src/include/daos_srv/bio.h
  src/vos/vos_pool.c
Labels: release-2.4, priority

#11027 DAOS-12255 control: Correct hugepage affinity with multi-engine-per-NUMA
  src/control/fault/code/codes.go
  src/control/server/faults.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
Labels: control-plane, release-2.4, forced-landing

#11003 DAOS-12214 tests: VOS unit tests for WAL
  src/bio/bio_wal.c
  src/vos/tests/SConscript
  src/vos/tests/vos_tests.c
  src/vos/tests/vts_common.h
  src/vos/tests/vts_wal.c
Labels: release-2.4, priority

#10981 DAOS-12058 common: Fixed leaks in BMEM WAL reserve/commit.
  src/common/dav/out.h
  src/common/dav/tx.c
Labels: release-2.4, priority

#11044 DAOS-12254 ucx: UCX initialization failing because of change to CI system configuration.
  src/control/lib/hardware/ucx/bindings.go
Labels: clean-cherry-pick, release-2.2, priority

#11042 DAOS-12265 control: Fix SPDK include path symlink for dev setup (#11032)
  utils/setup_daos_admin.sh
Labels: clean-cherry-pick, release-2.2

#11019 DAOS-12229 bio: Fixed several coverity issues
  src/bio/bio_config.c
  src/bio/bio_device.c
Labels: release-2.4, priority

#11016 DAOS-11412 bio: WAL metrics
  src/bio/bio_buffer.c
  src/bio/bio_internal.h
  src/bio/bio_wal.c
  src/bio/bio_wal.h
  src/bio/bio_xstream.c
  src/common/debug.c
  src/include/daos/debug.h
  src/include/daos_srv/bio.h
  src/tests/ftest/util/telemetry_utils.py
Labels: release-2.4, priority

#11028 DAOS-11437 test: Support multiple IP addresses per node for test_netw…
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/network_failure.yaml
Labels: clean-cherry-pick

#11031 DAOS-9218 test: data-mover erasure code support (#10008)
  src/gurt/tests/test_gurt.c
  src/include/gurt/list.h
  src/object/cli_obj.c
  src/tests/ftest/deployment/io_sys_admin.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/file_count_test_base.py
  src/tests/suite/daos_obj.c
  src/tests/suite/daos_obj_ec.c
Labels: unclean-cherry-pick, priority

#11046 DAOS-12257 pool: create logging with log_mask: INFO and DEBUG
  src/mgmt/srv_pool.c
  src/mgmt/srv_target.c
Labels: forced-landing

#10925 DAOS-11192 test: simplify ior/crash subprocess checking
  src/tests/ftest/ior/crash.py
  src/tests/ftest/util/ior_test_base.py
Labels: forced-landing

#10885 DAOS-10854 test: verify multi-user dfuse permissions
  src/tests/ftest/dfuse/mu_mount.py
  src/tests/ftest/dfuse/mu_mount.yaml
  src/tests/ftest/dfuse/mu_perms.py
  src/tests/ftest/dfuse/mu_perms.yaml
  src/tests/ftest/dfuse/multi_user.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/user_utils.py
  src/tests/ftest/util/verify_perms.py
Labels: release-2.4, priority

#10943 DAOS-11975 test: replace dfuse_utils pcmd with run_remote (#10696)
  src/tests/ftest/dfuse/caching_check.py
  src/tests/ftest/dfuse/root_container.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/run_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: unclean-cherry-pick, release-2.4, priority, forced-landing

#11062 DAOS-12076 test: Automate multiple engines/sockets (2 engines per socket, total 4 engines)
  src/tests/ftest/server/multiengine_persocket.yaml
Labels: release-2.4, priority

#11054 DAOS-11517 test: deployment/network_failure.py - Create pool across 4…
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/network_failure.yaml
Labels: clean-cherry-pick, priority

#11055 DAOS-11602 vos: fix some DTX visibility issues
  src/vos/vos_dtx.c
Labels: clean-cherry-pick, release-2.2

#10662 DAOS-11192 test: simplify ior/crash subprocess checking (#10925)
  src/tests/ftest/ior/crash.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/server_utils.py
Labels: unclean-cherry-pick

#11025 DAOS-12185 cart: Prevent shared address configuration for UCX.
  src/cart/crt_init.c
Labels: release-2.4, priority

#11058 DAOS-12091 dtx: commit DTX on remote participants before local
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos/dtx.h
  src/include/daos_srv/vos.h
  src/include/daos_srv/vos_types.h
  src/object/obj_tx.c
  src/object/srv_obj.c
  src/vos/vos_dtx.c
Labels: clean-cherry-pick

#11095 DAOS-12296 common: Fix Intel compiler warnings
  src/common/btree.c
  src/tests/suite/daos_iotest.h
  src/tests/suite/daos_test.h
  src/vos/evt_priv.h
  src/vos/vos_aggregate.c
  src/vos/vos_internal.h
Labels: release-2.4, priority

#11096 DAOS-12296 common: Fix Intel compiler warnings (#11095)
  src/common/btree.c
  src/tests/suite/daos_iotest.h
  src/tests/suite/daos_test.h
  src/vos/evt_priv.h
  src/vos/vos_aggregate.c
  src/vos/vos_internal.h
Labels: clean-cherry-pick

#11061 DAOS-12260 vos: Fix bug where uncommitted update can be removed (#11038)
  src/vos/tests/vts_pm.c
  src/vos/vos_ilog.c
Labels: unclean-cherry-pick, release-2.2

#11080 SRE-416 test: Fix Launchable xunit1 de-mangle
  src/tests/ftest/launch.py
Labels: forced-landing

#11101 DAOS-12257 test: increase tmpfs scm_size in some tests
  src/tests/ftest/control/daos_object_query.yaml
  src/tests/ftest/object/create_many_dkeys.yaml
  src/tests/ftest/object/integrity.yaml
Labels: forced-landing

#11017 DAOS-11605 common: a few refine for AD mem
  src/common/ad_mem.c
  src/common/ad_mem.h
Labels: release-2.4, priority

#11049 DAOS-11126 test: add unit test for DAOS-10748
  src/bio/bio_buffer.c
  src/include/daos/common.h
  src/vos/tests/vts_io.c
Labels: release-2.4, priority

#11087 DAOS-12298 test: fix verify_perms.py typo and cd
  src/tests/ftest/util/verify_perms.py
Labels: forced-landing
