Repository daos-stack/daos, pull requests merged in 2022-11, with the labels that each got.

#10558 DAOS-11146 object: cache dc_pool and dc_cont
  src/container/cli.c
  src/container/cli_internal.h
  src/include/daos/container.h
  src/include/daos/pool.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/object/obj_tx.c
  src/object/obj_verify.c
  src/pool/cli.c
  src/pool/cli_internal.h
Labels: release-2.4, priority

#3956 DAOS-6540 dfuse: Enable multi-user support in dfuse
  docs/admin/deployment.md
  docs/user/filesystem.md
  src/client/dfs/duns.c
  src/client/dfuse/dfuse.h
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/dfuse_main.c
  src/client/dfuse/ops/create.c
  src/tests/ftest/dfuse/multi_user.py
  src/tests/ftest/dfuse/multi_user.yaml
  src/tests/ftest/scripts/setup_nodes.sh
  src/tests/ftest/util/dfuse_utils.py
  utils/node_local_test.py
Labels: release-2.4, priority

#10629 DAOS-11946 test: Fix control/config_generate_run.py error
  src/tests/ftest/control/config_generate_run.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/server_utils_params.py
Labels: forced-landing

#10634 DAOS-9221 test: remove self._env_names
  src/tests/ftest/daos_racer/multi.py
  src/tests/ftest/daos_racer/parallel.py
  src/tests/ftest/daos_racer/simple.py
  src/tests/ftest/erasurecode/rank_failure.py
  src/tests/ftest/io/unaligned_io.py
  src/tests/ftest/osa/online_extend.py
  src/tests/ftest/osa/online_parallel_test.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/rebuild/io_conf_run.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/daos_io_conf.py
  src/tests/ftest/util/daos_perf_base.py
  src/tests/ftest/util/daos_perf_utils.py
  src/tests/ftest/util/daos_racer_utils.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/macsio_test_base.py
  src/tests/ftest/util/macsio_util.py
  src/tests/ftest/util/mdtest_utils.py
  src/tests/ftest/util/soak_utils.py
  utils/cq/words.dict
Labels: forced-landing

#10635 DAOS-623 test: remove dead ior_test_base code
  src/tests/ftest/util/ior_test_base.py
Labels: forced-landing

#10617 DAOS-11685 dtx: handle DTX abort by race
  src/dtx/dtx_common.c
  src/dtx/dtx_rpc.c
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/vos/vos_dtx.c
Labels: release-2.2, release-2.4

#10672 DAOS-11408 bio: WAL APIs for replay & checkpoint
  src/bio/bio_wal.c
  src/include/daos_srv/bio.h
Labels: release-2.4, priority

#9978 DAOS-10289 bio: tuneable SPDK subsystem fini timeout (#8705)
  src/bio/bio_xstream.c
Labels: clean-cherry-pick, release-2.4

#10557 DAOS-11605 common: provide umem_ops_t table for ADMEM
  src/bio/bio_buffer.c
  src/bio/bio_context.c
  src/bio/bio_internal.h
  src/bio/bio_wal.c
  src/bio/bio_xstream.c
  src/common/SConscript
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
  src/common/btree_class.c
  src/common/mem.c
  src/common/tests/SConscript
  src/include/daos/mem.h
  src/include/daos_srv/ad_mem.h
  src/include/daos_srv/bio.h
  src/vea/vea_alloc.c
  src/vea/vea_api.c
  src/vea/vea_free.c
  src/vea/vea_hint.c
  src/vos/vos_aggregate.c
  src/vos/vos_gc.c
  src/vos/vos_io.c
Labels: release-2.4, priority, meta-on-ssd

#10512 DAOS-11870 object: log data inconsistency as D_WARN
  src/object/cli_obj.c
  src/object/obj_verify.c
  src/object/srv_obj.c
Labels: release-2.4

#10679 DAOS-11949 tests: Do not kill all replicas
  src/tests/suite/daos_rebuild.c
Labels: release-2.4, priority

#10549 DAOS-11639 test: Do not install slurm on VM stage (#10428)
  src/tests/ftest/scripts/main.sh
Labels: clean-cherry-pick

#10705 DAOS-11981 tools: Check rc in label prop handler
  src/control/cmd/daos/property.go
Labels: forced-landing

#10715 DAOS-11959 control: Improve server/engine unit tests (#10682)
  src/control/server/engine/exec_test.go
Labels: forced-landing

#10667 DAOS-11724 test: pool/svc.py - Update the number of ranks to stop (#1…
  src/tests/ftest/pool/svc.py
Labels: clean-cherry-pick, priority

#10595 DAOS-11761 mgmt: Fix retried pool destroys
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/include/daos_srv/pool.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_pool.c
  src/mgmt/srv_target.c
  src/pool/srv_pool.c
Labels: forced-landing

#10731 DAOS-11605 common: free blob on destroy
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/tests/ad_mem_tests.c
Labels: release-2.4, priority

#10613 DAOS-11635 doc: fixes to QSG setup guide (#10582)
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
Labels: unclean-cherry-pick, release-2.2, priority

#10320 DAOS-11269 test: Update pipeline-lib to enable soak-branch (#9911)
  ci/provisioning/post_provision_config_common_functions.sh
  ftest.sh
  src/tests/ftest/launch.py
  src/tests/ftest/scripts/main.sh
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/soak/faults.py
  src/tests/ftest/soak/harassers.py
  src/tests/ftest/soak/smoke.py
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress_2h.py
  src/tests/ftest/soak/stress_2h.yaml
  src/tests/ftest/soak/stress_48h.py
  src/tests/ftest/soak/stress_48h.yaml
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: clean-cherry-pick, release-2.4

#10729 DAOS-11390 control: Refactor mount logic
  src/control/cmd/daos_server/storage_legacy_test.go
  src/control/cmd/daos_server/storage_scm_test.go
  src/control/cmd/daos_server_helper/handler.go
  src/control/cmd/daos_server_helper/handler_test.go
  src/control/fault/code/codes.go
  src/control/provider/system/mocks.go
  src/control/provider/system/system.go
  src/control/provider/system/system_linux.go
  src/control/provider/system/system_linux_test.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/ctl_storage_test.go
  src/control/server/ctl_svc_test.go
  src/control/server/harness_test.go
  src/control/server/instance_storage_test.go
  src/control/server/instance_superblock_test.go
  src/control/server/server_utils_test.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/runner.go
  src/control/server/storage/device.go
  src/control/server/storage/faults.go
  src/control/server/storage/mocks.go
  src/control/server/storage/mount.go
  src/control/server/storage/mount/provider.go
  src/control/server/storage/mount/provider_test.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm/faults.go
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/mocks.go
  src/control/server/storage/scm/provider.go
  src/control/server/storage/scm/provider_test.go
Labels: release-2.4, priority, forced-landing

#10719 DAOS-11885 bio: remove umem from bio_io_context
  src/bio/bio_buffer.c
  src/bio/bio_context.c
  src/bio/bio_internal.h
  src/bio/bio_wal.c
  src/bio/bio_xstream.c
  src/include/daos_srv/bio.h
  src/include/daos_srv/vea.h
  src/vea/vea_api.c
  src/vos/vos_aggregate.c
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_obj.c
  src/vos/vos_pool.c
  src/vos/vos_pool_scrub.c
Labels: release-2.4, priority

#10716 DAOS-11887 test: Remove control/dmg_system_leader_query
  src/tests/ftest/control/dmg_system_leader_query.py
  src/tests/ftest/control/dmg_system_leader_query.yaml
Labels: forced-landing

#10726 DAOS-11999 test: adjust ior_test_base to use mpi_type from yaml
  src/tests/ftest/aggregation/multiple_pool_cont.py
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/ior/intercept_verify_data_integrity.py
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/util/ior_test_base.py
Labels: forced-landing

#10619 DAOS-623 test: remove MappedParameter
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/data_mover_test_base.py
  utils/cq/words.dict
Labels: forced-landing

#10490 DAOS-11828 dtx: handle excluded participant as prepared when DTX resync
  src/dtx/dtx_rpc.c
Labels: release-2.4, priority

#10569 DAOS-11679 dtx: bulk transfer for large CPD RPC body
  src/object/obj_rpc.c
  src/object/obj_rpc.h
  src/object/obj_tx.c
  src/object/srv_internal.h
  src/object/srv_obj.c
  src/object/srv_obj_remote.c
Labels: release-2.4, priority

#10594 DAOS-11924 dtx: handle race among DTX commit and DTX refresh
  src/dtx/dtx_rpc.c
  src/vos/vos_dtx.c
Labels: release-2.4, priority

#10714 DAOS-11943 objects: online extending fixes
  src/common/pool_map.c
  src/include/daos/pool_map.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/srv_obj_remote.c
  src/placement/jump_map.c
  src/placement/pl_map.h
  src/placement/pl_map_common.c
  src/placement/tests/jump_map_place_obj.c
  src/pool/srv_pool.c
  src/pool/srv_pool_map.c
  src/pool/srv_target.c
  src/rebuild/srv.c
  src/tests/suite/daos_extend_simple.c
Labels: release-2.4, priority

#10627 DAOS-11396 control: Enable hugepage support for tmpfs (#10566)
  src/control/server/config/server_test.go
  src/control/server/storage/config.go
  src/control/server/storage/mocks.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm/provider.go
  src/control/server/storage/scm/provider_test.go
  src/tests/ftest/pool/create_all_vm.yaml
  src/tests/ftest/util/server_utils_params.py
  utils/config/daos_server.yml
Labels: release-2.4, priority

#10755 DAOS-11989 test: dmg --size may not be mixed with --tier-ratio
  src/tests/ftest/pool/autotest.yaml
Labels: forced-landing

#10754 DAOS-11761 mgmt: Fix retried pool destroys (#10595)
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/include/daos_srv/pool.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_pool.c
  src/mgmt/srv_target.c
  src/pool/srv_pool.c
Labels: unclean-cherry-pick, priority

#10780 DAOS-4713 bio: introduce retry-able DER_NVME_IO (#10589)
  src/bio/bio_buffer.c
  src/bio/bio_internal.h
  src/bio/bio_monitor.c
  src/bio/bio_recovery.c
  src/bio/bio_xstream.c
  src/include/daos_errno.h
  src/object/cli_obj.c
  src/object/obj_internal.h
Labels: unclean-cherry-pick, meta-on-ssd

#10727 DAOS-11981 tools: Check rc in label prop handler (#10705)
  src/control/cmd/daos/property.go
Labels: priority

#10775 DAOS-11907 dfs: check passed in object classes if they satisfy the RF
  src/client/dfs/dfs.c
  src/include/daos/object.h
  src/object/cli_obj.c
  src/object/obj_class.c
Labels: priority, forced-landing

#10758 DAOS-11885 bio: extended bio_nvme_configured()
  src/bio/bio_context.c
  src/bio/bio_xstream.c
  src/bio/smd/smd_internal.h
  src/engine/srv.c
  src/engine/srv_internal.h
  src/include/daos_srv/bio.h
  src/include/daos_srv/smd.h
  src/vos/vos_common.c
  src/vos/vos_pool.c
Labels: release-2.4, priority, meta-on-ssd

#10183 DAOS-11297 test: Support multiple ranks for check_rank_state() (#9969)
  src/tests/ftest/deployment/critical_integration.py
  src/tests/ftest/util/server_utils.py
Labels: clean-cherry-pick, priority

#10774 DAOS-12011 test: setup fuse3.conf
  src/tests/ftest/launch.py
  src/tests/ftest/scripts/setup_nodes.sh
Labels: priority, forced-landing

#10750 DAOS-11605 common: generate tx_add redo acts
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
  src/common/tests/ad_mem_tests.c
  src/include/daos/mem.h
  src/include/daos_srv/ad_mem.h
Labels: release-2.4, priority, meta-on-ssd

#10783 DAOS-11538 chk: misc fixes for chk related issues - III
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_leader.c
  src/include/daos_srv/daos_mgmt_srv.h
  src/mgmt/srv_pool.c
  src/pool/srv_pool_check.c
Labels: CR

#10446 DAOS-10138 chk: Schedule PS reconf before DONE
  src/chk/chk_engine.c
  src/include/daos_srv/pool.h
  src/pool/srv_pool.c
  src/rsvc/srv.c
Labels: CR

#10796 DAOS-11284 test: Disk Failure Testing. (#10468)
  src/tests/ftest/deployment/disk_failure.py
  src/tests/ftest/deployment/disk_failure.yaml
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/osa_utils.py
Labels: clean-cherry-pick

#10766 DAOS-12020 vos: cancel deferred nvme list unconditionally
  src/vos/vos_common.c
Labels: release-2.4, priority

#10787 DAOS-12008 ci: Fix missing whitespace
  Jenkinsfile
Labels: release-2.4, forced-landing

#10660 DAOS-11149 pool: bump GC ULT stack size (#9924)
  src/pool/srv_target.c
Labels: unclean-cherry-pick, priority

#10712 DAOS-11605 common: add arena free memory management
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
  src/common/tests/ad_mem_tests.c
Labels: release-2.4, priority, meta-on-ssd

#10779 DAOS-11952 rebuild: Do not need migration query/stop for reclaim
  src/include/daos/common.h
  src/object/srv_obj_migrate.c
  src/rebuild/srv.c
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/daos_rebuild_simple.c
Labels: release-2.4, priority

#10470 DAOS-11811 control: Tighten up permissions of dRPC socket files
  src/common/drpc.c
  src/common/tests/common-mock-ld-opts
  src/common/tests/test_mocks.c
  src/control/cmd/daos_agent/start.go
  src/control/cmd/drpc_test/main.go
  src/control/drpc/README.md
  src/control/drpc/drpc_server.go
  src/control/drpc/drpc_server_test.go
  src/control/server/drpc.go
  src/engine/tests/drpc_client_tests.c
  src/include/daos/test_mocks.h
Labels: release-2.2, forced-landing

#10614 DAOS-11634 doc: misc doc improvements (#10585)
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
  docs/QSG/tour.md
  docs/testing/datamover.md
  docs/testing/ior.md
Labels: unclean-cherry-pick, release-2.2, priority

#10786 DAOS-12038 dfs: add file_oclass option for DFS container creation
  src/client/dfs/README.md
  src/client/dfs/dfs.c
  src/client/dfs/duns.c
  src/control/cmd/daos/container.go
  src/include/daos_fs.h
  src/include/daos_uns.h
  src/utils/daos_hdlr.c
  src/utils/daos_hdlr.h
  utils/node_local_test.py
Labels: release-2.4, priority, forced-landing

#10782 DAOS-11885 bio: prepare umem_store
  src/bio/bio_buffer.c
  src/bio/bio_context.c
  src/bio/bio_internal.h
  src/bio/bio_wal.c
  src/bio/bio_xstream.c
  src/bio/smd/smd_store.c
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
  src/common/mem.c
  src/common/tests/ad_mem_tests.c
  src/common/tests/utest_common.c
  src/include/daos/mem.h
  src/include/daos_srv/ad_mem.h
  src/include/daos_srv/bio.h
  src/include/daos_srv/vos.h
  src/mgmt/srv_target.c
  src/vea/tests/vea_stress.c
  src/vea/tests/vea_ut.c
  src/vos/sys_db.c
  src/vos/vos_aggregate.c
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_obj.c
  src/vos/vos_pool.c
  src/vos/vos_pool_scrub.c
Labels: release-2.4, priority

#10785 DAOS-11605 common: arena overflow
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/tests/ad_mem_tests.c
Labels: release-2.4, priority

#10768 DAOS-12015 control,bio: Add timeout option to LED identify command
  docs/admin/administration.md
  src/bio/bio_device.c
  src/bio/bio_internal.h
  src/bio/bio_xstream.c
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/lib/control/server_meta.go
  src/control/lib/control/server_meta_test.go
  src/include/daos_srv/bio.h
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_query.c
  src/mgmt/tests/srv_drpc_tests.c
  src/proto/ctl/smd.proto
Labels: release-2.4

#10823 DAOS-11811 control: Tighten up permissions of dRPC socket files (#10470)
  src/common/drpc.c
  src/common/tests/common-mock-ld-opts
  src/common/tests/test_mocks.c
  src/control/cmd/daos_agent/start.go
  src/control/cmd/drpc_test/main.go
  src/control/drpc/README.md
  src/control/drpc/drpc_server.go
  src/control/drpc/drpc_server_test.go
  src/control/server/drpc.go
  src/engine/tests/drpc_client_tests.c
  src/include/daos/test_mocks.h
Labels: unclean-cherry-pick, release-2.2

#10788 DAOS-11390 control: refactor mount logic (#10729)
  src/control/cmd/daos_server/storage_legacy_test.go
  src/control/cmd/daos_server/storage_scm_test.go
  src/control/cmd/daos_server_helper/handler.go
  src/control/cmd/daos_server_helper/handler_test.go
  src/control/fault/code/codes.go
  src/control/provider/system/mocks.go
  src/control/provider/system/system.go
  src/control/provider/system/system_linux.go
  src/control/provider/system/system_linux_test.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/ctl_storage_test.go
  src/control/server/ctl_svc_test.go
  src/control/server/harness_test.go
  src/control/server/instance_storage_test.go
  src/control/server/instance_superblock_test.go
  src/control/server/server_utils_test.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/runner.go
  src/control/server/storage/device.go
  src/control/server/storage/faults.go
  src/control/server/storage/mocks.go
  src/control/server/storage/mount.go
  src/control/server/storage/mount/provider.go
  src/control/server/storage/mount/provider_test.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm/faults.go
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/mocks.go
  src/control/server/storage/scm/provider.go
  src/control/server/storage/scm/provider_test.go
Labels: unclean-cherry-pick, release-2.4, priority, meta-on-ssd

#10076 DAOS-10880 control: Don't use multirail with UCX
  src/control/lib/hardware/ucx/ucx.go
  src/control/lib/hardware/ucx/ucx_test.go
Labels: clean-cherry-pick, release-2.2, priority, forced-landing

#10772 DAOS-11679 dtx: misc patch for dtx related issues - b22
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
  src/include/daos_srv/dtx_srv.h
  src/include/daos_srv/vos.h
  src/object/srv_obj_remote.c
  src/vos/tests/vts_dtx.c
  src/vos/vos_dtx.c
  src/vos/vos_tls.h
Labels: unclean-cherry-pick, release-2.2

#10435 DAOS-11274 cart: Fix swim paranoia (#10378)
  src/cart/crt_swim.c
  src/cart/swim/swim.c
  src/cart/swim/swim_internal.h
  src/include/cart/swim.h
  src/tests/ftest/cart/test_swim.c
  src/tests/ftest/cart/test_swim_emu.c
  src/tests/ftest/cart/test_swim_net.c
Labels: unclean-cherry-pick

#10771 DAOS-11828 dtx: handle excluded participant as prepared when DTX resync
  src/dtx/dtx_rpc.c
Labels: clean-cherry-pick, release-2.2

#10640 DAOS-11224 datamover: accept user container label (#10023)
  src/client/dfs/dfs.c
  src/common/prop.c
  src/tests/ftest/datamover/dst_create.py
  src/tests/ftest/datamover/negative.py
  src/tests/ftest/datamover/obj_large_posix.py
  src/tests/ftest/datamover/obj_small.py
  src/tests/ftest/datamover/posix_preserve_props.py
  src/tests/ftest/datamover/posix_types.py
  src/tests/ftest/datamover/posix_types.yaml
  src/tests/ftest/datamover/serial_large_posix.py
  src/tests/ftest/datamover/serial_small.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/duns_utils.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/test_utils_container.py
  src/utils/daos_hdlr.c
  utils/node_local_test.py
Labels: unclean-cherry-pick, priority, forced-landing

#10836 DAOS-11605 common: rename heap_ops to avoid conflict
  src/common/ad_mem.c
  src/vea/vea_init.c
Labels: release-2.4, priority

#10586 DAOS-11916 object: fix a bug of req_tgts->ort_start_shard
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/srv_ec.c
Labels: release-2.4, priority

#10848 DAOS-11605 common: reorg a few functions
  src/common/ad_mem.c
  src/common/tests/ad_mem_tests.c
  src/include/daos_srv/ad_mem.h
Labels: release-2.4, priority

#10713 DAOS-11993 vos: new flags VOS_OBJ_KILL_DKEY for vos_obj_del_key
  src/vos/vos_obj.c
  src/vos/vos_obj.h
  src/vos/vos_obj_cache.c
Labels: release-2.4, priority

#10817 DAOS-11885 umem: async data bio_desc
  src/bio/bio_buffer.c
  src/bio/bio_context.c
  src/bio/bio_internal.h
  src/bio/bio_wal.c
  src/bio/bio_xstream.c
  src/common/ad_tx.c
  src/common/mem.c
  src/include/daos/mem.h
  src/object/srv_obj.c
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_obj.c
Labels: release-2.4, priority

#10178 DAOS-8722 dfuse: Improve dfuse readdir code.
  src/client/dfuse/dfuse.h
  src/client/dfuse/dfuse_fuseops.c
  src/client/dfuse/ops/create.c
  src/client/dfuse/ops/opendir.c
  src/client/dfuse/ops/readdir.c
  src/client/dfuse/ops/rename.c
  src/client/dfuse/ops/unlink.c
  utils/node_local_test.py
Labels: release-2.4, priority

#10521 DAOS-11695 test: Add test users to CI env
  src/tests/ftest/harness/launch_setup.py
  src/tests/ftest/harness/launch_setup.yaml
  src/tests/ftest/launch.py
  src/tests/ftest/util/run_utils.py
  src/tests/ftest/util/user_utils.py
  utils/cq/words.dict
Labels: release-2.4, priority, forced-landing

#10818 DAOS-12020 vos: cancel deferred nvme list unconditionally
  src/vos/vos_common.c
Labels: clean-cherry-pick, release-2.2

#10834 DAOS-12063 object: reset kds and recxs for each shard
  src/object/cli_obj.c
  src/tests/suite/dfs_unit_test.c
Labels: release-2.4, priority

#10864 DAOS-12115 cart: Fix UCX client startup
  src/cart/crt_context.c
  src/cart/crt_hg.c
Labels: forced-landing

#10870 DAOS-12120 test: increase NLT log file size limit
  ci/unit/test_nlt_node.sh
Labels: forced-landing

#10867 DAOS-11885 bio: various bug fixes
  src/bio/bio_context.c
  src/bio/bio_internal.h
  src/bio/bio_recovery.c
  src/bio/bio_wal.c
  src/bio/bio_wal.h
  src/bio/smd/smd_pool.c
  src/engine/init.c
  src/engine/srv.c
  src/include/daos_srv/bio.h
  src/include/daos_srv/smd.h
  src/include/daos_srv/vos_types.h
  src/rdb/rdb.c
  src/vos/vos_internal.h
  src/vos/vos_pool.c
Labels: release-2.4, priority, meta-on-ssd

#10696 DAOS-11975 test: replace dfuse_utils pcmd with run_remote
  src/tests/ftest/dfuse/caching_check.py
  src/tests/ftest/dfuse/root_container.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/run_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: release-2.4, priority, forced-landing

#10881 DAOS-11919 control: Add concurrent pool ops protection (#10668)
  src/control/common/test/mocks.go
  src/control/common/test/utils.go
  src/control/fault/code/codes.go
  src/control/lib/control/pool.go
  src/control/lib/control/system.go
  src/control/server/mgmt_cont_test.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/control/system/database.go
  src/control/system/database_test.go
  src/control/system/faults.go
  src/control/system/pool_lock.go
  src/control/system/pool_lock_test.go
  src/control/system/raft.go
Labels: unclean-cherry-pick

#10826 DAOS-11999 test: adjust ior_test_base to use mpi_type from yaml (#10726)
  src/tests/ftest/aggregation/multiple_pool_cont.py
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/ior/intercept_verify_data_integrity.py
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/util/ior_test_base.py
Labels: unclean-cherry-pick, priority

#10850 DAOS-11605 common: fill gap between admem and umem
  src/bio/bio_xstream.c
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
  src/common/mem.c
  src/include/daos_srv/ad_mem.h
Labels: release-2.4, priority

#10868 DAOS-11813 swim: fix race access in crt_swim_cli_cb() (#10524)
  src/cart/crt_swim.c
Labels: clean-cherry-pick, release-2.2, release-2.4

#10907 DAOS-11605 common: reuse act and tx memory
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
Labels: release-2.4, priority

#10901 DAOS-11048 bio: monitor WAL and Meta SSDs
  src/bio/bio_internal.h
  src/bio/bio_monitor.c
  src/bio/bio_xstream.c
Labels: release-2.4, priority

#10773 DAOS-11924 dtx: handle race among DTX commit and DTX refresh
  src/dtx/dtx_rpc.c
  src/vos/vos_dtx.c
Labels: clean-cherry-pick, release-2.4

#10545 DAOS-11892 object: add spec shard case in tgts_query
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/tests/suite/daos_obj_ec.c
Labels: release-2.4, priority

#10918 DAOS-11605 ad_mem: fix a bug for group search
  src/common/ad_mem.c
Labels: release-2.4, priority

#10828 DAOS-9221 test: remove self._env_names (#10634)
  src/tests/ftest/daos_racer/multi.py
  src/tests/ftest/daos_racer/parallel.py
  src/tests/ftest/daos_racer/simple.py
  src/tests/ftest/erasurecode/rank_failure.py
  src/tests/ftest/io/unaligned_io.py
  src/tests/ftest/osa/online_extend.py
  src/tests/ftest/osa/online_parallel_test.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/rebuild/io_conf_run.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/daos_io_conf.py
  src/tests/ftest/util/daos_perf_base.py
  src/tests/ftest/util/daos_perf_utils.py
  src/tests/ftest/util/daos_racer_utils.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/macsio_test_base.py
  src/tests/ftest/util/macsio_util.py
  src/tests/ftest/util/mdtest_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: unclean-cherry-pick, priority, forced-landing

#10931 DAOS-12167 test: remove ftest/ior/intercept_verify_data_integrity
  src/tests/ftest/ior/intercept_verify_data_integrity.py
  src/tests/ftest/ior/intercept_verify_data_integrity.yaml
Labels: forced-landing

#10761 DAOS-11950 object: Infinite Retry Loop Fix
  src/object/cli_obj.c
Labels: forced-landing

#10902 DAOS-10301 test: pass dmg command line with mmap() (#10394)
  Jenkinsfile
  src/common/tests_dmg_helpers.c
Labels: clean-cherry-pick, priority

#10874 DAOS-12001 test: change logging of dfs tests to INFO
  src/tests/ftest/daos_test/dfs.py
  src/tests/ftest/daos_test/dfs.yaml
  src/tests/ftest/util/daos_core_base.py
Labels: forced-landing

#10898 DAOS-12144 test: improve dfuse mount checking
  src/tests/ftest/util/dfuse_utils.py
Labels: forced-landing

#10851 DAOS-12079 test: Move HW Small tests to HW Medium
  src/tests/ftest/aggregation/dfuse_space_check.py
  src/tests/ftest/container/fill_destroy_loop.py
  src/tests/ftest/container/full_pool_container_create.py
  src/tests/ftest/control/config_generate_output.py
  src/tests/ftest/control/config_generate_run.py
  src/tests/ftest/control/daos_server_helper.py
  src/tests/ftest/control/dmg_network_scan.py
  src/tests/ftest/control/dmg_pool_query_test.py
  src/tests/ftest/control/dmg_storage_query.py
  src/tests/ftest/control/dmg_storage_scan_scm.py
  src/tests/ftest/control/dmg_system_reformat.py
  src/tests/ftest/control/dmg_telemetry_io_basic.py
  src/tests/ftest/control/dmg_telemetry_nvme.py
  src/tests/ftest/control/ssd_socket.py
  src/tests/ftest/daos_perf/small.py
  src/tests/ftest/daos_vol/bigio.py
  src/tests/ftest/daos_vol/h5_suite.py
  src/tests/ftest/datamover/copy_procs.py
  src/tests/ftest/datamover/negative_space.py
  src/tests/ftest/dfuse/bash.py
  src/tests/ftest/dfuse/daos_build.py
  src/tests/ftest/dfuse/root_container.py
  src/tests/ftest/dfuse/simul.py
  src/tests/ftest/dfuse/sparse_file.py
  src/tests/ftest/harness/advanced.py
  src/tests/ftest/harness/basic.py
  src/tests/ftest/harness/config.py
  src/tests/ftest/harness/setup.py
  src/tests/ftest/harness/setup_hw.py
  src/tests/ftest/harness/slurm.py
  src/tests/ftest/harness/timeout.py
  src/tests/ftest/ior/intercept_basic.py
  src/tests/ftest/ior/intercept_messages.py
  src/tests/ftest/mpiio/hdf5.py
  src/tests/ftest/mpiio/romio.py
  src/tests/ftest/server/cpu_usage.py
  src/tests/ftest/server/daos_server_config.py
  src/tests/ftest/server/storage_tiers.py
Labels: release-2.4, priority

#10744 DAOS-11829 object: add a DAOS API to allow users to set an anchor at …
  src/client/api/init.c
  src/client/api/object.c
  src/client/dfs/dfs.c
  src/client/dfs/dfs_internal.c
  src/include/daos/object.h
  src/include/daos/task.h
  src/include/daos_fs.h
  src/include/daos_obj.h
  src/include/daos_task.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/object/obj_rpc.c
  src/object/obj_rpc.h
  src/object/obj_task.c
  src/object/srv_internal.h
  src/object/srv_obj.c
  src/tests/ftest/util/telemetry_utils.py
  src/tests/suite/dfs_unit_test.c
  src/vos/vos_obj.c
Labels: forced-landing

#10847 DAOS-9355 doc: fix more broken hyperlinks, improve mpi-io.md (#10844)
  docs/QSG/setup_rhel.md
  docs/admin/administration.md
  docs/admin/hardware.md
  docs/admin/nondefault-agent-socket.txt
  docs/admin/pool_operations.md
  docs/admin/tiering_uns.md
  docs/admin/troubleshooting.md
  docs/testing/datamover.md
  docs/testing/ior.md
  docs/user/container.md
  docs/user/datamover.md
  docs/user/interface.md
  docs/user/mpi-io.md
  docs/user/python.md
  docs/user/spark.md
Labels: unclean-cherry-pick
