Repository daos-stack/daos, pull requests merged in 2022-06, with the labels that each got.

#9227 DAOS-10396 build: Patch build for SPDK (#9223)
  site_scons/prereq_tools/base.py
  utils/build.config
Labels: clean-cherry-pick

#9151 DAOS-10397 ci: Fix post_provision_config scripts (#9140)
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes.sh
  ci/provisioning/post_provision_config_nodes_UBUNTU_20_04.sh
Labels: clean-cherry-pick

#9150 DAOS-10397 ci: Fix post_provision_config scripts (#9140)
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes.sh
  ci/provisioning/post_provision_config_nodes_UBUNTU_20_04.sh
Labels: clean-cherry-pick

#9239 DAOS-9310 test: Fix dtx/basic.py pool connect timeout (#7840)
  src/tests/ftest/dtx/basic.yaml
Labels: clean-cherry-pick

#9135 DAOS-10442 test: add state to expected output (#9065)
  src/tests/ftest/pool/list_verbose.py
  src/tests/ftest/pool/list_verbose.yaml
Labels: clean-cherry-pick

#9263 DAOS-8918 container: Fix key conflict with pool MD (#8824)
  src/container/srv_container.c
  src/container/srv_layout.c
  src/container/srv_layout.h
  src/pool/srv_layout.h
Labels: clean-cherry-pick

#9276 DAOS-10674 build: Add UCX builder, similar to other dependencies (#9190)
  debian/changelog
  debian/control
  site_scons/components/__init__.py
  site_scons/prereq_tools/base.py
  src/control/SConscript
  utils/build.config
  utils/rpms/daos.spec
Labels: unclean-cherry-pick

#9285 DAOS-10748 bio: missed error code in bulk_map_one() (#9265)
  src/bio/bio_buffer.c
  src/bio/bio_bulk.c
Labels: clean-cherry-pick

#9284 DAOS-10748 bio: missed error code in bulk_map_one() (#9265)
  src/bio/bio_buffer.c
  src/bio/bio_bulk.c
Labels: clean-cherry-pick

#9294 DAOS-5813 vos: get rid of NVMe reservation (#9280)
  src/vos/vos_space.c
Labels: clean-cherry-pick

#9286 DAOS-10255 test: adjust minimum containers expectation again (#9162)
  src/tests/ftest/server/metadata.py
Labels: clean-cherry-pick

#9300 DAOS-10448 test: reduce SCM size in create_all_vm/other tests (#9291)
  src/tests/ftest/container/query_properties.yaml
  src/tests/ftest/control/dmg_telemetry_basic.yaml
  src/tests/ftest/pool/create_all_vm.yaml
  src/tests/ftest/telemetry/dkey_akey_enum_punch.yaml
Labels: clean-cherry-pick

#9189 DAOS-10621 test: Fix not disabling daos repos for weekly branch PRs (…
  ci/provisioning/post_provision_config.sh
  ci/provisioning/post_provision_config_common_functions.sh
Labels: unclean-cherry-pick

#9251 DAOS-6322 test: Re-enable test_dmg_system_reformat (#7849)
  src/tests/ftest/control/dmg_system_reformat.py
  src/tests/ftest/control/dmg_system_reformat.yaml
  src/tests/ftest/util/server_utils.py
Labels: clean-cherry-pick

#9306 DAOS-10085 doc: Add syslog delivery failure to troubleshooting (#9220)
  docs/admin/troubleshooting.md
  src/control/lib/control/event.go
Labels: control-plane, clean-cherry-pick

#9340 DAOS-10593 control: Fix NVMe available space (#9203)
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/tests/ftest/pool/create_all_hw.py
  src/tests/ftest/pool/create_all_hw.yaml
Labels: clean-cherry-pick

#9278 DAOS-10641 doc: document DAOS container types (#9257)
  docs/user/container.md
Labels: clean-cherry-pick

#9279 DAOS-10641 doc: document DAOS container types (#9257)
  docs/user/container.md
Labels: clean-cherry-pick

#9088 DAOS-10367 tests: enable NVMe for VOS unit tests (#8822)
  ci/unit/test_main_node.sh
  src/vos/tests/daos_nvme.conf
  src/vos/tests/vts_aggregate.c
  src/vos/vos_common.c
  utils/run_test.sh
Labels: clean-cherry-pick

#9281 DAOS-10612 pool, container: simplify layout versioning (#9055)
  src/container/srv_container.c
  src/container/srv_layout.h
  src/pool/srv_layout.h
  src/pool/srv_pool.c
Labels: clean-cherry-pick

#9339 DAOS-8870 pool: Allow srv_hdls in TGT_QUERY_MAP (#7082)
  src/include/daos_srv/daos_engine.h
  src/pool/cli.c
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/pool/srv_target.c
Labels: clean-cherry-pick

#9323 DAOS-9989 test: Adding launch.py --provider option. (#8960)
  Jenkinsfile
  src/tests/ftest/launch.py
Labels: clean-cherry-pick

#9326 DAOS-10608 test: Run vfio-pci workaround fix between tests (#9271)
  src/tests/ftest/launch.py
Labels: clean-cherry-pick

#9359 DAOS-10845 packaging: do not ship UCX packages (#9358)
  .rpmignore
Labels: clean-cherry-pick

#9372 DAOS-10845 packaging: do not ship UCX packages (#9358)
  .rpmignore
Labels: clean-cherry-pick

#9181 DAOS-10630 test: passwdlessssh not start servers (#9083)
  src/tests/ftest/deployment/critical_integration.py
  src/tests/ftest/util/apricot/apricot/test.py
Labels: clean-cherry-pick

#9352 DAOS-8870 pool: Allow srv_hdls in TGT_QUERY_MAP (#7082)
  src/include/daos_srv/daos_engine.h
  src/pool/cli.c
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/pool/srv_target.c
Labels: clean-cherry-pick

#9344 DAOS-10770 test: agent_failure.py - Update IOR error expectations - release/2.2
  src/tests/ftest/deployment/agent_failure.py
Labels: clean-cherry-pick

#9328 DAOS-10661 control: Use DB replica addr for JoinReq
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/server/server.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
Labels: clean-cherry-pick

#9368 DAOS-10608 test: Run vfio-pci workaround fix between tests (#9271)
  src/tests/ftest/launch.py
Labels: clean-cherry-pick

#9367 DAOS-9865 test: Increase tearDown() timeout for pool destroy (#8721)
  src/tests/ftest/control/dmg_system_reformat.py
  src/tests/ftest/daos_test/dfs.yaml
  src/tests/ftest/daos_test/rebuild.yaml
  src/tests/ftest/daos_test/suite.yaml
  src/tests/ftest/harness/advanced.py
  src/tests/ftest/harness/advanced.yaml
  src/tests/ftest/nvme/pool_exclude.py
  src/tests/ftest/osa/dmg_negative_test.py
  src/tests/ftest/osa/offline_drain.py
  src/tests/ftest/osa/offline_extend.py
  src/tests/ftest/osa/offline_parallel_test.py
  src/tests/ftest/osa/offline_reintegration.py
  src/tests/ftest/osa/online_extend.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/pool/evict.py
  src/tests/ftest/scripts/main.sh
  src/tests/ftest/server/daos_server_restart.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/daos_core_base.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/test_utils_pool.py
Labels: unclean-cherry-pick

#9431 DAOS-9355 doc: switch doc URLs to https (#9428)
  CONTRIBUTING.md
  README.md
  docs/admin/troubleshooting.md
  docs/dev/contributing.md
  docs/overview/fault.md
  docs/overview/terminology.md
Labels: clean-cherry-pick

#9432 DAOS-9355 doc: switch doc URLs to https (#9428)
  README.md
  docs/admin/troubleshooting.md
  docs/dev/contributing.md
  docs/overview/fault.md
  docs/overview/terminology.md
Labels: clean-cherry-pick

#9415 DAOS-10132 doc: Describe disable_vfio usage in admin guide (#9249)
  docs/admin/deployment.md
Labels: clean-cherry-pick

#9434 DAOS-10493 doc: document DFS dot-dir behaviour (#9433)
  docs/user/filesystem.md
Labels: clean-cherry-pick

#9435 DAOS-10493 doc: document DFS dot-dir behaviour (#9433)
  docs/user/filesystem.md
Labels: clean-cherry-pick

#9437 DAOS-9644 doc: clarify default engine logfile in server.yml (#9436)
  utils/config/daos_server.yml
Labels: clean-cherry-pick

#9438 DAOS-9644 doc: clarify default engine logfile in server.yml (#9436)
  utils/config/daos_server.yml
Labels: clean-cherry-pick

#9448 DAOS-9901 doc: explain multi-NIC support on the client (#8765)
  docs/admin/hardware.md
Labels: clean-cherry-pick

#9412 DAOS-10863 control: Log warning for single access point (#9395)
  src/control/server/config/server.go
Labels: unclean-cherry-pick

#9515 DAOS-9989 test: Enable provider-testing branches (#9506)
  ci/provisioning/post_provision_config_common_functions.sh
Labels: clean-cherry-pick

#9497 DAOS-10473 control: Do not require IOMMU for emulated NVMe (#9272)
  docs/admin/deployment.md
  src/control/cmd/daos_server/storage.go
  src/control/fault/code/codes.go
  src/control/server/config/server.go
  src/control/server/engine/config_test.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
  src/control/server/storage/config.go
  src/control/server/storage/faults.go
Labels: control-plane, unclean-cherry-pick
