Repository daos-stack/daos, pull requests merged in 2022-10, with the labels that each got.

#10290 DAOS-9784 dfuse: Tune dfuse tests for performance.
  src/tests/ftest/dfuse/daos_build.py
  src/tests/ftest/dfuse/daos_build.yaml
  src/tests/ftest/performance/mdtest_easy.py
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/util/dfuse_test_base.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/performance_test_base.py
  utils/cq/pylintrc
  utils/node_local_test.py
Labels: release-2.4, priority

#9950 DAOS-11279 test: Implement test utils for daos_server ms and dmg chec…
  src/tests/ftest/control/version.py
  src/tests/ftest/control/version.yaml
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/server_utils_base.py
  src/tests/ftest/util/test_utils_pool.py
  utils/cq/words.dict
Labels: forced-landing

#10465 DAOS-11766 test: Fix harness/advanced.py bandit check
  src/tests/ftest/harness/advanced.py
Labels: forced-landing

#10447 DAOS-623 ci: Remove the releasever removal (#10413)
  ci/provisioning/post_provision_config_nodes.sh
Labels: clean-cherry-pick, release-2.0

#10384 DAOS-11231 client: fix memory corruption during query_key
  src/client/array/dc_array.c
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/object/obj_task.c
Labels: release-2.2

#10415 DAOS-11688 mercury: Fix 2.2 build to select correct mercury-ucx RPM.
  ci/provisioning/post_provision_config_common_functions.sh
Labels: release-2.2

#10439 DAOS-11391 control,bio: Add explicit SSD role assignment to server config
  src/control/fault/code/codes.go
  src/control/lib/control/auto_test.go
  src/control/server/config/server_test.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend_class_test.go
  src/control/server/storage/bdev/backend_json.go
  src/control/server/storage/bdev/backend_json_test.go
  src/control/server/storage/config.go
  src/control/server/storage/config_test.go
  src/control/server/storage/faults.go
  src/control/server/storage/provider.go
  src/include/daos_srv/control.h
  utils/config/daos_server.yml
Labels: release-2.4, priority, forced-landing

#10472 DAOS-11648 doc: fabric_iface_port is not optional
  utils/config/daos_server.yml
Labels: release-2.2

#10473 DAOS-11648 doc: fabric_iface_port is not optional (#10472)
  utils/config/daos_server.yml
Labels: clean-cherry-pick, release-2.2, priority

#10445 DAOS-11664 agent: Add config option to ignore interfaces
  src/control/cmd/daos_agent/config.go
  src/control/cmd/daos_agent/config_test.go
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/fabric_test.go
  src/control/cmd/daos_agent/infocache.go
  src/control/cmd/daos_agent/infocache_test.go
  src/control/cmd/daos_agent/start.go
  src/control/common/collection_utils.go
  src/control/common/collection_utils_test.go
  utils/config/daos_agent.yml
Labels: forced-landing

#10475 DAOS-11815 ci: Add "agent" as commit msg component
  ci/jira_query.py
Labels: forced-landing

#10480 DAOS-11255 test: Removing the network/zero_config.py test (#10462)
  src/tests/ftest/network/zero_config.py
  src/tests/ftest/network/zero_config.yaml
Labels: clean-cherry-pick

#10474 DAOS-9582 control: Fix raft test fixture generation
  src/control/system/raft/raft.go
Labels: forced-landing

#10497 Build(deps): Bump protobuf-java in /src/client/java/daos-java (#10484)
  src/client/java/daos-java/pom.xml
Labels: ast-fixes, clean-cherry-pick, release-2.2, forced-landing

#10448 DAOS-11396 control: Add NUMA affinity to tmpfs mount options
  src/control/cmd/daos_admin/handler_test.go
  src/control/lib/control/auto.go
  src/control/lib/control/auto_test.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/engine/config.go
  src/control/server/storage/config.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm/provider.go
Labels: release-2.4, priority, forced-landing

#10479 DAOS-11762 test: Match log threshold with log rollover size
  ftest.sh
  src/tests/ftest/launch.py
  src/tests/ftest/scripts/main.sh
Labels: forced-landing

#10482 DAOS-11664 test: support agent exclude_fabric_ifaces
  src/tests/ftest/harness/config.py
  src/tests/ftest/harness/config.yaml
  src/tests/ftest/util/agent_utils_params.py
Labels: forced-landing

#10433 DAOS-11706 control: Add pool svc list to property query
  src/common/prop.c
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_properties.go
  src/control/cmd/dmg/pool_test.go
  src/control/cmd/dmg/pretty/pool.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool_cont_prop.go
  src/control/lib/daos/pool_property.go
  src/control/lib/daos/pool_property_test.go
  src/mgmt/srv_drpc.c
  src/mgmt/tests/srv_drpc_tests.c
  src/pool/rpc.c
Labels: forced-landing

#10414 DAOS-5921 md: bypass space checks in pool evict rdb tx update
  src/include/daos_srv/rdb.h
  src/pool/srv_pool.c
  src/rdb/rdb_tx.c
  src/tests/ftest/server/metadata.py
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#10275 DAOS-8648 tests: Re-enable skipped tests
  src/tests/ftest/nvme/pool_extend.py
  src/tests/ftest/osa/offline_extend.py
  src/tests/ftest/osa/offline_parallel_test.py
  src/tests/ftest/osa/online_extend.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#10421 DAOS-11605 common: basic ad tx undo/redo
  src/common/SConscript
  src/common/ad_tx.c
  src/include/daos/common.h
  src/include/daos/mem.h
  src/include/daos_srv/ad_mem.h
Labels: release-2.4, priority

#10516 DAOS-11391 control: Rename Index SSD role assignment to Meta
  src/control/server/storage/bdev.go
  src/control/server/storage/config.go
  src/control/server/storage/config_test.go
  src/control/server/storage/faults.go
  src/include/daos_srv/control.h
  utils/config/daos_server.yml
Labels: release-2.4, priority, forced-landing

#10485 DAOS-11601 object: refine daos_recx_ep_list_set
  src/object/srv_obj.c
Labels: priority

#10438 DAOS-10663 dfs: add new DFS readdirplus API
  src/client/dfs/dfs.c
  src/include/daos_fs.h
  src/tests/suite/dfs_unit_test.c
Labels: forced-landing

#10501 DAOS-11145 csum: Scrubbing Upgrade Fix
  src/container/srv_container.c
  src/include/daos_prop.h
  src/pool/srv_layout.c
  src/pool/srv_layout.h
  src/pool/srv_pool.c
Labels: release-2.4, priority, forced-landing

#10424 DAOS-11400 bio: preliminary WAL implementation
  src/bio/SConscript
  src/bio/bio_buffer.c
  src/bio/bio_internal.h
  src/bio/bio_wal.c
  src/bio/bio_wal.h
  src/include/daos_srv/bio.h
Labels: release-2.4, priority

#10394 DAOS-10301 test: pass dmg command line with mmap()
  src/common/tests_dmg_helpers.c
Labels: priority, forced-landing

#10534 DAOS-9355 doc: fix doc URLs in src tree (#10527)
  src/control/README.md
  src/control/cmd/daos_admin/README.md
  src/control/cmd/daos_server/README.md
  src/control/server/README.md
  src/tests/simple_obj.c
Labels: unclean-cherry-pick

#10511 DAOS-11865 control: Rename privileged helpers
  .dockerignore
  ci/docker_nlt.sh
  ci/unit/test_main_node.sh
  ci/unit/test_nlt_node.sh
  debian/changelog
  debian/daos-server.install
  debian/daos-server.postinst
  debian/rules
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
  docs/admin/predeployment_check.md
  docs/admin/troubleshooting.md
  docs/dev/development.md
  src/control/README.md
  src/control/SConscript
  src/control/cmd/daos_firmware_helper/handler.go
  src/control/cmd/daos_firmware_helper/handler_test.go
  src/control/cmd/daos_firmware_helper/main.go
  src/control/cmd/daos_server/main.go
  src/control/cmd/daos_server/storage_legacy.go
  src/control/cmd/daos_server_helper/README.md
  src/control/cmd/daos_server_helper/handler.go
  src/control/cmd/daos_server_helper/handler_test.go
  src/control/cmd/daos_server_helper/main.go
  src/control/lib/spdk/src/nvme_control.c
  src/control/pbin/pbin.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/init/setup_spdk.sh
  src/control/server/server_utils.go
  src/control/server/storage/bdev.go
  src/control/server/storage/scm.go
  src/tests/ftest/control/daos_server_helper.py
  src/tests/ftest/control/daos_server_helper.yaml
  src/tests/ftest/scripts/setup_nodes.sh
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/server_utils_params.py
  utils/ansible/ftest/templates/daos-make.sh.j2
  utils/ci/run_in_gha.sh
  utils/config/daos_server.yml
  utils/rpms/daos.spec
  utils/setup_daos_server_helper.sh
Labels: forced-landing

#10536 DAOS-11597 object: coverity fix
  src/object/cli_shard.c
Labels: release-2.4, priority

#10071 DAOS-11418 container: rename redundancy container properties
  docs/QSG/tour.md
  docs/user/container.md
  src/client/pydaos/raw/daos_api.py
  src/common/prop.c
  src/common/tests/prop_tests.c
  src/control/cmd/daos/container.go
  src/control/cmd/daos/property.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_properties.go
  src/control/cmd/dmg/pool_test.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool_property.go
  src/control/lib/daos/pool_property_test.go
  src/control/lib/ui/prop_flags.go
  src/control/lib/ui/prop_flags_test.go
  src/include/daos/cont_props.h
  src/tests/ftest/container/auto_oc_selection.py
  src/tests/ftest/container/query_properties.py
  src/tests/ftest/container/rf_enforcement.yaml
  src/tests/ftest/control/dmg_telemetry_io_latency.py
  src/tests/ftest/deployment/network_failure.yaml
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/deployment/target_failure.yaml
  src/tests/ftest/dfuse/fio_small.yaml
  src/tests/ftest/erasurecode/online_rebuild_mdtest.yaml
  src/tests/ftest/erasurecode/rebuild_fio.yaml
  src/tests/ftest/erasurecode/truncate.yaml
  src/tests/ftest/fault_injection/ec.yaml
  src/tests/ftest/interoperability/updown_grade.yaml
  src/tests/ftest/nvme/fault.yaml
  src/tests/ftest/nvme/pool_exclude.yaml
  src/tests/ftest/nvme/pool_extend.yaml
  src/tests/ftest/osa/offline_drain.yaml
  src/tests/ftest/osa/offline_extend.yaml
  src/tests/ftest/osa/offline_parallel_test.yaml
  src/tests/ftest/osa/offline_reintegration.yaml
  src/tests/ftest/osa/online_drain.yaml
  src/tests/ftest/osa/online_extend.yaml
  src/tests/ftest/osa/online_reintegration.yaml
  src/tests/ftest/pool/rf.py
  src/tests/ftest/pool/rf.yaml
  src/tests/ftest/rebuild/cascading_failures.yaml
  src/tests/ftest/rebuild/container_rf.yaml
  src/tests/ftest/rebuild/no_cap.yaml
  src/tests/ftest/rebuild/widely_striped.yaml
  src/tests/ftest/rebuild/with_ior.yaml
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress_48h.yaml
  src/tests/ftest/telemetry/telemetry_pool_metrics.yaml
  src/tests/ftest/util/container_rf_test_base.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/file_count_test_base.py
  src/tests/ftest/util/osa_utils.py
  src/tests/ftest/util/performance_test_base.py
  src/tests/ftest/util/soak_utils.py
  src/tests/ftest/util/test_utils_container.py
  utils/ansible/ftest/templates/daos-ld.so.conf.j2
Labels: release-2.4, priority, forced-landing

#10385 DAOS-11586 bio: implement bio changes for metadata on ssd
  src/bio/bio_buffer.c
  src/bio/bio_context.c
  src/bio/bio_internal.h
  src/bio/bio_monitor.c
  src/bio/bio_recovery.c
  src/bio/bio_xstream.c
  src/bio/smd/smd_internal.h
  src/include/daos_srv/bio.h
  src/include/daos_srv/smd.h
  src/mgmt/srv_internal.h
  src/mgmt/srv_query.c
  src/object/srv_obj.c
  src/vos/vos_aggregate.c
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_obj.c
  src/vos/vos_pool.c
  src/vos/vos_pool_scrub.c
Labels: release-2.4, priority

#10524 DAOS-11813 swim: fix race access in crt_swim_cli_cb()
  src/cart/crt_swim.c
Labels: release-2.4, priority, forced-landing

#10455 DAOS-11749 test: Use default svcn in /pool/create_capacity.py test
  src/tests/ftest/pool/create_capacity.py
  src/tests/ftest/pool/create_capacity.yaml
Labels: forced-landing

#10573 DAOS-9355 doc: document VMD support
  docs/admin/vmd.md
  docs/release/release_notes_v2_2.md
Labels: release-2.2

#10582 DAOS-11635 doc: fixes to QSG setup guide
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
Labels: release-2.2

#10583 DAOS-11674 doc: document default EC cell size change in DAOS 2.2
  docs/admin/pool_operations.md
  docs/release/release_notes_v2_2.md
  docs/user/container.md
Labels: release-2.2

#10585 DAOS-11634 doc: misc doc improvements
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
  docs/QSG/tour.md
  docs/testing/datamover.md
  docs/testing/ior.md
Labels: release-2.2

#10345 DAOS-10524 pool: add rebuild version to pool query
  src/include/daos/placement.h
  src/include/daos/pool.h
  src/include/daos_srv/pool.h
  src/include/daos_srv/rebuild.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/object/obj_rpc.h
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/object/srv_obj_migrate.c
  src/placement/jump_map.c
  src/placement/pl_map.c
  src/placement/pl_map.h
  src/placement/ring_map.c
  src/placement/tests/pl_bench.c
  src/placement/tests/place_obj_common.c
  src/pool/cli.c
  src/pool/rpc.h
  src/pool/srv_iv.c
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: release-2.4, priority

#10577 DAOS-11915 vos: Reregistration of btree doesn't fail
  src/common/btree.c
  src/pool/srv_pool.c
Labels: forced-landing

#10559 DAOS-11132 rebuild: Incorrect deletion of local objects
  src/placement/pl_map.c
Labels: forced-landing

#10506 DAOS-11587 bio: sysdb changes for metadata on ssd
  src/bio/bio_buffer.c
  src/bio/bio_context.c
  src/bio/bio_device.c
  src/bio/bio_internal.h
  src/bio/bio_recovery.c
  src/bio/bio_xstream.c
  src/engine/sched.c
  src/engine/srv.c
  src/engine/srv_internal.h
  src/include/daos_srv/bio.h
  src/include/daos_srv/control.h
  src/include/daos_srv/vos_types.h
  src/mgmt/srv_query.c
  src/vos/sys_db.c
  src/vos/vos_common.c
  src/vos/vos_pool.c
Labels: release-2.4, priority

#10596 DAOS-9355 doc: activate 2.2 relnotes
  docs/release/release_notes.md
  docs/release/release_notes_v2_2.md
Labels: release-2.2

#10342 DAOS-11192 test: increase subprocess pattern_timeout
  src/tests/ftest/ior/crash.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/server_utils.py
Labels: priority, forced-landing

#10566 DAOS-11396 control: Enable hugepage support for tmpfs
  src/control/server/config/server_test.go
  src/control/server/storage/config.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm/mocks.go
  src/control/server/storage/scm/provider.go
  src/control/server/storage/scm/provider_test.go
  utils/config/daos_server.yml
Labels: release-2.4, priority

#10587 DAOS-11587 vos: standalone vos support for metadata on ssd
  src/bio/bio_context.c
  src/bio/bio_xstream.c
  src/include/daos_srv/bio.h
  src/tests/vos_engine.c
  src/vos/tests/pool_scrubbing_tests.c
  src/vos/tests/vos_tests.c
  src/vos/tests/vts_common.c
  src/vos/vos_common.c
  src/vos/vos_size.c
Labels: release-2.4, priority, forced-landing

#10451 DAOS-11605 common: ad-hoc allocator for umem
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
  src/common/tests/SConscript
  src/common/tests/ad_mem_tests.c
  src/include/daos_srv/ad_mem.h
Labels: release-2.4, priority

#10624 DAOS-623 utils: daos fs copy: don't try to create root
  src/utils/daos_hdlr.c
Labels: forced-landing

#10599 DAOS-11026 dfs: update daos tool output for dir_oclass and add nlt tests
  src/client/dfs/dfs.c
  src/control/cmd/daos/container.go
  utils/node_local_test.py
Labels: release-2.4, priority, forced-landing

#10392 DAOS-11685 dtx: handle DTX abort by race
  src/dtx/dtx_common.c
  src/dtx/dtx_rpc.c
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/vos/vos_dtx.c
Labels: release-2.4, priority

#9924 DAOS-11149 pool: bump GC ULT stack size
  src/pool/srv_target.c
Labels: priority

#10616 DAOS-11633 doc: fix hrefs to DAOS 2.0 docs (#10584)
  docs/testing/ior.md
Labels: release-2.4

#10615 DAOS-11674 doc: document default EC cell size change in DAOS 2.2 (#10583)
  docs/admin/pool_operations.md
  docs/user/container.md
Labels: unclean-cherry-pick, release-2.4

#10612 DAOS-9355 doc: document VMD support (#10573)
  docs/admin/vmd.md
Labels: unclean-cherry-pick

#10609 DAOS-11462 doc: fix typo (#10608)
  docs/admin/hardware.md
Labels: clean-cherry-pick, release-2.4

#10608 DAOS-11462 doc: fix typo
  docs/admin/hardware.md
Labels: release-2.2

#10578 DAOS-11901 test: Cleanup and coverity fixes for multi-send
  src/tests/ftest/cart/test_multisend_client.c
  src/tests/ftest/cart/test_multisend_common.h
Labels: release-2.4, priority

#10575 DAOS-11755 control: Allow daos_server to show version/help without helper (#10528)
  src/control/cmd/daos_server/command_test.go
  src/control/cmd/daos_server/main.go
Labels: unclean-cherry-pick

#10643 DAOS-11664 agent: Add config option to ignore interfaces (#10445)
  src/control/cmd/daos_agent/config.go
  src/control/cmd/daos_agent/config_test.go
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/fabric_test.go
  src/control/cmd/daos_agent/infocache.go
  src/control/cmd/daos_agent/infocache_test.go
  src/control/cmd/daos_agent/start.go
  src/control/common/collection_utils.go
  src/control/common/collection_utils_test.go
  src/tests/ftest/harness/config.py
  src/tests/ftest/harness/config.yaml
  src/tests/ftest/util/agent_utils_params.py
  utils/config/daos_agent.yml
Labels: unclean-cherry-pick, priority

#10641 DAOS-11514 control: Detect IB pkey parent devices (#10328)
  src/control/lib/hardware/sysfs/provider.go
  src/control/lib/hardware/sysfs/provider_test.go
Labels: clean-cherry-pick, priority

#10647 DAOS-11872 tests: Move fault injection dependent code into new test c…
  src/tests/suite/daos_container.c
Labels: unclean-cherry-pick, priority

#10282 DAOS-11552 control: Interop rule processing fixes
  src/control/build/interop.go
  src/control/build/interop_test.go
  src/control/build/version.go
  src/control/build/version_test.go
  src/control/server/interceptors.go
Labels: release-2.2, priority

#10308 DAOS-11447 rebuild: ignore exist ERROR for object insert (#10097)
  src/rebuild/rebuild_iv.c
  src/rebuild/scan.c
Labels: release-2.2

#10622 DAOS-11913 dfs: coverity fixes CID 452244 & 452245
  src/client/dfs/dfs.c
  src/client/dfs/duns.c
  src/include/daos/object.h
  src/object/cli_obj.c
Labels: release-2.4, priority, forced-landing

#10592 DAOS-11764 build: Enable debuginfo sub-packages
  Jenkinsfile
  src/tests/ftest/harness/advanced.py
  src/tests/ftest/harness/basic.py
  src/tests/ftest/process_core_files.py
  utils/githooks/pre-commit.d/20-flake.sh
  utils/githooks/pre-commit.d/40-pylint.sh
  utils/rpms/daos.spec
Labels: forced-landing

#10653 DAOS-11953 control: Add DataPlaneNotStarted to retryable pool errors
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/server/mgmt_pool.go
Labels: release-2.4, priority, forced-landing

#10604 DAOS-11936 object: fix online extending bugs
  src/object/cli_obj.c
  src/placement/pl_map_common.c
  src/pool/srv_cli.c
  src/tests/ftest/osa/online_extend.py
Labels: release-2.4, priority

#10642 DAOS-11554 control: Don't log missing lib as error (#10327)
  src/control/lib/hardware/hwprov/defaults.go
  src/control/lib/hardware/libfabric/bindings.go
  src/control/lib/hardware/ucx/bindings.go
Labels: clean-cherry-pick, priority

#10664 DAOS-623 vea: fix spelling in vea test (#10605, #10607)
  src/vea/tests/vea_stress.c
Labels: clean-cherry-pick

#10554 DAOS-11655 rebuild: missing riv_sync (#10519)
  src/rebuild/srv.c
Labels: release-2.4

#10618 DAOS-11894 vos: Avoid segfault due to default evtree sort policy
  src/vos/evtree.c
  src/vos/tests/evt_stress.py
  utils/run_test.sh
Labels: priority, forced-landing

#10652 DAOS-11163 test: set redun fac property for container
  src/tests/ftest/rebuild/with_io.yaml
Labels: forced-landing

#10661 DAOS-11882 pydaos: AsyncWorker1() should use passed DaosEvent() (#10530)
  src/client/pydaos/raw/daos_cref.py
Labels: clean-cherry-pick

#10659 DAOS-11643 tests: fix parameters passing to API (#10529)
  src/client/pydaos/raw/daos_api.py
Labels: clean-cherry-pick, priority

#9914 DAOS-11187 dtx: properly handle DTX commit failure
  src/dtx/dtx_rpc.c
Labels: release-2.2, priority

#10228 DAOS-11035 dtx: continue to fix DXT related issues
  src/container/srv_target.c
  src/dtx/dtx_common.c
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
  src/include/daos_srv/dtx_srv.h
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/vos/tests/vts_dtx.c
  src/vos/vos_dtx.c
  src/vos/vos_dtx_iter.c
  src/vos/vos_internal.h
Labels: release-2.2, priority

#10680 DAOS-11605 common: arena registration test
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/tests/ad_mem_tests.c
  src/include/daos_srv/ad_mem.h
Labels: release-2.4, priority

#10551 DAOS-11444 pool: return rc for ds_pool_lookup
  src/container/container_iv.c
  src/container/srv_container.c
  src/container/srv_target.c
  src/dtx/dtx_resync.c
  src/include/daos_srv/pool.h
  src/object/srv_obj_migrate.c
  src/pool/srv_iv.c
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/pool/srv_util.c
  src/rebuild/srv.c
Labels: release-2.4, priority

#10674 DAOS-11894 vos: Avoid segfault due to default evtree sort policy (#10618 and #10552)
  src/vos/evtree.c
  src/vos/tests/evt_ctl.c
  src/vos/tests/evt_stress.py
  src/vos/vos_common.c
  utils/run_test.sh
Labels: clean-cherry-pick, release-2.2, priority

#10673 DAOS-11764 build: Enable debuginfo sub-packages... (#10592)
  Jenkinsfile
  src/tests/ftest/launch.py
  utils/githooks/pre-commit.d/20-flake.sh
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, priority, forced-landing

#10675 DAOS-11953 control: Add DataPlaneNotStarted to retryable pool errors (#10653)
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/server/mgmt_pool.go
Labels: release-2.4

#10655 DAOS-11961 control: Add config awareness for daos_server nvme scan cmd
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/server/storage/bdev/mocks.go
Labels: control-plane, release-2.4, forced-landing

#10632 DAOS-10633 control: Add IntPropVal type to system properties
  src/control/lib/daos/system_prop.go
  src/control/lib/daos/system_prop_test.go
Labels: forced-landing

#10620 DAOS-11422 dfs: add support for mtime and ctime on directory objects
  src/client/api/object.c
  src/client/dfs/dfs.c
  src/include/daos/task.h
  src/include/daos_obj.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_task.c
  src/tests/suite/dfs_unit_test.c
Labels: forced-landing

#10525 DAOS-11043 common: Blob backed Memory(BMEM) interface for umem
  src/common/SConscript
  src/common/dav/README.md
  src/common/dav/alloc_class.c
  src/common/dav/alloc_class.h
  src/common/dav/bucket.c
  src/common/dav/bucket.h
  src/common/dav/container.h
  src/common/dav/container_ravl.c
  src/common/dav/container_ravl.h
  src/common/dav/container_seglists.c
  src/common/dav/container_seglists.h
  src/common/dav/critnib.c
  src/common/dav/critnib.h
  src/common/dav/dav.h
  src/common/dav/dav_clogs.c
  src/common/dav/dav_clogs.h
  src/common/dav/dav_iface.c
  src/common/dav/dav_internal.h
  src/common/dav/fault_injection.h
  src/common/dav/fs.h
  src/common/dav/fs_posix.c
  src/common/dav/heap.c
  src/common/dav/heap.h
  src/common/dav/heap_layout.h
  src/common/dav/memblock.c
  src/common/dav/memblock.h
  src/common/dav/memops.c
  src/common/dav/memops.h
  src/common/dav/obj.h
  src/common/dav/os_thread.h
  src/common/dav/os_thread_posix.c
  src/common/dav/out.h
  src/common/dav/page_size.h
  src/common/dav/palloc.c
  src/common/dav/palloc.h
  src/common/dav/pmemops.h
  src/common/dav/queue.h
  src/common/dav/ravl.c
  src/common/dav/ravl.h
  src/common/dav/ravl_interval.c
  src/common/dav/ravl_interval.h
  src/common/dav/recycler.c
  src/common/dav/recycler.h
  src/common/dav/stats.c
  src/common/dav/stats.h
  src/common/dav/sys_util.h
  src/common/dav/tx.c
  src/common/dav/tx.h
  src/common/dav/ulog.c
  src/common/dav/ulog.h
  src/common/dav/util.c
  src/common/dav/util.h
  src/common/dav/valgrind_internal.h
  src/common/dav/vec.h
  src/common/dav/vecq.h
  src/common/mem.c
  src/include/daos/mem.h
  src/vos/tests/vts_ts.c
  utils/run_test.sh
Labels: release-2.4, priority

#10096 DAOS-10289 bio: bump subsystem fini timeout
  src/bio/bio_xstream.c
Labels: release-2.4, priority

#10233 DAOS-11189 test: support multiple dfuse instances (#9848)
  src/tests/ftest/dfuse/bash.py
  src/tests/ftest/dfuse/find.py
  src/tests/ftest/util/dfuse_test_base.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/ior_test_base.py
Labels: unclean-cherry-pick, priority

#10683 DAOS-11952 rebuild: increase stack size for rebuild ULT
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: release-2.2, release-2.4, priority

#10710 DAOS-11605 common: fix to calculate group address
  src/common/ad_mem.c
  src/common/tests/ad_mem_tests.c
Labels: release-2.4, priority

#10707 DAOS-11945 tests: Increase timeout of create_capacity.py
  src/tests/ftest/pool/create_capacity.yaml
Labels: forced-landing
