Repository daos-stack/daos, pull requests merged in 2022-07, with the labels that each got.

#9575 DAOS-9355 doc: update system_architecture.png (#9574)
  docs/graph/system_architecture.png
Labels: clean-cherry-pick

#9576 DAOS-9355 doc: update system_architecture.png (#9574)
  docs/graph/system_architecture.png
Labels: clean-cherry-pick

#9571 DAOS-10960 pool,container,rsvc: fix Coverity issues
  src/common/rsvc.c
  src/pool/srv_pool.c
Labels: ast-fixes

#9499 DAOS-10656 test: Add libfabric version check to deployment/critical_integration.py (#9128)
  src/tests/ftest/deployment/critical_integration.py
  src/tests/ftest/deployment/critical_integration.yaml
Labels: clean-cherry-pick

#9623 DAOS-11053 build: Remove check for dpdk/rte_eal.h (#9588)
  site_scons/components/__init__.py
Labels: clean-cherry-pick, release-2.2

#9638 DAOS-11001 dfuse: Remove unused test code. (#9607)
  src/client/dfuse/SConscript
  src/client/dfuse/test/SConscript
  src/client/dfuse/test/test_ioil.c
Labels: unclean-cherry-pick, release-2.2

#9404 DAOS-10500 test: Make nvme/health more flexible (#9346)
  src/tests/ftest/nvme/health.py
  src/tests/ftest/nvme/health.yaml
Labels: clean-cherry-pick, release-2.2

#9403 DAOS-10498 test: improve nvme/fragmentation (#9274)
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/fragmentation.yaml
  src/tests/ftest/util/test_utils_base.py
Labels: clean-cherry-pick, release-2.2

#9531 DAOS-10892 control: Add backward compatibility for enable_vmd param
  src/control/cmd/dmg/auto_test.go
  src/control/fault/code/codes.go
  src/control/lib/control/auto_test.go
  src/control/server/config/faults.go
  src/control/server/config/server.go
  src/control/server/config/server_legacy.go
  src/control/server/config/server_test.go
  src/control/server/server_utils.go
Labels: control-plane, release-2.2

#9524 DAOS-9599 chk: handle inconsistent pool label
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_leader.c
  src/chk/chk_rpc.c
  src/chk/chk_upcall.c
  src/engine/drpc_ras.c
  src/include/daos_prop.h
  src/include/daos_srv/daos_chk.h
  src/mgmt/srv_chk.c
  src/mgmt/srv_internal.h
  src/mgmt/tests/mocks.c
  src/pool/srv_layout.c
  src/pool/srv_pool_check.c
Labels: CR

#9646 DAOS-10870 dtx: handle active DTX entry update properly
  src/include/daos_errno.h
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_tx.c
  src/vos/vos_dtx.c
Labels: release-2.2

#9625 DAOS-11031 control: Clean hugepages on engine startup
  src/control/server/instance_exec.go
  src/control/server/instance_exec_test.go
  src/control/server/instance_storage.go
  src/control/server/instance_storage_test.go
  src/control/server/server_utils.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
Labels: control-plane, release-2.2

#9650 DAOS-10892 control: Add backward compatibility for enable_vmd param (…
  src/control/cmd/dmg/auto_test.go
  src/control/fault/code/codes.go
  src/control/lib/control/auto_test.go
  src/control/server/config/faults.go
  src/control/server/config/server.go
  src/control/server/config/server_legacy.go
  src/control/server/config/server_test.go
  src/control/server/server_utils.go
Labels: control-plane, unclean-cherry-pick, release-2.2

#9613 DAOS-10953 test: Detect issue with remove in unit test code
  src/common/tests/utest_common.c
  src/vos/tests/vts_mvcc.c
Labels: ast-fixes

#9020 DAOS-10346 test: Fix tests to use the existing container uuid instead…
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/nvme/enospace.yaml
  src/tests/ftest/nvme/fault.yaml
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/nvme_utils.py
Labels: clean-cherry-pick, release-2.2

#9535 DAOS-10904 test: Update network scan test to use cxi provider
  src/tests/ftest/control/dmg_network_scan.py
  src/tests/ftest/util/network_utils.py
Labels: release-2.2

#9654 DAOS-7821 gha: Add code to report Jira status into GitHub. (#9628)
  .github/workflows/pr-metadata.yml
  ci/jira_query.py
  utils/docker/Dockerfile.checkpatch
Labels: unclean-cherry-pick

#9573 DAOS-10960 pool,container,rsvc: fix Coverity issues
  src/common/rsvc.c
  src/pool/srv_pool.c
Labels: ast-fixes, clean-cherry-pick, release-2.2

#9635 DAOS-7326 test: Aggregation with multiple pools/cont.(Cherry-pick 2.2)
  src/tests/ftest/aggregation/multiple_pool_cont.py
  src/tests/ftest/aggregation/multiple_pool_cont.yaml
Labels: clean-cherry-pick, release-2.2

#9546 DAOS-10929 container: fix size of cont_global_version value (#9545)
  src/container/srv_container.c
Labels: clean-cherry-pick, release-2.2

#9620 DAOS-10954 test: Fix for CID 21969
  src/common/tests_dmg_helpers.c
Labels: ast-fixes, release-2.2

#9621 DAOS-10954 test: Fix for CID 21969
  src/common/tests_dmg_helpers.c
Labels: clean-cherry-pick

#9658 DAOS-10820 control: Set system name in set engine log masks RPC (#9471)
  src/control/cmd/dmg/server.go
  src/control/lib/control/server.go
  src/control/server/ctl_ranks_rpc.go
  src/tests/ftest/control/dmg_server_set_logmasks.py
  src/tests/ftest/control/dmg_server_set_logmasks.yaml
  src/tests/ftest/control/dmg_storage_scan_scm.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: control-plane, unclean-cherry-pick, release-2.2, priority

#9666 DAOS-10904 test: Update network scan test to use cxi provider (#9535)
  src/tests/ftest/control/dmg_network_scan.py
  src/tests/ftest/util/network_utils.py
Labels: clean-cherry-pick, release-2.2

#9661 DAOS-10953 test: Detect issue with remove in unit test code (#9613)
  src/common/tests/utest_common.c
  src/vos/tests/vts_mvcc.c
Labels: clean-cherry-pick, release-2.2

#9660 DAOS-11031 control: Clean hugepages on engine startup (#9625)
  src/control/server/instance_exec.go
  src/control/server/instance_exec_test.go
  src/control/server/instance_storage.go
  src/control/server/instance_storage_test.go
  src/control/server/server_utils.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
Labels: control-plane, unclean-cherry-pick, release-2.2

#9622 DAOS-10954 test: Fix for CID 21969
  src/common/tests_dmg_helpers.c
Labels: clean-cherry-pick

#9362 DAOS-10828 mercury: Update to mercury 2.2.0rc6
  debian/changelog
  debian/control
  site_scons/components/__init__.py
  src/cart/crt_hg.c
  utils/build.config
  utils/rpms/daos.spec
Labels: clean-cherry-pick, release-2.2, priority

#9653 DAOS-10372 bio: wait DMA buffer in FIFO order (#9584)
  src/bio/bio_buffer.c
  src/bio/bio_bulk.c
  src/bio/bio_internal.h
  src/bio/bio_xstream.c
  src/tests/ftest/util/telemetry_utils.py
Labels: unclean-cherry-pick, release-2.2

#9610 DAOS-8722 dfuse: Add timeouts to readdir caching.
  docs/user/filesystem.md
  src/client/dfuse/dfuse.h
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/ops/create.c
  src/client/dfuse/ops/open.c
  src/client/dfuse/ops/opendir.c
  src/client/dfuse/ops/readdir.c
Labels: release-2.4, priority

#9686 DAOS-11120 control: Fix block device size display
  src/control/lib/hardware/hwloc/bindings.go
  src/control/lib/hardware/hwloc/provider_test.go
Labels: release-2.2, release-2.4

#9687 DAOS-11120 control: Fix block device size display
  src/control/lib/hardware/hwloc/bindings.go
  src/control/lib/hardware/hwloc/provider_test.go
Labels: clean-cherry-pick, priority

#9609 DAOS-10961 vos: dynamically allocate space for DTX commit
  src/vos/vos_dtx.c
Labels: ast-fixes

#9063 DAOS-10595 build: Update SPDK to v22.01.1
  debian/changelog
  debian/control
  src/bio/bio_device.c
  src/bio/bio_monitor.c
  src/control/server/storage/bdev/backend_vmd.go
  src/control/server/storage/bdev/backend_vmd_test.go
  utils/build.config
  utils/rpms/daos.spec
Labels: release-2.4, priority

#9641 DAOS-10003 test: Add network failure and target failure tests - release/2.2 (#8977)
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/network_failure.yaml
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/util/network_utils.py
  src/tests/ftest/util/test_utils_container.py
Labels: clean-cherry-pick, release-2.2

#9670 DAOS-10534 test: improve nvme/fault.py (#8982)
  src/tests/ftest/nvme/fault.py
  src/tests/ftest/nvme/fault.yaml
  src/tests/ftest/util/nvme_utils.py
Labels: clean-cherry-pick, priority

#9690 DAOS-9820 test: simplify datamover test base (#8109)
  src/tests/ftest/soak/utils.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/data_mover_utils.py
  src/tests/ftest/util/duns_utils.py
Labels: clean-cherry-pick, priority

#9712 DAOS-11141 build: Use githash for patch rather than branch
  utils/build.config
Labels: release-2.2

#9709 DAOS-10961 vos: dynamically allocate space for DTX commit
  src/vos/vos_dtx.c
Labels: clean-cherry-pick, release-2.0

#9693 DAOS-10348 object: clone sub requests for CPD RPC
  src/include/daos/object.h
  src/object/obj_rpc.h
  src/object/obj_tx.c
  src/object/srv_obj.c
  src/object/srv_obj_remote.c
Labels: release-2.2

#9699 DAOS-10961 vos: dynamically allocate space for DTX commit
  src/vos/vos_dtx.c
Labels: ast-fixes, release-2.2

#9458 DAOS-10743 dtx: test case for handle DTX commit failure
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos/common.h
  src/tests/suite/daos_base_tx.c
Labels: priority

#9600 DAOS-10970 tests, ftest, object, dfuse: multiple coverity issues
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/il/int_posix.c
  src/common/tests_lib.c
  src/object/srv_obj.c
  src/tests/ftest/cart/threaded_server.c
  src/tests/ftest/cart/utest/utest_hlc.c
  src/tests/simple_obj.c
  src/tests/suite/daos_test.c
  src/tests/suite/dfs_test.c
  src/vea/tests/vea_stress.c
  src/vos/tests/vts_dtx.c
Labels: unclean-cherry-pick

#9033 DAOS-10331 test: Cherry-pick 2.2: Update the rf, objectclass and pool_fillup.(#8951)
  src/tests/ftest/osa/offline_drain.yaml
  src/tests/ftest/osa/offline_reintegration.yaml
Labels: clean-cherry-pick, release-2.2

#9704 DAOS-10953 test: Detect issue with remove in unit test code (#9613)
  src/common/tests/utest_common.c
  src/vos/tests/vts_mvcc.c
Labels: ast-fixes, clean-cherry-pick, release-2.0

#9245 DAOS-10500 test: nvme/health.py: increase pool capacity (#9066)
  src/tests/ftest/nvme/health.py
  src/tests/ftest/nvme/health.yaml
Labels: clean-cherry-pick, release-2.0

#9720 DAOS-10300 test: fix dmg_pool_query
  src/tests/ftest/control/dmg_pool_query_test.py
Labels: release-2.2

#9718 DAOS-10595 build: Update SPDK to v22.01.1 (#9063)
  debian/changelog
  debian/control
  src/bio/bio_device.c
  src/bio/bio_monitor.c
  src/control/server/storage/bdev/backend_vmd.go
  src/control/server/storage/bdev/backend_vmd_test.go
  utils/build.config
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, release-2.2

#9719 DAOS-10736 Cart: Add support for UCX tcp transport
  src/cart/crt_hg.c
  src/cart/crt_hg.h
Labels: clean-cherry-pick, release-2.2

#9601 DAOS-10970 coverity: tests, ftest, object, dfuse: multiple coverity issues
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/il/int_posix.c
  src/common/tests_lib.c
  src/object/srv_obj.c
  src/tests/ftest/cart/threaded_server.c
  src/tests/ftest/cart/utest/utest_hlc.c
  src/tests/simple_obj.c
  src/tests/suite/daos_test.c
  src/tests/suite/dfs_test.c
  src/vea/tests/vea_stress.c
  src/vos/tests/vts_dtx.c
Labels: unclean-cherry-pick

#9572 DAOS-10960 pool,container,rsvc: fix Coverity null deref issue
  src/common/rsvc.c
  src/pool/srv_pool.c
Labels: ast-fixes, clean-cherry-pick, release-2.0

#9316 DAOS-10743 dtx: not rollback partially committed DTX
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos/common.h
  src/tests/suite/daos_base_tx.c
Labels: release-2.2, priority

#9706 CORCI-1200 Build: Collect Job Information to YAML
  Jenkinsfile
Labels: unclean-cherry-pick

#9632 DAOS-10984 DFS: fix coverity ID 105871, 119081 (#9594)
  src/client/dfs/dfs.c
Labels: clean-cherry-pick

#9643 DAOS-10984 DFS: fix coverity ID 105871, 119081
  src/client/dfs/dfs.c
Labels: clean-cherry-pick

#9731 DAOS-11001 dfuse: Remove unused test code. (#9607) (#9638)
  src/client/dfuse/SConscript
  src/client/dfuse/test/SConscript
  src/client/dfuse/test/test_ioil.c
Labels: clean-cherry-pick

#9649 DAOS-10471 pool: support older pool_hdl format
  src/pool/srv_pool.c
Labels: release-2.2, priority

#9736 DAOS-7267 build: remove openpa dependency
  SConstruct
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes_UBUNTU_20_04.sh
  debian/changelog
  site_scons/compiler_setup.py
  site_scons/components/__init__.py
  src/cart/utils/build-master.config
  utils/build.config
  utils/check/handle_rpms.sh
  utils/rpms/daos.spec
Labels: clean-cherry-pick

#8662 DAOS-9820 test: make large datamover tests more configurable
  src/tests/ftest/datamover/large_dir.py
  src/tests/ftest/datamover/large_dir.yaml
  src/tests/ftest/datamover/large_file.py
  src/tests/ftest/datamover/large_file.yaml
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/data_mover_utils.py
Labels: priority

#9636 DAOS-11077 dfs: fix mtime accounting for user set mtime
  src/cart/crt_hlc.c
  src/client/dfs/README.md
  src/client/dfs/dfs.c
  src/include/cart/api.h
  src/tests/suite/dfs_unit_test.c
Labels: release-2.2, priority

#9614 DAOS-11066 dtx: discard old DTX entries during server reintegration
  src/dtx/dtx_resync.c
Labels: release-2.2, priority

#9747 DAOS-9820 test: make large datamover tests more configurable (#8662)
  src/tests/ftest/datamover/large_dir.py
  src/tests/ftest/datamover/large_dir.yaml
  src/tests/ftest/datamover/large_file.py
  src/tests/ftest/datamover/large_file.yaml
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/data_mover_utils.py
Labels: clean-cherry-pick, release-2.2

#9732 DAOS-1452 test: ensure ULTs stacks are dumped when needed (#7768)
  src/tests/ftest/server/daos_server_dump.py
  src/tests/ftest/server/daos_server_dump.yaml
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/server_utils.py
Labels: clean-cherry-pick

#9753 DAOS-10622 pool: Fix ds_pool_get_version for NULL sp_map (#9277)
  src/include/daos_srv/pool.h
  src/rebuild/srv.c
Labels: clean-cherry-pick, release-2.2

#9749 DAOS-10843 test: move ior_intercept_multi_client to HW Large (#9378)
  src/tests/ftest/ior/intercept_multi_client.py
  src/tests/ftest/ior/intercept_multi_client.yaml
  src/tests/ftest/util/ior_intercept_test_base.py
Labels: clean-cherry-pick, release-2.2

#9758 DAOS-6530 test: remove feature tags from dfuse_find_perf (#9715)
  src/tests/ftest/dfuse/find.py
Labels: clean-cherry-pick, release-2.2

#9748 DAOS-10466 test: improve dfusespacecheck (#9015)
  src/tests/ftest/aggregation/dfuse_space_check.py
  src/tests/ftest/aggregation/dfuse_space_check.yaml
Labels: clean-cherry-pick, release-2.2

#9761 DAOS-7757 build: Do not install libnvme_control.a (#9735)
  ci/test_files_to_stash.txt
  src/control/lib/spdk/SConscript
  src/control/run_go_tests.sh
Labels: unclean-cherry-pick

#9760 DAOS-11077 dfs: fix mtime accounting for user set mtime (#9636)
  src/cart/crt_hlc.c
  src/client/dfs/README.md
  src/client/dfs/dfs.c
  src/include/cart/api.h
  src/tests/suite/dfs_unit_test.c
Labels: unclean-cherry-pick, release-2.2

#6939 DAOS-8719 il: Add support for streaming I/O
  src/client/dfuse/SConscript
  src/client/dfuse/il/int_posix.c
  src/client/dfuse/il/intercept.h
  src/client/dfuse/il/ioil.h
  src/client/dfuse/il/ioil_preload.h
  src/gurt/telemetry.c
Labels: release-2.4, priority

#9780 DAOS-7821 gha: Tweak jira reporting script. (#9671)
  .github/workflows/pr-metadata.yml
  ci/jira_query.py
Labels: clean-cherry-pick

#9763 DAOS-11066 dtx: discard old DTX entries during server reintegration (…
  src/dtx/dtx_resync.c
Labels: clean-cherry-pick, release-2.2

#9752 DAOS-10986 pool: Add forgotten s_mutex unlock (#9538)
  src/pool/srv_pool.c
Labels: clean-cherry-pick, release-2.2

#9792 DAOS-11175 control: Add Notice log level
  src/control/cmd/dmg/storage.go
  src/control/lib/control/pool.go
  src/control/logging/defaults.go
  src/control/logging/json.go
  src/control/logging/level.go
  src/control/logging/level_test.go
  src/control/logging/logger.go
  src/control/logging/logging_test.go
  src/control/logging/notice.go
  src/control/logging/syslog.go
  src/control/logging/syslog_test.go
  src/control/server/config/server.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/server_utils.go
  src/control/server/telemetry.go
Labels: control-plane

#9688 DAOS-10599 test: Fix bullseye report (#9114)
  site_scons/prereq_tools/base.py
  src/tests/ftest/util/dfuse_utils.py
Labels: priority

#9754 DAOS-10471 pool: safely compute old format pool_hdl size
  src/pool/srv_pool.c
Labels: release-2.2, priority

#9826 DAOS-6128 doc: add object class naming conventions (#9342)
  src/object/README.md
Labels: release-2.2

#9781 DAOS-11155 test: Increase pool size for container/multiple_delete.py …
  src/tests/ftest/container/multiple_delete.py
  src/tests/ftest/container/multiple_delete.yaml
Labels: clean-cherry-pick, release-2.2

#9488 DAOS-10894 pool: reject pool connection from old clients
  src/container/srv_container.c
  src/include/daos/pool.h
  src/include/daos_srv/pool.h
  src/pool/cli.c
  src/pool/rpc.c
  src/pool/rpc.h
  src/pool/srv_internal.h
  src/pool/srv_layout.c
  src/pool/srv_pool.c
Labels: release-2.2, priority

#9807 DAOS-11170 test: Increase timeout for daos log archiving. (#9741)
  src/tests/ftest/launch.py
Labels: clean-cherry-pick

#9806 DAOS-11193 object: Properly handle object existence check result
  src/object/obj_tx.c
Labels: release-2.4, priority

#9821 DAOS-10967 vos: coverity issue fix (#9681)
  src/vos/evtree.c
Labels: clean-cherry-pick, release-2.0

#9820 DAOS-10967 vos: coverity issue fix (#9681)
  src/vos/evtree.c
Labels: clean-cherry-pick, release-2.2

#9819 DAOS-10968 VOS: error handling fix (#9679)
  src/vos/vos_obj.c
Labels: clean-cherry-pick, release-2.0

#9816 DAOS-10952 object: fix coverity issue for echo_rw (#9680)
  src/object/srv_obj.c
Labels: clean-cherry-pick, release-2.2

#9822 DAOS-11073 control: Don't remove pool label during destroy (#9746)
  src/control/lib/control/pool.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
Labels: clean-cherry-pick, release-2.2

#9823 DAOS-11175 control: Add Notice log level (#9792)
  src/control/cmd/dmg/storage.go
  src/control/lib/control/pool.go
  src/control/logging/defaults.go
  src/control/logging/json.go
  src/control/logging/level.go
  src/control/logging/level_test.go
  src/control/logging/logger.go
  src/control/logging/logging_test.go
  src/control/logging/notice.go
  src/control/logging/syslog.go
  src/control/logging/syslog_test.go
  src/control/server/config/server.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/server_utils.go
  src/control/server/telemetry.go
Labels: unclean-cherry-pick, release-2.2

#9770 DAOS-10339 control: Fix pool creation drpc response (#8864)
  src/control/server/mgmt_pool.go
  src/mgmt/srv_drpc.c
  src/tests/ftest/pool/create_query.py
  src/tests/ftest/pool/create_query.yaml
  src/tests/ftest/util/test_utils_pool.py
Labels: clean-cherry-pick, priority

#9678 DAOS-10300 pool: report pool global version for list
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/include/daos/mgmt.h
  src/include/daos_srv/pool.h
  src/mgmt/cli_mgmt.c
  src/mgmt/cont.pb-c.h
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_pool.c
  src/mgmt/tests/mocks.c
  src/object/cli_mod.c
  src/pool/cli.c
  src/pool/rpc.c
  src/pool/rpc.h
  src/pool/srv.c
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/proto/mgmt/pool.proto
  src/tests/ftest/control/dmg_pool_query_test.py
Labels: unclean-cherry-pick, release-2.2, priority

#9769 DAOS-10998 vos: to address Coverity CID 105900 (#9627)
  src/vos/vos_gc.c
Labels: clean-cherry-pick

#9818 DAOS-10968 VOS: error handling fix (#9679)
  src/vos/vos_obj.c
Labels: clean-cherry-pick, release-2.2

#9827 DAOS-10887 test: Increased set of parameters in widely_striped.py
  src/tests/ftest/rebuild/widely_striped.yaml
Labels: release-2.2, priority

#9846 DAOS-10300 build: Fix merge conflict after landing
  src/mgmt/srv_drpc.c
Labels: release-2.2, priority

#9817 DAOS-10952 object: fix coverity issue for echo_rw (#9680)
  src/object/srv_obj.c
Labels: clean-cherry-pick, release-2.0

#9835 DAOS-11193 object: Properly handle object existence check result
  src/object/obj_tx.c
Labels: release-2.2

#9840 DAOS-10471 pool: support older pool_hdl format (#9649)
  src/pool/srv_pool.c
Labels: clean-cherry-pick, release-2.2

#9844 DAOS-10887 test: Increased set of parameters in widely_striped.py (#9827)
  src/tests/ftest/rebuild/widely_striped.yaml
Labels: clean-cherry-pick, release-2.2, priority

#9832 DAOS-9898 tests: Add ior/mdtest-easy to basic_checkout.py (#9397)
  src/tests/ftest/deployment/basic_checkout.py
  src/tests/ftest/deployment/basic_checkout.yaml
  src/tests/ftest/util/performance_test_base.py
Labels: clean-cherry-pick, priority

#9833 DAOS-9898 tests: Small improvements in test yaml (#9542)
  src/tests/ftest/deployment/basic_checkout.yaml
Labels: clean-cherry-pick, priority
