Repository daos-stack/daos, pull requests merged in 2022-09, with the labels that each got.

#10113 DAOS-11232 vos: Add some instrumentation to aggregation
  src/vos/vos_aggregate.c
Labels: release-2.2, priority

#10138 DAOS-11480 dfs: fix for coverity issues 119081, 119136, 105926, 105915
  src/client/dfs/dfs.c
Labels: release-2.2, priority

#10147 DAOS-11480 dfs: fix for coverity issues
  src/client/dfs/dfs.c
Labels: clean-cherry-pick, release-2.2, priority

#10150 DAOS-11171 test: add dfuse mtime unit tests (#9778)
  src/client/dfuse/dfuse_fuseops.c
  src/tests/ftest/daos_test/dfuse.py
  src/tests/suite/dfuse_test.c
Labels: unclean-cherry-pick, release-2.2, priority

#10155 DAOS-11443 test: fix set_environment() (#10060)
  src/tests/ftest/util/command_utils.py
Labels: clean-cherry-pick

#10107 DAOS-11465 dfs: fix dfs_open for directories without O_EXCL
  src/client/dfs/dfs.c
  src/tests/suite/dfs_par_test.c
Labels: release-2.4, priority

#10123 DAOS-11160 test: Fixing Misspelling of 'Sending' (#9993)
  src/tests/ftest/cart/no_pmix_corpc_errors.c
  src/tests/ftest/cart/no_pmix_group_test.c
  src/tests/ftest/cart/no_pmix_group_version.c
Labels: clean-cherry-pick

#10156 DAOS-11486 test: Coverity CID 449352, fix NULL dereference...
  src/tests/suite/daos_test_common.c
Labels: release-2.2, priority

#10134 DAOS-11476 test: Fix coverity unchecked return in jobtest
  src/tests/jobtest.c
Labels: ast-fixes

#10169 DAOS-11494 tests: check return value
  src/tests/suite/daos_rebuild_common.c
Labels: release-2.2, priority

#10168 DAOS-11493 rebuild: check tgts before print
  src/rebuild/srv.c
Labels: release-2.2, release-2.4, priority

#10167 DAOS-11492 object: check return value for dsc_cont_close
  src/object/srv_obj_migrate.c
Labels: release-2.2, release-2.4, priority

#10094 DAOS-11417 rebuild: do not use stable epoch for reclaim
  src/pool/srv_pool.c
  src/rebuild/rebuild_internal.h
  src/rebuild/rpc.h
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/tests/ftest/cart/util/cart_logtest.py
Labels: release-2.2, release-2.4, priority

#10102 DAOS-9355 doc: remove nr_hugepages from QSG
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
Labels: clean-cherry-pick

#10157 DAOS-11486 test: Coverity CID 449352, fix NULL dereference...
  src/tests/suite/daos_test_common.c
Labels: clean-cherry-pick, release-2.2

#10153 DAOS-11478 pool: Coverity CID 105939: check rank list copy
  src/pool/srv_iv.c
Labels: ast-fixes, clean-cherry-pick, release-2.2, priority

#10151 DAOS-11476 test: Fix coverity unchecked return in jobtest
  src/tests/jobtest.c
Labels: ast-fixes, unclean-cherry-pick, release-2.2, priority

#10099 DAOS-11462 doc: document UCX support
  docs/admin/deployment.md
  docs/admin/hardware.md
  docs/admin/ucx.md
  docs/overview/terminology.md
  docs/user/mpi-io.md
  docs/user/spark.md
  utils/config/examples/daos_server_ucx.yml
Labels: release-2.4, priority

#10100 DAOS-11462 doc: document UCX support
  docs/admin/deployment.md
  docs/admin/hardware.md
  docs/admin/ucx.md
  docs/overview/terminology.md
  docs/user/mpi-io.md
  docs/user/spark.md
  utils/config/examples/daos_server_ucx.yml
Labels: clean-cherry-pick, release-2.2

#10148 DAOS-11417 rebuild: do not use stable epoch for reclaim
  src/pool/srv_pool.c
  src/rebuild/rebuild_internal.h
  src/rebuild/rpc.h
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: release-2.2, release-2.4, priority

#9856 DAOS-9827 test: unified container create (#8082)
  src/tests/ftest/container/auto_oc_selection.py
  src/tests/ftest/control/dmg_telemetry_basic.py
  src/tests/ftest/io/parallel_io.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/ior_test_base.py
Labels: clean-cherry-pick, priority

#10174 DAOS-11505 vos: Update durable format version on pool upgrade
  src/include/daos_srv/vos.h
  src/include/daos_srv/vos_types.h
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
  src/rdb/raft_tests/raft_tests.py
  src/tests/vos_engine.c
  src/vos/tests/vts_common.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
  utils/run_test.sh
Labels: ast-fixes, release-2.2

#10159 DAOS-11488 object: resolve some coverity issues
  src/dtx/dtx_rpc.c
  src/object/cli_obj.c
  src/object/obj_tx.c
Labels: release-2.2, release-2.4, priority

#10055 DAOS-9815 object: some refine related with EC obj aggregation (#9903)
  src/tests/ftest/erasurecode/rebuild_disabled.py
  src/tests/ftest/erasurecode/rebuild_disabled.yaml
  src/tests/ftest/erasurecode/rebuild_fio.py
  src/tests/ftest/erasurecode/rebuild_fio.yaml
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/test_utils_pool.py
  src/vos/evtree.c
Labels: unclean-cherry-pick, release-2.0

#10120 DAOS-10524 object: skip extending shards for update shards check
  src/object/cli_obj.c
  src/object/obj_tx.c
Labels: release-2.4, priority

#10181 DAOS-11232 vos: Add some instrumentation to aggregation (#10113)
  src/vos/vos_aggregate.c
Labels: clean-cherry-pick, release-2.2

#10184 DAOS-11505 vos: Update durable format version on pool upgrade (#10174)
  src/include/daos_srv/vos.h
  src/include/daos_srv/vos_types.h
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
  src/rdb/raft_tests/raft_tests.py
  src/tests/vos_engine.c
  src/vos/tests/vts_common.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
  utils/run_test.sh
Labels: ast-fixes, unclean-cherry-pick, release-2.2

#10191 DAOS-11492 object: check return value for dsc_cont_close (#10167)
  src/object/srv_obj_migrate.c
  src/rebuild/srv.c
  src/tests/suite/daos_rebuild_common.c
Labels: release-2.2, release-2.4

#10190 DAOS-11491 object: echo_rw only supports one iod
  src/object/srv_obj.c
Labels: release-2.2, release-2.4, priority

#10180 DAOS-11490 erasure code: Fix Coverity issue with integer overflow.
  src/object/srv_ec_aggregate.c
Labels: release-2.2, release-2.4, priority

#10193 DAOS-11488 object: resolve some coverity issues
  src/dtx/dtx_rpc.c
  src/object/cli_obj.c
  src/object/obj_tx.c
Labels: clean-cherry-pick, release-2.2, release-2.4

#10152 DAOS-11477 pool: Coverity CIDs 105913/105918 always free prop
  src/pool/srv_pool.c
Labels: ast-fixes, release-2.2, priority

#10192 DAOS-11522 common: Address overflow in bit shift operation
  src/common/fail_loc.c
Labels: ast-fixes

#10130 DAOS-9602 chk: verify container label
  src/chk/chk_engine.c
  src/chk/chk_upcall.c
  src/container/srv_container.c
  src/include/daos/common.h
  src/include/daos_srv/container.h
Labels: CR

#10122 DAOS-11393 control: Log numa stats after hugepage cleanup
  src/control/server/config/server.go
  src/control/server/server_utils.go
  src/control/server/storage/bdev/backend.go
Labels: control-plane

#10205 DAOS-11491 object: echo_rw only supports one iod (#10190)
  src/object/srv_obj.c
Labels: clean-cherry-pick, release-2.2

#10197 DAOS-11380 rebuild: set rebuild complete status
  src/rebuild/srv.c
Labels: release-2.4

#10163 DAOS-11480 dfs: fix for coverity issues
  src/client/dfs/dfs.c
Labels: priority, release-2.0

#9855 DAOS-9827 test: datamover: use get_container (#9768)
  src/tests/ftest/datamover/copy_procs.py
  src/tests/ftest/datamover/dst_create.py
  src/tests/ftest/datamover/large_dir.py
  src/tests/ftest/datamover/large_file.py
  src/tests/ftest/datamover/negative.py
  src/tests/ftest/datamover/negative_space.py
  src/tests/ftest/datamover/obj_large_posix.py
  src/tests/ftest/datamover/obj_small.py
  src/tests/ftest/datamover/posix_meta_entry.py
  src/tests/ftest/datamover/posix_preserve_props.py
  src/tests/ftest/datamover/posix_subsets.py
  src/tests/ftest/datamover/posix_symlinks.py
  src/tests/ftest/datamover/posix_types.py
  src/tests/ftest/datamover/serial_large_posix.py
  src/tests/ftest/datamover/serial_small.py
  src/tests/ftest/deployment/basic_checkout.py
  src/tests/ftest/deployment/io_sys_admin.py
  src/tests/ftest/util/data_mover_test_base.py
Labels: unclean-cherry-pick, priority

#10216 DAOS-11532 test: Increase unit test timeout (#10211)
  Jenkinsfile
Labels: unclean-cherry-pick

#10161 DAOS-11241 object: fix a bug of req_reasbed flag
  src/object/cli_obj.c
  src/tests/perf_common.c
Labels: priority

#10206 DAOS-11490 erasure code: Fix Coverity issue with integer overflow. (#…
  src/object/srv_ec_aggregate.c
Labels: clean-cherry-pick, release-2.2, release-2.4

#10154 DAOS-11485 object, tests: fixed several coverity issues
  src/object/srv_obj_migrate.c
  src/tests/ftest/cart/utest/utest_swim.c
  src/tests/suite/daos_rebuild_common.c
Labels: release-2.2, priority

#10172 DAOS-11485 object, tests: fixed several coverity issues
  src/object/srv_obj_migrate.c
  src/tests/ftest/cart/utest/utest_swim.c
  src/tests/suite/daos_rebuild_common.c
Labels: release-2.2

#10217 DAOS-11527 tests: Check return value in cart test
  src/tests/ftest/cart/common.h
  src/tests/ftest/cart/threaded_server.c
Labels: ast-fixes

#10221 DAOS-11423 object: Set EC cell alignment to 32 bytes
  src/include/daos/object.h
Labels: priority

#10199 DAOS-11241 object: fix a task err handling bug
  src/object/cli_obj.c
Labels: priority

#10185 DAOS-11465 dfs: fix dfs_open for directories without O_EXCL (#10107)
  src/client/dfs/dfs.c
  src/tests/suite/dfs_par_test.c
Labels: unclean-cherry-pick, release-2.4

#9848 DAOS-11189 test: support multiple dfuse instances
  src/tests/ftest/dfuse/bash.py
  src/tests/ftest/dfuse/find.py
  src/tests/ftest/util/dfuse_test_base.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/ior_test_base.py
Labels: priority

#10215 DAOS-11540 tests: only free line upon exit in verify_state_in_log()
  src/tests/suite/daos_test_common.c
Labels: release-2.2, release-2.4, priority

#9896 DAOS-11182 test: Increase timeout for pool/create_all_hw.py (#9815)
  src/tests/ftest/pool/create_all_hw.yaml
Labels: clean-cherry-pick, priority, forced-landing

#10220 DAOS-11434 test: Fix segfault in dmg test helper (#10140)
  src/common/tests_dmg_helpers.c
Labels: clean-cherry-pick, priority

#10246 DAOS-11540 tests: only free line upon exit in verify_state_in_log()
  src/tests/suite/daos_test_common.c
Labels: release-2.2, release-2.4

#10236 DAOS-11232 vos: Remove unecessary and incorrect assertion
  src/vos/vos_aggregate.c
Labels: release-2.2, priority

#10237 DAOS-11232 vos: Remove unecessary and incorrect assertion (#10236)
  src/vos/vos_aggregate.c
Labels: clean-cherry-pick, release-2.2, priority

#10238 DAOS-11232 vos: Remove unecessary and incorrect assertion (#10236)
  src/vos/vos_aggregate.c
Labels: unclean-cherry-pick

#10202 DAOS-11477 pool: pool_prop_read() to free daos_prop_t upon error
  src/pool/srv_pool.c
Labels: priority

#10222 DAOS-11423 engine: choose helper randomly
  src/engine/ult.c
Labels: release-2.4, priority

#10213 DAOS-11530 test: fix dfuse_unit return code
  src/tests/ftest/daos_test/dfuse.py
  src/tests/ftest/daos_test/dfuse.yaml
  src/tests/suite/dfuse_test.c
Labels: don't land, unclean-cherry-pick, release-2.2

#10143 DAOS-11472 control: Compare nr backing devs across engines if VMD ena…
  src/control/cmd/daos_server/main.go
  src/control/cmd/daos_server/storage_scm.go
  src/control/cmd/dmg/pretty/storage_nvme.go
  src/control/cmd/dmg/pretty/storage_nvme_test.go
  src/control/lib/control/auto_test.go
  src/control/lib/hardware/pci_test.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/server.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
  src/control/server/storage/bdev/backend_vmd_test.go
  src/control/server/storage/provider.go
Labels: control-plane

#10234 DAOS-11156 test: improve nvme/health.py (#9966)
  src/tests/ftest/nvme/health.py
Labels: clean-cherry-pick, priority

#10227 DAOS-11457 test: support multiple launch.py -e (#10081)
  src/tests/ftest/launch.py
Labels: clean-cherry-pick, priority

#10087 DAOS-11437 test: Support multiple IP addresses per node for test_netw…
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/network_failure.yaml
Labels: release-2.2

#10229 DAOS-11442 test: add option for --bind-to (#10061)
  src/tests/ftest/cart/util/cart_utils.py
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/ior_hard.yaml
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/performance/mdtest_hard.yaml
  src/tests/ftest/soak/utils.py
  src/tests/ftest/util/job_manager_utils.py
Labels: clean-cherry-pick, priority

#9875 DAOS-10830 test: Add recovery/ddb.py to test ddb
  src/tests/ftest/SConscript
  src/tests/ftest/recovery/ddb.py
  src/tests/ftest/recovery/ddb.yaml
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/general_utils.py
  utils/cq/words.dict
Labels: CR

#10139 DAOS-11478 pool: Coverity CID 105939: check rank list copy
  src/pool/srv_iv.c
Labels: ast-fixes, priority

#10258 DAOS-11423 object: cacluate the dkey hash by reply
  src/object/cli_shard.c
Labels: release-2.4, priority

#10255 DAOS-11552 control: Support 2.0/2.2 agent interop
  src/control/build/interop.go
  src/control/build/interop_test.go
  src/control/build/version.go
  src/control/cmd/daos_agent/attachinfo.go
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/cmd/daos_agent/procmon.go
  src/control/lib/control/request.go
  src/control/lib/control/rpc.go
  src/control/server/interceptors.go
  src/control/server/interceptors_test.go
Labels: bug, control-plane, release-2.2

#10263 DAOS-11544 object: RPC interoperability between 2.0 and 2.2
  src/include/daos/object.h
  src/object/obj_rpc.c
  src/object/obj_rpc.h
  src/object/srv_obj_remote.c
Labels: release-2.2

#10248 DAOS-11393 control: Log numa stats after hugepage cleanup (#10122)
  src/control/server/config/server.go
  src/control/server/server_utils.go
  src/control/server/storage/bdev/backend.go
Labels: control-plane, clean-cherry-pick, release-2.2

#10226 DAOS-11473 control: Fix VMD domain parsing (#10145)
  src/control/lib/hardware/pci.go
  src/control/lib/hardware/pci_test.go
Labels: priority

#10265 DAOS-11522 control: Allow server/agent interop across minor versions
  src/control/build/interop.go
  src/control/build/interop_test.go
  src/control/build/version.go
  src/control/server/interceptors.go
  src/control/server/interceptors_test.go
Labels: release-2.4, priority

#9871 DAOS-10885: dmg pool create --size=percentage should allow --ranks
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/control/common/proto/ctl/storage_scm.pb.go
  src/control/lib/control/mocks.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/server/ctl_storage.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/ctl_storage_test.go
  src/control/server/storage/mocks.go
  src/control/server/storage/scm.go
  src/proto/ctl/storage_scm.proto
  src/tests/ftest/pool/create_all_vm.py
  src/tests/ftest/pool/create_all_vm.yaml
  src/tests/ftest/soak/utils.py
  src/tests/ftest/util/pool_create_all_base.py
  utils/ansible/ftest/templates/daos-launch.sh.j2
  utils/ansible/ftest/templates/daos-make.sh.j2
  utils/ansible/ftest/vars/Rocky8.yml
Labels: forced-landing

#10280 DAOS-11565 dfs: fix dfs sys tests to ignore atime setting
  src/include/daos_fs_sys.h
  src/tests/suite/dfs_sys_unit_test.c
Labels: release-2.2, priority

#10125 DAOS-11470 dfs: add proper ctime support
  src/client/dfs/dfs.c
  src/tests/suite/dfs_unit_test.c
Labels: release-2.4, priority

#10292 DAOS-11606 dfs: fix init and fini declaration
  src/client/dfs/dfs_internal.c
  src/include/daos_fs.h
Labels: release-2.2, priority

#10284 DAOS-11595 cart: Fix Coverity CID 449436
  src/cart/crt_swim.c
Labels: release-2.4, priority

#10291 DAOS-11570 tests: do not check if line is NULL
  src/tests/suite/daos_test_common.c
Labels: release-2.2

#10281 DAOS-11596 utils: Fix version check in libdpar.so
  src/include/daos/dpar.h
  src/utils/wrap/mpi/dpar_mpi.c
  src/utils/wrap/mpi/dpar_stub.c
Labels: ast-fixes, release-2.4, priority

#10257 DAOS-11232 tests: Add a vos command line test
  src/vos/tests/SConscript
  src/vos/tests/vos_cmd.c
  src/vos/tests/vos_tests.c
  src/vos/tests/vts_common.h
  src/vos/vos_internal.h
  src/vos/vos_pool.c
  utils/run_test.sh
Labels: release-2.2, priority

#9911 DAOS-11269 test: Update pipeline-lib to enable soak-branch
  ci/provisioning/post_provision_config_common_functions.sh
  ftest.sh
  src/tests/ftest/launch.py
  src/tests/ftest/scripts/main.sh
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/soak/faults.py
  src/tests/ftest/soak/harassers.py
  src/tests/ftest/soak/smoke.py
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress_2h.py
  src/tests/ftest/soak/stress_2h.yaml
  src/tests/ftest/soak/stress_48h.py
  src/tests/ftest/soak/stress_48h.yaml
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: release-2.4, priority

#10300 DAOS-11359 vos: Add subcategory to test suite
  ci/unit/test_main.sh
  src/vos/tests/evt_ctl.sh
  src/vos/tests/vos_tests.c
  src/vos/tests/vts_aggregate.c
  src/vos/tests/vts_checksum.c
  src/vos/tests/vts_container.c
  src/vos/tests/vts_dtx.c
  src/vos/tests/vts_gc.c
  src/vos/tests/vts_ilog.c
  src/vos/tests/vts_io.c
  src/vos/tests/vts_mvcc.c
  src/vos/tests/vts_pm.c
  src/vos/tests/vts_pool.c
  src/vos/tests/vts_ts.c
  utils/run_test.sh
Labels: release-2.2, priority

#10066 DAOS-11450 object: add bulk and vos latency to metrics
  src/include/daos_srv/vos.h
  src/object/srv_internal.h
  src/object/srv_mod.c
  src/object/srv_obj.c
  src/tests/ftest/util/telemetry_utils.py
  src/vos/vos_io.c
Labels: release-2.4, priority

#10285 DAOS-10524 rebuild: skip reclaim job during merge
  src/rebuild/srv.c
Labels: release-2.4, priority

#10294 DAOS-11565 dfs: fix dfs sys tests to ignore atime setting
  src/include/daos_fs_sys.h
  src/tests/suite/dfs_sys_unit_test.c
Labels: clean-cherry-pick, release-2.2, forced-landing

#10293 DAOS-11606 dfs: fix init and fini declaration
  src/client/dfs/dfs_internal.c
  src/include/daos_fs.h
Labels: clean-cherry-pick, release-2.2

#10266 DAOS-11498 mgmt: Fix PS replica leaks (#10162)
  src/include/daos_srv/pool.h
  src/mgmt/srv_internal.h
  src/mgmt/srv_pool.c
  src/mgmt/srv_system.c
  src/mgmt/srv_target.c
  src/mgmt/srv_util.c
  src/pool/README.md
  src/pool/srv_pool.c
Labels: unclean-cherry-pick, priority

#10311 DAOS-10454 test: improve rebuild_widely_striped (#8863)
  src/tests/ftest/rebuild/widely_striped.py
  src/tests/ftest/rebuild/widely_striped.yaml
Labels: clean-cherry-pick

#10288 DAOS-11602 vos: fix some DTX visibility issues
  src/vos/vos_dtx.c
Labels: release-2.4, priority

#10325 DAOS-11609 test: increase rebuild/cascading_failures timeout (#10307)
  src/tests/ftest/rebuild/cascading_failures.yaml
Labels: clean-cherry-pick, priority

#10298 DAOS-8464 test: Test lots of pool connections (#8605)
  src/tests/ftest/container/boundary.py
  src/tests/ftest/container/boundary.yaml
Labels: unclean-cherry-pick, release-2.2

#10306 DAOS-10659 test: Remove extra container created by ior/hard_rebuild.py
  src/tests/ftest/ior/hard_rebuild.py
Labels: forced-landing

#10303 DAOS-11446 object: check DER_NEED_TX when convert to distributed TX
  src/object/obj_tx.c
Labels: priority

#10250 DAOS-11146 gurt: don't hold lock for d_hhash_link_{get,put}ref
  src/gurt/hash.c
Labels: release-2.4, priority

#10158 DAOS-10376 test: datamover: use -E -X -G 27 (#8737)
  src/tests/ftest/datamover/large_dir.py
  src/tests/ftest/datamover/large_dir.yaml
  src/tests/ftest/datamover/obj_large_posix.py
  src/tests/ftest/datamover/obj_large_posix.yaml
  src/tests/ftest/datamover/serial_large_posix.py
  src/tests/ftest/datamover/serial_large_posix.yaml
Labels: unclean-cherry-pick, priority, forced-landing

#10283 DAOS-11552 control: Interop rule processing fixes
  src/control/build/interop.go
  src/control/build/interop_test.go
  src/control/build/version.go
  src/control/build/version_test.go
Labels: release-2.2, priority

#10304 DAOS-11446 object: check DER_NEED_TX when convert to distributed TX
  src/object/obj_tx.c
Labels: clean-cherry-pick, release-2.2, priority

#10131 DAOS-8012 tests: allow test_daos_server_dump_basic to run in CI (#9219)
  src/tests/ftest/server/daos_server_dump.py
Labels: clean-cherry-pick

#10337 DAOS-11642 container: 2.2 client -> 2.0 engine: use pool RF 0
  src/include/daos_prop.h
  src/pool/cli.c
  src/pool/srv_layout.c
  src/pool/srv_pool.c
Labels: release-2.2, priority

#10348 DAOS-10919 test: Fix io_verification tests (use container label) (#10095)
  src/tests/ftest/nvme/io_verification.py
Labels: clean-cherry-pick

#10313 DAOS-11557 container: fix assertion in dc_cont_free() (#10261)
  src/container/cli.c
  src/container/cli_internal.h
  src/container/srv_cli.c
  src/include/daos/common.h
  src/object/cli_obj.c
  src/object/obj_verify.c
  src/tests/suite/daos_container.c
Labels: priority

#10343 DAOS-11660 tests: Address coverity issues in new VOS test
  src/vos/tests/vos_cmd.c
Labels: ast-fixes, release-2.4, priority

#10352 DAOS-11419 object: handle S object classes when grp_nr is not predefined
  src/object/obj_class.c
Labels: priority

#10354 DAOS-11623 test: Fix cmocka_utils Leap 15 timeout
  src/tests/ftest/util/cmocka_utils.py
Labels: forced-landing

#10329 DAOS-11453 test: Detect silent daos_test failures (#10084)
  src/tests/ftest/daos_test/dfuse.py
  src/tests/ftest/scripts/post_process_xml.sh
  src/tests/ftest/util/cmocka_utils.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/daos_core_base.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/results_utils.py
Labels: unclean-cherry-pick

#10359 DAOS-11613 cart: fix race condition (#10334)
  src/cart/crt_context.c
  src/cart/crt_group.c
  src/tests/ftest/cart/no_pmix_multi_ctx.c
Labels: unclean-cherry-pick, priority

#10356 DAOS-11419 object: handle S object classes when grp_nr is not predefined
  src/object/obj_class.c
Labels: clean-cherry-pick, priority

#10301 DAOS-11613 test: reproducer for multi EQ / multi thread issue
  src/tests/suite/daos_obj_array.c
Labels: forced-landing

#10355 DAOS-10339 test: Fix inconsitant size test
  src/tests/ftest/pool/list_verbose.py
Labels: priority, forced-landing

#10363 DAOS-11564 test: Update scm_size,nvme_size. (#10357)
  src/tests/ftest/aggregation/multiple_pool_cont.yaml
Labels: clean-cherry-pick, priority

#10321 DAOS-11363 test: Apply threshold for SCM free space check in test (#9…
  src/tests/ftest/container/multiple_delete.py
  src/tests/ftest/container/multiple_delete.yaml
Labels: clean-cherry-pick

#10256 DAOS-11205 test: support access_points_suffix (#9986)
  src/tests/ftest/harness/config.py
  src/tests/ftest/harness/config.yaml
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/server_utils.py
Labels: unclean-cherry-pick, priority, forced-landing

#10371 DAOS-11667 object: fix auto object class selection for RP hints for arrays
  src/object/obj_class.c
  src/tests/suite/daos_obj.c
Labels: release-2.4, priority

#10379 DAOS-10339 test: Fix inconsitant size test (#10355)
  src/tests/ftest/pool/list_verbose.py
Labels: clean-cherry-pick, priority, forced-landing

#10331 DAOS-11400 bio: Meta & WAL layout
  src/bio/bio_wal.h
  src/include/daos_srv/bio.h
Labels: release-2.4, priority, forced-landing

#10427 DAOS-623 build: move the stdatomic.h check after sconslocal.rc is read
  SConstruct
Labels: forced-landing

#10434 DAOS-623 ci: Remove the releasever removal (#10413)
  ci/provisioning/post_provision_config_nodes.sh
Labels: clean-cherry-pick, release-2.2

#10409 DAOS-11231 client: fix memory corruption during query_key
  src/client/array/dc_array.c
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/object/obj_task.c
Labels: release-2.2, priority
