Repository daos-stack/daos, pull requests merged in 2022-08, with the labels that each got.

#9842 DAOS-10029 test: Use python3 for list_tests. (#8911)
  src/tests/ftest/launch.py
  src/tests/ftest/list_tests.py
  utils/sl/pylint3.rc
Labels: clean-cherry-pick

#9857 DAOS-11201 test: Always restart servers when mux'ing server hosts
  src/tests/ftest/erasurecode/offline_rebuild.yaml
  src/tests/ftest/erasurecode/rebuild_disabled.yaml
  src/tests/ftest/erasurecode/rebuild_disabled_single.yaml
Labels: release-2.2, priority

#9834 DAOS-10894 pool: reject pool connection from old clients (#9488)
  src/container/srv_container.c
  src/include/daos/pool.h
  src/include/daos_srv/pool.h
  src/pool/cli.c
  src/pool/rpc.c
  src/pool/rpc.h
  src/pool/srv_internal.h
  src/pool/srv_layout.c
  src/pool/srv_pool.c
Labels: unclean-cherry-pick, release-2.2, priority

#8804 SRE-92 ci: Updates to allow testing images
  Jenkinsfile
  ci/provisioning/post_provision_config.sh
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes_EL_8.sh
  utils/docker/Dockerfile.centos.7
  utils/rpms/Makefile
  utils/rpms/packaging/Dockerfile.mockbuild
  utils/rpms/packaging/Makefile_distro_vars.mk
  utils/rpms/packaging/Makefile_packaging.mk
  utils/rpms/packaging/rpm_chrootbuild
  utils/rpms/packaging/rpmlint--ignore-unused-rpmlintrc.patch
Labels: release-2.4

#9877 DAOS-11201 test: Always restart servers when mux'ing server hosts (#9…
  src/tests/ftest/erasurecode/offline_rebuild.yaml
  src/tests/ftest/erasurecode/rebuild_disabled.yaml
  src/tests/ftest/erasurecode/rebuild_disabled_single.yaml
Labels: unclean-cherry-pick, release-2.2, priority

#9764 DAOS-10998 vos: to address Coverity CID 105900 (#9627)
  src/vos/vos_gc.c
Labels: clean-cherry-pick

#9884 DAOS-11175 control: Add prefix to notice logging
  src/control/cmd/daos_server/start.go
  src/control/cmd/dmg/storage.go
  src/control/lib/control/pool.go
  src/control/logging/notice.go
  src/control/server/config/server.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
Labels: priority

#9828 DAOS-11168 test: Handle BlockingIOError in launch.py (#9767)
  src/tests/ftest/launch.py
Labels: clean-cherry-pick, priority

#9843 DAOS-10596 test: Increase the csum_basic test timeout (#9010)
  src/tests/ftest/checksum/csum_basic.yaml
Labels: priority

#9850 DAOS-11153 test: Increase the mean threshold percentage. (#9802)
  src/tests/ftest/server/metadata.yaml
Labels: clean-cherry-pick, priority

#9858 DAOS-11190 test: Fix deployment/network_failure.py by using NodeSet f…
  src/tests/ftest/deployment/network_failure.py
Labels: clean-cherry-pick, release-2.2

#8887 SRE-92 ci: Updates to allow testing images
  Jenkinsfile
  ci/provisioning/post_provision_config.sh
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes.sh
  ci/provisioning/post_provision_config_nodes_EL_8.sh
  utils/rpms/packaging/rpm_chrootbuild
Labels: unclean-cherry-pick, release-2.2

#8891 SRE-92 ci: Updates to allow testing images
  Jenkinsfile
  ci/provisioning/post_provision_config.sh
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes.sh
  ci/provisioning/post_provision_config_nodes_EL_8.sh
  ci/rpm/test_daos_node.sh
  utils/rpms/packaging/rpm_chrootbuild
  utils/scripts/install-el8.sh
Labels: unclean-cherry-pick, release-2.0

#5111 DAOS-4183 iosrv: mmap()'ed externally alloc'ed ULTs stacks
  ci/unit/test_nlt_node.sh
  docs/admin/predeployment_check.md
  site_scons/prereq_tools/base.py
  src/common/SConscript
  src/common/stack_mmap.c
  src/common/tests/SConscript
  src/common/tests/abt_perf.c
  src/engine/SConscript
  src/engine/init.c
  src/engine/sched.c
  src/engine/srv.c
  src/engine/srv_internal.h
  src/include/daos/debug.h
  src/include/daos/stack_mmap.h
  src/tests/SConscript
  src/tests/ftest/cart/util/cart_logtest.py
  src/tests/ftest/scripts/main.sh
  src/tests/ftest/scripts/setup_nodes.sh
  src/tests/vos_perf.c
  utils/rpms/10-daos_server.conf
Labels: ast-fixes

#9341 DAOS-10803 test: Update the object class and RF. (#7690)
  src/tests/ftest/osa/offline_reintegration.yaml
Labels: unclean-cherry-pick

#9739 DAOS-10300 control: improve pool list output
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/lib/control/pool.go
  src/mgmt/cli_mgmt.c
  src/mgmt/srv_pool.c
Labels: release-2.2, priority

#9838 DAOS-10344 object: fix OID leak in OIT
  src/container/srv_oi_table.c
Labels: release-2.2, priority

#9667 DAOS-11092 bio: restrict inflight ios
  src/bio/bio_buffer.c
  src/bio/bio_context.c
  src/bio/bio_internal.h
  src/bio/bio_xstream.c
Labels: release-2.4, priority

#9744 DAOS-10524 rebuild: master leader changing during rebuild
  src/container/srv_oi_table.c
  src/dtx/dtx_resync.c
  src/include/daos_srv/rebuild.h
  src/placement/pl_map.c
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/rebuild/rebuild_internal.h
  src/rebuild/rebuild_iv.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/vos/vos_obj_cache.c
Labels: release-2.4, priority

#9894 DAOS-10956 test: fail the test for ENOMEM (#9682)
  src/common/tests/btree.c
Labels: clean-cherry-pick

#9399 DAOS-10835 test: enable D_LOG_FILE_APPEND_PID in the client
  src/tests/ftest/launch.py
Labels: release-2.2, priority

#9893 DAOS-10956 test: fail the test for ENOMEM (#9682)
  src/common/tests/btree.c
Labels: clean-cherry-pick

#9934 DAOS-11248 build: don't ship daos-mofed shim RPM
  .rpmignore
Labels: priority

#9935 DAOS-11248 build: don't ship daos-mofed shim RPM (#9934)
  .rpmignore
Labels: clean-cherry-pick

#9936 DAOS-11248 build: don't ship daos-mofed shim RPM (#9934)
  .rpmignore
Labels: clean-cherry-pick

#9937 DAOS-10835 test: enable D_LOG_FILE_APPEND_PID in the client (#9399)
  src/tests/ftest/launch.py
Labels: clean-cherry-pick

#9916 DAOS-10344 object: fix OID leak in OIT (#9838)
  src/container/srv_oi_table.c
Labels: clean-cherry-pick, release-2.2

#9954 DAOS-11146 client: refine lock handling in d_hhash_link_insert()
  src/common/misc.c
  src/gurt/hash.c
  src/include/gurt/hash.h
  src/tests/suite/daos_obj.c
Labels: release-2.2, priority

#9910 DAOS-11232 vos: Add more information on aggregation crash
  src/vos/vos_aggregate.c
Labels: release-2.2, priority

#9923 DAOS-11232 vos: Add more information on aggregation crash
  src/vos/vos_aggregate.c
Labels: clean-cherry-pick, release-2.2

#9930 DAOS-10525 pool: cleanup MAP rank init (#9183)
  src/container/srv_container.c
  src/gurt/misc.c
  src/include/daos/common.h
  src/include/daos_srv/pool.h
  src/include/gurt/common.h
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/pool/srv_util.c
Labels: release-2.4

#9938 DAOS-11180 dtx: re-index committed DTX entries for DTX_CHECK
  src/dtx/dtx_resync.c
  src/dtx/dtx_srv.c
Labels: release-2.2, release-2.4, priority

#9931 DAOS-11295 gurt: increase DD_ENV_MAX_LEN
  src/gurt/debug.c
Labels: release-2.4, priority

#9959 DAOS-623 ci: ticket status need not to be updated to push PRs (#9928)
  ci/jira_query.py
Labels: clean-cherry-pick

#9913 DAOS-11275 mercury: update to 2.2.0
  Jenkinsfile
  debian/changelog
  debian/control
  utils/build.config
  utils/rpms/daos.spec
Labels: release-2.2, release-2.4, priority

#9932 DAOS-11275 mercury: update to 2.2.0
  debian/changelog
  debian/control
  utils/build.config
  utils/rpms/daos.spec
Labels: clean-cherry-pick, release-2.2, release-2.4

#9854 DAOS-10869 test: fix passwdlessssh index error (#9785)
  src/tests/ftest/deployment/critical_integration.py
Labels: clean-cherry-pick, priority

#9962 DAOS-11319 test: fix pylint errors
  src/tests/ftest/deployment/critical_integration.py
  src/vos/storage_estimator/common/explorer.py
Labels: release-2.2

#9918 DAOS-10300 control: improve pool list output (#9739)
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/lib/control/pool.go
  src/mgmt/cli_mgmt.c
  src/mgmt/srv_pool.c
Labels: unclean-cherry-pick, release-2.2, priority

#9631 DAOS-10215 container: set default fault domain level on NODE
  src/container/srv_layout.c
  src/object/cli_obj.c
  src/placement/jump_map.c
  src/placement/pl_map.c
  src/tests/ftest/datamover/dst_create.yaml
  src/tests/ftest/datamover/posix_preserve_props.yaml
  src/tests/ftest/util/daos_utils.py
  src/tests/suite/daos_aggregate_ec.c
  src/tests/suite/daos_obj.c
  src/tests/suite/daos_obj_ec.c
  src/tests/suite/daos_rebuild_common.c
  src/tests/suite/daos_rebuild_ec.c
  src/tests/suite/daos_rebuild_simple.c
  src/tests/suite/daos_test_common.c
  src/tests/suite/dfs_par_test.c
  src/utils/daos_autotest.c
Labels: release-2.4, priority

#9944 DAOS-11031 control: Log details of hugepage cleanup when starting engine
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
Labels: priority

#9861 DAOS-11164 pool: also save credentials in pool handle db
  src/pool/srv_layout.h
  src/pool/srv_pool.c
Labels: release-2.2, release-2.4, priority

#9947 DAOS-11289 build: Fix compiler warning on amd64 clang (#9926)
  src/vos/tests/evt_ctl.c
Labels: clean-cherry-pick, release-2.2

#9958 DAOS-11296 engine: Reduce size of stack used by print_backtrace (#9951)
  src/engine/init.c
Labels: clean-cherry-pick

#9939 DAOS-10157 test: Increase timeout for erasurecode/rebuild_disabled_si…
  src/tests/ftest/erasurecode/rebuild_disabled_single.yaml
Labels: unclean-cherry-pick, release-2.2

#9946 DAOS-11109 test: fix thread_manager usage (#9784)
  src/tests/ftest/server/metadata.py
  src/tests/ftest/server/metadata.yaml
Labels: clean-cherry-pick, priority

#9904 DAOS-11180 dtx: trigger DTX reindex before DTX resync
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_resync.c
  src/dtx/dtx_srv.c
Labels: unclean-cherry-pick, release-2.2, release-2.4

#9903 DAOS-10916 object: some refine related with EC obj aggregation
  src/tests/ftest/erasurecode/rebuild_disabled.py
  src/tests/ftest/erasurecode/rebuild_disabled.yaml
  src/tests/ftest/erasurecode/rebuild_fio.py
  src/tests/ftest/erasurecode/rebuild_fio.yaml
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/test_utils_pool.py
  src/vos/evtree.c
Labels: release-2.2, priority

#8821 DAOS-10233 pool: add fault injection for pool upgrade
  debian/changelog
  debian/daos-client-tests.install
  src/include/daos/common.h
  src/pool/srv_pool.c
  src/tests/suite/SConscript
  src/tests/suite/daos_debug_set_params.c
  utils/rpms/daos.spec
Labels: release-2.2, priority

#9812 DAOS-10607 rebuild: put rebuild obj cache by tgt id
  src/include/daos_srv/daos_engine.h
  src/object/srv_obj_migrate.c
  src/rebuild/rebuild_internal.h
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: release-2.2, priority

#9961 DAOS-11315 tools: Update daos CLI arg handling
  src/control/cmd/daos/container.go
  src/control/cmd/daos/pool.go
  src/tests/ftest/util/daos_utils_base.py
  utils/node_local_test.py
Labels: release-2.2, priority

#9960 DAOS-11311 control: Fix srx_disabled config field
  src/control/server/engine/config.go
  src/control/server/engine/config_test.go
Labels: release-2.2, priority

#9940 DAOS-10916 object: some refine related with EC obj aggregation
  src/object/cli_obj.c
  src/tests/ftest/erasurecode/rebuild_disabled.py
  src/tests/ftest/erasurecode/rebuild_disabled.yaml
  src/tests/ftest/erasurecode/rebuild_fio.py
  src/tests/ftest/erasurecode/rebuild_fio.yaml
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/test_utils_pool.py
  src/vos/evtree.c
Labels: release-2.2

#9984 DAOS-11311 control: Fix srx_disabled config field (#9960)
  src/control/server/engine/config.go
  src/control/server/engine/config_test.go
Labels: clean-cherry-pick, release-2.2, priority

#9976 DAOS-11164 pool: also save credentials in pool handle db (#9861)
  src/pool/srv_layout.h
  src/pool/srv_pool.c
Labels: clean-cherry-pick, release-2.2, release-2.4, priority

#9982 DAOS-10607 rebuild: put rebuild obj cache by tgt id (#9812)
  src/include/daos_srv/daos_engine.h
  src/object/srv_obj_migrate.c
  src/rebuild/rebuild_internal.h
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: clean-cherry-pick, release-2.2

#10015 DAOS-11381 control: Optimize Prometheus metrics exporter (#9983)
  src/control/SConscript
  src/control/cmd/dmg/telemetry.go
  src/control/lib/control/pprof.go
  src/control/lib/control/pprof_stub.go
  src/control/lib/telemetry/promexp/collector.go
  src/control/lib/telemetry/promexp/collector_test.go
  src/control/lib/telemetry/telemetry.go
  src/control/server/server.go
  src/control/server/telemetry.go
  src/tests/ftest/util/telemetry_utils.py
Labels: unclean-cherry-pick

#10028 DAOS-9355 build: fix URL in daos.spec (#10027)
  utils/rpms/daos.spec
Labels: clean-cherry-pick, release-2.2

#10029 DAOS-9355 build: fix URL in daos.spec (#10027)
  utils/rpms/daos.spec
Labels: clean-cherry-pick, release-2.0

#9830 DAOS-11165 test: fix pylint in same_key_different_value (#9762)
  src/tests/ftest/object/same_key_different_value.py
  src/tests/ftest/object/same_key_different_value.yaml
Labels: unclean-cherry-pick, priority

#9996 DAOS-9221 test: pass client variables in yaml (#8628)
  src/tests/ftest/aggregation/basic.yaml
  src/tests/ftest/ior/intercept_basic.yaml
  src/tests/ftest/ior/intercept_messages.py
  src/tests/ftest/ior/intercept_messages.yaml
  src/tests/ftest/ior/intercept_multi_client.yaml
  src/tests/ftest/ior/intercept_verify_data_integrity.yaml
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/daos_racer_utils.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/job_manager_utils.py
Labels: unclean-cherry-pick, priority

#10037 DAOS-623 ci: Clean up spelling errors (#10031)
  ci/codespell.ignores
  docs/admin/troubleshooting.md
  docs/user/container.md
  src/README.md
  src/bio/bio_xstream.c
  src/cart/README.env
  src/cart/crt_iv.c
  src/client/pydaos/pydaos_shim.c
  src/common/cont_props.c
  src/common/prop.c
  src/control/server/mgmt_system.go
  src/control/server/storage/bdev/backend_vmd.go
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/gurt/debug.c
  src/gurt/dlog.c
  src/gurt/examples/telem_producer_example.c
  src/include/cart/api.h
  src/include/daos/btree.h
  src/include/daos/placement.h
  src/include/daos_fs.h
  src/include/daos_obj.h
  src/include/gurt/dlog.h
  src/object/srv_ec_aggregate.c
  src/placement/tests/ring_map_place_obj.c
  src/pool/srv_pool.c
  src/rebuild/rebuild_iv.c
  src/rebuild/srv.c
  src/tests/ftest/cart/group_test/group_test.py
  src/tests/ftest/cart/iv/iv_one_node.py
  src/tests/ftest/cart/util/cart_utils.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/soak/utils.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/thread_manager.py
  src/tests/suite/daos_obj.c
  src/vos/vos_obj_index.c
  src/vos/vos_space.c
  src/vos/vos_ts.h
Labels: unclean-cherry-pick

#10014 DAOS-11419 object: oclass_id2name return oclass name even if not pred…
  src/object/obj_class.c
Labels: release-2.2

#9963 DAOS-11318 bio: one bulk handle per DMA chunk
  src/bio/bio_bulk.c
  src/bio/bio_internal.h
  src/object/srv_obj.c
Labels: release-2.4, priority

#9971 DAOS-10889 doc: document MOFED prereq on IB (#9970)
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
  docs/admin/predeployment_check.md
Labels: unclean-cherry-pick

#9892 DAOS-4891 test: Enable multiple management service replicas (#8217)
  src/tests/ftest/control/ms_failover.py
  src/tests/ftest/control/ms_resilience.py
  src/tests/ftest/pool/destroy.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/test_utils_base.py
Labels: clean-cherry-pick, priority

#9859 DAOS-8465 test: Loop to fill and destroy container and pool.
  src/tests/ftest/container/fill_destroy_loop.py
  src/tests/ftest/container/fill_destroy_loop.yaml
Labels: release-2.2, priority

#9992 DAOS-11151 build: Update pmdk to 1.12.1~rc1
  debian/changelog
  debian/control
  site_scons/components/__init__.py
  utils/build.config
  utils/rpms/daos.spec
Labels: release-2.2, release-2.4, priority

#10033 DAOS-11426 java: Bump hadoop-common in /src/client/java/hadoop-daos (…
  src/client/java/hadoop-daos/pom.xml
Labels: clean-cherry-pick, release-2.0

#10032 DAOS-11426 java: Bump hadoop-common in /src/client/java/hadoop-daos (…
  src/client/java/hadoop-daos/pom.xml
Labels: clean-cherry-pick, release-2.2, release-2.4

#9973 DAOS-10233 pool: add fault injection for pool upgrade (#8821)
  debian/changelog
  debian/daos-client-tests.install
  src/include/daos/common.h
  src/pool/srv_pool.c
  src/tests/SConscript
  src/tests/daos_debug_set_params.c
  src/tests/suite/SConscript
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, release-2.2, priority

#9997 DAOS-11151 build: Update pmdk to 1.12.1~rc1
  debian/changelog
  debian/control
  site_scons/components/__init__.py
  utils/build.config
  utils/docker/Dockerfile.centos.7
  utils/rpms/daos.spec
  utils/scripts/install-centos7.sh
Labels: unclean-cherry-pick, release-2.0

#9998 DAOS-11151 build: Update pmdk to 1.12.1~rc1
  debian/changelog
  debian/control
  site_scons/components/__init__.py
  src/tests/ftest/control/ms_failover.py
  utils/build.config
  utils/rpms/daos.spec
  utils/scripts/install-centos7.sh
Labels: unclean-cherry-pick, release-2.2, release-2.4, priority

#10049 DAOS-11419 object: oclass_id2name return oclass name even if not pred…
  src/include/daos_obj_class.h
  src/object/obj_class.c
Labels: unclean-cherry-pick

#10056 DAOS-11035 dtx: fix some DXT related issues
  src/dtx/dtx_resync.c
  src/vos/vos_dtx.c
  src/vos/vos_dtx_iter.c
Labels: release-2.2, priority

#10072 DAOS-11419 test: update io test to use proper str length for oclass
  src/tests/suite/daos_obj.c
Labels: priority

#10045 DAOS-8465 test: Loop to fill and destroy container and pool. (#9859)
  src/tests/ftest/container/fill_destroy_loop.py
  src/tests/ftest/container/fill_destroy_loop.yaml
Labels: clean-cherry-pick, release-2.2, priority

#10042 DAOS-11237 test: Collect checksum cmocka results (#9909)
  src/tests/ftest/scripts/main.sh
Labels: clean-cherry-pick

#10043 DAOS-10837 test: Move dmg_telemetry_io_basic.py to HW Small (#9952)
  src/tests/ftest/control/dmg_telemetry_io_basic.py
  src/tests/ftest/control/dmg_telemetry_io_basic.yaml
Labels: clean-cherry-pick

#10073 DAOS-11419 test: update io test to use proper str length for oclass
  src/tests/suite/daos_obj.c
Labels: clean-cherry-pick, priority

#10048 DAOS-11433 dfs: fix mtime set to not rely on DAOS HLC
  src/client/dfs/README.md
  src/client/dfs/dfs.c
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/ops/setattr.c
  src/tests/suite/dfs_unit_test.c
Labels: bug, release-2.2, priority

#9778 DAOS-11171 test: add dfuse mtime unit tests
  src/client/dfuse/dfuse_fuseops.c
  src/tests/ftest/daos_test/dfuse.py
  src/tests/suite/dfuse_test.c
Labels: release-2.2, priority

#10067 DAOS-11035 dtx: fix some DXT related issues (#10056)
  src/dtx/dtx_resync.c
  src/vos/vos_dtx.c
  src/vos/vos_dtx_iter.c
Labels: clean-cherry-pick, release-2.2

#10064 DAOS-623 ci: Clean up spelling errors (#10037)
  ci/codespell.ignores
  docs/user/container.md
  src/README.md
  src/bio/bio_xstream.c
  src/cart/README.env
  src/cart/crt_iv.c
  src/client/pydaos/pydaos_shim.c
  src/client/pydaos/raw/daos_api.py
  src/common/cont_props.c
  src/common/prop.c
  src/control/server/storage/bdev/backend_vmd.go
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/gurt/debug.c
  src/gurt/dlog.c
  src/gurt/examples/telem_producer_example.c
  src/include/cart/api.h
  src/include/daos/btree.h
  src/include/daos/placement.h
  src/include/daos_fs.h
  src/include/daos_obj.h
  src/include/gurt/dlog.h
  src/object/cli_obj.c
  src/object/srv_cli.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/placement/tests/ring_map_place_obj.c
  src/rebuild/rebuild_iv.c
  src/rebuild/srv.c
  src/tests/ftest/cart/group_test/group_test.py
  src/tests/ftest/cart/iv/iv_one_node.py
  src/tests/ftest/cart/util/cart_utils.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/security/pool_acl.py
  src/tests/ftest/security/pool_groups.py
  src/tests/ftest/soak/utils.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/thread_manager.py
  src/tests/suite/daos_obj.c
  src/vos/vos_obj_index.c
  src/vos/vos_space.c
  src/vos/vos_ts.h
Labels: unclean-cherry-pick, release-2.0

#9948 DAOS-11231 dtx: handle dependency during task conversion
  src/common/tse.c
  src/object/obj_tx.c
  src/pool/cli.c
Labels: release-2.2, priority

#10088 DAOS-11433 dfs: fix mtime set to not rely on DAOS HLC (#10048)
  src/client/dfs/README.md
  src/client/dfs/dfs.c
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/ops/setattr.c
  src/tests/suite/dfs_unit_test.c
Labels: unclean-cherry-pick, release-2.2, priority

#10000 DAOS-11380 rebuild: set rebuild complete status
  src/rebuild/srv.c
Labels: release-2.4, priority

#9873 DAOS-10524 object: few fixes for multiple group of EC object
  src/object/cli_obj.c
  src/object/srv_ec.c
  src/object/srv_obj_remote.c
Labels: release-2.4, priority

#8704 DAOS-11146 client: reduce lock contention on hash lock
  src/client/api/init.c
  src/common/misc.c
  src/gurt/hash.c
  src/include/daos/common.h
  src/include/gurt/atomic.h
  src/include/gurt/hash.h
  src/tests/suite/daos_obj.c
Labels: release-2.2, priority

#10083 DAOS-11432 test: Fix cmocka post processing with Test-repeat (#10041)
  src/tests/ftest/scripts/main.sh
Labels: clean-cherry-pick

#10035 DAOS-11160 test: Fixing Misspelling of 'Sending' (#9993)
  src/tests/ftest/cart/no_pmix_corpc_errors.c
  src/tests/ftest/cart/no_pmix_group_test.c
  src/tests/ftest/cart/no_pmix_group_version.c
Labels: clean-cherry-pick, priority

#10092 DAOS-623 build: Improve the preprocessing steps (#9390)
  .clang-format
  .flake8
  site_scons/site_tools/extra/extra.py
  src/cart/SConscript
  src/cart/macro_prefix.h_in
  src/tests/ftest/cart/util/cart_logtest.py
  utils/githooks/pre-commit.d/40-clang-format
  utils/sl/fake_scons/SCons/Script/__init__.py
Labels: unclean-cherry-pick

#9957 DAOS-11231 dtx: handle dependency during task conversion
  src/common/tse.c
  src/object/obj_tx.c
  src/pool/cli.c
Labels: release-2.2

#10012 DAOS-11137 cart: Set UCX env var to allow memory allocation.
  src/cart/crt_init.c
  src/gurt/misc.c
  src/include/gurt/common.h
Labels: release-2.2, release-2.4, priority

#10108 DAOS-11146 client: reduce lock contention on hash lock (#8704)
  src/client/api/init.c
  src/common/misc.c
  src/gurt/hash.c
  src/include/daos/common.h
  src/include/gurt/atomic.h
  src/include/gurt/hash.h
  src/tests/suite/daos_obj.c
Labels: clean-cherry-pick, release-2.2

#10038 DAOS-11227 client: Combined tse, map_refresh, and dc_tx fixes
  src/common/tests/sched.c
  src/common/tse.c
  src/container/cli.c
  src/include/daos/common.h
  src/include/daos/pool.h
  src/include/daos_api.h
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_tx.c
  src/pool/cli.c
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/daos_dist_tx.c
  src/tests/suite/daos_pool.c
Labels: clean-cherry-pick, release-2.2

#10132 DAOS-11137 cart: Set UCX env var to allow memory allocation (#10012)
  src/cart/crt_init.c
  src/gurt/misc.c
  src/include/gurt/common.h
Labels: clean-cherry-pick, release-2.2, release-2.4, priority

#10112 DAOS-10488 test: Add dfuse unit test code and call it from ftest. (#7286)
  debian/changelog
  debian/daos-client-tests.install
  src/tests/ftest/daos_test/dfuse.py
  src/tests/ftest/daos_test/dfuse.yaml
  src/tests/ftest/launch.py
  src/tests/suite/SConscript
  src/tests/suite/dfuse_test.c
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, release-2.2

#10068 DAOS-11035 dtx: continue to fix DXT related issues
  src/container/srv_target.c
  src/dtx/dtx_common.c
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
  src/include/daos_srv/dtx_srv.h
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/vos/tests/vts_dtx.c
  src/vos/vos_dtx.c
  src/vos/vos_dtx_iter.c
  src/vos/vos_internal.h
Labels: release-2.2, priority

#10020 DAOS-11265 test: Wait 1 min after bringing up the network in deployme…
  src/tests/ftest/deployment/network_failure.py
Labels: release-2.2

#8737 DAOS-10376 test: datamover: use -E -X -G 27
  src/tests/ftest/datamover/large_dir.py
  src/tests/ftest/datamover/large_dir.yaml
  src/tests/ftest/datamover/obj_large_posix.py
  src/tests/ftest/datamover/obj_large_posix.yaml
  src/tests/ftest/datamover/serial_large_posix.py
  src/tests/ftest/datamover/serial_large_posix.yaml
Labels: priority

#10115 DAOS-11151 build: Update developer PMDK version to 1.12.1
  utils/build.config
Labels: release-2.2, release-2.4, priority

#10116 DAOS-11151 build: Update developer PMDK version to 1.12.1 (#10115)
  utils/build.config
Labels: clean-cherry-pick, release-2.2, release-2.4, priority

#10117 DAOS-11151 build: Update developer PMDK version to 1.12.1
  utils/build.config
Labels: clean-cherry-pick, release-2.0

#9905 DAOS-11241 object: add EC full-stripe and partial update metrics
  src/object/obj_ec.h
  src/object/obj_internal.h
  src/object/srv_ec.c
  src/object/srv_mod.c
  src/object/srv_obj.c
Labels: priority
