Repository daos-stack/daos, pull requests merged in 2023-12, with the labels that each got.

#13376 DAOS-14590 tests: increase test_daos_ec_obj timeout
  src/tests/ftest/daos_test/suite.yaml
Labels: forced-landing

#13363 DAOS-14552 object: trigger inflight condition for sys TLS (#13232)
  src/object/srv_obj_migrate.c
Labels: clean-cherry-pick

#13383 DAOS-13129 vos: refresh lru entry key with DTX epoch renew
  src/dtx/dtx_common.c
  src/include/daos_srv/dtx_srv.h
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/tests/ftest/util/telemetry_utils.py
  src/vos/lru_array.h
  src/vos/tests/vts_ilog.c
  src/vos/vos_dtx.c
Labels: priority

#12566 DAOS-13883 cart: control request_post_init/incr through env vars
  src/cart/crt_hg.c
  src/cart/crt_hg.h
  src/cart/crt_init.c
  src/cart/crt_internal_types.h
Labels: unclean-cherry-pick, forced-landing

#13439 DAOS-14711 dfs: fix coverity 1565890
  src/client/dfs/dfs.c
Labels: clean-cherry-pick

#13419 DAOS-14686 test: ior/crash.py fix race in ci_nhandles check (#13405)
  src/tests/ftest/ior/crash.py
Labels: clean-cherry-pick, forced-landing

#13387 DAOS-14624 gurt: Fix d_rank_list_del and friends (#13317)
  src/cart/crt_group.c
  src/gurt/misc.c
  src/include/gurt/common.h
  src/rdb/rdb_raft.c
Labels: clean-cherry-pick, priority

#13412 DAOS-14413 cart: Cherry-pick several patches for IV operations
  src/cart/crt_hg_proc.c
  src/cart/crt_init.c
  src/cart/crt_internal.h
  src/cart/crt_internal_types.h
  src/cart/crt_iv.c
  src/cart/crt_rpc.h
  src/common/misc.c
  src/container/container_iv.c
  src/container/oid_iv.c
  src/engine/server_iv.c
  src/include/cart/api.h
  src/include/cart/iv.h
  src/include/daos_srv/iv.h
  src/include/gurt/common.h
  src/object/obj_rpc.c
  src/pool/srv_iv.c
  src/rebuild/rebuild_iv.c
  src/tests/ftest/cart/iv_server.c
Labels: unclean-cherry-pick, forced-landing

#13437 DAOS-14716 dfuse: Add a inode lock for readdir and remove assert.
  src/client/dfuse/dfuse.h
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/ops/readdir.c
Labels: unclean-cherry-pick

#13461 DAOS-14732 test: Temporarily remove Test RPMs stages
  Jenkinsfile
Labels: forced-landing

#13426 DAOS-13433 test: increase timeout for dfuse/caching_check (#13355)
  src/tests/ftest/dfuse/caching_check.py
  src/tests/ftest/dfuse/caching_check.yaml
Labels: clean-cherry-pick, priority, forced-landing

#13431 DAOS-14714 vos: return fetch handle only when vos_fetch_begin succeed - b24
  src/vos/vos_io.c
Labels: release-2.4, forced-landing

#13415 DAOS-14450 rebuild: Only print target buffers if there are any (#13127)
  src/rebuild/srv.c
Labels: clean-cherry-pick

#13458 DAOS-14048 test: Avoid dmg_command objects race condition. (#12750)
  src/tests/ftest/util/osa_utils.py
Labels: clean-cherry-pick

#13406 DAOS-14597 test: Pool destroy taking longer
  src/tests/ftest/pool/create_all_hw.yaml
Labels: forced-landing

#13446 DAOS-14590 tests: increase test_daos_ec_obj timeout (#13376)
  src/tests/ftest/daos_test/suite.yaml
Labels: clean-cherry-pick, priority

#13396 DAOS-14020 pool: dup op detection logic disabled, retry tests
  ci/unit/test_nlt_node.sh
  src/common/tests_dmg_helpers.c
  src/container/cli.c
  src/container/srv_container.c
  src/container/srv_epoch.c
  src/container/srv_internal.h
  src/include/daos/common.h
  src/include/daos/tests_lib.h
  src/pool/cli.c
  src/pool/rpc.h
  src/pool/srv_pool.c
  src/tests/suite/daos_container.c
  src/tests/suite/daos_pool.c
  src/tests/suite/daos_rebuild_common.c
Labels: forced-landing

#13455 DAOS-14727 pool: Clean orphaned NVMe blobs on create
  src/mgmt/srv_target.c
Labels: forced-landing

#13382 DAOS-14181 control,bio,mgmt: Return NVMe details over dRPC
  src/bio/bio_config.c
  src/bio/bio_device.c
  src/bio/bio_internal.h
  src/bio/bio_xstream.c
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/pretty/storage.go
  src/control/cmd/dmg/pretty/storage_nvme_test.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/common/proto/ctl/firmware.pb.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/common/proto/ctl/storage_nvme.pb.go
  src/control/common/proto/types_test.go
  src/control/lib/control/mocks.go
  src/control/lib/control/pool.go
  src/control/lib/control/server_meta.go
  src/control/lib/control/server_meta_test.go
  src/control/lib/spdk/ctests/nvme_control_ut.c
  src/control/lib/spdk/include/nvme_control_common.h
  src/control/lib/spdk/nvme_default.go
  src/control/lib/spdk/src/nvme_control_common.c
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_smd_rpc_test.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/instance_drpc.go
  src/control/server/instance_storage_rpc.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_vmd.go
  src/control/server/storage/bdev/provider.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/mocks.go
  src/control/server/storage/provider.go
  src/include/daos_srv/bio.h
  src/include/daos_srv/control.h
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_query.c
  src/proto/ctl/firmware.proto
  src/proto/ctl/smd.proto
  src/proto/ctl/storage_nvme.proto
  src/tests/ftest/control/dmg_storage_query.py
Labels: forced-landing

#13472 DAOS-14726 build: Handle corner case…
  .github/workflows/bash_unit_testing.yml
  .github/workflows/rpm-build-and-test.yml
  ci/gha_functions.sh
Labels: forced-landing

#13310 DAOS-14591 test: Avoid including xml CDATA in the job.log
  src/tests/ftest/util/collection_utils.py
Labels: forced-landing

#13249 SRE-574 Test: Testing hardware failures
  ci/functional/test_main.sh
  ci/functional/test_main_prep_node.sh
Labels: forced-landing

#13474 DAOS-14590 tests: increase test_daos_ec_obj timeout (#13376)
  src/tests/ftest/daos_test/suite.yaml
Labels: clean-cherry-pick, priority

#13465 DAOS-14707 control: Allow multiple agents simultaneously
  src/control/cmd/daos_agent/start.go
  src/control/drpc/drpc_server.go
  src/control/drpc/drpc_server_test.go
  src/control/drpc/fault.go
  src/control/fault/code/codes.go
  utils/test_memcheck.supp
Labels: control-plane, forced-landing

#13527 DAOS-14707 control: Allow multiple agents simultaneously (#13465)
  src/control/cmd/daos_agent/start.go
  src/control/drpc/drpc_server.go
  src/control/drpc/drpc_server_test.go
  src/control/drpc/fault.go
  src/control/fault/code/codes.go
  utils/test_memcheck.supp
Labels: control-plane, clean-cherry-pick, forced-landing

#13514 DAOS-14591 test: Avoid including xml CDATA in the job.log (#13310)
  src/tests/ftest/util/collection_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#13384 DAOS-13129 vos: refresh lru entry key with DTX epoch renew - b24
  src/dtx/dtx_common.c
  src/include/daos_srv/dtx_srv.h
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/tests/ftest/util/telemetry_utils.py
  src/vos/lru_array.h
  src/vos/tests/vts_ilog.c
  src/vos/vos_dtx.c
Labels: release-2.4, forced-landing

#13503 DAOS-14793 control: Fail if VMD has no backing storage
  src/control/server/server_utils_test.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
  src/control/server/storage/bdev/firmware.go
  src/control/server/storage/bdev/firmware_test.go
  src/control/server/storage/faults.go
Labels: control-plane, forced-landing

#13500 DAOS-14748 bio: race in stopping health monitor
  src/bio/bio_internal.h
  src/bio/bio_monitor.c
  src/bio/bio_xstream.c
Labels: forced-landing

#13523 DAOS-14801 mgmt: Fix LedManage dRPC handler response cleanup
  src/mgmt/srv_query.c
Labels: vmd
