Repository daos-stack/daos, pull requests merged in 2023-11, with the labels that each got.

#13110 DAOS-13882 test: Continue archiving on successful hosts.
  src/tests/ftest/control/dmg_network_scan.py
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/harness/core_files.py
  src/tests/ftest/launch.py
  src/tests/ftest/process_core_files.py
  src/tests/ftest/scripts/main.sh
  src/tests/ftest/scripts/post_process_xml.sh
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/util/avocado_utils.py
  src/tests/ftest/util/code_coverage_utils.py
  src/tests/ftest/util/collection_utils.py
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/host_utils.py
  src/tests/ftest/util/launch_utils.py
  src/tests/ftest/util/logger_utils.py
  src/tests/ftest/util/network_utils.py
  src/tests/ftest/util/package_utils.py
  src/tests/ftest/util/results_utils.py
  src/tests/ftest/util/slurm_utils.py
  src/tests/ftest/util/storage_utils.py
  src/tests/ftest/util/user_utils.py
  src/tests/ftest/util/yaml_utils.py
  utils/cq/words.dict
Labels: forced-landing

#13264 DAOS-14251 control: Allow premounted empty tmpfs (#12968)
  src/control/cmd/daos_server/start.go
  src/control/fault/code/codes.go
  src/control/server/config/server.go
  src/control/server/config/server_legacy.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/harness.go
  src/control/server/instance_exec.go
  src/control/server/instance_storage.go
  src/control/server/instance_storage_test.go
  src/control/server/instance_superblock.go
  src/control/server/instance_superblock_test.go
  src/control/server/instance_test.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
  src/control/server/storage/faults.go
Labels: clean-cherry-pick, forced-landing

#13213 DAOS-14537 control: Re-create PMem regions even if state cannot be determined
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/ipmctl_region.go
  src/control/server/storage/scm/ipmctl_test.go
Labels: control-plane

#13304 Revert "DAOS-623 build: Use leap-dnf Docker image"
  utils/docker/Dockerfile.el.8
  utils/docker/Dockerfile.leap.15
  utils/scripts/helpers/repo-helper-el8.sh
  utils/scripts/helpers/repo-helper-leap15.sh
  utils/scripts/install-leap15.sh
Labels: priority

#13218 DAOS-14541 test: remove redundant write_objects_wo_failon
  src/tests/ftest/container/fill_destroy_loop.py
  src/tests/ftest/control/dmg_system_cleanup.py
  src/tests/ftest/pool/evict.py
  src/tests/ftest/rebuild/container_create_race.py
  src/tests/ftest/util/container_rf_test_base.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#13295 DAOS-14588 doc: transaction md description fix
  docs/overview/transaction.md
Labels: forced-landing

#13257 DAOS-14512 tests: add more tests for pil4dfs and bug fix for memory leak
  src/client/dfuse/pil4dfs/int_dfs.c
  src/tests/ftest/dfuse/bash.py
Labels: priority

#13190 pool: cart proto update for dup op detection
  src/include/daos/rpc.h
  src/include/daos_srv/pool.h
  src/include/daos_task.h
  src/pool/cli.c
  src/pool/rpc.c
  src/pool/rpc.h
  src/pool/srv.c
  src/pool/srv_cli.c
  src/pool/srv_internal.h
  src/pool/srv_pool.c
Labels: forced-landing

#13272 DAOS-14418 mercury: Update Mercury and DAOS to handle UCX active message failure.
  utils/build.config
Labels: release-2.4, priority

#13101 DAOS-14052 test: Update cart_logtest usage in launch.py (#13005)
  src/tests/ftest/cart/util/cart_logtest.py
  src/tests/ftest/launch.py
Labels: unclean-cherry-pick, priority

#13319 DAOS-14537 control: Re-create PMem regions even if state cannot be de…
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/ipmctl_region.go
  src/control/server/storage/scm/ipmctl_test.go
Labels: control-plane, clean-cherry-pick, priority, forced-landing

#13323 DAOS-14547 tools: fs copy only needs R for source (#13231)
  src/utils/daos_hdlr.c
Labels: clean-cherry-pick, priority, forced-landing

#13348 DAOS-14640 rebuild: rpt ref leak in rebuild_iv_ent_refresh()
  src/rebuild/rebuild_iv.c
Labels: forced-landing

#13334 DAOS-14322 build: update to libfabric 1.19.0 (#13277)
  utils/build.config
Labels: clean-cherry-pick, forced-landing

#13318 DAOS-14573 bio: Skip role assignment for hotplugged bdev (#13280)
  src/bio/bio_device.c
  src/bio/bio_xstream.c
Labels: control-plane, clean-cherry-pick, priority, forced-landing, meta-on-ssd, hotplug

#13300 DAOS-14526 dtx: do not cleanup DTX with new leader on current target
  src/dtx/dtx_rpc.c
Labels: forced-landing

#13366 DAOS-14052 test: Fix broken merge.
  src/tests/ftest/util/collection_utils.py
Labels: priority, forced-landing

#13293 DAOS-13882 test: Continue archiving on successful hosts. (#13110)
  debian/changelog
  src/tests/ftest/control/dmg_network_scan.py
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/harness/core_files.py
  src/tests/ftest/launch.py
  src/tests/ftest/process_core_files.py
  src/tests/ftest/scripts/main.sh
  src/tests/ftest/scripts/post_process_xml.sh
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/util/avocado_utils.py
  src/tests/ftest/util/code_coverage_utils.py
  src/tests/ftest/util/collection_utils.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/host_utils.py
  src/tests/ftest/util/launch_utils.py
  src/tests/ftest/util/logger_utils.py
  src/tests/ftest/util/network_utils.py
  src/tests/ftest/util/package_utils.py
  src/tests/ftest/util/results_utils.py
  src/tests/ftest/util/slurm_utils.py
  src/tests/ftest/util/storage_utils.py
  src/tests/ftest/util/user_utils.py
  src/tests/ftest/util/yaml_utils.py
  src/tests/ftest/verify_perms.py
  utils/cq/words.dict
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, priority, forced-landing

#13393 DAOS-14658 test: Disable timed builds
  Jenkinsfile
Labels: forced-landing

#13394 DAOS-14658 test: Disable timed builds.
  Jenkinsfile
Labels: forced-landing

#13367 DAOS-14565 build: update to mercury 2.3.1 (#13269)
  debian/changelog
  debian/control
  src/tests/ftest/cart/utest/utest_protocol.c
  utils/build.config
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, priority, forced-landing

#13403 DAOS-14680 ci: Update go suppressions. (#13402)
  src/cart/utils/memcheck-cart.supp
Labels: clean-cherry-pick, forced-landing

#13379 DAOS-14086 test: Fix client logs parsing (#13141)
  src/client/pydaos/raw/conversion.py
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/nvme/enospace.yaml
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/nvme_utils.py
  utils/node_local_test.py
Labels: unclean-cherry-pick, priority

#13342 DAOS-12268 build: don't overwrite LINKFLAGS (#13201)
  src/gurt/tests/SConscript
  src/tests/ftest/cart/utest/SConscript
Labels: unclean-cherry-pick, forced-landing

#12565 DAOS-13883 cart: control request_post_init/incr through env vars
  src/cart/crt_hg.c
  src/cart/crt_hg.h
  src/cart/crt_init.c
  src/cart/crt_internal_types.h
Labels: forced-landing
