Repository daos-stack/daos, pull requests merged in 2023-02, with the labels that each got.

#10024 DAOS-11423 object: remove obj_ec_rw_req_split
  src/object/obj_ec.h
  src/object/obj_internal.h
  src/object/srv_ec.c
  src/object/srv_internal.h
  src/object/srv_obj.c
  src/object/srv_obj_remote.c
  src/tests/suite/daos_obj_ec.c
  src/tests/suite/daos_rebuild_ec.c
Labels: release-2.4, priority

#11336 DAOS-12469 bio: Fix regression preventing LED state return
  src/bio/bio_device.c
Labels: bug, release-2.4

#11315 DAOS-12319 test: invoke ior with clush not orterun
  src/tests/ftest/server/metadata.py
Labels: clean-cherry-pick, forced-landing

#11174 DAOS-11979 docker: fix daos agent with docker
  docs/QSG/docker.md
  utils/docker/vcluster/.env
  utils/docker/vcluster/daos-admin/el8/Dockerfile
  utils/docker/vcluster/daos-admin/el8/daos_control.yml.in
  utils/docker/vcluster/daos-base/el8/Dockerfile
  utils/docker/vcluster/daos-client/el8/Dockerfile
  utils/docker/vcluster/daos-client/el8/daos_agent.yml.in
  utils/docker/vcluster/daos-cm.sh
  utils/docker/vcluster/daos-server/el8/Dockerfile
  utils/docker/vcluster/daos-server/el8/daos_server.yml.in
  utils/docker/vcluster/docker-compose.yml
Labels: unclean-cherry-pick, release-2.2

#11254 DAOS-12306 object: fix a bug of server reject IO incorrectly (#11108)
  src/object/cli_obj.c
  src/tests/suite/daos_obj_ec.c
  src/vos/vos_io.c
Labels: release-2.4, priority

#10745 DAOS-11401 common: umem cache API for tracking dirty pages
  src/bio/bio_wal.c
  src/bio/bio_wal.h
  src/common/dav/dav_iface.c
  src/common/dav/dav_internal.h
  src/common/dav/wal_tx.c
  src/common/mem.c
  src/common/tests/umem_test.c
  src/include/daos/mem.h
  src/include/daos_errno.h
  src/include/daos_srv/pool.h
  src/include/daos_srv/vos.h
  src/object/obj_internal.h
  src/object/srv_obj.c
  src/pool/SConscript
  src/pool/srv_pool_chkpt.c
  src/pool/srv_target.c
  src/vos/vos_pool.c
  utils/run_test.sh
Labels: release-2.4, priority, meta-on-ssd

#11301 DAOS-12443 common: umem unit tests for bmem
  src/common/dav/tx.c
  src/common/dav/wal_tx.c
  src/common/tests/SConscript
  src/common/tests/btree.c
  src/common/tests/btree_direct.c
  src/common/tests/umem_test.c
  src/common/tests/umem_test_bmem.c
  src/common/tests/utest_common.c
  src/common/tests/utest_common.h
  src/vos/tests/evt_ctl.c
Labels: release-2.4, priority

#11337 DAOS-10258 dfs: lookupx should properly set mtime/ctime in stbuf
  src/client/dfs/dfs.c
  src/tests/suite/dfs_unit_test.c
Labels: forced-landing

#11361 DAOS-12558 build: BR libuuid-devel
  utils/rpms/daos.spec
Labels: release-2.4, priority, forced-landing

#11348 DAOS-11964 object: reset the iov off to 0
  src/object/cli_obj.c
  src/object/srv_obj_migrate.c
Labels: release-2.4, priority

#11363 DAOS-12558 build: BR libuuid-devel
  utils/rpms/daos.spec
Labels: release-2.4, forced-landing

#11319 DAOS-12449 engine: Auto-detect MD-on-SSD and LMM db path in engine
  src/bio/bio_xstream.c
  src/common/mem.c
  src/common/tests/umem_test_bmem.c
  src/engine/init.c
  src/engine/srv.c
  src/include/daos/mem.h
  src/vos/tests/vts_wal.c
  src/vos/vos_common.c
  src/vos/vos_internal.h
  src/vos/vos_pool.c
  utils/run_test.sh
Labels: meta-on-ssd

#10631 DAOS-11624 test: Adjust test infrastructure to support md_on_ssd
  Jenkinsfile
  src/bio/SConscript
  src/tests/ftest/launch.py
  src/tests/ftest/server/storage_tiers.py
  src/tests/ftest/server/storage_tiers.yaml
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/server_utils_params.py
  utils/cq/words.dict
Labels: release-2.4, priority

#11297 DAOS-12144 test: improve dfuse mount checking (#10898)
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/run_utils.py
Labels: unclean-cherry-pick, priority

#11267 DAOS-11987 test: Support of SCM tmpfs hugepages
  src/tests/ftest/pool/create_all_hw.py
  src/tests/ftest/pool/create_all_vm.py
  src/tests/ftest/pool/create_all_vm.yaml
  src/tests/ftest/util/pool_create_all_base.py
  utils/ansible/ftest/templates/daos-make.sh.j2
Labels: release-2.4, priority

#11371 DAOS-12499 tools: improve error logging of dfs fs get-attr
  src/control/cmd/daos/filesystem.go
Labels: forced-landing

#11356 DAOS-10258 dfs: lookupx should properly set mtime in stbuf (#11337)
  src/client/dfs/dfs.c
  src/tests/ftest/datamover/posix_meta_entry.py
  src/tests/suite/dfs_unit_test.c
Labels: unclean-cherry-pick, release-2.2

#11304 DAOS-10753 csum: Checksum Scrubber Metrics Update
  docs/overview/data_integrity.md
  src/include/daos_srv/vos.h
  src/pool/srv_pool_scrub_ult.c
  src/vos/vos_pool_scrub.c
Labels: forced-landing

#11295 DAOS-9511 csum: Initial VOS scan counts corrupted values
  src/include/daos_srv/vos.h
  src/pool/srv_pool_scrub_ult.c
  src/vos/tests/pool_scrubbing_tests.c
  src/vos/vos_pool_scrub.c
Labels: forced-landing

#11234 DAOS-12228 docs: Remove info about VMD backing addresses in cfg
  docs/admin/vmd.md
Labels: dependencies, release-2.4, priority, forced-landing, vmd

#11369 DAOS-11625 test: Add new umem unit tests in CI
  ci/test_files_to_stash.txt
  src/common/tests/umem_test_bmem.c
  utils/run_test.sh
Labels: release-2.4, priority

#11343 DAOS-623 test: use dfuse positional args
  src/tests/ftest/util/dfuse_utils.py
Labels: forced-landing

#11391 DAOS-12454 test: fix functional leap 15.4 results name
  src/tests/ftest/launch.py
Labels: priority, forced-landing

#11324 DAOS-7590 test: use container labels with daos by default
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/io_verification.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/test_utils_base.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#11401 DAOS-12228 docs: Remove info about VMD backing addresses in cfg (#11234)
  docs/admin/vmd.md
Labels: clean-cherry-pick, release-2.2, vmd

#11375 DAOS-12074 rebuild: add generation to migrate tls
  src/include/daos_srv/daos_engine.h
  src/object/obj_rpc.h
  src/object/srv_internal.h
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/tests/suite/daos_rebuild_simple.c
Labels: release-2.2, release-2.4, priority

#11374 DAOS-10681 container: add sc_discarding
  src/container/srv_target.c
  src/include/daos_srv/container.h
  src/rebuild/scan.c
Labels: release-2.4, priority

#11290 DAOS-12112 rebuild:rebuild patches port from 2.4
  src/container/container_iv.c
  src/container/srv_container.c
  src/container/srv_target.c
  src/dtx/dtx_resync.c
  src/engine/server_iv.c
  src/include/daos/common.h
  src/include/daos_obj.h
  src/include/daos_srv/iv.h
  src/include/daos_srv/pool.h
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_verify.c
  src/object/srv_internal.h
  src/object/srv_obj_migrate.c
  src/pool/srv_internal.h
  src/pool/srv_iv.c
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/pool/srv_util.c
  src/rebuild/rebuild_internal.h
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: unclean-cherry-pick

#11399 DAOS-12580 test: Fix vos md-on-ssd unit tests
  src/bio/bio_xstream.c
  utils/run_test.sh
Labels: bug, meta-on-ssd

#11389 DAOS-12419 object: missing fill_oid in obj enum (#11272)
  src/object/cli_ec.c
  src/object/srv_obj.c
  src/object/srv_obj_migrate.c
Labels: clean-cherry-pick

#11394 DAOS-12501 container: Container label may not exist.
  src/container/srv_container.c
Labels: release-2.4, priority

#11395 DAOS-12578 test:
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/run_utils.py
  src/tests/ftest/util/server_utils.py
Labels: forced-landing

#11352 DAOS-11403 common: Add unit testing and fix bugs
  src/common/dav/dav_iface.c
  src/common/dav/wal_tx.c
  src/common/mem.c
  src/common/tests/umem_test.c
Labels: release-2.4, priority

#11404 DAOS-12314 build: change ipmctl from v2 to v3
  debian/changelog
  debian/control
  utils/rpms/daos.spec
Labels: release-2.4, priority

#11386 DAOS-12567 control,engine: Fix list-devices for MD-on-SSD
  src/bio/bio_device.c
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/pretty/storage.go
  src/control/cmd/dmg/pretty/storage_nvme_test.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/common/proto/ctl/addons.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/lib/control/server_meta_test.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend_class_test.go
  src/control/server/storage/bdev/backend_json.go
  src/control/server/storage/bdev/backend_json_test.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/config.go
  src/control/server/storage/mocks.go
  src/include/daos_srv/bio.h
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_query.c
  src/proto/ctl/smd.proto
Labels: control-plane, release-2.4, priority, meta-on-ssd

#11281 DAOS-11290 test: Add VMD LED test scripts.
  src/tests/ftest/SConscript
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/vmd/led.py
  src/tests/ftest/vmd/led.yaml
Labels: release-2.4, priority

#11443 DAOS-12633 test: Set provider explicitly
  src/client/api/tests/eq_tests.c
Labels: forced-landing

#11353 DAOS-11964 container: update agg boundary eph
  src/container/srv_container.c
  src/container/srv_target.c
  src/include/daos_srv/container.h
  src/object/srv_obj.c
  src/object/srv_obj_migrate.c
Labels: release-2.4, priority

#11410 DAOS-10681 rebuild: Move debug ahead of dbtree_iter_del
  src/rebuild/scan.c
Labels: release-2.4, priority

#11411 DAOS-5912 rebuild: restore pool map if extend/drain fail
  src/common/pool_map.c
  src/include/daos_srv/rebuild.h
  src/object/srv_obj_migrate.c
  src/pool/srv_pool.c
  src/pool/srv_pool_map.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/tests/suite/daos_drain_simple.c
  src/tests/suite/daos_extend_simple.c
  src/tests/suite/daos_rebuild.c
Labels: release-2.4, priority

#11398 DAOS-12583 vos: flush WAL header explicitly
  src/vos/vos_aggregate.c
  src/vos/vos_container.c
  src/vos/vos_internal.h
Labels: release-2.4, priority

#11441 DAOS-12442 tests: add large transactions to VOS tests for WAL
  src/vos/tests/vts_wal.c
Labels: release-2.4, priority

#11378 DAOS-12454 test: fix leap generation of results.xml,html (#11330)
  src/tests/ftest/launch.py
  src/tests/ftest/util/results_utils.py
Labels: clean-cherry-pick, priority

#11366 DAOS-12551 doc: fix zypper typo (#11365)
  docs/QSG/setup_suse.md
Labels: unclean-cherry-pick

#11384 DAOS-12364 gurt: Delete old metrics shmem region on startup
  src/gurt/telemetry.c
  src/gurt/tests/test_gurt_telem_producer.c
Labels: release-2.4, priority, forced-landing

#11341 DAOS-12144 test: cleanup rougue processes after tests
  src/tests/ftest/harness/advanced.py
  src/tests/ftest/harness/advanced.yaml
  src/tests/ftest/launch.py
Labels: priority

#11360 DAOS-12554 bio: BIO unit tests for WAL
  debian/daos-server-tests.install
  src/bio/SConscript
  src/bio/bio_context.c
  src/bio/bio_wal.c
  src/bio/tests/SConscript
  src/bio/tests/bio_ut.c
  src/bio/tests/bio_ut.h
  src/bio/tests/wal_ut.c
  src/include/daos_srv/bio.h
  src/vos/vos_pool.c
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
  utils/run_test.sh
Labels: release-2.4, priority

#11448 DAOS-7430 test: update sched and eq_test to use cmocka for xml result…
  src/client/api/tests/eq_tests.c
  src/common/tests/sched.c
Labels: forced-landing

#11431 DAOS-12314 build: change ipmctl from v2 to v3 (#11404)
  debian/changelog
  debian/control
  utils/rpms/daos.spec
Labels: release-2.4, priority

#11442 DAOS-12585 build: Remove R: protobuf-c
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#11405 DAOS-12528 cart: enable MR cache by default for CXI (#11351)
  src/cart/crt_init.c
Labels: unclean-cherry-pick, priority, forced-landing

#11357 DAOS-12128 test: fix telemetry expected values
  src/tests/ftest/telemetry/telemetry_pool_metrics.py
Labels: release-2.4, priority

#11460 DAOS-12645 test: Impose a test repeat limit in CI.
  src/tests/ftest/launch.py
Labels: forced-landing

#11461 DAOS-7430 test: update sched and eq_test to use cmocka for xml result…
  src/client/api/tests/eq_tests.c
  src/common/tests/sched.c
Labels: clean-cherry-pick, forced-landing

#11456 DAOS-12144 test: cleanup rougue processes after tests (#11341)
  src/tests/ftest/harness/advanced.py
  src/tests/ftest/harness/advanced.yaml
  src/tests/ftest/launch.py
Labels: unclean-cherry-pick, priority

#11418 DAOS-8844 test: NVMe pool exclude test passed but has TypeError
  src/tests/ftest/nvme/pool_exclude.py
  src/tests/ftest/util/ior_utils.py
Labels: release-2.4, priority

#9238 DAOS-7289 test: Enable online drain tests.
  src/tests/ftest/osa/online_drain.py
Labels: release-2.4, priority

#11454 DAOS-12647 doc: Update LED instructions with custom timeout
  docs/admin/administration.md
  src/bio/README.md
  src/control/cmd/dmg/storage_query.go
Labels: vmd

#11439 DAOS-12387 cart: Improve swim rankless operation
  src/cart/crt_swim.c
  src/cart/swim/swim.c
  src/include/cart/swim.h
Labels: release-2.4, priority

#11425 DAOS-12074 rebuild: add generation to migrate tls (#11375)
  src/include/daos_srv/daos_engine.h
  src/object/obj_internal.h
  src/object/obj_rpc.h
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/tests/suite/daos_rebuild_simple.c
Labels: unclean-cherry-pick, release-2.2, release-2.4

#10440 DAOS-11728 object: refine sgl iov_len handling in EC data recovery
  src/common/misc.c
  src/object/cli_ec.c
  src/object/cli_obj.c
  src/tests/suite/daos_obj_ec.c
Labels: release-2.4, priority

#11397 DAOS-12072 control: Check client cert dir on startup
  src/control/lib/daos/status.go
  src/control/security/config.go
  src/control/security/config_test.go
  src/control/server/security_rpc.go
  src/control/server/security_rpc_test.go
  src/include/daos_errno.h
Labels: release-2.4, priority, forced-landing

#11495 DAOS-12334 control: Remove obsolete checks in SPDK setup script
  src/control/server/init/setup_spdk.sh
Labels: priority

#11099 DAOS-9335 doc: online docfix
  docs/release/updating.md
Labels: forced-landing

#11488 DAOS-12334 control: Do not print spurious errors on SPDK setup
  src/control/server/init/setup_spdk.sh
Labels: control-plane, release-2.2, priority, forced-landing

#11452 DAOS-8714 pool: move pool map transfer outside of the wr lock
  src/pool/srv_pool.c
Labels: release-2.4, priority, forced-landing

#11392 SRE-549 test: Install MOFED ... (#10628)
  ci/provisioning/post_provision_config_common.sh
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes.sh
  ci/provisioning/post_provision_config_nodes_EL_8.sh
Labels: forced-landing

#11477 DAOS-12455 test: Update usage percentage check for nvme/enospace.py
  src/tests/ftest/nvme/enospace.py
Labels: release-2.4, priority

#11483 DAOS-12308 control: Fix dmg system stop RC
  src/control/server/ctl_ranks_rpc.go
  src/control/server/ctl_ranks_rpc_test.go
  src/control/server/instance_drpc.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/system/membership.go
Labels: release-2.4, priority, forced-landing

#11474 DAOS-12645 test: Impose a test repeat limit in CI. (#11460)
  src/tests/ftest/launch.py
Labels: priority

#11464 SRE-1665 test: update ssh-keygen to fix dfuse/sparse_file.py (#11368)
  ci/provisioning/post_provision_config.sh
Labels: clean-cherry-pick

#11413 DAOS-12007 dtx: misc fixes for DTX related issues
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/engine/srv.c
  src/vos/vos_dtx.c
Labels: release-2.4, priority

#11486 DAOS-12631 object: force degrade fetch for EC reintegration
  src/object/srv_obj_migrate.c
  src/tests/suite/daos_rebuild_ec.c
Labels: release-2.4, priority

#11402 DAOS-12584 build: fix d_test_program() method's prototype
  src/common/tests/SConscript
Labels: release-2.4, priority

#11496 DAOS-12501 container: Container label may not exist.
  src/container/srv_container.c
Labels: clean-cherry-pick, priority

#11437 DAOS-11272 test: container label test cases
  src/tests/ftest/container/label.py
  src/tests/ftest/container/label.yaml
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/server_rank_failure.py
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/util/test_utils_container.py
Labels: release-2.4, priority, forced-landing

#11482 DAOS-12572 test: erasurecode rebuild_fio.py ec_online_rebuild_fio aggregation failed to start
  src/tests/ftest/erasurecode/rebuild_fio.py
  src/tests/ftest/erasurecode/rebuild_fio.yaml
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/test_utils_pool.py
Labels: release-2.4, priority

#11527 DAOS-12348 test: Move dfuse/posix_stat.py to hw,medium from vm
  src/tests/ftest/dfuse/posix_stat.py
Labels: release-2.4, priority

#11400 DAOS-12570 test: multi-engine per socket test for the latest DAOS changes
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/server/multiengine_persocket.yaml
  src/tests/ftest/util/general_utils.py
Labels: release-2.4, priority

#11542 DAOS-12612 common: Add properties to control checkpoint behavior
  src/common/prop.c
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool_cont_prop.go
  src/control/lib/daos/pool_property.go
  src/include/daos/pool.h
  src/include/daos_prop.h
  src/include/daos_srv/pool.h
  src/pool/rpc.c
  src/pool/srv_internal.h
  src/pool/srv_iv.c
  src/pool/srv_layout.c
  src/pool/srv_layout.h
  src/pool/srv_pool.c
  src/pool/srv_pool_chkpt.c
  src/pool/srv_target.c
Labels: release-2.4, priority

#11519 DAOS-12558 build: BR libuuid-devel (#11361)
  debian/changelog
  utils/rpms/daos.spec
Labels: release-2.4, priority

#11548 DAOS-12103 cq: Let bandit scan SConscript as well as .py
  ci/bandit.config
  src/tests/suite/SConscript
Labels: release-2.4, priority, forced-landing

#11512 DAOS-12639 object: Revert a change with checksum scrubbing (#11445)
  src/container/srv_target.c
Labels: clean-cherry-pick, release-2.4, priority

#11513 DAOS-12501 container: Container label may not exist. (#11394)
  src/container/srv_container.c
Labels: clean-cherry-pick, release-2.4, priority

#11573 DAOS-12570 test: multiple engine per socket test needs update based on the latest DAOS changes.
  src/tests/ftest/server/multiengine_persocket.yaml
Labels: release-2.4, priority

#11571 DAOS-12570 test: multi-engine per socket test for the latest DAOS changes (#11400)
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/server/multiengine_persocket.yaml
  src/tests/ftest/util/general_utils.py
Labels: release-2.4, priority
