Repository daos-stack/daos, pull requests merged in 2023-06, with the labels that each got.

#12249 DAOS-13409 tools: Ignore D_LOG_FILE=/dev/null
  src/common/debug.c
Labels: release-2.4

#12252 DAOS-13254 il: Update logging for incorrect ioctl size.
  src/client/dfuse/il/int_posix.c
  src/client/dfuse/ops/ioctl.c
  src/pool/cli.c
Labels: release-2.4, priority

#12222 DAOS-13519 control: Control metadata path invalid if no bdevs in cfg
  src/control/server/storage/config.go
  src/control/server/storage/config_test.go
  utils/nlt_server.yaml
Labels: control-plane, meta-on-ssd

#12231 DAOS-13325 test: set wrx for daos_testing on localhost
  src/tests/ftest/launch.py
Labels: priority

#12229 DAOS-12456 test: replace ftest/container/async.py with cmocka test
  src/tests/ftest/container/async.py
  src/tests/ftest/container/async.yaml
  src/tests/ftest/util/test_utils_base.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/util/test_utils_pool.py
  src/tests/suite/daos_container.c
Labels: forced-landing

#12230 DAOS-13200 rebuild: fix reclaim epoch for extend (#12050)
  src/include/daos/placement.h
  src/include/daos_srv/rebuild.h
  src/object/srv_obj_migrate.c
  src/placement/pl_map.c
  src/pool/srv_pool.c
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: unclean-cherry-pick, release-2.2

#11511 DAOS-6540 dfuse: Improve the dfuse multi-user documentation.
  docs/admin/deployment.md
  docs/user/filesystem.md
  docs/user/multi-user-dfuse.md
  src/client/dfuse/dfuse_main.c
Labels: release-2.4, priority

#12273 DAOS-13514 vos: not return non-durable data for solo modification
  src/vos/vos_dtx.c
Labels: release-2.4, priority

#12267 DAOS-13554 test: remove ftest/container/close,create
  src/tests/ftest/container/close.py
  src/tests/ftest/container/close.yaml
  src/tests/ftest/container/create.py
  src/tests/ftest/container/create.yaml
Labels: forced-landing

#12243 DAOS-12750: Update percentage-based pool allocation for md-on-ssd
  src/bio/bio_context.c
  src/bio/bio_internal.h
  src/bio/bio_monitor.c
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/pool_test.go
  src/control/common/file_utils.go
  src/control/common/file_utils_test.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/common/proto/ctl/storage_nvme.pb.go
  src/control/common/proto/ctl/storage_scm.pb.go
  src/control/lib/control/mocks.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/server/ctl_storage.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/harness.go
  src/control/server/instance_drpc.go
  src/control/server/instance_test.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm.go
  src/include/daos_srv/bio.h
  src/include/daos_srv/control.h
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_query.c
  src/proto/ctl/smd.proto
  src/proto/ctl/storage_nvme.proto
  src/proto/ctl/storage_scm.proto
  src/tests/ftest/pool/create_all_hw.py
  src/tests/ftest/pool/create_all_hw.yaml
  src/tests/ftest/pool/create_all_vm.py
  src/tests/ftest/pool/create_all_vm.yaml
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/pool_create_all_base.py
  utils/ansible/ftest/tasks/el8/devs_dependencies.yml
  utils/ansible/ftest/templates/daos-launch.sh.j2
  utils/ansible/ftest/vars/Rocky8.yml
Labels: bug, release-2.4, priority, meta-on-ssd

#12289 DAOS-623 build: move master branch to 2.6 test builds
  TAG
  VERSION
  debian/changelog
  docs/index.md
  mkdocs.yml
  utils/rpms/daos.spec
Labels: don't land

#12139 DAOS-13403 test: verify reliability and serviceability in logs
  src/tests/ftest/container/basic_snapshot.py
  src/tests/ftest/container/snapshot.py
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/ftest/control/dmg_telemetry_basic.py
  src/tests/ftest/control/log_entry.py
  src/tests/ftest/control/log_entry.yaml
  src/tests/ftest/control/ms_failover.py
  src/tests/ftest/control/ms_resilience.py
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/critical_integration.py
  src/tests/ftest/object/integrity.py
  src/tests/ftest/pool/api_attribute.py
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/soak_test_base.py
Labels: forced-landing

#12260 DAOS-13089 control: Fix debounce evt unit test race
  src/control/events/pubsub_test.go
Labels: bug, control-plane

#12302 DAOS-13592 gurt: Fix race in d_log_setmasks (#12287)
  src/gurt/dlog.c
Labels: clean-cherry-pick, priority

#12305 DAOS-13558 control: Fix bdev count check on scan with vmd
  src/control/lib/control/auto.go
  src/control/lib/hardware/pci.go
  src/control/lib/hardware/pci_test.go
  src/control/lib/spdk/spdk.go
  src/control/lib/spdk/spdk_default.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend_vmd.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/provider.go
  src/control/server/storage/provider_test.go
Labels: bug, control-plane

#12172 DAOS-13326 doc: Update Predeployment Checklist for server helper
  docs/admin/predeployment_check.md
Labels: forced-landing

#12314 DAOS-13403 test: verify reliability and serviceability in logs (#12139)
  src/tests/ftest/container/basic_snapshot.py
  src/tests/ftest/container/snapshot.py
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/ftest/control/dmg_telemetry_basic.py
  src/tests/ftest/control/log_entry.py
  src/tests/ftest/control/log_entry.yaml
  src/tests/ftest/control/ms_failover.py
  src/tests/ftest/control/ms_resilience.py
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/critical_integration.py
  src/tests/ftest/object/integrity.py
  src/tests/ftest/pool/api_attribute.py
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/soak_test_base.py
Labels: clean-cherry-pick, priority, forced-landing

#12316 DAOS-13592 gurt: Fix race in d_log_setmasks (#12287)
  src/gurt/dlog.c
Labels: clean-cherry-pick, priority

#12269 DAOS-13557 control: Set control_metadata path in example MD-on-SSD co…
  src/control/server/storage/faults.go
  utils/config/examples/daos_server_mdonssd.yml
Labels: control-plane, release-2.4

#12242 DAOS-13047 chk: properly handle start options
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_leader.c
  src/tests/ftest/recovery/pass_1.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: CR

#12320 DAOS-13603 common: Fix bug in ad_mem with open/create
  src/common/ad_mem.c
Labels: release-2.4, priority

#12337 DAOS-13605 test: Fix RAM mem test for dmg_pool_query (#12313)
  src/tests/ftest/control/dmg_pool_query_test.yaml
Labels: clean-cherry-pick, priority, forced-landing

#12358 DAOS-13557 control: Set control_metadata path in example MD-on-SSD co…
  src/control/server/storage/faults.go
  utils/config/examples/daos_server_mdonssd.yml
Labels: control-plane, clean-cherry-pick, priority

#12352 DAOS-13089 control: Fix debounce evt unit test race (#12260)
  src/control/events/pubsub_test.go
Labels: control-plane, clean-cherry-pick

#12336 DAOS-7029 control: Quiet noisy fabric ready logging (#12298)
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/infocache.go
  src/control/cmd/daos_agent/infocache_test.go
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/cmd/daos_agent/start.go
Labels: clean-cherry-pick, priority

#11963 DAOS-13660 client: fixes to tse, array, and KV for thread safety
  src/client/array/dc_array.c
  src/client/kv/dc_kv.c
  src/common/tse.c
Labels: release-2.4, priority

#12369 Revert "DAOS-13558 control: Fix bdev count check on scan with vmd"
  src/control/lib/control/auto.go
  src/control/lib/hardware/pci.go
  src/control/lib/hardware/pci_test.go
  src/control/lib/spdk/spdk.go
  src/control/lib/spdk/spdk_default.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend_vmd.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/provider.go
  src/control/server/storage/provider_test.go
Labels: priority

#12291 DAOS-13574 client: add return value for discover_dfuse()
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: forced-landing

#12348 DAOS-13593 build: update to mercury 2.3.0
  utils/build.config
Labels: release-2.4, priority, forced-landing

#12378 DAOS-12648 ci: Adding support for new 2.4 testing branches. (#12368)
  ci/provisioning/post_provision_config_common_functions.sh
Labels: clean-cherry-pick

#12370 DAOS-7029 control: Add refresh methods for agent cache (feature/multiprovider)
  src/control/cmd/daos_agent/config.go
  src/control/cmd/daos_agent/config_test.go
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/fabric_test.go
  src/control/cmd/daos_agent/infocache.go
  src/control/cmd/daos_agent/infocache_test.go
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/cmd/daos_agent/start.go
  src/control/lib/cache/cache.go
  src/control/lib/cache/cache_test.go
  src/control/lib/hardware/fabric.go
  src/control/lib/hardware/fabric_test.go
  src/control/lib/hardware/mocks.go
  utils/config/daos_agent.yml
Labels: unclean-cherry-pick, priority

#12393 DAOS-11610 test: change dfuse caching param for fio (#12321)
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress.yaml
  src/tests/ftest/util/soak_utils.py
Labels: priority

#12377 DAOS-13660 client: fixes to tse, array, and KV for thread safety (#11…
  src/client/array/dc_array.c
  src/client/kv/dc_kv.c
  src/common/tse.c
Labels: clean-cherry-pick, release-2.4

#12382 DAOS-13598 dfs: Convert a return code correctly in dfs_read.
  src/client/dfs/dfs.c
Labels: release-2.4, priority

#12365 DAOS-13603 common: Fix bug in ad_mem with open/create (#12320)
  src/common/ad_mem.c
Labels: clean-cherry-pick, release-2.4, forced-landing

#12381 DAOS-13597 tools: coverity ids 22055, 21738, 21798 (#12319)
  src/client/serialize/daos_serialize.c
  src/tests/ftest/datamover/serial_small.py
Labels: clean-cherry-pick, priority

#12420 DAOS-623 test: Dash in RE class needs to be first (#12387)
  ci/provisioning/post_provision_config_common_functions.sh
Labels: clean-cherry-pick

#12400 DAOS-13661 test: Allow different mpi_types for mdtest (#12371)
  src/tests/ftest/util/mdtest_test_base.py
Labels: priority

#12376 DAOS-13558 control: Fix bdev count check on scan with vmd
  src/control/lib/control/auto.go
  src/control/lib/hardware/pci.go
  src/control/lib/hardware/pci_test.go
  src/control/lib/spdk/spdk.go
  src/control/lib/spdk/spdk_default.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend_vmd.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/provider.go
  src/control/server/storage/provider_test.go
Labels: bug, control-plane, forced-landing

#12404 DAOS-13645 control: Make '@' optional in owner user/group
  src/control/cmd/daos/acl.go
Labels: forced-landing

#12418 DAOS-13717 client: use d_rand() to generate random number
  src/client/api/rpc.c
Labels: release-2.4, priority

#12398 DAOS-13437 csum: Unskip tests (#12318)
  src/tests/suite/daos_checksum.c
Labels: priority

#12416 DAOS-13720 common: Check return code for negative value
  src/common/tests/acl_api_tests.c
Labels: release-2.4, priority

#12415 DAOS-13711 client: several coverity silencing fixes
  src/client/api/event.c
  src/client/array/dc_array.c
  src/client/ds3/bucket.c
  src/client/kv/dc_kv.c
  src/object/cli_obj.c
  src/tests/suite/daos_kv.c
Labels: release-2.4, priority

#12421 DAOS-13593 build: update to mercury 2.3.0 (#12348)
  utils/build.config
Labels: clean-cherry-pick, release-2.4, priority

#12434 DAOS-13555 test: remove ftest/pool,container/global_handle
  src/tests/ftest/container/global_handle.py
  src/tests/ftest/container/global_handle.yaml
  src/tests/ftest/pool/global_handle.py
  src/tests/ftest/pool/global_handle.yaml
Labels: forced-landing

#12433 DAOS-13648 test: Add release/2.4 skip-list
  src/tests/ftest/util/apricot/apricot/test.py
Labels: priority, forced-landing

#12435 DAOS-13558 control: Fix bdev count check on scan with vmd (#12376)
  src/control/lib/control/auto.go
  src/control/lib/hardware/pci.go
  src/control/lib/hardware/pci_test.go
  src/control/lib/spdk/spdk.go
  src/control/lib/spdk/spdk_default.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend_vmd.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/provider.go
  src/control/server/storage/provider_test.go
Labels: clean-cherry-pick, priority, forced-landing

#12397 DAOS-13521 control: Reset unbound NVMe devs on daos_server nvme reset
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
  src/control/server/storage/bdev/mocks.go
  src/control/server/storage/bdev/provider.go
Labels: control-plane, forced-landing

#12445 DAOS-13689 chk: fix double free when handle chk RPC failure
  src/chk/chk_rpc.c
  src/chk/chk_srv.c
  src/pool/srv_pool_check.c
Labels: CR

#12457 DAOS-13707 doc: add libpil4dfs in filesystem.md
  docs/user/filesystem.md
Labels: release-2.4, priority, doc-only

#12409 DAOS-13710 client: Fix a return code in dfs_sys.
  src/client/dfs/dfs_sys.c
Labels: release-2.4, priority

#12306 DAOS-13650 object: remove multiple RPC version of object
  src/client/array/dc_array.c
  src/object/cli_mod.c
  src/object/cli_shard.c
  src/object/obj_rpc.c
  src/object/obj_rpc.h
  src/object/srv_internal.h
  src/object/srv_mod.c
  src/object/srv_obj.c
Labels: forced-landing

#12346 DAOS-13595 utils: Check return codes
  src/client/dfuse/dfuse_core.c
  src/pool/cli.c
  src/utils/daos_hdlr.c
Labels: release-2.4, priority, forced-landing

#12380 DAOS-13090 control: Output ERR logs to stderr for daos tool (#12307)
  src/control/cmd/daos/main.go
  utils/node_local_test.py
Labels: clean-cherry-pick, priority, forced-landing

#12448 DAOS-13214 control: Check engines are ready before fetching usage
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/instance_storage.go
Labels: bug, control-plane

#12295 DAOS-12949 pipeline: Pipeline API feature branch
  debian/changelog
  debian/daos-server.install
  site_scons/site_tools/compiler_setup.py
  src/SConscript
  src/client/api/SConscript
  src/client/api/init.c
  src/client/api/pipeline.c
  src/engine/init.c
  src/include/daos/debug.h
  src/include/daos/object.h
  src/include/daos/pipeline.h
  src/include/daos/rpc.h
  src/include/daos/task.h
  src/include/daos_errno.h
  src/include/daos_pipeline.h
  src/include/daos_task.h
  src/object/cli_obj.c
  src/pipeline/README.md
  src/pipeline/SConscript
  src/pipeline/aggr_funcs.c
  src/pipeline/cli_mod.c
  src/pipeline/cli_pipeline.c
  src/pipeline/common_pipeline.c
  src/pipeline/filter.c
  src/pipeline/filter_funcs.c
  src/pipeline/getdata_funcs.c
  src/pipeline/pipeline_internal.h
  src/pipeline/pipeline_rpc.c
  src/pipeline/pipeline_rpc.h
  src/pipeline/pipeline_task.c
  src/pipeline/srv_mod.c
  src/pipeline/srv_pipeline.c
  src/tests/ftest/daos_test/suite.py
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/SConscript
  src/tests/suite/daos_pipeline.c
  src/tests/suite/daos_test.c
  src/tests/suite/daos_test.h
  utils/rpms/daos.spec
Labels: forced-landing

#12438 DAOS-623 ci: Remove checkpatch.py, replaced by clang-format
  ci/patch_src_in_place
Labels: forced-landing

#12466 DAOS-13707 doc: add libpil4dfs in filesystem.md (#12457)
  docs/user/filesystem.md
Labels: clean-cherry-pick, release-2.4, priority, doc-only

#12429 DAOS-11830 test: merge intercept_basic with intercept_multi_client
  src/tests/ftest/ior/intercept_basic.py
  src/tests/ftest/ior/intercept_basic.yaml
  src/tests/ftest/ior/intercept_multi_client.py
  src/tests/ftest/ior/intercept_multi_client.yaml
  src/tests/ftest/util/ior_intercept_test_base.py
Labels: forced-landing

#12379 DAOS-13167 test: Enable bullseye build.
  ci/bullseye_generate_report.sh
  utils/docker/Dockerfile.el.8
  utils/docker/Dockerfile.el.9
Labels: release-2.4, priority

#12487 DAOS-13626 build: add libfabric 1.18.0 patches
  utils/build.config
Labels: release-2.4, priority

#12495 DAOS-13626 build: add libfabric 1.18.0 patches (#12487)
  utils/build.config
Labels: clean-cherry-pick, release-2.4, priority

#12471 DAOS-13684 test: Bump docker nlt system_ram_reserved (#12432)
  ci/docker_nlt.sh
Labels: clean-cherry-pick, priority

#12467 DAOS-13785 gurt: protect d_log_refcount with d_log_lock
  src/gurt/debug.c
Labels: release-2.4, priority, forced-landing

#12474 DAOS-13785 gurt: protect d_log_refcount with d_log_lock
  src/gurt/debug.c
Labels: clean-cherry-pick, release-2.4, priority

#12482 DAOS-13521 control: Reset unbound NVMe devs on daos_server nvme reset…
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
  src/control/server/storage/bdev/mocks.go
  src/control/server/storage/bdev/provider.go
Labels: control-plane, clean-cherry-pick, priority

#12473 DAOS-13786 client: pool_free take rdlock for dp_co_list check
  src/pool/cli.c
Labels: clean-cherry-pick, release-2.4, priority, forced-landing

#12477 DAOS-13720 common: Check return code for negative value (#12416)
  src/common/tests/acl_api_tests.c
Labels: clean-cherry-pick, release-2.4, priority

#12479 DAOS-13595 utils: Check return codes (#12346)
  src/client/dfuse/dfuse_core.c
  src/pool/cli.c
  src/utils/daos_hdlr.c
Labels: clean-cherry-pick, release-2.4, priority, forced-landing

#12431 DAOS-9249 test: tag vm tests with vm tag
  src/tests/ftest/avocado_tests.py
  src/tests/ftest/cart/corpc/corpc_five_node.py
  src/tests/ftest/cart/corpc/corpc_one_node.py
  src/tests/ftest/cart/corpc/corpc_two_node.py
  src/tests/ftest/cart/ctl/ctl_five_node.py
  src/tests/ftest/cart/ctl/ctl_one_node.py
  src/tests/ftest/cart/ghost_rank_rpc/ghost_rank_rpc_one_node.py
  src/tests/ftest/cart/group_test/group_test.py
  src/tests/ftest/cart/iv/iv_one_node.py
  src/tests/ftest/cart/iv/iv_two_node.py
  src/tests/ftest/cart/no_pmix/multictx_one_node.py
  src/tests/ftest/cart/nopmix_launcher/launcher_one_node.py
  src/tests/ftest/cart/rpc/multisend_one_node.py
  src/tests/ftest/cart/rpc/rpc_one_node.py
  src/tests/ftest/cart/rpc/rpc_two_node.py
  src/tests/ftest/cart/rpc/swim_notification.py
  src/tests/ftest/cart/selftest/selftest_three_node.py
  src/tests/ftest/checksum/csum_basic.py
  src/tests/ftest/harness/basic.py
  src/tests/ftest/harness/unit.py
Labels: forced-landing

#12424 DAOS-13740 cart: fix coverity warning of unused rc
  src/cart/crt_corpc.c
Labels: release-2.4, priority

#12486 DAOS-13792 dfs: fix for coverity 1443161
  src/client/dfs/dfs_internal.c
  src/client/dfs/dfs_internal.h
Labels: release-2.4, priority, forced-landing

#12247 DAOS-9952 control: Usability improvements to dmg system leader-query
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/system.go
  src/control/cmd/dmg/system_test.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/common/proto/ctl/storage_scm.pb.go
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/svc.pb.go
  src/control/lib/control/system.go
  src/mgmt/smd.pb-c.h
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/proto/mgmt/svc.proto
Labels: forced-landing

#12407 DAOS-8781 client: allow polling timeout to be modified via env (#12124)
  docs/admin/env_variables.md
  src/cart/crt_init.c
  src/client/api/event.c
Labels: clean-cherry-pick, forced-landing

#12481 DAOS-13783 common: Address a couple of coverity issues
  src/common/ad_mem.c
  src/common/dav/heap.c
Labels: release-2.4, priority

#12355 DAOS-13540 object: handle TX_RESTART during TX convert
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_tx.c
Labels: release-2.4

#12524 DAOS-13792 dfs: fix for coverity 1443161 (#12486)
  src/client/dfs/dfs_internal.c
  src/client/dfs/dfs_internal.h
Labels: clean-cherry-pick, release-2.4

#12361 DAOS-9355 doc: overhaul dfuse --help
  src/client/dfuse/dfuse_main.c
Labels: forced-landing

#12535 DAOS-13451 cart: Don't drain queue for cart clients
  src/cart/utils/crt_utils.c
Labels: forced-landing

#12530 DAOS-13086 cart: add support for ofi tcp w/o rxm (#12436)
  src/cart/crt_hg.c
  src/cart/crt_hg.h
  src/cart/crt_init.c
  src/include/cart/types.h
Labels: clean-cherry-pick, release-2.4, priority

#12541 DAOS-13175 dfs: print progress of dfs mwc checker (#12470)
  src/client/dfs/dfs.c
  utils/node_local_test.py
Labels: clean-cherry-pick

#12525 DAOS-13791 client: free iod->iod_recxs first, then free params (#12475)
  src/client/array/dc_array.c
Labels: clean-cherry-pick, release-2.4, priority

#12539 DAOS-13801 array: fix possible double free with FI (#12507)
  src/client/array/dc_array.c
  src/client/dfs/dfs.c
Labels: clean-cherry-pick

#12542 DAOS-13113 common: Fixed coverity issue in dav code (#12493)
  src/common/dav/alloc_class.c
Labels: clean-cherry-pick, release-2.4

#12533 DAOS-13783 common: Address a couple of coverity issues (#12481)
  src/common/ad_mem.c
  src/common/dav/heap.c
Labels: clean-cherry-pick, release-2.4, forced-landing

#12553 DAOS-13451 cart: Don't drain queue for cart clients (#12535)
  src/cart/utils/crt_utils.c
Labels: clean-cherry-pick

#12408 DAOS-13604 dfuse: Fix resource leaks in readdir.
  src/client/dfuse/ops/readdir.c
Labels: release-2.4, priority

#12491 DAOS-13716 cart: Fix coverity issue cid 1404275 (#12459)
  src/cart/crt_hg.c
Labels: clean-cherry-pick, release-2.4, priority, forced-landing

#12468 DAOS-13781 dfuse: Remove a pointless assignment.
  src/client/dfuse/dfuse_core.c
Labels: release-2.4, priority

#12490 DAOS-13721 cart: Fix coverity cid 1426658
  src/cart/crt_ctl.c
Labels: release-2.4, priority, forced-landing

#12070 DAOS-12132 test: Enable setting up slurm for tests using partitions
  src/tests/ftest/launch.py
  src/tests/ftest/scripts/main.sh
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress.yaml
  src/tests/ftest/util/package_utils.py
  utils/cq/words.dict
Labels: forced-landing

#12384 DAOS-13496 test: Add logging to MockInvoker
  src/control/lib/control/mocks.go
Labels: forced-landing

#12504 DAOS-13214 engine: Setup modules in DRPC SetUp handler
  src/engine/init.c
  src/engine/srv_internal.h
  src/include/daos_srv/daos_engine.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_target.c
  src/mgmt/tests/mocks.c
Labels: priority, forced-landing

#12503 DAOS-13214 control: Disallow dRPCs if engine is not ready
  src/control/lib/daos/status.go
  src/control/server/ctl_ranks_rpc.go
  src/control/server/ctl_ranks_rpc_test.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/harness.go
  src/control/server/harness_test.go
  src/control/server/instance.go
  src/control/server/instance_drpc.go
  src/control/server/instance_drpc_test.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_system.go
Labels: priority
