Repository daos-stack/daos, pull requests merged in 2023-08, with the labels that each got.

#12430 DAOS-13672 control: Bump system_ram_reserved to reduce OOM occurrences
  src/control/cmd/dmg/auto_test.go
  src/control/lib/control/auto_test.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm_test.go
  src/tests/ftest/container/snapshot_aggregation.yaml
  src/tests/ftest/control/dmg_server_set_logmasks.yaml
  src/tests/ftest/pool/create_all_vm.yaml
  src/tests/ftest/security/cont_overwrite_acl.yaml
  src/tests/ftest/security/cont_update_acl.yaml
  src/tests/ftest/telemetry/pool_space_metrics.yaml
  utils/config/daos_server.yml
Labels: control-plane, forced-landing

#12719 DAOS-13988 control: MemberResult state should reflect error
  src/control/lib/control/system_test.go
  src/control/server/ctl_ranks_rpc.go
  src/control/server/ctl_ranks_rpc_test.go
  src/control/system/member.go
  src/control/system/membership_test.go
Labels: bug, control-plane, release-2.4, forced-landing

#12740 DAOS-13905 common: Fix return code from daos_sgl functions. (#12706)
  src/common/misc.c
  src/engine/server_iv.c
Labels: clean-cherry-pick, priority

#12742 DAOS-14091 control: Validate against negative ints in engine conf
  src/control/server/engine/config.go
  src/control/server/engine/config_test.go
Labels: control-plane

#12748 DAOS-14071 client: do not assert event is ready if progress fails (#1…
  src/client/api/event.c
Labels: clean-cherry-pick

#12747 DAOS-12638 cart: fix a HG handle leak when HG_Reset() fails
  src/cart/crt_hg.c
Labels: priority

#12756 DAOS-14053 test: Removing some swim timeouts added previously (#12735)
  src/tests/ftest/rebuild/widely_striped.yaml
Labels: clean-cherry-pick

#12759 DAOS-13964 test: use hg_info instead of fi_info (#12724)
  src/tests/ftest/control/dmg_network_scan.py
  src/tests/ftest/launch.py
Labels: clean-cherry-pick, release-2.4, forced-landing

#12754 DAOS-13988 control: MemberResult state should reflect error (#12719)
  src/control/lib/control/system_test.go
  src/control/server/ctl_ranks_rpc.go
  src/control/server/ctl_ranks_rpc_test.go
  src/control/system/member.go
  src/control/system/membership_test.go
Labels: control-plane, clean-cherry-pick

#12739 DAOS-14074 object: Compound RPC interop fix
  src/object/cli_mod.c
  src/object/obj_rpc.c
  src/object/obj_rpc.h
  src/object/srv_mod.c
Labels: release-2.4, priority

#12704 DAOS-13964 build: update libfabric to 1.18.1 and apply prov/tcp patches
  utils/build.config
Labels: release-2.4, priority

#12697 DAOS-12725 test: Update ior_small ior timeout.
  src/tests/ftest/ior/small.yaml
Labels: priority

#12763 DAOS-13493 rebuild: upgrate the whole group (#12550)
  src/include/daos_srv/daos_engine.h
  src/object/obj_layout.c
  src/object/srv_obj_migrate.c
  src/rebuild/scan.c
  src/tests/suite/daos_upgrade.c
Labels: clean-cherry-pick, release-2.4

#12772 DAOS-13964 build: update libfabric to 1.18.1 and apply prov/tcp patch…
  utils/build.config
Labels: release-2.4, priority

#12771 DAOS-14074 object: Compound RPC interop fix (#12739)
  src/object/cli_mod.c
  src/object/obj_rpc.c
  src/object/obj_rpc.h
  src/object/srv_mod.c
Labels: clean-cherry-pick, release-2.4

#12689 DAOS-13968 vos: handle race between DTX prepare and DTX abort
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
Labels: priority

#12638 DAOS-13503 object: skip redundancy group verification when DTX resync
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/object/cli_mod.c
  src/object/obj_internal.h
  src/object/obj_tx.c
  src/tests/suite/daos_dist_tx.c
Labels: clean-cherry-pick, release-2.4, priority

#12781 DAOS-13493 rebuild: various fixes for upgrade
  src/container/srv_container.c
  src/placement/jump_map.c
  src/placement/jump_map_versions.c
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: clean-cherry-pick, release-2.4

#12790 DAOS-14132 test: Fix d_errstr unit test
  src/gurt/tests/test_gurt.c
Labels: CR

#12751 DAOS-14094 test: only remove fault_file if exists
  src/tests/ftest/util/fault_config_utils.py
Labels: forced-landing

#12777 DAOS-13968 vos: handle race between DTX prepare and DTX abort
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
Labels: clean-cherry-pick, release-2.4, priority

#12534 DAOS-13540 object: handle TX_RESTART during TX convert
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_tx.c
Labels: clean-cherry-pick, release-2.4, priority

#12799 DAOS-14118 pool: Fix a race on pool upgrade
  src/pool/srv_iv.c
Labels: release-2.4, priority

#12797 DAOS-14143 test: Adjust system_ram_reserved for recovery VM tests
  src/tests/ftest/recovery/ddb.yaml
  src/tests/ftest/recovery/ms_membership.yaml
  utils/test_memcheck.supp
Labels: CR

#12671 DAOS-13295 rebuild: exclude EC aggregation with discard (#12513)
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: clean-cherry-pick, release-2.4, priority

#12441 DAOS-12945 container: skip prop get for container server handle
  src/container/container_iv.c
  src/container/srv_target.c
  src/object/srv_obj.c
Labels: priority

#12785 DAOS-623 csum: check for 0 size array before alloc (#12714)
  src/common/checksum.c
  src/object/rpc_csum.c
Labels: clean-cherry-pick

#12776 DAOS-13976 control: Reset checker reports only for pools requested
  src/control/server/mgmt_check.go
  src/control/server/mgmt_check_test.go
  src/control/server/mgmt_system.go
  src/control/system/raft/database.go
  src/control/system/raft/database_checker.go
  src/control/system/raft/raft.go
Labels: CR

#12679 DAOS-13941 rebuild: reclaim phase should be marked as complete
  src/rebuild/rebuild_internal.h
  src/rebuild/srv.c
  src/tests/suite/daos_rebuild_common.c
Labels: priority

#12811 DAOS-14094 test: only remove fault_file if exists (#12751)
  src/tests/ftest/util/fault_config_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#12770 DAOS-14085 control: Fix config generate yaml printed to stdout
  src/control/cmd/daos_server/auto.go
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/dmg/auto.go
  src/control/cmd/dmg/auto_test.go
Labels: bug, control-plane

#12692 DAOS-13974 control: Print actions in same order as JSON
  src/control/lib/control/check.go
  src/control/lib/control/check_test.go
Labels: CR

#12666 DAOS-10653 test: use a test's name as its unique tag
  src/tests/ftest/container/per_server_fault_domain.py
  src/tests/ftest/control/daos_agent_support_collect_log.py
  src/tests/ftest/control/daos_server_support_collect_log.py
  src/tests/ftest/control/daos_system_query.py
  src/tests/ftest/daos_racer/multi.py
  src/tests/ftest/daos_racer/parallel.py
  src/tests/ftest/daos_racer/simple.py
  src/tests/ftest/daos_vol/bigio.py
  src/tests/ftest/dfuse/fio_pil4dfs_small.py
  src/tests/ftest/harness/unit.py
  src/tests/ftest/interoperability/diff_versions.py
  src/tests/ftest/ior/hard.py
  src/tests/ftest/object/fetch_bad_param.py
  src/tests/ftest/object/update_bad_param.py
  src/tests/ftest/pool/bad_evict.py
  src/tests/ftest/pool/create_all_hw.py
  src/tests/ftest/pool/create_all_hw.yaml
  src/tests/ftest/pool/create_all_vm.py
  src/tests/ftest/pool/create_all_vm.yaml
  src/tests/ftest/pool/create_capacity.py
  src/tests/ftest/pool/evict.py
  src/tests/ftest/rebuild/io_conf_run.py
  src/tests/ftest/security/cont_delete_acl.py
  src/tests/ftest/security/cont_get_acl.py
  src/tests/ftest/security/cont_overwrite_acl.py
  src/tests/ftest/security/cont_update_acl.py
  src/tests/ftest/security/pool_acl.py
  src/tests/ftest/security/pool_groups.py
  src/tests/ftest/server/replay.py
  src/tests/ftest/soak/stress_2h.py
Labels: forced-landing

#12778 DAOS-12945 vos: use DAOS_INTENT_DISCARD intent for vos_obj_discard_hold
  src/vos/vos_obj_cache.c
Labels: release-2.4, priority

#12831 SRE-1935 build: Disable bootstrap-image use
  utils/rpms/packaging/Dockerfile.mockbuild
  utils/rpms/packaging/rpm_chrootbuild
Labels: forced-landing

#12641 DAOS-13295 rebuild: reverse recx enumeration order for rebuild
  src/container/srv_target.c
  src/include/daos/object.h
  src/include/daos_srv/container.h
  src/include/daos_srv/pool.h
  src/include/daos_srv/vos.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/object/srv_obj_migrate.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/vos/vos_aggregate.c
Labels: release-2.4, priority

#12821 DAOS-12945 container: skip prop get for container server handle (#12441)
  src/container/container_iv.c
  src/object/srv_obj.c
Labels: clean-cherry-pick, release-2.4

#12798 DAOS-14015 test: Updating the targets_str config val. (#12732)
  src/tests/ftest/server/daos_server_config.yaml
Labels: unclean-cherry-pick

#12820 DAOS-13941 object: enumerate all groups for upgrade (#12762)
  src/object/cli_obj.c
  src/object/srv_obj_migrate.c
  src/tests/suite/daos_upgrade.c
Labels: release-2.4

#12809 DAOS-13816 pool: add reintegration mode to pool property (#12646)
  docs/admin/pool_operations.md
  src/common/prop.c
  src/container/srv_container.c
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool_cont_prop.go
  src/control/lib/daos/pool_property.go
  src/control/lib/daos/pool_property_test.go
  src/include/daos/pool.h
  src/include/daos_prop.h
  src/include/daos_srv/pool.h
  src/object/srv_obj.c
  src/pool/rpc.c
  src/pool/srv_internal.h
  src/pool/srv_iv.c
  src/pool/srv_layout.c
  src/pool/srv_layout.h
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/rebuild/srv.c
  src/tests/suite/daos_rebuild_simple.c
Labels: unclean-cherry-pick

#12834 DAOS-13941 rebuild: reclaim phase should be marked as complete (#12679)
  src/rebuild/rebuild_internal.h
  src/rebuild/srv.c
  src/tests/suite/daos_rebuild_common.c
Labels: clean-cherry-pick, release-2.4

#12779 DAOS-14101 control: Retry SMD manage request on DER_BUSY
  src/bio/bio_device.c
  src/bio/bio_xstream.c
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_smd_rpc_test.go
Labels: control-plane, release-2.4

#12816 DAOS-13295 object: shrink the object migrate ULT limit
  src/object/srv_obj_migrate.c
Labels: release-2.4, priority

#12841 DAOS-12945 vos: use DAOS_INTENT_DISCARD intent for vos_obj_discard_hold
  src/vos/vos_obj_cache.c
Labels: clean-cherry-pick, release-2.4, priority

#12856 SRE-1935 build: Disable bootstrap-image use (#12831)
  utils/rpms/packaging/Dockerfile.mockbuild
  utils/rpms/packaging/rpm_chrootbuild
Labels: unclean-cherry-pick, forced-landing

#12829 DAOS-14150 object: restart distributed TX if hit unavailable target
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_tx.c
Labels: clean-cherry-pick, release-2.4, priority

#12862 SRE-1935 build: Build Leap 15 RPMs with FVERSION=37
  Jenkinsfile
Labels: forced-landing

#12859 DAOS-14151 array: change error logging to debug for array existence (…
  src/client/array/dc_array.c
  src/client/dfs/dfs.c
Labels: clean-cherry-pick, priority

#12855 DAOS-13587 test: Re-enable skipped DAOS Seg Count test (#12283)
  src/tests/ftest/io/seg_count.py
  src/tests/ftest/io/seg_count.yaml
Labels: unclean-cherry-pick, priority

#12869 DAOS-14205 container: missing pool hdl put
  src/container/srv_container.c
Labels: release-2.4, priority

#12866 DAOS-14194 common: Address admem coverity issues
  src/common/ad_mem.c
Labels: release-2.4, priority

#12845 DAOS-14085 control: Fix config generate yaml printed to stdout (#12770)
  src/control/cmd/daos_server/auto.go
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/dmg/auto.go
  src/control/cmd/dmg/auto_test.go
Labels: bug, control-plane, clean-cherry-pick, priority, forced-landing

#12824 DAOS-13964 test: use hg_info instead of fi_info (#12724)
  src/tests/ftest/control/dmg_network_scan.py
  src/tests/ftest/launch.py
Labels: unclean-cherry-pick, release-2.4, priority, forced-landing

#12867 DAOS-14198 placement: check spare_left
  src/placement/jump_map_versions.c
Labels: release-2.4, priority

#12865 DAOS-14202 object: check failed targets during retry
  src/include/daos/common.h
  src/object/cli_ec.c
  src/object/cli_obj.c
  src/object/srv_obj.c
  src/tests/suite/daos_obj_ec.c
  src/tests/suite/daos_rebuild_common.c
  src/tests/suite/daos_test.h
Labels: release-2.4, priority

#12749 DAOS-14075 bio: Sync LED state on engine start
  src/bio/bio_device.c
  src/bio/bio_xstream.c
  src/vos/tests/bio_ut.c
  utils/run_utest.py
Labels: forced-landing

#12520 DAOS-13697 doc: add document for pool upgrade
  docs/admin/administration.md
  docs/admin/pool_operations.md
Labels: forced-landing

#12848 DAOS-12670 control: Select all devices by default in led manage cmds
  docs/admin/administration.md
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_smd_rpc_test.go
  src/mgmt/srv_query.c
Labels: control-plane, forced-landing, go

#12836 DAOS-13295 rebuild: check dtx global version before wait
  src/rebuild/rebuild_iv.c
  src/rebuild/scan.c
Labels: release-2.4, priority

#12881 DAOS-14169 rebuild: revert PR-12679
  src/rebuild/rebuild_internal.h
  src/rebuild/srv.c
  src/tests/suite/daos_rebuild_common.c
Labels: release-2.4, priority

#12861 DAOS-13295 object: shrink the object migrate ULT limit (#12816)
  src/object/srv_obj_migrate.c
Labels: clean-cherry-pick, release-2.4

#12863 DAOS-13295 pool: retry discard for INPROGRESS failure (#12817)
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
  src/rebuild/srv.c
Labels: clean-cherry-pick, release-2.4

#12879 DAOS-14205 container: missing pool hdl put (#12869)
  src/container/srv_container.c
Labels: clean-cherry-pick, release-2.4

#12882 DAOS-14194 common: Address admem coverity issues (#12866)
  src/common/ad_mem.c
Labels: clean-cherry-pick, release-2.4

#12849 DAOS-14028 vos: skip mlock for MD-on-SSD case
  src/vos/vos_pool.c
Labels: forced-landing

#12818 DAOS-13341 test: fix improper assert
  src/tests/dts.c
Labels: priority

#12902 DAOS-14191 test: Soak updates for harassers (#12860)
  src/tests/ftest/soak/harassers.py
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress.yaml
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: clean-cherry-pick, release-2.4

#12904 SRE-1935 build: Disable bootstrap-image use (#12831)
  Jenkinsfile
  utils/rpms/packaging/Dockerfile.mockbuild
  utils/rpms/packaging/rpm_chrootbuild
Labels: unclean-cherry-pick, release-2.2, forced-landing

#12888 DAOS-14169 rebuild: revert PR-12679 (#12881)
  src/rebuild/rebuild_internal.h
  src/rebuild/srv.c
  src/tests/suite/daos_rebuild_common.c
Labels: release-2.4

#12864 DAOS-14155 gurt: Add new logging macros and tools to support them. (#…
  src/cart/crt_bulk.c
  src/include/gurt/debug.h
  src/object/srv_obj_migrate.c
Labels: unclean-cherry-pick

#12886 DAOS-13295 rebuild: check dtx global version before wait (#12836)
  src/rebuild/rebuild_iv.c
  src/rebuild/scan.c
Labels: clean-cherry-pick, release-2.4

#12843 DAOS-13295 rebuild: reverse recx enumeration order for rebuild (#12641)
  src/container/srv_target.c
  src/include/daos/object.h
  src/include/daos_srv/container.h
  src/include/daos_srv/pool.h
  src/include/daos_srv/vos.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/object/srv_obj_migrate.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/vos/vos_aggregate.c
Labels: release-2.4, priority

#12907 DAOS-14216 build: Build fail if home is under /usr
  site_scons/prereq_tools/base.py
Labels: forced-landing

#12919 DAOS-14176 object: refine obj_capa_check (#12873)
  src/object/srv_obj.c
Labels: clean-cherry-pick, release-2.4, priority

#12916 DAOS-14185 test: Randomize server ranks for soak extend (#12850)
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: clean-cherry-pick, release-2.4

#12853 DAOS-14113 control: Fix unit test race condition (#12803)
  src/control/server/harness_test.go
Labels: clean-cherry-pick, priority

#12920 DAOS-14217 build: Add fusermount3 dependency…
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes.sh
  debian/changelog
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
Labels: release-2.4, priority, forced-landing

#12923 DAOS-14216 build: Build fail if home is under /usr (#12907)
  site_scons/prereq_tools/base.py
Labels: clean-cherry-pick

#12937 DAOS-14217 build: Add fusermount3 dependency (#12920)
  ci/provisioning/post_provision_config_common_functions.sh
  ci/provisioning/post_provision_config_nodes.sh
  debian/changelog
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, release-2.4, forced-landing

#12932 DAOS-14165 client: fix thread sanitizer warnings on the client side (…
  src/client/api/client_internal.h
  src/client/api/event.c
  src/common/tse.c
  src/common/tse_internal.h
  src/include/daos/tse.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/placement/pl_map.c
Labels: clean-cherry-pick

#12870 DAOS-14101 control: Bump maximum number of retries for dev replace
  src/control/server/ctl_smd_rpc.go
Labels: control-plane

#12871 DAOS-14101 control: Set NVMe device state zero value to UNKNOWN
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/server/ctl_smd_rpc_test.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev_test.go
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_query.c
  src/proto/ctl/smd.proto
Labels: bug, control-plane, release-2.4

#12951 DAOS-14222 test: Fix harasser name in yaml (#12930)
  src/tests/ftest/soak/harassers.yaml
Labels: clean-cherry-pick, release-2.4

#12957 DAOS-14230 test: Add unique id to dfuse mountpoint (#12954)
  src/tests/ftest/util/soak_utils.py
Labels: clean-cherry-pick, release-2.4

#12938 DAOS-13697 doc: add documentation for pool upgrade
  docs/admin/administration.md
  docs/admin/pool_operations.md
Labels: clean-cherry-pick

#12931 DAOS-10653 test: use a test's name as its unique tag (#12666)
  src/tests/ftest/container/per_server_fault_domain.py
  src/tests/ftest/control/daos_system_query.py
  src/tests/ftest/daos_racer/multi.py
  src/tests/ftest/daos_racer/parallel.py
  src/tests/ftest/daos_racer/simple.py
  src/tests/ftest/daos_vol/bigio.py
  src/tests/ftest/dfuse/fio_pil4dfs_small.py
  src/tests/ftest/harness/unit.py
  src/tests/ftest/interoperability/diff_versions.py
  src/tests/ftest/ior/hard.py
  src/tests/ftest/object/fetch_bad_param.py
  src/tests/ftest/object/update_bad_param.py
  src/tests/ftest/pool/bad_evict.py
  src/tests/ftest/pool/create_all_hw.py
  src/tests/ftest/pool/create_all_hw.yaml
  src/tests/ftest/pool/create_all_vm.py
  src/tests/ftest/pool/create_all_vm.yaml
  src/tests/ftest/pool/create_capacity.py
  src/tests/ftest/pool/evict.py
  src/tests/ftest/rebuild/io_conf_run.py
  src/tests/ftest/security/cont_delete_acl.py
  src/tests/ftest/security/cont_get_acl.py
  src/tests/ftest/security/cont_overwrite_acl.py
  src/tests/ftest/security/cont_update_acl.py
  src/tests/ftest/security/pool_acl.py
  src/tests/ftest/security/pool_groups.py
  src/tests/ftest/server/replay.py
  src/tests/ftest/soak/stress_2h.py
Labels: unclean-cherry-pick, priority

#12939 DAOS-13341 test: fix improper assert (#12818)
  src/tests/dts.c
Labels: clean-cherry-pick, priority

#12715 DAOS-13967 engine: Fix NVMe storage leakage with md-on-ssd
  src/control/server/ctl_storage_rpc.go
  src/include/daos_srv/rsvc.h
  src/mgmt/srv_target.c
  src/rsvc/srv.c
  src/tests/ftest/pool/create.yaml
  src/vos/vos_pool.c
  utils/ansible/ftest/templates/daos-make.sh.j2
Labels: bug, meta-on-ssd

#12959 DAOS-14208 container: do not disable vos aggregation (#12934)
  src/container/srv_target.c
Labels: clean-cherry-pick, release-2.4

#12956 DAOS-14211 vos: fix improper assert in umark_removals() (#12910)
  src/container/srv_target.c
  src/vos/vos_aggregate.c
Labels: clean-cherry-pick, release-2.4

#12966 DAOS-14171 test: Exclude mounted devices in auto storage (#12839)
  src/tests/ftest/util/storage_utils.py
  utils/cq/words.dict
Labels: clean-cherry-pick

#12973 DAOS-14247 build: update to mercury 2.3.1rc1
  utils/build.config
Labels: release-2.4, priority

#12948 DAOS-14163 cart: Do not access rpc after decref
  src/cart/crt_rpc.h
Labels: unclean-cherry-pick

#12927 GCP-215 vos: warning message for purging old non-committed DTX
  src/dtx/dtx_common.c
  src/gurt/hlc.c
  src/include/daos_srv/dtx_srv.h
  src/include/gurt/common.h
  src/vos/vos_dtx.c
Labels: release-2.4

#12977 DAOS-14247 build: update to mercury 2.3.1rc1 (#12973)
  utils/build.config
Labels: clean-cherry-pick, release-2.4

#12971 DAOS-14139 test: Abort testing if there's avocado timeout in _cleanup…
  src/tests/ftest/util/apricot/apricot/test.py
Labels: clean-cherry-pick

#12981 DAOS-14224 cart: call crt_bulk_free before iv_put
  src/cart/crt_corpc.c
  src/cart/crt_iv.c
Labels: release-2.4

#12965 DAOS-14224 cart: call crt_bulk_free before iv_put
  src/cart/crt_corpc.c
  src/cart/crt_iv.c
Labels: release-2.4, priority

#12944 DAOS-14214 control: Fix potential missed call to drpc failure handlers
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/common/proto/ctl/smd.pb.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/harness.go
  src/control/server/harness_test.go
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/proto/ctl/smd.proto
Labels: bug, control-plane

#12897 DAOS-12670 control: Select all devices by default in led manage cmds …
  docs/admin/administration.md
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_smd_rpc_test.go
  src/mgmt/srv_query.c
Labels: control-plane, clean-cherry-pick

#12896 DAOS-14075 bio: Sync LED state on engine start (#12749)
  docs/admin/administration.md
  src/bio/bio_device.c
  src/bio/bio_xstream.c
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_smd_rpc_test.go
  src/mgmt/srv_query.c
  src/vos/tests/bio_ut.c
  utils/run_utest.py
Labels: clean-cherry-pick

#12996 DAOS-14271 build: Tag 2.4.0 rc1
  TAG
  VERSION
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing
