Repository daos-stack/daos, pull requests merged in 2023-04, with the labels that each got.

#11846 DAOS-11394 test: Save dmg log for daos_test suite (#11783)
  src/tests/ftest/checksum/csum_error_logging.py
  src/tests/ftest/daos_test/suite.py
  src/tests/ftest/util/daos_core_base.py
Labels: unclean-cherry-pick

#11812 DAOS-13006 test: resolve all flake issues in ftest
  .github/workflows/flake.yml
  src/client/pydaos/__init__.py
  src/tests/ftest/deployment/ior_per_rank.py
  src/tests/ftest/object/fetch_bad_param.py
  src/tests/ftest/object/integrity.py
  src/tests/ftest/object/open_bad_param.py
  src/tests/ftest/object/punch_test.py
  src/tests/ftest/object/update_bad_param.py
  src/tests/ftest/pool/global_handle.py
Labels: forced-landing

#11815 DAOS-12964 control: Refine dmg hostlist help
  src/control/cmd/dmg/auto.go
  src/control/cmd/dmg/firmware.go
  src/control/cmd/dmg/main.go
  src/control/cmd/dmg/network.go
  src/control/cmd/dmg/server.go
  src/control/cmd/dmg/storage.go
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/cmd/dmg/telemetry.go
  src/control/cmd/dmg/telemetry_test.go
  src/control/cmd/dmg/utils.go
  src/control/cmd/dmg/utils_test.go
Labels: forced-landing

#11807 DAOS-10637 control: Scan only for specified provider
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/network.go
  src/control/cmd/daos_server/network.go
  src/control/cmd/daos_server/storage_utils.go
  src/control/lib/hardware/fabric.go
  src/control/lib/hardware/fabric_test.go
  src/control/lib/hardware/libfabric/bindings.go
  src/control/lib/hardware/libfabric/provider.go
  src/control/lib/hardware/libfabric/provider_test.go
  src/control/lib/hardware/mocks.go
  src/control/lib/hardware/sysfs/provider.go
  src/control/lib/hardware/sysfs/provider_test.go
  src/control/lib/hardware/ucx/ucx.go
  src/control/lib/hardware/ucx/ucx_interfaces_test.go
  src/control/server/ctl_network_rpc.go
  src/control/server/server.go
  src/control/server/server_utils.go
Labels: forced-landing

#11861 DAOS-13087 build: Use ar instead of xiar for Intel builds (#11859)
  site_scons/site_tools/doneapi.py
Labels: clean-cherry-pick, priority

#11851 DAOS-12672 control: Make dRPC calls context aware (#11760)
  src/control/cmd/drpc_test/main.go
  src/control/drpc/drpc_client.go
  src/control/drpc/drpc_client_test.go
  src/control/drpc/drpc_server_test.go
  src/control/server/drpc.go
  src/control/server/drpc_test.go
  src/control/server/mgmt_pool_test.go
  src/control/server/util_test.go
Labels: release-2.4, priority

#11856 DAOS-12727 cart: Set FI_OFI_RXM_DEF_TCP_WAIT_OBJ to pollfd on the server
  src/cart/crt_init.c
Labels: unclean-cherry-pick, priority

#11848 DAOS-12628 control: Add non-debug event logging for daos_server
  src/control/system/membership.go
  src/control/system/raft/database.go
Labels: forced-landing

#11802 DAOS-12988 cart: Pin libfabric to be below 1.18 version for 2.2 branch
  debian/changelog
  debian/control
  utils/rpms/daos.spec
Labels: priority

#11639 DAOS-12679 object: refresh DTX ID for DER_EP_OLD
  src/object/cli_obj.c
  src/object/obj_tx.c
  src/tests/suite/daos_base_tx.c
Labels: unclean-cherry-pick, release-2.2

#11696 DAOS-12739 test: ensure that we use MOFED 5.8-1.1.2.1 with 2.2.1
  ci/provisioning/post_provision_config_common.sh
  src/tests/ftest/util/job_manager_utils.py
Labels: release-2.4

#11866 DAOS-11572 pool: add term to the IV srv HDL invalidate
  src/pool/srv_iv.c
  src/pool/srv_pool.c
Labels: release-2.2

#11889 DAOS-12410 object: fix a bug in recov_task_cb
  src/container/container_iv.c
  src/include/daos/common.h
  src/object/cli_ec.c
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_ec.h
  src/tests/suite/daos_obj_ec.c
Labels: priority

#11833 DAOS-13046 common: fix to return sys db commit failure
  src/common/sys_lmdb.c
Labels: meta-on-ssd

#11816 DAOS-13011 test: Add dmg storage query role verification
  src/tests/ftest/control/dmg_storage_query.py
Labels: release-2.4, priority

#11905 DAOS-11925 test: Error running cart/cart_logtest.py on the /var/tmp/daos_testing/*log* files
  src/tests/ftest/launch.py
Labels: priority

#11930 SRE-415 test: Add some diagnostics
  ci/functional/launchable_analysis
Labels: release-2.4, forced-landing

#11895 DAOS-13115 rdb: coverity CID 1347786
  src/rdb/rdb_raft.c
Labels: release-2.4, priority, forced-landing

#11867 DAOS-13088 control: Support fabric scan with multiple providers
  src/control/lib/hardware/fabric.go
  src/control/lib/hardware/fabric_test.go
  src/control/lib/hardware/mocks.go
Labels: forced-landing

#11830 DAOS-13002 pool: Use deep stack for pool child discard
  src/bio/bio_wal.c
  src/pool/srv_target.c
Labels: release-2.4, priority

#11507 DAOS-5912 rebuild: restore pool map if extend/drain fail (#11411)
  src/common/pool_map.c
  src/include/daos_srv/rebuild.h
  src/object/srv_obj_migrate.c
  src/pool/srv_pool.c
  src/pool/srv_pool_map.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/tests/suite/daos_drain_simple.c
  src/tests/suite/daos_extend_simple.c
  src/tests/suite/daos_rebuild.c
  src/tests/suite/daos_rebuild_common.c
  src/tests/suite/daos_test.h
  src/tests/suite/daos_test_common.c
Labels: unclean-cherry-pick, release-2.4, priority

#11890 DAOS-13111 bio: address coverity issues
  src/bio/bio_buffer.c
  src/bio/bio_wal.c
  src/bio/bio_xstream.c
  src/bio/tests/bio_ut.c
  src/bio/tests/bio_ut.h
  src/bio/tests/wal_ut.c
Labels: release-2.4, priority

#11933 DAOS-13137 pool: use a deep stack for pool open ULT
  src/pool/srv_target.c
Labels: release-2.4, priority

#11929 DAOS-13144 common: fix to free lmdb memory
  src/common/sys_lmdb.c
  src/engine/init.c
  src/vos/vos_common.c
Labels: release-2.4, priority

#11951 DAOS-12407 cart: Update libfabric to v1.17.1
  utils/build.config
Labels: release-2.4, priority, forced-landing

#11818 DAOS-12945 rebuild: add DER_VOS_PARTIAL_UPDATE
  src/common/pool_map.c
  src/container/srv_target.c
  src/include/daos/placement.h
  src/include/daos/pool.h
  src/include/daos/pool_map.h
  src/include/daos_errno.h
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_layout.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/object/srv_obj_migrate.c
  src/placement/jump_map.c
  src/placement/jump_map_versions.c
  src/placement/pl_map.c
  src/placement/pl_map.h
  src/placement/pl_map_common.c
  src/placement/ring_map.c
  src/placement/tests/pl_bench.c
  src/placement/tests/place_obj_common.c
  src/pool/cli.c
  src/pool/rpc.h
  src/pool/srv_cli.c
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/daos_drain_simple.c
  src/tests/suite/daos_rebuild_common.c
  src/tests/suite/daos_test_common.c
  src/vos/evtree.c
  src/vos/vos_io.c
Labels: release-2.4, priority

#11957 DAOS-13144 bio: suppress some memcheck errors
  src/bio/bio_wal.c
  src/bio/bio_xstream.c
  src/include/gurt/common.h
  utils/test_memcheck.supp
Labels: release-2.4, priority

#11962 SRE-415 test: Add more diagnostics
  ci/functional/launchable_analysis
Labels: release-2.4, forced-landing

#11912 DAOS-9355 doc: add IBM Cloud VPC (#11911)
  docs/cloud/index.md
Labels: clean-cherry-pick

#11919 DAOS-11874 doc: fixes to QSG docs
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
Labels: release-2.4, priority

#11920 DAOS-11869 doc: misc QSG fixes
  docs/QSG/setup_rhel.md
  docs/QSG/tour.md
  docs/testing/autotest.md
  docs/testing/datamover.md
Labels: release-2.4, priority

#11947 DAOS-12601 mercury: disable multi-recv except for prov/cxi
  src/cart/crt_init.c
Labels: release-2.4, priority, forced-landing

#11981 DAOS-7590 test: use container labels with daos by default (#11324)
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/io_verification.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/test_utils_base.py
  src/tests/ftest/util/test_utils_container.py
Labels: unclean-cherry-pick, forced-landing

#11948 DAOS-12601 mercury: disable multi-recv for all providers
  src/cart/crt_init.c
Labels: release-2.4

#12002 DAOS-13144 common: Fixed valgrind errors around DAV.
  src/bio/bio_wal.c
  src/common/dav/memblock.c
Labels: release-2.4, priority

#11882 DAOS-13055 control: Port daos ACL command handlers to Go
  ci/codespell.ignores
  src/control/cmd/daos/acl.go
  src/control/cmd/daos/container.go
  src/control/cmd/dmg/acl.go
  src/control/cmd/dmg/acl_test.go
  src/control/common/proto/types.go
  src/control/common/types.go
  src/control/lib/control/acl.go
  src/control/lib/control/acl_test.go
  src/tests/ftest/security/cont_overwrite_acl.py
  src/tests/ftest/security/cont_overwrite_acl.yaml
  src/tests/ftest/security/cont_update_acl.py
  src/tests/ftest/security/cont_update_acl.yaml
  src/utils/daos_hdlr.c
  src/utils/daos_hdlr.h
Labels: forced-landing

#11887 DAOS-12153 cart: Correct mapping of HG_PROTOCOL_ERROR to DER_PROTO.
  src/cart/crt_hg.c
  src/cart/crt_hg.h
  src/include/daos_errno.h
Labels: release-2.4, priority

#11918 DAOS-13123 control: Increase pool timeout to 5 minutes
  src/control/drpc/drpc_client.go
  src/control/drpc/drpc_client_test.go
  src/control/drpc/mocks_test.go
  src/control/lib/control/pool.go
  src/control/server/harness.go
  src/control/server/harness_test.go
Labels: forced-landing

#11893 DAOS-13114 control: Add batching support for PoolEvict requests
  src/control/cmd/daos_agent/procmon.go
  src/control/common/proc_utils.go
  src/control/common/proc_utils_test.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_svc.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/server/server.go
Labels: forced-landing

#12004 DAOS-11869 doc: add documentation for NVMe-oF export
  docs/user/blockdev.md
  mkdocs.yml
Labels: release-2.4, priority

#11060 DAOS-12137 cart: ensure buffer is unregistered upon IV operation timeout
  src/cart/crt_iv.c
Labels: release-2.4, priority, forced-landing

#12010 DAOS-13195 container: use cont_svc for rdb iterate
  src/container/srv_container.c
  src/include/daos_srv/container.h
  src/pool/srv_pool.c
Labels: release-2.4, priority

#11944 DAOS-11421 test: Use explicit bdev tier roles.
  src/tests/ftest/control/dmg_storage_query.py
  src/tests/ftest/util/storage_utils.py
Labels: release-2.4, priority, forced-landing

#11922 DAOS-13144 test: Enable valgrind on tests that use NVMe
  Jenkinsfile
  ci/unit/test_main.sh
  ci/unit/test_main_node.sh
  utils/run_utest.py
  utils/utest.yaml
Labels: release-2.4, priority

#11943 DAOS-10383 test: Improve failure reporting for enospace test.
  src/tests/ftest/dfuse/enospace.py
  src/tests/ftest/dfuse/sparse_file.py
Labels: release-2.4, priority

#11790 DAOS-9721 test: replace daos.container_create with self.get_container
  src/tests/ftest/container/list.py
  src/tests/ftest/container/list.yaml
  src/tests/ftest/security/cont_acl.yaml
  src/tests/ftest/security/pool_acl.py
  src/tests/ftest/security/pool_acl.yaml
  src/tests/ftest/security/pool_groups.py
  src/tests/ftest/security/pool_groups.yaml
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/pool_security_test_base.py
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#12020 DAOS-13189 test: propagate client/env_vars to daos command
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/performance_test_base.py
Labels: forced-landing

#11952 DAOS-10930 pydaos: Adding option to pass the object class for dictionary as an argument.
  docs/user/python.md
  src/client/pydaos/__init__.py
  src/client/pydaos/pydaos_core.py
  src/client/pydaos/pydaos_shim.c
  src/client/pydaos/raw/README.md
  utils/node_local_test.py
Labels: release-2.4, priority

#12044 DAOS-13144 common/dav: fix Valgrind issues when running DAV unit…
  src/bio/bio_buffer.c
  src/common/dav/dav_iface.c
  src/common/dav/heap.c
  src/common/dav/memblock.c
  src/common/dav/palloc.c
  src/common/dav/tx.c
  src/common/dav/ulog.c
  src/common/dav/util.c
  src/common/dav/valgrind_internal.h
  src/common/tests/umem_test_bmem.c
Labels: release-2.4, priority

#12016 DAOS-13110 common: coverity fixes for vos_on_blob
  src/common/ad_mem.c
  src/common/ad_mem.h
  src/common/ad_tx.c
  src/common/tests/ad_mem_tests.c
Labels: release-2.4, priority
