Repository daos-stack/daos, pull requests merged in 2023-05, with the labels that each got.

#12048 DAOS-13116 doc: Add cert details to security overview
  docs/overview/security.md
Labels: forced-landing, doc-only

#12053 DAOS-13232 bio: adjust minmal hugepages requirement
  src/bio/bio_xstream.c
  src/control/fault/code/codes.go
  src/control/server/config/faults.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/faults.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
Labels: release-2.4, priority

#11969 DAOS-12398 object: Check punch epoch before migration punch (#11667)
  src/include/daos_srv/rebuild.h
  src/object/obj_tx.c
  src/object/srv_obj_migrate.c
  src/placement/jump_map.c
  src/pool/cli.c
  src/pool/srv_pool.c
  src/rebuild/srv.c
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/suite/daos_rebuild.c
  src/tests/suite/daos_rebuild_common.c
  src/tests/suite/daos_rebuild_simple.c
  src/tests/suite/daos_test_common.c
Labels: unclean-cherry-pick

#11996 DAOS-13141 control: Port daos cont create handlers to Go
  src/control/cmd/daos/container.go
  src/utils/daos_hdlr.c
  src/utils/daos_hdlr.h
Labels: forced-landing

#12029 DAOS-12153 cart: Correct mapping of HG_PROTOCOL_ERROR to DER_PROTO. (…
  src/cart/crt_hg.c
  src/cart/crt_hg.h
  src/include/daos_errno.h
Labels: unclean-cherry-pick, release-2.2, priority

#12031 DAOS-12435 control: Remove dmg storage query target-health cmd
  docs/admin/administration.md
  src/bio/README.md
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/json_test.go
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/lib/control/server_meta.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_smd_rpc_test.go
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_query.c
  src/mgmt/tests/mocks.c
  src/proto/ctl/smd.proto
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: forced-landing

#12046 DAOS-12725 test: IOR/small.py Failed (with TCP): Timeout detected.
  src/tests/ftest/ior/small.yaml
Labels: release-2.4, priority

#11971 DAOS-7983 control: Add daos system query command
  src/cart/utils/crt_utils.c
  src/client/api/mgmt.c
  src/control/cmd/daos/main.go
  src/control/cmd/daos/system.go
  src/control/cmd/daos/util.h
  src/control/cmd/daos_agent/attachinfo.go
  src/control/cmd/daos_agent/infocache.go
  src/control/cmd/daos_agent/infocache_test.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/common/proto/mgmt/svc.pb.go
  src/control/lib/control/network.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/system/raft/mocks.go
  src/include/daos/mgmt.h
  src/include/daos_mgmt.h
  src/include/daos_types.h
  src/mgmt/cli_mgmt.c
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/proto/mgmt/svc.proto
  src/tests/ftest/control/daos_system_query.py
  src/tests/ftest/control/daos_system_query.yaml
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/daos_utils_base.py
  src/tests/suite/daos_mgmt.c
Labels: forced-landing

#10846 DAOS-11810 security: improve gen_certificates.sh (#10845)
  utils/certs/SConscript
  utils/certs/ca.cnf
  utils/certs/gen_certificates.sh
Labels: clean-cherry-pick, release-2.2

#11973 DAOS-13122 object: support to bulk transfer CPD RPC sub requests
  src/cart/crt_hg_proc.c
  src/include/cart/api.h
  src/include/daos/object.h
  src/object/obj_rpc.c
  src/object/obj_rpc.h
  src/object/obj_tx.c
  src/object/srv_internal.h
  src/object/srv_obj.c
  src/object/srv_obj_remote.c
Labels: release-2.4

#11616 DAOS-12601 mercury: update to 2.3.0rc5
  site_scons/components/__init__.py
  src/cart/crt_hg.c
  src/cart/utils/memcheck-cart.supp
  utils/build.config
  utils/test_memcheck.supp
Labels: release-2.4, priority

#12034 DAOS-13186 rdb: Enable vos checkpoint ULT in rdb
  src/rdb/rdb.c
  src/rdb/rdb_internal.h
  src/rdb/rdb_raft.c
  src/vos/vos_pool.c
Labels: release-2.4, priority

#12068 DAOS-13259 engine: Check return values
  src/common/tests/drpc_tests.c
  src/engine/drpc_handler.c
  src/engine/drpc_progress.c
  src/engine/srv.c
Labels: release-2.4, priority, forced-landing

#12011 DAOS-12888 test: skip non data device checking
  src/tests/ftest/checksum/csum_error_logging.py
Labels: forced-landing

#12093 DAOS-12562 test: Enable basic test for provider test stages
  src/tests/ftest/harness/basic.py
Labels: release-2.4, priority, forced-landing

#12081 DAOS-13281 test: Fix dmg_storage_query.py bdev_role access
  src/tests/ftest/control/dmg_storage_query.py
Labels: forced-landing

#12090 DAOS-13300 pydaos: Use EX mode for container open in checker
  src/client/pydaos/pydaos_shim.c
  utils/node_local_test.py
Labels: forced-landing

#12079 DAOS-13192 control: Fix NVMe scan when multiple tiers exist
  src/bio/README.md
  src/control/server/ctl_storage.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/server_utils.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/provider.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/provider.go
  src/control/server/storage/provider_test.go
Labels: bug, control-plane, release-2.4, priority, meta-on-ssd

#11925 DAOS-13124 dtx: handle race between DTX refresh and DTX commit
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
Labels: release-2.4

#12021 DAOS-13206 chk: properly set pool status when stop check
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_leader.c
  src/chk/chk_rpc.c
  src/chk/chk_srv.c
Labels: CR

#12013 DAOS-13197 chk: properly handle interrupted check interaction
  src/chk/chk_engine.c
  src/chk/chk_leader.c
Labels: CR

#12105 DAOS-13325 test: set execute permission on tmp test dirs
  src/tests/ftest/launch.py
Labels: forced-landing

#12096 DAOS-13324 test: Sync with pipeline-lib
  Jenkinsfile
Labels: release-2.4, priority

#12017 DAOS-12002 control: General logging cleanup
  src/control/cmd/daos/main.go
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/infocache.go
  src/control/cmd/daos_agent/main.go
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/cmd/daos_agent/procmon.go
  src/control/cmd/daos_agent/security_rpc.go
  src/control/cmd/daos_agent/start.go
  src/control/cmd/daos_server/main.go
  src/control/cmd/daos_server/start.go
  src/control/cmd/daos_server/start_test.go
  src/control/cmd/dmg/main.go
  src/control/common/loglevel.go
  src/control/common/proto/logging.go
  src/control/lib/hardware/fabric.go
  src/control/lib/hardware/hwloc/provider.go
  src/control/lib/hardware/libfabric/provider.go
  src/control/lib/hardware/sysfs/provider.go
  src/control/logging/debug.go
  src/control/logging/defaults.go
  src/control/logging/level.go
  src/control/logging/level_test.go
  src/control/logging/logger.go
  src/control/logging/logging_test.go
  src/control/security/domain_info.go
  src/control/system/raft/database.go
  src/tests/ftest/control/dmg_network_scan.yaml
  utils/config/daos_agent.yml
  utils/config/daos_server.yml
  utils/node_local_test.py
Labels: forced-landing

#12049 DAOS-12859 test: use pool and container labels (pass 1)
  src/tests/ftest/aggregation/multiple_pool_cont.py
  src/tests/ftest/aggregation/shutdown_restart.py
  src/tests/ftest/container/fill_destroy_loop.py
  src/tests/ftest/container/full_pool_container_create.py
  src/tests/ftest/container/multiple_delete.py
  src/tests/ftest/container/per_server_fault_domain.py
  src/tests/ftest/container/snapshot_aggregation.py
  src/tests/ftest/control/daos_object_query.py
  src/tests/ftest/control/daos_snapshot.py
  src/tests/ftest/datamover/dst_create.py
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/basic_checkout.py
  src/tests/ftest/deployment/disk_failure.py
  src/tests/ftest/deployment/io_sys_admin.py
  src/tests/ftest/deployment/server_rank_failure.py
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/erasurecode/cell_size_property.py
  src/tests/ftest/ior/crash.py
  src/tests/ftest/nvme/pool_exclude.py
  src/tests/ftest/nvme/pool_extend.py
  src/tests/ftest/osa/offline_drain.py
  src/tests/ftest/osa/offline_extend.py
  src/tests/ftest/osa/offline_parallel_test.py
  src/tests/ftest/osa/offline_reintegration.py
  src/tests/ftest/osa/online_drain.py
  src/tests/ftest/osa/online_extend.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/pool/autotest.py
  src/tests/ftest/rebuild/delete_objects.py
  src/tests/ftest/scrubber/target_auto_eviction.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/vmd/fault_reintegration.py
Labels: forced-landing

#12101 DAOS-13253 test: Enable libioil and libpil4dfs in soak
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress.py
  src/tests/ftest/soak/stress.yaml
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: release-2.4, priority

#11521 DAOS-12694 cart: Incorporate OPX enablement patch
  site_scons/components/__init__.py
  src/cart/crt_group.c
  src/cart/crt_hg.c
  src/cart/crt_init.c
  src/include/cart/types.h
Labels: forced-landing

#11986 DAOS-13063 admin: Disable parallel rebuild operation in document
  docs/admin/pool_operations.md
Labels: release-2.4, priority

#12117 DAOS-13200 placement: reintegrate rebuilding shard
  src/placement/jump_map.c
  src/placement/tests/jump_map_place_obj.c
Labels: release-2.4, priority

#12072 DOAS-13231 dtx: fix out of boundary issue in dtx_list_cos
  src/dtx/dtx_cos.c
Labels: release-2.4

#12145 DAOS-13440 test: daos_test -R: specify number of svc replicas
  src/tests/ftest/daos_test/suite.yaml
Labels: forced-landing

#12142 DAOS-13432 dtx: fix memory leak for dtx_refresh_internal
  src/dtx/dtx_rpc.c
Labels: release-2.4, priority

#12014 DAOS-13187 client: interoperability between 2.4 client vs 2.2 server
  src/client/api/rpc.c
  src/common/rsvc.c
  src/container/cli.c
  src/container/rpc.h
  src/include/daos/rpc.h
  src/object/cli_mod.c
  src/pool/cli.c
Labels: forced-landing

#12140 DAOS-13410 bio: fix smd_pool_list() without data blobs
  src/bio/smd/smd_pool.c
  src/common/sys_lmdb.c
Labels: forced-landing

#12148 DAOS-13428 test: Fix expected bdev roles for pmem config
  src/control/server/storage/config.go
  src/tests/ftest/control/dmg_storage_query.py
  src/tests/ftest/server/replay.py
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#11345 DAOS-12142 client: add a new interception library
  ci/unit/required_packages.sh
  debian/changelog
  debian/control
  debian/daos-client.install
  src/client/dfuse/SConscript
  src/client/dfuse/pil4dfs/hook.c
  src/client/dfuse/pil4dfs/hook.h
  src/client/dfuse/pil4dfs/hook_int.h
  src/client/dfuse/pil4dfs/int_dfs.c
  src/tests/ftest/daos_test/dfuse.py
  src/tests/ftest/dfuse/fio_pil4dfs_small.py
  src/tests/ftest/dfuse/fio_pil4dfs_small.yaml
  src/tests/ftest/dfuse/mu_perms.py
  src/tests/ftest/ior/intercept_basic.py
  src/tests/ftest/ior/intercept_messages_pil4dfs.py
  src/tests/ftest/ior/intercept_messages_pil4dfs.yaml
  src/tests/ftest/ior/intercept_multi_client.py
  src/tests/ftest/ior/small.yaml
  src/tests/ftest/mdtest/small.yaml
  src/tests/ftest/performance/mdtest_hard.py
  src/tests/ftest/performance/mdtest_hard.yaml
  src/tests/ftest/util/ior_intercept_test_base.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/mdtest_utils.py
  src/tests/ftest/util/performance_test_base.py
  utils/node_local_test.py
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
  utils/scripts/install-el8.sh
  utils/scripts/install-el9.sh
  utils/scripts/install-leap15.sh
  utils/scripts/install-ubuntu.sh
Labels: release-2.4, priority

#12154 DAOS-13444 test: Include stdout for timed out run_remote commands. (#…
  src/tests/ftest/util/run_utils.py
Labels: clean-cherry-pick, forced-landing

#12161 DAOS-13450 cart: Update cart_utils.py to parse out HG_ variables
  src/tests/ftest/cart/util/cart_utils.py
Labels: forced-landing

#12180 DAOS-13479 client: init base_opc in daos_rpc_proto_query()
  src/client/api/rpc.c
Labels: forced-landing

#12156 DAOS-13354 control: Minor code review related fixes
  src/control/server/config/server.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/server_utils.go
  utils/config/daos_server.yml
Labels: control-plane, forced-landing

#12067 DAOS-12899 test: Fix test_create_pool_quantity DER_NOSPACE
  src/tests/ftest/pool/create_capacity.py
  src/tests/ftest/pool/create_capacity.yaml
Labels: forced-landing

#12177 DAOS-9918 test: Remove small pool (128MB) variant from container/full…
  src/tests/ftest/container/full_pool_container_create.yaml
Labels: clean-cherry-pick

#12173 DAOS-13485 client: fix several coverity issues in libpil4dfs
  src/client/dfuse/pil4dfs/hook.c
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: release-2.4, priority

#12197 DAOS-13483 client: to fix libpil4dfs compiling issue on CentOS 7.9
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: release-2.4, priority

#12174 DAOS-12945 object: choose minimum epoch correctly
  src/object/srv_obj_migrate.c
  src/tests/suite/daos_drain_simple.c
Labels: release-2.4, priority

#12129 DAOS-12725 cart: Set server-side cart timeout for ior tests.
  src/tests/ftest/daos_test/dfs.yaml
  src/tests/ftest/erasurecode/ior_smoke.yaml
  src/tests/ftest/erasurecode/mdtest_smoke.yaml
  src/tests/ftest/ior/small.yaml
  src/tests/ftest/mdtest/small.yaml
Labels: release-2.4, priority

#12210 DAOS-12638 array: fix cb order on array get_size and stat (#12204)
  src/client/api/event.c
  src/client/array/dc_array.c
  src/client/dfs/dfs.c
Labels: clean-cherry-pick, release-2.4

#12041 DAOS-9755 control: Add DD_MASK and DD_SUBSYS opts to dmg set-logmasks
  docs/admin/administration.md
  docs/admin/troubleshooting.md
  src/control/cmd/dmg/server.go
  src/control/cmd/dmg/server_test.go
  src/control/common/env_utils.go
  src/control/common/proto/ctl/server.pb.go
  src/control/lib/control/server.go
  src/control/server/ctl_ranks_rpc.go
  src/control/server/ctl_ranks_rpc_test.go
  src/control/server/engine/config.go
  src/control/server/engine/config_test.go
  src/control/server/engine/exec.go
  src/control/server/engine/utils.go
  src/control/server/engine/utils_test.go
  src/gurt/debug.c
  src/gurt/dlog.c
  src/include/gurt/dlog.h
  src/mgmt/server.pb-c.c
  src/mgmt/server.pb-c.h
  src/mgmt/srv_drpc.c
  src/proto/ctl/server.proto
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: control-plane

#12183 DAOS-13447 pil4dfs: Add NLT test for running without dfuse.
  ci/jira_query.py
  utils/node_local_test.py
Labels: release-2.4, priority
