Repository daos-stack/daos, pull requests merged in 2023-07, with the labels that each got.

#12414 DAOS-13730 client: add lock for eq_ref
  src/client/api/event.c
Labels: release-2.4, priority

#12442 DAOS-13696 control: Eliminate possible data races
  docs/admin/troubleshooting.md
  src/control/cmd/daos_agent/infocache.go
  src/control/lib/cache/cache.go
Labels: forced-landing

#12496 DAOS-13412 object: Check shard anchor for enumeration
  src/include/daos_task.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_task.c
  src/tests/suite/daos_obj_ec.c
Labels: release-2.4, priority

#12536 DAOS-13740 cart: fix coverity warning of unused rc
  src/cart/crt_corpc.c
  src/tests/suite/daos_capa.c
Labels: release-2.4, priority

#12514 DAOS-13799 object: check discard status
  src/include/daos_srv/pool.h
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
Labels: release-2.4, priority

#12417 DAOS-13737 container: remove unnecessary assignment
  src/container/srv_target.c
Labels: release-2.4, priority

#12562 DAOS-13781 dfuse: Remove a pointless assignment. (#12468)
  src/client/dfuse/dfuse_core.c
Labels: clean-cherry-pick, release-2.4

#12559 DAOS-13604 dfuse: Fix resource leaks in readdir. (#12408)
  src/client/dfuse/ops/readdir.c
Labels: clean-cherry-pick, release-2.4

#12540 DAOS-13710 client: Fix a return code in dfs_sys. (#12409)
  src/client/dfs/dfs_sys.c
Labels: clean-cherry-pick, release-2.4, priority

#12528 DAOS-13381 il: Reserve low numbered fds when calling daos_init() (#12447)
  src/client/dfuse/il/int_posix.c
Labels: clean-cherry-pick, priority

#12406 DAOS-13598 dfs: Convert a return code correctly in dfs_read. (#12382)
  src/client/dfs/dfs.c
Labels: clean-cherry-pick, release-2.4, priority

#12476 DAOS-13645 control: Make '@' optional in owner user/group (#12404)
  src/control/cmd/daos/acl.go
Labels: clean-cherry-pick, priority, forced-landing

#12489 DAOS-13555 test: remove ftest/pool,container/global_handle (#12434)
  src/tests/ftest/container/global_handle.py
  src/tests/ftest/container/global_handle.yaml
  src/tests/ftest/pool/global_handle.py
  src/tests/ftest/pool/global_handle.yaml
Labels: clean-cherry-pick, priority, forced-landing

#12567 DAOS-12132 test: Enable setting up slurm for tests using partitions (…
  src/tests/ftest/launch.py
  src/tests/ftest/scripts/main.sh
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress.yaml
  src/tests/ftest/util/package_utils.py
  utils/cq/words.dict
Labels: clean-cherry-pick, forced-landing

#12570 DAOS-13886 test: Fix system name validation
  src/control/cmd/dmg/main.go
  src/tests/ftest/control/daos_agent_config.py
  src/tests/ftest/control/daos_agent_config.yaml
  src/tests/ftest/control/daos_control_config.py
  src/tests/ftest/control/daos_control_config.yaml
  src/tests/ftest/control/version.py
Labels: bug

#12564 DAOS-13721 cart: Fix coverity cid 1426658 (#12490)
  src/cart/crt_ctl.c
Labels: clean-cherry-pick, release-2.4, priority, forced-landing

#12364 DAOS-9355 doc: overhaul dfuse --help (#12361)
  src/client/dfuse/dfuse_main.c
Labels: release-2.4

#12569 DAOS-13884 vos: Avoid updating HAE when entries are skipped. (#12557)
  src/vos/vos_aggregate.c
Labels: release-2.4

#12518 DAOS-13341 vos: few other error propagation issues (#12389)
  src/common/btree.c
Labels: release-2.4

#12609 DAOS-13907 kv: allow users to insert keys with empty values (#12590)
  src/client/kv/dc_kv.c
  src/tests/suite/daos_kv.c
Labels: clean-cherry-pick, priority

#12460 DAOS-13694 bio: use large cluster size for pmem mode
  src/bio/bio_xstream.c
Labels: release-2.4

#12603 DAOS-13799 object: check discard status (#12514)
  src/include/daos_srv/pool.h
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
Labels: clean-cherry-pick, release-2.4

#12604 DAOS-13412 object: Check shard anchor for enumeration (#12496)
  src/include/daos_task.h
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_task.c
  src/tests/suite/daos_obj_ec.c
Labels: clean-cherry-pick, release-2.4

#12465 DAOS-12746 control: Support of of NetVSC Azure VM NIC
  src/control/common/env_utils.go
  src/control/common/env_utils_test.go
  src/control/lib/hardware/sysfs/provider.go
  src/control/lib/hardware/sysfs/provider_test.go
  src/control/server/config/server.go
  src/control/server/engine/config.go
  src/control/server/engine/exec.go
Labels: bug

#12513 DAOS-13295 rebuild: exclude EC aggregation with discard
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: release-2.4, priority

#12521 DAOS-13515 vos: use vos format to store SMD (#12251)
  debian/changelog
  debian/control
  site_scons/components/__init__.py
  site_scons/prereq_tools/base.py
  src/bio/SConscript
  src/bio/smd/tests/smd_ut.c
  src/bio/tests/SConscript
  src/common/SConscript
  src/common/mem.c
  src/common/sys_lmdb.c
  src/common/tests/umem_test.c
  src/common/tests/umem_test_bmem.c
  src/common/tests/utest_common.c
  src/engine/srv.c
  src/engine/srv_internal.h
  src/include/daos/mem.h
  src/include/daos/sys_db.h
  src/include/daos_srv/daos_engine.h
  src/include/daos_srv/vos.h
  src/include/daos_srv/vos_types.h
  src/object/srv_ec_aggregate.c
  src/vos/sys_db.c
  src/vos/tests/SConscript
  src/vos/tests/bio_ut.c
  src/vos/tests/bio_ut.h
  src/vos/tests/vts_aggregate.c
  src/vos/tests/vts_io.c
  src/vos/tests/vts_ts.c
  src/vos/tests/vts_wal.c
  src/vos/tests/wal_ut.c
  src/vos/vos_aggregate.c
  src/vos/vos_common.c
  src/vos/vos_container.c
  src/vos/vos_dtx.c
  src/vos/vos_gc.c
  src/vos/vos_ilog.c
  src/vos/vos_ilog.h
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_iterator.c
  src/vos/vos_obj.c
  src/vos/vos_obj.h
  src/vos/vos_obj_cache.c
  src/vos/vos_obj_index.c
  src/vos/vos_pool.c
  src/vos/vos_query.c
  src/vos/vos_tls.h
  src/vos/vos_tree.c
  src/vos/vos_ts.c
  src/vos/vos_ts.h
  utils/rpms/daos.spec
  utils/scripts/install-el8.sh
  utils/scripts/install-el9.sh
  utils/scripts/install-leap15.sh
  utils/scripts/install-ubuntu.sh
  utils/utest.yaml
Labels: unclean-cherry-pick, priority

#12619 DAOS-13696 control: Eliminate possible data races (#12442)
  docs/admin/troubleshooting.md
  src/control/cmd/daos_agent/infocache.go
  src/control/lib/cache/cache.go
Labels: clean-cherry-pick, priority, forced-landing

#12616 DAOS-13776 cart: Inherit CORPC timeout across children (#12585)
  src/cart/crt_corpc.c
  src/cart/crt_hg_proc.c
  src/cart/crt_rpc.c
  src/cart/crt_rpc.h
  src/include/cart/api.h
Labels: clean-cherry-pick, priority

#12591 DAOS-13496 control: Extend timeout for SystemJoin unit test
  src/control/lib/control/mocks.go
  src/control/lib/control/system_test.go
Labels: forced-landing

#12626 DAOS-13876 engine: fix assertion with STACK_MMAP enabled (#12552)
  src/engine/srv_internal.h
Labels: clean-cherry-pick

#12623 DAOS-13694 bio: use large cluster size for pmem mode (#12460)
  src/bio/bio_xstream.c
Labels: clean-cherry-pick, release-2.4

#12615 DAOS-13886 test: Fix version functional test
  src/tests/ftest/control/version.py
  src/tests/ftest/control/version.yaml
  src/tests/ftest/util/general_utils.py
Labels: priority, forced-landing

#12617 DAOS-11830 test: merge intercept_basic with intercept_multi_client (#…
  src/tests/ftest/ior/intercept_basic.py
  src/tests/ftest/ior/intercept_basic.yaml
  src/tests/ftest/ior/intercept_multi_client.py
  src/tests/ftest/ior/intercept_multi_client.yaml
  src/tests/ftest/util/ior_intercept_test_base.py
Labels: clean-cherry-pick, priority

#12558 DAOS-13794 vos: non-committed DTX entry must be in active table
  src/vos/vos_dtx.c
Labels: release-2.4

#12506 DAOS-13805 test: Add support for unique stderr output in run_remote
  src/tests/ftest/harness/unit.py
  src/tests/ftest/harness/unit.yaml
  src/tests/ftest/util/run_utils.py
Labels: forced-landing

#12632 DAOS-11551 control: Flush c output buffer.
  src/control/cmd/daos/util.go
  src/utils/daos_hdlr.c
Labels: priority

#12628 DAOS-13737 container: remove unnecessary assignment (#12417)
  src/container/srv_target.c
Labels: clean-cherry-pick, release-2.4, priority

#12624 DAOS-13678 mgmt: use large RPC timeout for pool creation (#12462)
  src/mgmt/srv_pool.c
Labels: unclean-cherry-pick, release-2.4

#12636 DAOS-13957 object: revert object RPC version bump
  src/object/obj_rpc.h
Labels: release-2.4, priority

#12485 DAOS-13777 control: Invalid storage information with MD-on-SSD
  src/control/lib/control/mocks.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
Labels: bug, forced-landing

#12630 DAOS-13774 control: Don't append ofi_rxm to ofi+tcp provider (#12546)
  src/control/server/server.go
  src/control/server/server_utils_test.go
  src/tests/ftest/launch.py
  src/tests/ftest/util/server_utils_params.py
Labels: clean-cherry-pick, priority, forced-landing

#12437 DAOS-13680 test: fix env_modules exception handling
  site_scons/env_modules.py
Labels: forced-landing

#12639 DAOS-13496 control: Extend timeout for SystemJoin unit test
  src/control/lib/control/mocks.go
  src/control/lib/control/system_test.go
Labels: clean-cherry-pick, priority

#12593 DAOS-13833 test: Add a test for seekdir use in readdir.
  src/client/dfuse/ops/readdir.c
  src/tests/suite/dfuse_test.c
Labels: release-2.4, priority

#12640 DAOS-13805 test: Add support for unique stderr output in run_remote (…
  src/tests/ftest/harness/unit.py
  src/tests/ftest/harness/unit.yaml
  src/tests/ftest/util/run_utils.py
Labels: clean-cherry-pick, forced-landing

#12651 DAOS-13957 object: revert object RPC version bump (#12636)
  src/object/obj_rpc.h
Labels: clean-cherry-pick, release-2.4

#12403 DAOS-13516 object: shrink the group number of GX object (#12217)
  src/include/daos/object.h
  src/object/cli_obj.c
  src/object/obj_class.c
Labels: clean-cherry-pick, release-2.4, priority

#12662 DAOS-13990 test: Allow provider alias values as launch.py inputs.
  src/tests/ftest/launch.py
Labels: forced-landing

#12650 DAOS-11551 control: Flush c output buffer. (#12632)
  src/control/cmd/daos/util.go
Labels: unclean-cherry-pick, priority

#12597 DAOS-13672 control: Calculate engine memory reservation on nr targets
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/dmg/auto_test.go
  src/control/lib/control/auto_test.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm_test.go
Labels: control-plane, forced-landing

#12544 DAOS-13471 control: Add structured version info to utilities
  ci/provisioning/post_provision_config_common_functions.sh
  ci/unit/required_packages.sh
  debian/changelog
  debian/control
  site_scons/site_tools/go_builder.py
  src/control/SConscript
  src/control/build/info.go
  src/control/build/string.go
  src/control/build/variables.go
  src/control/cmd/daos/acl.go
  src/control/cmd/daos/container.go
  src/control/cmd/daos/filesystem.go
  src/control/cmd/daos/main.go
  src/control/cmd/daos/object.go
  src/control/cmd/daos/pool.go
  src/control/cmd/daos/snapshot.go
  src/control/cmd/daos/system.go
  src/control/cmd/daos/util.go
  src/control/cmd/daos_agent/attachinfo.go
  src/control/cmd/daos_agent/main.go
  src/control/cmd/daos_agent/network.go
  src/control/cmd/daos_server/main.go
  src/control/cmd/dmg/auto.go
  src/control/cmd/dmg/cont.go
  src/control/cmd/dmg/firmware.go
  src/control/cmd/dmg/main.go
  src/control/cmd/dmg/network.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/server.go
  src/control/cmd/dmg/storage.go
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/system.go
  src/control/cmd/dmg/telemetry.go
  src/control/common/cmdutil/json.go
  src/control/lib/atm/bool.go
  src/control/lib/control/network.go
  src/control/lib/hardware/hwprov/topology_cmd.go
  src/tests/ftest/control/version.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/server_utils_base.py
  utils/rpms/daos.spec
Labels: priority, forced-landing

#12658 DAOS-13973 cart: Fix interop breakage between 2.2 and 2.4
  src/cart/crt_corpc.c
  src/cart/crt_rpc.h
Labels: clean-cherry-pick, release-2.4, forced-landing

#12673 DAOS-13990 test: Allow provider alias values as launch.py inputs. (#1…
  src/tests/ftest/launch.py
Labels: clean-cherry-pick, forced-landing

#12656 DAOS-13680 test: fix env_modules exception handling (#12437)
  site_scons/env_modules.py
Labels: clean-cherry-pick, priority, forced-landing

#12668 DAOS-13901 client: need to query whether a fd is redirected
  src/client/dfuse/pil4dfs/int_dfs.c
  utils/node_local_test.py
Labels: clean-cherry-pick, release-2.4, priority

#12655 DAOS-13984 test: add ftest utilities for dmg pool upgrade
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#12648 DAOS-13925 object: fix conversion to daos_obj_redun (#12613)
  src/include/daos_obj.h
Labels: bug, clean-cherry-pick, release-2.4, forced-landing

#12589 DAOS-13540 object: handle RESTART for TX convert with condition
  src/object/obj_tx.c
Labels: release-2.4, priority

#12647 DAOS-12746 control: Support of of NetVSC Azure VM NIC (#12465)
  src/control/common/env_utils.go
  src/control/common/env_utils_test.go
  src/control/lib/hardware/sysfs/provider.go
  src/control/lib/hardware/sysfs/provider_test.go
  src/control/server/config/server.go
  src/control/server/engine/config.go
  src/control/server/engine/exec.go
Labels: bug, control-plane, clean-cherry-pick, release-2.4, forced-landing

#12607 DAOS-13928 test: fix nvme/object.py
  src/tests/ftest/nvme/object.py
  src/tests/ftest/nvme/object.yaml
Labels: forced-landing

#12653 DAOS-13833 dfuse: Fix an issue in readdir with seek to start. (#12593)
  src/client/dfuse/ops/readdir.c
  src/tests/suite/dfuse_test.c
Labels: clean-cherry-pick, release-2.4, priority

#12579 DAOS-13503 object: skip redundancy group verification when DTX resync
  src/object/cli_mod.c
  src/object/obj_internal.h
  src/object/obj_tx.c
  src/tests/suite/daos_dist_tx.c
Labels: release-2.4, priority

#12670 DAOS-13896 pool: reintegration discard after rebuild (#12577)
  src/pool/srv_pool.c
Labels: clean-cherry-pick, release-2.4

#12676 DAOS-13906 engine: Check for memory allocation properly to avoid crash. (#12635)
  src/cart/crt_iv.c
  src/engine/server_iv.c
Labels: clean-cherry-pick, priority

#12649 DAOS-13902 pool: Avoid double-free on error. (#12586)
  src/pool/srv_iv.c
Labels: clean-cherry-pick, priority

#12694 DAOS-13940 gurt: Fix log rotation error (#12660)
  src/cart/crt_init.c
  src/gurt/dlog.c
Labels: unclean-cherry-pick, priority

#12703 DAOS-14031 client: change close functions with NULL ev to bypass tse (…
  src/client/api/array.c
  src/client/api/kv.c
  src/client/api/object.c
  src/client/array/dc_array.c
  src/client/dfs/dfs.c
  src/client/dfs/dfs_sys.c
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/il/int_posix.c
  src/client/kv/dc_kv.c
  src/include/daos/array.h
  src/include/daos/kv.h
  src/include/daos/object.h
  src/object/cli_obj.c
Labels: clean-cherry-pick

#12644 DAOS-13670 control: Add system name validation on startup
  src/control/cmd/daos_agent/config.go
  src/control/cmd/dmg/main.go
  src/control/lib/control/config.go
  src/control/lib/daos/system_prop.go
  src/control/server/config/server.go
  src/tests/ftest/control/daos_agent_config.py
  src/tests/ftest/control/daos_agent_config.yaml
  src/tests/ftest/control/daos_control_config.py
  src/tests/ftest/control/daos_control_config.yaml
  src/tests/ftest/control/version.py
  src/tests/ftest/control/version.yaml
  src/tests/ftest/server/daos_server_config.py
  src/tests/ftest/util/general_utils.py
Labels: control-plane, unclean-cherry-pick, priority, forced-landing

#12711 DAOS-13931 object: choose the right target to skip (#12674)
  src/object/cli_obj.c
Labels: clean-cherry-pick, release-2.4

#12707 DAOS-13966 rebuild: don't treat DRAIN target as failed (#12631)
  src/pool/srv_util.c
  src/tests/suite/daos_drain_simple.c
Labels: priority

#12713 DAOS-13964 test: use hg_info instead of fi_info
  src/tests/ftest/launch.py
Labels: release-2.4, priority

#12708 DAOS-13919 control: Fix dmg pool get-prop compat with v2.2 pools
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
Labels: bug, control-plane

#12725 DAOS-14031 client: fix leak in direct calls for closing handles
  src/client/array/dc_array.c
  src/client/kv/dc_kv.c
Labels: priority

#12723 DAOS-13919 control: Fix dmg pool get-prop compat with v2.2 pools (#12…
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
Labels: bug, control-plane, clean-cherry-pick, priority

#12722 DAOS-14064 control: INFO logging for ramdisk/hugepages (#12717)
  src/control/server/config/server.go
Labels: clean-cherry-pick, priority, forced-landing

#12730 DAOS-14031 client: fix leak in direct calls for closing handles (#12725)
  src/client/array/dc_array.c
  src/client/kv/dc_kv.c
Labels: clean-cherry-pick, priority

#12731 DAOS-12638 object: close shard in task completion callback (#12726)
  src/object/cli_obj.c
Labels: clean-cherry-pick

#12738 DAOS-13957 object: revert object RPC version bump (#12636)
  src/object/obj_rpc.h
Labels: clean-cherry-pick, release-2.4, priority
