Repository daos-stack/daos, pull requests merged in 2023-10, with the labels that each got.

#13086 DAOS-14420 control: use hostname -s instead of -d
  src/control/lib/support/log_test.go
Labels: forced-landing

#13027 DAOS-11552 doc: Document Interoperability Policy
  docs/admin/administration.md
Labels: release-2.2, priority

#12949 DAOS-10942 utils: chmod should ignore unsupported bits
  src/control/cmd/daos/filesystem.go
  src/utils/daos_hdlr.c
  src/utils/daos_hdlr.h
Labels: forced-landing

#13108 DAOS-13813 ci: Move GHA build to Fedora 38 (#12516)
  .github/workflows/ci2.yml
  .github/workflows/landing-builds.yml
  site_scons/components/__init__.py
  site_scons/prereq_tools/base.py
  src/bio/bio_wal.c
  src/cart/crt_internal_types.h
  src/client/java/daos-java/pom.xml
  src/client/java/hadoop-daos/pom.xml
  src/object/tests/srv_checksum_tests.c
  utils/build.config
  utils/docker/Dockerfile.el.8
  utils/scripts/install-el8.sh
Labels: clean-cherry-pick

#13046 DAOS-11955 pool: Ensure a PS is inside pool
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/pool/srv_util.c
Labels: forced-landing

#12241 DAOS-12859 test: use pool and container labels (pass 2)
  src/tests/ftest/container/query_attribute.py
  src/tests/ftest/security/cont_acl.py
  src/tests/ftest/security/cont_create_acl.py
  src/tests/ftest/security/cont_delete_acl.py
  src/tests/ftest/security/cont_get_acl.py
  src/tests/ftest/security/cont_overwrite_acl.py
  src/tests/ftest/security/cont_update_acl.py
  src/tests/ftest/security/pool_acl.py
  src/tests/ftest/security/pool_groups.py
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/cont_security_test_base.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/pool_security_test_base.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#13078 DAOS-14018 pool: dup operation detection metadata layout
  src/container/srv_container.c
  src/container/srv_internal.h
  src/container/srv_layout.c
  src/container/srv_layout.h
  src/include/daos/pool.h
  src/include/daos_srv/container.h
  src/include/daos_srv/control.h
  src/include/daos_srv/pool.h
  src/include/daos_srv/rdb.h
  src/pool/srv_layout.c
  src/pool/srv_layout.h
  src/pool/srv_pool.c
  src/rdb/rdb.c
  src/rsvc/srv.c
Labels: forced-landing

#13107 DAOS-13499 tools: fix datamover container create message (#12642)
  src/control/cmd/daos/container.go
  src/control/cmd/daos/filesystem.go
  src/tests/ftest/deployment/basic_checkout.py
  src/utils/daos_hdlr.c
Labels: clean-cherry-pick, priority, forced-landing

#13126 DAOS-14472 cq: fix codespell errors
  .github/workflows/ci2.yml
  SConstruct
  docs/admin/troubleshooting.md
  site_scons/prereq_tools/base.py
  src/bio/bio_context.c
  src/cart/crt_hg_proc.c
  src/cart/crt_register.c
  src/cart/crt_self_test.h
  src/cart/crt_self_test_client.c
  src/client/api/README.md
  src/client/dfuse/dfuse.h
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/il/int_posix.c
  src/client/dfuse/pil4dfs/int_dfs.c
  src/client/java/daos-java/src/main/native/io_daos_dfs_DaosFsClient.c
  src/common/ad_mem.h
  src/common/dav/util.h
  src/control/cmd/daos/README.md
  src/engine/sched.c
  src/gurt/slab.c
  src/gurt/telemetry.c
  src/include/cart/iv.h
  src/include/daos/checksum.h
  src/include/daos/stack_mmap.h
  src/include/daos/tests_lib.h
  src/include/daos_array.h
  src/include/daos_srv/ad_mem.h
  src/include/daos_srv/bio.h
  src/object/obj_tx.c
  src/placement/ring_map.c
  src/rebuild/srv.c
  src/rsvc/srv.c
  src/tests/ftest/cart/util/cart_logparse.py
  src/tests/ftest/dfuse/daos_build.yaml
  src/tests/ftest/harness/skip_list.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/suite/daos_obj.c
  src/utils/ctl/cart_ctl.c
  src/vos/vos_aggregate.c
  src/vos/vos_csum_recalc.c
  utils/cq/words.dict
  utils/scripts/install-leap15.sh
Labels: forced-landing

#13102 DAOS-14427 test: Bump system_ram_reserved for control/log_entry ftest (#13105)
  src/tests/ftest/control/log_entry.yaml
Labels: clean-cherry-pick, priority

#13116 DAOS-12174 control: Query all device-health by default (#12701)
  docs/admin/administration.md
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/server/ctl_smd_rpc_test.go
Labels: control-plane, clean-cherry-pick, priority, go

#13044 DAOS-14223 control: Tidy up pool create workflow
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/ranklist/rank.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
Labels: control-plane, meta-on-ssd

#13161 DAOS-14254 test: Improve test harness server file cleanup in startup (#12978)
  src/tests/ftest/util/server_utils.py
Labels: clean-cherry-pick

#13125 DAOS-14470 test: fix except TestFail uses
  src/tests/ftest/control/dmg_system_cleanup.py
  src/tests/ftest/dfuse/posix_stat.py
  src/tests/ftest/nvme/enospace.py
Labels: forced-landing

#13148 DAOS-13982 rsvc: DAOS_MD_CAP fix, test set compact threshold
  src/include/daos_srv/control.h
  src/rsvc/srv.c
  src/tests/ftest/server/metadata.yaml
Labels: forced-landing

#13179 DAOS-14347 control: Enable setting of port numbers in config generate…
  docs/admin/deployment.md
  src/control/cmd/daos_server/auto.go
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/dmg/auto.go
  src/control/cmd/dmg/auto_test.go
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/pool.go
  src/control/common/cmdutil/auto.go
  src/control/lib/control/auto.go
  src/control/lib/control/auto_test.go
  src/control/lib/control/mocks.go
  src/control/lib/ui/list_flags.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/storage/config.go
  utils/config/daos_server.yml
Labels: control-plane, clean-cherry-pick

#13147 DAOS-14475 test: fix container_create_race
  src/tests/ftest/rebuild/container_create_race.yaml
Labels: forced-landing

#13173 DAOS-13687 test: Fix storage query for multiple data NVMes
  src/tests/ftest/control/dmg_storage_query.py
Labels: forced-landing

#13176 SRE-200 Build: Validate hardware before tests
  Jenkinsfile
  ci/functional/test_main.sh
  ci/functional/test_main_prep_node.sh
  ci/storage/test_main.sh
  ci/storage/test_main_storage_prepare_node.sh
  utils/githooks/find_base.sh
  utils/scripts/helpers/scan_daos_maldet.sh
Labels: unclean-cherry-pick

#13159 DAOS-7847 control: Minor wording changes for pool list
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
Labels: control-plane

#13187 DAOS-14475 test: fix container_create_race (#13147)
  src/tests/ftest/rebuild/container_create_race.yaml
Labels: clean-cherry-pick, forced-landing

#13154 DAOS-14472 cq: fix codespell errors (#13126)
  .github/workflows/ci2.yml
  SConstruct
  docs/admin/troubleshooting.md
  site_scons/prereq_tools/base.py
  src/bio/bio_context.c
  src/cart/crt_hg_proc.c
  src/cart/crt_register.c
  src/cart/crt_self_test.h
  src/cart/crt_self_test_client.c
  src/client/api/README.md
  src/client/dfuse/dfuse.h
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/il/int_posix.c
  src/client/dfuse/pil4dfs/int_dfs.c
  src/client/java/daos-java/src/main/native/io_daos_dfs_DaosFsClient.c
  src/common/ad_mem.h
  src/common/dav/util.h
  src/control/cmd/daos/README.md
  src/engine/sched.c
  src/gurt/slab.c
  src/gurt/telemetry.c
  src/include/cart/iv.h
  src/include/daos/checksum.h
  src/include/daos/stack_mmap.h
  src/include/daos/tests_lib.h
  src/include/daos_array.h
  src/include/daos_srv/ad_mem.h
  src/include/daos_srv/bio.h
  src/object/obj_tx.c
  src/placement/ring_map.c
  src/rebuild/srv.c
  src/rsvc/srv.c
  src/tests/ftest/cart/util/cart_logparse.py
  src/tests/ftest/dfuse/daos_build.yaml
  src/tests/ftest/harness/skip_list.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/suite/daos_obj.c
  src/utils/ctl/cart_ctl.c
  src/vos/vos_aggregate.c
  src/vos/vos_csum_recalc.c
  utils/cq/words.dict
  utils/scripts/install-leap15.sh
Labels: unclean-cherry-pick, priority

#13188 DAOS-13687 test: Fix storage query for multiple data NVMes (#13173)
  src/tests/ftest/control/dmg_storage_query.py
Labels: clean-cherry-pick, forced-landing

#12988 DAOS-13682 client: fix issues of pil4dfs on EL9
  src/client/dfuse/pil4dfs/hook.c
  src/client/dfuse/pil4dfs/hook.h
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: forced-landing

#13193 DAOS-3672 test: Fix larger capacity pool size verification
  src/tests/ftest/pool/verify_space.py
Labels: priority

#13171 DAOS-3672 test: Verify pool space usage via sys commands (#13045)
  src/tests/ftest/pool/verify_space.py
  src/tests/ftest/pool/verify_space.yaml
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/test_utils_pool.py
Labels: clean-cherry-pick, priority

#13186 DAOS-14470 test: fix except TestFail uses (#13125)
  src/tests/ftest/control/dmg_system_cleanup.py
  src/tests/ftest/dfuse/posix_stat.py
  src/tests/ftest/nvme/enospace.py
Labels: clean-cherry-pick, priority

#13205 DAOS-12859 test: use pool and container labels (pass 2) (#12241)
  src/tests/ftest/container/query_attribute.py
  src/tests/ftest/security/cont_acl.py
  src/tests/ftest/security/cont_create_acl.py
  src/tests/ftest/security/cont_delete_acl.py
  src/tests/ftest/security/cont_get_acl.py
  src/tests/ftest/security/cont_overwrite_acl.py
  src/tests/ftest/security/cont_update_acl.py
  src/tests/ftest/security/pool_acl.py
  src/tests/ftest/security/pool_groups.py
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/cont_security_test_base.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/pool_security_test_base.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/util/test_utils_pool.py
Labels: clean-cherry-pick, priority, forced-landing

#13198 DAOS-8100 test: Enable checksum scrubber on online OSA tests.
  src/tests/ftest/osa/online_drain.yaml
  src/tests/ftest/osa/online_extend.yaml
  src/tests/ftest/osa/online_reintegration.yaml
Labels: forced-landing

#13207 DAOS-14461 test: Fix ignoring ior/dfuse failures
  src/tests/ftest/control/dmg_telemetry_io_basic.py
Labels: forced-landing

#13191 DAOS-14028 vos: skip mlock for MD-on-SSD case (#12849)
  src/vos/vos_pool.c
Labels: release-2.4, priority, forced-landing

#13223 DAOS-14461 test: Fix ignoring ior/dfuse failures (#13207)
  src/tests/ftest/control/dmg_telemetry_io_basic.py
Labels: clean-cherry-pick

#13156 DAOS-13613 test: Make 2nd pool create fail with ENOSPACE (#12998)
  src/tests/ftest/control/dmg_system_reformat.yaml
Labels: bug, clean-cherry-pick, priority, meta-on-ssd

#13211 DAOS-14534 test: Fix bandit issues in CR demo scripts
  utils/cr_demo/demo_utils.py
  utils/cr_demo/run_demo_aurora.py
  utils/cr_demo/show_fixed_aurora.py
Labels: forced-landing

#13032 DAOS-14223 mgmt: Use meta blob size if set when creating tgts on rank
  src/control/cmd/dmg/pool.go
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/include/daos_srv/vos.h
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/rpc.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_pool.c
  src/mgmt/srv_target.c
  src/mgmt/tests/mocks.c
  src/proto/mgmt/pool.proto
  src/rdb/rdb.c
  src/tests/vos_engine.c
  src/vos/sys_db.c
  src/vos/tests/pool_scrubbing_tests.c
  src/vos/tests/vos_cmd.c
  src/vos/tests/vts_common.c
  src/vos/tests/vts_container.c
  src/vos/tests/vts_io.c
  src/vos/tests/vts_pool.c
  src/vos/tests/vts_wal.c
  src/vos/vos_pool.c
Labels: forced-landing, meta-on-ssd

#13178 DAOS-13295 rebuild: remove unnecessary yield in container scan cb
  src/rebuild/scan.c
Labels: release-2.4, priority

#13216 DAOS-14475 cq: fix find_base issue from #13135
  utils/githooks/find_base.sh
Labels: priority

#13230 DAOS-13967 engine: Fix NVMe storage leakage with md-on-ssd #12715
  src/control/server/ctl_storage_rpc.go
  src/include/daos_srv/rsvc.h
  src/mgmt/srv_target.c
  src/rsvc/srv.c
  src/tests/ftest/pool/create.yaml
  src/vos/vos_pool.c
  utils/ansible/ftest/templates/daos-make.sh.j2
Labels: clean-cherry-pick, priority

#13229 DAOS-14220 test: Fix ior errors management and fetch metric threshold #12478 #13122
  src/tests/ftest/telemetry/telemetry_pool_metrics.py
Labels: clean-cherry-pick, forced-landing

#13214 DAOS-14475 cq: enhance githook target branch detection (#13135)
  utils/githooks/find_base.sh
  utils/githooks/pre-commit
  utils/githooks/pre-commit.d/10-update-copyright
  utils/githooks/pre-commit.d/20-flake.sh
  utils/githooks/pre-commit.d/40-gofmt.sh
  utils/githooks/pre-commit.d/40-pylint.sh
Labels: unclean-cherry-pick, priority

#13248 DAOS-13503 gurt: add memory metrics (#11956)
  src/cart/README.env
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_srv.c
  src/engine/init.c
  src/engine/srv.c
  src/engine/srv_internal.h
  src/engine/srv_metrics.c
  src/gurt/misc.c
  src/gurt/telemetry.c
  src/include/daos_errno.h
  src/include/daos_srv/dtx_srv.h
  src/include/gurt/common.h
  src/include/gurt/telemetry_common.h
  src/include/gurt/telemetry_producer.h
  src/tests/ftest/util/telemetry_utils.py
  src/utils/daos_metrics/daos_metrics.c
  src/vos/lru_array.c
  src/vos/lru_array.h
  src/vos/tests/vts_io.c
  src/vos/tests/vts_ts.c
  src/vos/vos_common.c
  src/vos/vos_container.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
  src/vos/vos_obj_cache.c
  src/vos/vos_tls.h
  src/vos/vos_ts.c
  src/vos/vos_ts.h
Labels: unclean-cherry-pick, priority

#13174 DAOS-14332 control: Use gRPC metadata for interop (#13018)
  src/control/cmd/daos_agent/main.go
  src/control/cmd/dmg/main.go
  src/control/common/proto/consts.go
  src/control/lib/control/interceptors.go
  src/control/lib/control/mocks.go
  src/control/lib/control/rpc.go
  src/control/security/grpc_authorization.go
  src/control/security/grpc_authorization_test.go
  src/control/server/interceptors.go
  src/control/server/interceptors_test.go
  src/control/server/server.go
  src/control/server/server_utils.go
Labels: clean-cherry-pick, priority
