Repository daos-stack/daos, pull requests merged in 2023-03, with the labels that each got.

#11522 DAOS-11040 common: Move generic slab registration to pool open/create
  src/common/ad_tx.c
  src/common/mem.c
  src/common/tests/umem_test_bmem.c
  src/include/daos/mem.h
  src/vos/evtree.c
  src/vos/tests/vos_cmd.c
  src/vos/vos_internal.h
  src/vos/vos_obj_index.c
  src/vos/vos_pool.c
  src/vos/vos_tree.c
Labels: release-2.4, priority

#11514 DAOS-12308 control: Fix dmg system stop RC (#11483)
  src/control/server/ctl_ranks_rpc.go
  src/control/server/ctl_ranks_rpc_test.go
  src/control/server/instance_drpc.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/system/membership.go
Labels: control-plane, clean-cherry-pick, release-2.2, priority, forced-landing

#11510 DAOS-8714 pool: move pool map transfer outside of the wr lock (#11452)
  src/pool/srv_pool.c
Labels: clean-cherry-pick, release-2.4, priority, forced-landing

#11503 DAOS-12685 test: handle when extra yaml does not exist
  src/tests/ftest/util/yaml_utils.py
Labels: forced-landing

#11593 DAOS-12734 common: Fix for failure/crash on container destroy
  src/common/dav/memops.c
Labels: release-2.4, priority

#11579 DAOS-12314 build: change ipmctl from v2 to v3
  debian/changelog
  debian/control
  utils/rpms/daos.spec
Labels: release-2.4, priority

#11574 DAOS-12721 control: Fix dmg pool get-prop
  src/control/cmd/daos/pool.go
  src/control/cmd/dmg/pool.go
Labels: forced-landing

#11549 DAOS-12690 build: Add go runtime suppression
  src/cart/utils/memcheck-cart.supp
Labels: forced-landing

#11453 DAOS-12646 test: use unique dfuse mount directory
  src/tests/ftest/aggregation/dfuse_space_check.yaml
  src/tests/ftest/control/dmg_telemetry_io_basic.yaml
  src/tests/ftest/daos_test/dfuse.yaml
  src/tests/ftest/daos_vol/bigio.yaml
  src/tests/ftest/daos_vol/h5_suite.yaml
  src/tests/ftest/datamover/negative.py
  src/tests/ftest/datamover/negative.yaml
  src/tests/ftest/datamover/posix_meta_entry.py
  src/tests/ftest/datamover/posix_meta_entry.yaml
  src/tests/ftest/datamover/posix_symlinks.py
  src/tests/ftest/datamover/posix_symlinks.yaml
  src/tests/ftest/datamover/posix_types.py
  src/tests/ftest/datamover/posix_types.yaml
  src/tests/ftest/datamover/serial_large_posix.yaml
  src/tests/ftest/dbench/dbench.py
  src/tests/ftest/dbench/dbench.yaml
  src/tests/ftest/deployment/io_sys_admin.yaml
  src/tests/ftest/dfuse/container_type.yaml
  src/tests/ftest/dfuse/daos_build.yaml
  src/tests/ftest/dfuse/enospace.py
  src/tests/ftest/dfuse/enospace.yaml
  src/tests/ftest/dfuse/posix_stat.yaml
  src/tests/ftest/dfuse/root_container.yaml
  src/tests/ftest/dfuse/sparse_file.yaml
  src/tests/ftest/interoperability/diff_versions.yaml
  src/tests/ftest/io/io_consistency.yaml
  src/tests/ftest/io/large_file_count.yaml
  src/tests/ftest/io/macsio_test.yaml
  src/tests/ftest/io/parallel_io.py
  src/tests/ftest/io/parallel_io.yaml
  src/tests/ftest/io/small_file_count.yaml
  src/tests/ftest/ior/intercept_basic.yaml
  src/tests/ftest/ior/intercept_messages.yaml
  src/tests/ftest/ior/intercept_multi_client.yaml
  src/tests/ftest/mdtest/small.py
  src/tests/ftest/mdtest/small.yaml
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/ior_hard.yaml
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/telemetry/telemetry_pool_metrics.yaml
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/vmd/led.yaml
Labels: forced-landing

#11575 DAOS-12728 test: Fix dictionary string conversion
  src/tests/ftest/io/macsio_test.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#11493 DAOS-12509 dtx: always use helper XS for DTX RPC
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/engine/init.c
  src/engine/srv.c
  src/include/daos_srv/dtx_srv.h
Labels: release-2.4, priority

#11458 DAOS-8772 vos: space reserve for rebuild
  src/include/daos_srv/pool.h
  src/include/daos_srv/vos.h
  src/include/daos_srv/vos_types.h
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
  src/vos/vos_internal.h
  src/vos/vos_pool.c
  src/vos/vos_space.c
Labels: release-2.4, priority

#11584 DAOS-12743 vos: Ensure max_write and aggregation flags get flushed
  src/common/btree.c
  src/vos/evtree.c
  src/vos/vos_io.c
  src/vos/vos_obj.c
Labels: release-2.4, priority

#11416 DAOS-12491 vos: handle DTX conflict for conditional updating ilog
  src/vos/ilog.c
  src/vos/ilog.h
  src/vos/tests/vts_ilog.c
  src/vos/vos_ilog.c
  src/vos/vos_ilog.h
  src/vos/vos_io.c
  src/vos/vos_obj.c
  src/vos/vos_obj_cache.c
  src/vos/vos_obj_index.c
  src/vos/vos_query.c
Labels: release-2.4, priority

#11607 DAOS-623 test: update some missing docstrings
  src/tests/ftest/io/parallel_io.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/results_utils.py
  src/tests/ftest/util/slurm_utils.py
  src/tests/ftest/util/yaml_utils.py
Labels: forced-landing

#11613 DAOS-12441 build: Create 2.4 TB4
  Jenkinsfile
  TAG
  VERSION
  debian/changelog
  utils/rpms/daos.spec
Labels: release-2.4, priority

#11591 DAOS-12714 dfuse: Avoid a dangling pointer when create returns an existing file.
  src/client/dfuse/ops/lookup.c
Labels: release-2.4, priority

#11614 DAOS-12441 build: Create 2.4 TB4
  .github/workflows/create_release.yml
  TAG
  VERSION
  debian/changelog
  utils/rpms/daos.spec
Labels: release-2.4, priority

#11590 DAOS-12745 bio: Enable v2.0 daos_nvme.conf with v2.2 install
  src/bio/bio_config.c
Labels: priority, forced-landing

#11546 DAOS-12555 control: Misc improvements in stand-alone daos_server commands
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
  docs/admin/deployment.md
  src/control/cmd/daos_server/auto.go
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/daos_server/main.go
  src/control/cmd/daos_server/network.go
  src/control/cmd/daos_server/storage_legacy.go
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/cmd/daos_server/storage_scm.go
  src/control/cmd/daos_server/storage_scm_test.go
  src/control/cmd/daos_server/storage_utils.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/scm/mocks.go
Labels: control-plane

#11541 DAOS-12693 object: a few fixes for pool extending
  src/object/srv_obj.c
  src/placement/pl_map_common.c
Labels: release-2.4, priority

#11209 DAOS-11200 test: Test cases for per-server fault domain - rf_lvl:2
  src/tests/ftest/container/per_server_fault_domain.py
  src/tests/ftest/container/per_server_fault_domain.yaml
  src/tests/ftest/util/daos_utils.py
Labels: release-2.4, priority

#11604 DAOS-10859 test: verify dfuse multi-user UNS
  src/tests/ftest/dfuse/mu_mount.py
  src/tests/ftest/dfuse/mu_mount.yaml
Labels: release-2.4, priority, forced-landing

#11344 DAOS-12491 test: Update soak daos container create cmdline
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/soak/faults.yaml
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress_2h.yaml
  src/tests/ftest/soak/stress_48h.yaml
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
  utils/cq/words.dict
Labels: release-2.4, priority

#11619 DAOS-10472 bio: Use hugepages from any NUMA in legacy mode (#11594)
  src/bio/bio_xstream.c
  src/control/server/config/server.go
  src/control/server/config/server_test.go
Labels: control-plane, unclean-cherry-pick, forced-landing

#11615 DAOS-11816 test: wait for rebuild before container destroy
  src/tests/ftest/erasurecode/rebuild_fio.py
Labels: release-2.4, priority, forced-landing

#11570 DAOS-12723 test: fix ExecutableCommand.with_exports for sudo
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/util/cmocka_utils.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/fault_config_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/run_utils.py
Labels: forced-landing

#11540 DAOS-12643 security: Loosen ACL validation (#11499)
  src/client/api/container.c
  src/common/acl_api.c
  src/common/tests/acl_valid_tests.c
  src/container/srv_container.c
  src/include/daos_security.h
  src/security/tests/srv_acl_tests.c
  src/tests/suite/daos_container.c
Labels: clean-cherry-pick, forced-landing

#11538 DAOS-12431 control: Improve certificate error reporting
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/cmd/daos_agent/security_rpc.go
  src/control/cmd/daos_agent/security_rpc_test.go
  src/control/fault/code/codes.go
  src/control/lib/control/interceptors.go
  src/control/lib/control/response.go
  src/control/lib/control/system.go
  src/control/lib/control/system_test.go
  src/control/lib/daos/status.go
  src/control/security/config.go
  src/control/security/config_test.go
  src/control/security/faults.go
  src/control/security/pem.go
  src/control/security/testdata/certs/RSA.golden
  src/control/security/testdata/certs/agent.crt
  src/control/security/testdata/certs/agent.key
  src/control/security/testdata/certs/daosCA.crt
  src/control/security/testdata/certs/daosCA.key
  src/control/security/testdata/certs/server.crt
  src/control/security/testdata/certs/server.key
  src/include/daos_errno.h
Labels: forced-landing

#11626 DAOS-12573 test: wait on rebuild before teardown/cont destroy
  src/tests/ftest/erasurecode/online_rebuild_single.py
Labels: forced-landing

#11625 DAOS-12835 dfs: getxattr shouldn't return error if value wasn't set
  src/client/dfs/dfs.c
  src/tests/suite/dfs_unit_test.c
Labels: forced-landing

#11517 DAOS-12631 object: force degrade fetch for EC reintegration (#11486)
  src/object/cli_obj.c
  src/object/srv_obj_migrate.c
  src/tests/suite/daos_rebuild_ec.c
Labels: unclean-cherry-pick, release-2.4, priority

#11661 DAOS-11421 test: Adding weekly timed testing
  Jenkinsfile
Labels: release-2.4, priority

#11520 DAOS-10858 test: dfuse multi-user perms with caching
  src/tests/ftest/container/query_attribute.py
  src/tests/ftest/daos_test/dfuse.py
  src/tests/ftest/dfuse/daos_build.py
  src/tests/ftest/dfuse/mu_perms.py
  src/tests/ftest/dfuse/mu_perms.yaml
  src/tests/ftest/util/cont_security_test_base.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/fio_test_base.py
  src/tests/ftest/util/soak_utils.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/util/verify_perms.py
Labels: release-2.4, priority, forced-landing

#11640 DAOS-12689 control: Don't return an error if dlsym succeeded (#11596)
  src/control/lib/dlopen/dlopen.go
Labels: clean-cherry-pick, release-2.2

#11446 DAOS-7338 test: Exclude and Reintegration with EC Objects
  src/tests/ftest/nvme/pool_exclude.yaml
  src/tests/ftest/nvme/pool_extend.yaml
Labels: release-2.4, priority

#11601 DAOS-11203 dtx: reduce DTX refresh RPC timeout
  src/dtx/dtx_rpc.c
  src/object/cli_shard.c
Labels: release-2.4, priority

#11647 DAOS-12826 control: Handle empty storage tier in config unmarshal
  src/control/server/config/server_test.go
  src/control/server/storage/config.go
  src/control/server/storage/config_test.go
Labels: release-2.4, priority, forced-landing

#11611 DAOS-12728 test: Fix dictionary string conversion (#11575)
  src/tests/ftest/io/macsio_test.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: unclean-cherry-pick, priority

#11643 DAOS-12724 test: Increase test_dfuse_daos_build_wt scons timeout
  src/tests/ftest/dfuse/daos_build.py
Labels: forced-landing

#11467 DAOS-12636 container: set status property to unhealthy
  src/common/cont_props.c
  src/container/cli.c
  src/container/container_iv.c
  src/container/srv_container.c
  src/container/srv_epoch.c
  src/container/srv_internal.h
  src/container/srv_target.c
  src/include/daos_srv/container.h
  src/object/cli_obj.c
  src/object/obj_ec.h
  src/object/obj_task.c
  src/object/srv_obj.c
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/rebuild/basic.yaml
  src/tests/ftest/rebuild/cascading_failures.yaml
  src/tests/ftest/rebuild/delete_objects.yaml
  src/tests/ftest/rebuild/read_array.yaml
  src/tests/suite/daos_base_tx.c
  src/tests/suite/daos_container.c
  src/tests/suite/daos_degrade_ec.c
  src/tests/suite/daos_degraded.c
  src/tests/suite/daos_dist_tx.c
  src/tests/suite/daos_drain_simple.c
  src/tests/suite/daos_obj.c
  src/tests/suite/daos_oid_alloc.c
  src/tests/suite/daos_pool.c
  src/tests/suite/daos_rebuild.c
  src/tests/suite/daos_rebuild_common.c
  src/tests/suite/daos_rebuild_ec.c
  src/tests/suite/daos_rebuild_simple.c
  src/tests/suite/daos_test.h
  src/tests/suite/daos_test_common.c
Labels: release-2.4, priority

#11463 DAOS-10912 test: Verify EC space consumption
  src/tests/ftest/erasurecode/space_usage.py
  src/tests/ftest/erasurecode/space_usage.yaml
  src/tests/ftest/harness/unit.py
  src/tests/ftest/harness/unit.yaml
  src/tests/ftest/launch.py
  src/tests/ftest/util/data_utils.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/oclass_utils.py
  src/tests/ftest/util/test_utils_pool.py
  src/tests/ftest/util/yaml_utils.py
Labels: release-2.4, priority, forced-landing

#11550 DAOS-12705 test: Ensure daos_server processes are killed between tests
  src/tests/ftest/cart/util/cart_utils.py
  src/tests/ftest/container/boundary.py
  src/tests/ftest/control/ms_resilience.py
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/server_rank_failure.py
  src/tests/ftest/harness/setup.py
  src/tests/ftest/harness/setup.yaml
  src/tests/ftest/harness/setup_hw.py
  src/tests/ftest/harness/setup_hw.yaml
  src/tests/ftest/launch.py
  src/tests/ftest/network/cart_self_test.py
  src/tests/ftest/pool/management_race.py
  src/tests/ftest/util/agent_utils_params.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/control_test_base.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/dmg_utils_params.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/run_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/server_utils_params.py
  src/tests/ftest/util/test_utils_pool.py
Labels: release-2.4, priority

#11553 DAOS-10857 test: verify dfuse multi-user permissions with IL
  src/tests/ftest/dfuse/mu_perms.py
  src/tests/ftest/util/dfuse_utils.py
Labels: release-2.4, priority

#11662 DAOS-623 test: fix basic checkout dm ppn
  src/tests/ftest/deployment/basic_checkout.py
Labels: forced-landing

#11669 DAOS-12863 cart: Fix bug in d_rank_list_dup_sort_uniq
  src/gurt/misc.c
  src/gurt/tests/test_gurt.c
Labels: forced-landing

#11682 DAOS-12826 control: Handle empty storage tier in config unmarshal (#1…
  src/control/server/config/server_test.go
  src/control/server/storage/config.go
  src/control/server/storage/config_test.go
Labels: control-plane, unclean-cherry-pick, release-2.2, priority

#11691 DAOS-623 common: Fix codespell errors that started showing up on PRs …
  ci/codespell.ignores
  docs/admin/deployment.md
  docs/user/filesystem.md
  src/common/credit.c
  src/common/tests/acl_util_tests.c
  src/common/tests/checksum_tests.c
  src/include/daos_srv/daos_engine.h
  src/object/obj_tx.c
  src/tests/ftest/cart/test_group_np_common.h
  src/tests/ftest/soak/harassers.py
  src/tests/ftest/util/general_utils.py
  src/tests/suite/daos_obj.c
  src/vos/tests/vts_common.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
Labels: unclean-cherry-pick

#11676 DAOS-5936 control: Remove -u flag from daos cont create
  docs/user/container.md
  src/control/cmd/daos/container.go
Labels: forced-landing

#11700 DAOS-12412 test: Allow for log collection w/ No space left on device
  src/tests/ftest/launch.py
Labels: release-2.4, priority

#11709 DAOS-11421 test: Set the default Test-nvme arg for vos_on_blob
  Jenkinsfile
Labels: release-2.4, priority, forced-landing

#11711 DAOS-12719 test: Ignore missing expected stack trace on el7 (#11694)
  src/tests/ftest/harness/core_files.py
  src/tests/ftest/launch.py
Labels: clean-cherry-pick

#11705 DAOS-12447 vos: fix LRU array free lru_sub list corruption
  src/vos/lru_array.c
  src/vos/lru_array.h
Labels: clean-cherry-pick

#11725 DAOS-12903 test: Allow for log collection w/ No space left on device (#11700)
  src/tests/ftest/launch.py
Labels: clean-cherry-pick

#11651 DAOS-12677 test: Update dmg storage query commands to use json output
  src/tests/ftest/checksum/csum_error_logging.py
  src/tests/ftest/control/dmg_server_set_logmasks.py
  src/tests/ftest/control/dmg_storage_query.py
  src/tests/ftest/deployment/disk_failure.py
  src/tests/ftest/deployment/disk_failure.yaml
  src/tests/ftest/nvme/health.py
  src/tests/ftest/util/control_test_base.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/nvme_utils.py
  src/tests/ftest/vmd/led.py
Labels: release-2.4, priority

#11635 DAOS-12732 pool: recheck pool stopping in pool_iv_ent_refresh (#11605)
  src/pool/srv_iv.c
Labels: clean-cherry-pick, release-2.4

#11665 DAOS-10079 control: Include owner/group in JSON get-acl output
  src/control/common/proto/mgmt/acl.pb.go
  src/control/common/proto/types.go
  src/control/lib/control/acl.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_acl.go
  src/control/lib/control/pool_acl_test.go
  src/control/server/mgmt_pool_test.go
  src/mgmt/acl.pb-c.c
  src/mgmt/acl.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/tests/srv_drpc_tests.c
  src/proto/mgmt/acl.proto
Labels: forced-landing

#11624 DAOS-12706 object: Some memory corruption issue
  src/object/srv_obj.c
Labels: release-2.4, priority

#11708 DAOS-7615 test: Include DM job in soak
  src/tests/ftest/soak/faults.yaml
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress_2h.yaml
  src/tests/ftest/soak/stress_48h.yaml
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: release-2.4, priority

#11636 DAOS-12693 object: a few fixes for pool extending (#11541)
  src/object/srv_obj.c
  src/placement/pl_map_common.c
Labels: clean-cherry-pick, release-2.4

#11734 DAOS-12924 build: Add numactl dep to agent and server in spec
  debian/changelog
  utils/rpms/daos.spec
Labels: dependencies, forced-landing

#11750 DAOS-10035 test: Include VMD led check in soak harassers
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: release-2.4, priority

#11653 DAOS-12224 control: With md_on_ssd, remount tmpfs on engine restart
  src/bio/smd/smd_internal.h
  src/bio/smd/smd_pool.c
  src/control/server/instance_storage.go
  src/control/server/storage/provider.go
  src/include/daos_srv/smd.h
  src/mgmt/srv_target.c
Labels: release-2.4, priority

#7678 DAOS-9163 pool: Do map_dist for restarted ranks
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/pool/srv_util.c
Labels: forced-landing

#11749 DAOS-12843 ddb: Make sure VOS file is closed before exiting
  src/control/cmd/ddb/commands_wrapper.go
  src/control/cmd/ddb/main.go
  src/ddb/ddb.h
  src/ddb/ddb_commands.c
Labels: forced-landing

#11642 DAOS-12311 control: Enable socket affinity in daos_server scm cmds
  src/control/cmd/daos_server/storage_legacy_test.go
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_scm.go
  src/control/cmd/daos_server/storage_scm_test.go
  src/control/cmd/daos_server_helper/handler_test.go
  src/control/server/storage/faults.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/ipmctl_namespace.go
  src/control/server/storage/scm/ipmctl_region.go
  src/control/server/storage/scm/ipmctl_region_test.go
  src/control/server/storage/scm/ipmctl_test.go
  src/control/server/storage/scm/mocks.go
  src/control/server/storage/scm/ndctl.go
  src/control/server/storage/scm/ndctl_test.go
  src/control/server/storage/scm/provider_test.go
Labels: control-plane, forced-landing

#11798 DAOS-12857 csum: Initialize RPC object for CSUM Report
  src/object/cli_shard.c
  src/tests/suite/daos_rebuild_simple.c
Labels: forced-landing

#11703 DAOS-12595 dtx: support CPU yield during local TX commit
  src/dtx/dtx_common.c
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
  src/include/daos/dtx.h
  src/include/daos_srv/container.h
  src/include/daos_srv/dtx_srv.h
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/vos/ilog.c
  src/vos/lru_array.h
  src/vos/tests/vts_dtx.c
  src/vos/tests/vts_mvcc.c
  src/vos/vos_common.c
  src/vos/vos_container.c
  src/vos/vos_dtx.c
  src/vos/vos_dtx_iter.c
  src/vos/vos_ilog.c
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_obj.c
  src/vos/vos_tree.c
Labels: release-2.4, priority

#11768 DAOS-12904 tools: Close files in cleanup closure
  src/control/cmd/daos/container_test.go
  src/control/cmd/daos/util.go
Labels: forced-landing

#11736 DAOS-12847 container: cache nhandles in batch close rdb tx
  src/container/srv_container.c
  src/tests/ftest/ior/crash.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/suite/daos_container.c
Labels: forced-landing

#11723 DAOS-12911 dtx: handle stale pool map when prepare TX commit
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_tx.c
Labels: release-2.4, priority

#11537 DAOS-12707 cart: Automatically clamp ports to 0-511 range for CXI
  src/cart/README.env
  src/cart/crt_init.c
  src/tests/ftest/cart/dual_iface_server.c
  src/utils/crt_launch/crt_launch.c
Labels: forced-landing

#11799 DAOS-12674 test: nvme/enospace.py test not waiting for thread completion
  src/tests/ftest/nvme/enospace.py
Labels: release-2.4, priority

#11769 DAOS-9721 test: update tests to use get_container
  src/tests/ftest/container/simple_create_delete.py
  src/tests/ftest/control/dmg_telemetry_io_latency.py
  src/tests/ftest/control/dmg_telemetry_io_latency.yaml
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/security/cont_acl.py
  src/tests/ftest/security/cont_create_acl.py
  src/tests/ftest/security/cont_delete_acl.py
  src/tests/ftest/security/cont_get_acl.py
  src/tests/ftest/security/cont_overwrite_acl.py
  src/tests/ftest/security/cont_update_acl.py
  src/tests/ftest/util/cont_security_test_base.py
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/pool_security_test_base.py
Labels: forced-landing

#11572 DAOS-10192 vos: Add storage usage metrics
  src/tests/ftest/telemetry/pool_space_metrics.py
  src/tests/ftest/telemetry/pool_space_metrics.yaml
  src/tests/ftest/util/telemetry_utils.py
  src/vos/vos_common.c
  src/vos/vos_gc.c
  src/vos/vos_internal.h
  src/vos/vos_space.c
  utils/ansible/ftest/templates/daos-launch.sh.j2
  utils/ansible/ftest/templates/daos-make.sh.j2
Labels: release-2.4, priority

#11727 DAOS-11630 test: Add md on ssd replay test case
  src/tests/ftest/server/replay.py
  src/tests/ftest/server/replay.yaml
  src/tests/ftest/util/ior_utils.py
Labels: release-2.4, priority

#11599 DAOS-12577 dfuse: Update NLT to test cache on lookup.
  utils/node_local_test.py
Labels: release-2.4, priority

#11760 DAOS-12672 control: Make dRPC calls context aware
  src/control/cmd/hello_drpc/main.go
  src/control/drpc/drpc_client.go
  src/control/drpc/drpc_client_test.go
  src/control/drpc/drpc_server_test.go
  src/control/server/drpc.go
  src/control/server/drpc_test.go
  src/control/server/mgmt_pool_test.go
  src/control/server/util_test.go
Labels: bug, control-plane, release-2.4, priority, forced-landing

#11845 DAOS-13062 tests: change rd_fac to rf for 22
  src/tests/ftest/rebuild/basic.yaml
  src/tests/ftest/rebuild/cascading_failures.yaml
  src/tests/ftest/rebuild/delete_objects.yaml
  src/tests/ftest/rebuild/read_array.yaml
Labels: release-2.2
