Repository daos-stack/daos, pull requests merged in 2023-09, with the labels that each got.

#12994 DAOS-14208 object: do not cross stripe during parity rebuild
  src/object/srv_obj_migrate.c
Labels: release-2.4, priority

#13012 DAOS-13674 test: Bump pool size in container/snapshot.py
  src/tests/ftest/container/snapshot.py
  src/tests/ftest/container/snapshot.yaml
Labels: release-2.4, priority

#12995 DAOS-14208 object: do not cross stripe during parity rebuild
  src/object/srv_obj_migrate.c
Labels: clean-cherry-pick, release-2.4, priority

#13017 DAOS-14301 test: Disable fault injection tests from release testing. …
  src/tests/ftest/scrubber/csum_fault.py
Labels: clean-cherry-pick

#13015 DAOS-13674 test: Bump pool size in container/snapshot.py (#13012)
  src/tests/ftest/container/snapshot.py
  src/tests/ftest/container/snapshot.yaml
Labels: release-2.4

#12300 DAOS-12541 ddb: Improved List Output
  src/control/cmd/ddb/commands_wrapper.go
  src/control/cmd/ddb/ddb_commands.go
  src/control/cmd/ddb/main.go
  src/control/run_go_tests.sh
  src/ddb/SConscript
  src/ddb/ddb.c
  src/ddb/ddb.h
  src/ddb/ddb_commands.c
  src/ddb/ddb_common.h
  src/ddb/ddb_parse.c
  src/ddb/ddb_parse.h
  src/ddb/ddb_printer.c
  src/ddb/ddb_printer.h
  src/ddb/ddb_tree_path.c
  src/ddb/ddb_tree_path.h
  src/ddb/ddb_vos.c
  src/ddb/ddb_vos.h
  src/ddb/tests/SConscript
  src/ddb/tests/ddb_cmd_options_tests.c
  src/ddb/tests/ddb_cmocka.h
  src/ddb/tests/ddb_commands_print_tests.c
  src/ddb/tests/ddb_commands_tests.c
  src/ddb/tests/ddb_parse_tests.c
  src/ddb/tests/ddb_path_tests.c
  src/ddb/tests/ddb_test_driver.c
  src/ddb/tests/ddb_test_driver.h
  src/ddb/tests/ddb_vos_tests.c
  src/tests/ftest/recovery/ddb.py
Labels: forced-landing

#12852 DAOS-13975 control: Store checker policies in MS only
  src/control/cmd/dmg/check.go
  src/control/cmd/dmg/check_test.go
  src/control/common/proto/mgmt/check.pb.go
  src/control/server/mgmt_check.go
  src/control/server/mgmt_check_test.go
  src/mgmt/check.pb-c.c
  src/mgmt/check.pb-c.h
  src/proto/mgmt/check.proto
Labels: CR

#13025 DAOS-14228 tests: Adjust pool/create_all_vm.yaml (#12955)
  src/tests/ftest/pool/create_all_vm.yaml
Labels: clean-cherry-pick, forced-landing

#12978 DAOS-14254 test: Improve test harness server file cleanup in startup
  src/tests/ftest/util/server_utils.py
Labels: forced-landing

#13022 DAOS-14208 rebuild: several fixes for multiple shards in the same target
  src/object/srv_obj_migrate.c
  src/placement/jump_map.c
  src/placement/pl_map_common.c
  src/placement/tests/jump_map_place_obj.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/tests/ftest/daos_test/suite.yaml
  src/tests/ftest/rebuild/basic.py
  src/tests/ftest/rebuild/container_create_race.py
  src/tests/ftest/rebuild/with_io.py
  src/tests/ftest/util/rebuild_test_base.py
  src/tests/suite/daos_rebuild_ec.c
Labels: release-2.4, priority

#13040 DAOS-14254 test: Fix functional test server cleanup
  src/tests/ftest/util/server_utils.py
Labels: forced-landing

#13035 DAOS-14309 packaging: remove daos tests RPMs from distro
  .rpmignore
Labels: release-2.4

#13048 DAOS-14302 test: Skip DAOS_Drain_Simple w/o fault injection (#13039)
  src/tests/suite/daos_drain_simple.c
  src/tests/suite/daos_extend_simple.c
  src/tests/suite/daos_obj_ec.c
Labels: clean-cherry-pick, priority, forced-landing

#13042 Wangdi/release 24 14338
  src/object/srv_obj_migrate.c
Labels: clean-cherry-pick, release-2.4

#13051 DAOS-14302 test: Fix skipping DAOS_Drain_Simple tests
  src/tests/suite/daos_drain_simple.c
Labels: priority, forced-landing

#13059 DAOS-14365 build: Tag 2.4.0 rc2
  TAG
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#13062 DAOS-14385 test: Fix TestPool.pool_query_delay use
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#12857 DAOS-13989 control: Condense checker findings in non-verbose mode
  src/control/cmd/dmg/pretty/check.go
  src/control/cmd/dmg/pretty/check_test.go
Labels: CR

#11956 DAOS-12945 vos: add memory metrics
  src/cart/README.env
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_srv.c
  src/engine/init.c
  src/engine/srv.c
  src/engine/srv_internal.h
  src/engine/srv_metrics.c
  src/gurt/misc.c
  src/gurt/telemetry.c
  src/include/daos_errno.h
  src/include/daos_srv/dtx_srv.h
  src/include/gurt/common.h
  src/include/gurt/telemetry_common.h
  src/include/gurt/telemetry_producer.h
  src/tests/ftest/util/telemetry_utils.py
  src/utils/daos_metrics/daos_metrics.c
  src/vos/lru_array.c
  src/vos/lru_array.h
  src/vos/tests/vts_io.c
  src/vos/tests/vts_ts.c
  src/vos/vos_common.c
  src/vos/vos_container.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
  src/vos/vos_obj_cache.c
  src/vos/vos_tls.h
  src/vos/vos_ts.c
  src/vos/vos_ts.h
Labels: release-2.4, priority

#13001 DAOS-9882 doc: linkchecker on v2.4 docs
  docs/admin/performance_tuning.md
  docs/admin/predeployment_check.md
  docs/release/release_notes.md
  docs/release/support_matrix.md
  docs/release/upgrading.md
  docs/user/spark.md
Labels: release-2.4

#13074 DAOS-12425 control: Add opt to auto-format on server start-up
  src/control/cmd/daos_server/start.go
  src/control/server/config/server.go
  src/control/server/server.go
Labels: control-plane

#12900 DAOS-14101 control: dRPC related fixes for VMD-LED
  docs/admin/administration.md
  src/bio/bio_device.c
  src/bio/bio_xstream.c
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/lib/daos/status.go
  src/control/server/ctl_ranks_rpc.go
  src/control/server/ctl_ranks_rpc_test.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_smd_rpc_test.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/harness.go
  src/control/server/harness_test.go
  src/control/server/instance.go
  src/control/server/instance_drpc.go
  src/control/server/instance_drpc_test.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_system.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev_test.go
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_query.c
  src/proto/ctl/smd.proto
  src/vos/tests/bio_ut.c
  utils/run_utest.py
Labels: bug, enhancement, control-plane, unclean-cherry-pick, release-2.4, priority, vmd, go

#12906 DAOS-13759 control: Update support collect-log tool.
  src/control/cmd/daos_agent/support.go
  src/control/cmd/daos_server/support.go
  src/control/cmd/dmg/pretty/printers.go
  src/control/cmd/dmg/pretty/printers_test.go
  src/control/cmd/dmg/support.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/lib/control/pool.go
  src/control/lib/support/log.go
  src/mgmt/pool.pb-c.h
  src/proto/mgmt/pool.proto
  src/tests/ftest/control/daos_server_support_collect_log.py
  src/tests/ftest/control/dmg_support_collect_log.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/support_test_base.py
Labels: release-2.4, priority

#12975 DAOS-14246 vos: do not reset dae_preparing until dtx_rec_release done
  src/vos/vos_common.c
  src/vos/vos_dtx.c
Labels: release-2.4

#13075 DAOS-623 build: fix build when lustre APIs are installed (#13069)
  src/client/dfs/duns.c
Labels: clean-cherry-pick

#13104 Revert "DAOS-14225 control: Prevent duplicate call to SetRank"
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/svc.pb.go
  src/control/server/instance.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/proto/mgmt/svc.proto
Labels: priority
