Repository daos-stack/daos, pull requests merged in 2023-01, with the labels that each got.

#11118 DAOS-623 test: remove duplicate ior pool space functions
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#11116 DAOS-12259 test: reduce dfuse caching perf threshold
  src/tests/ftest/dfuse/caching_check.py
  src/tests/ftest/dfuse/caching_check.yaml
Labels: forced-landing

#11109 DAOS-12277 test: Convert suite to use new-style dmg helpers (#11090)
  src/common/tests_dmg_helpers.c
  src/include/daos/tests_lib.h
  src/tests/suite/daos_checksum.c
  src/tests/suite/daos_container.c
  src/tests/suite/daos_epoch_io.c
  src/tests/suite/daos_obj.c
  src/tests/suite/daos_pool.c
  src/tests/suite/daos_rebuild.c
  src/tests/suite/daos_rebuild_common.c
  src/tests/suite/daos_rebuild_simple.c
  src/tests/suite/daos_test.h
  src/tests/suite/daos_test_common.c
Labels: unclean-cherry-pick

#10689 DAOS-12041 test: Add a fault injection test for container create
  src/common/prop.c
  src/control/cmd/daos/container.go
  utils/node_local_test.py
Labels: priority

#11115 DAOS-11873 test: datamover dcp test with root->new dir
  src/tests/ftest/datamover/posix_subsets.py
  src/tests/ftest/datamover/posix_subsets.yaml
Labels: release-2.4, priority, forced-landing

#11050 DAOS-11040 common: add lmdb backend kv for SMD
  debian/control
  site_scons/components/__init__.py
  src/bio/bio_context.c
  src/bio/bio_wal.c
  src/bio/bio_wal.h
  src/bio/bio_xstream.c
  src/bio/smd/smd_internal.h
  src/bio/smd/tests/smd_ut.c
  src/common/SConscript
  src/common/sys_lmdb.c
  src/engine/srv.c
  src/include/daos/sys_db.h
  src/include/daos_srv/bio.h
  src/include/daos_srv/daos_engine.h
  src/include/daos_srv/vos_types.h
  src/vos/sys_db.c
  src/vos/vos_common.c
  src/vos/vos_internal.h
  src/vos/vos_pool.c
  utils/rpms/daos.spec
  utils/run_test.sh
  utils/scripts/install-el8.sh
  utils/scripts/install-el9.sh
  utils/scripts/install-leap15.sh
  utils/scripts/install-ubuntu.sh
Labels: release-2.4, priority

#10993 DAOS-12112 engine: check master rank for IV update
  src/engine/server_iv.c
Labels: release-2.2, release-2.4, priority

#10459 DAOS-11679 dtx: dispatch large transaction via multiple steps
  src/dtx/dtx_common.c
  src/dtx/dtx_rpc.c
  src/include/daos_srv/dtx_srv.h
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_tx.c
  src/object/srv_obj.c
  src/object/srv_obj_remote.c
Labels: release-2.4, priority

#11072 DAOS-11412 bio: verify tx blocks
  src/bio/bio_wal.c
Labels: release-2.4, priority

#11124 DAOS-12258 test: fix run_dm_activities_with_ior testfile
  src/tests/ftest/util/data_mover_test_base.py
Labels: release-2.2, forced-landing

#11117 DAOS-11605 ad_mem: add another performance test
  src/common/ad_mem.c
  src/common/tests/ad_mem_tests.c
Labels: release-2.4, priority

#11111 DAOS-12307 test: correct np to ppn
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/agent_failure.yaml
Labels: forced-landing

#11134 DAOS-8722 dfuse: Add common init function for inodes and checking to readdir.
  src/client/dfuse/dfuse.h
  src/client/dfuse/dfuse_cont.c
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/dfuse_pool.c
  src/client/dfuse/ops/create.c
  src/client/dfuse/ops/lookup.c
  src/client/dfuse/ops/mknod.c
  src/client/dfuse/ops/readdir.c
  src/client/dfuse/ops/symlink.c
Labels: release-2.4, priority, forced-landing

#11119 DAOS-623 test: resolve IorMetrics lint warnings
  src/tests/ftest/aggregation/throttling.py
  src/tests/ftest/dfuse/caching_check.py
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/util/ior_intercept_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/performance_test_base.py
Labels: forced-landing

#11077 DAOS-8135 test: dfuse mount permissions
  docs/user/filesystem.md
  src/tests/ftest/dfuse/mu_mount.py
  src/tests/ftest/dfuse/mu_mount.yaml
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/test_utils_container.py
Labels: release-2.4, priority, forced-landing

#11075 Ivanodmi/vos on blob/daos 12217
  src/bio/bio_context.c
  src/bio/bio_wal.c
  src/common/dav/dav_iface.c
  src/common/dav/wal_tx.c
  src/common/dav/wal_tx.h
  src/include/daos/mem.h
  src/include/daos_srv/bio.h
  src/vos/tests/vts_common.h
  src/vos/tests/vts_wal.c
  src/vos/vos_pool.c
Labels: release-2.4, meta-on-ssd

#10891 DAOS-10578 control: Add daos_server config generate command
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/fabric_test.go
  src/control/cmd/daos_agent/infocache_test.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/cmd/daos_agent/network.go
  src/control/cmd/daos_agent/network_test.go
  src/control/cmd/daos_server/auto.go
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/daos_server/command_test.go
  src/control/cmd/daos_server/main.go
  src/control/cmd/daos_server/network.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/cmd/dmg/auto.go
  src/control/cmd/dmg/auto_test.go
  src/control/lib/control/auto.go
  src/control/lib/control/auto_test.go
  src/control/lib/control/mocks.go
  src/control/lib/hardware/fabric.go
  src/control/lib/hardware/fabric_test.go
  src/control/lib/hardware/libfabric/provider.go
  src/control/lib/hardware/libfabric/provider_test.go
  src/control/lib/hardware/sysfs/provider.go
  src/control/lib/hardware/sysfs/provider_test.go
  src/control/lib/hardware/ucx/ucx.go
  src/control/lib/hardware/ucx/ucx_test.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/ctl_network_rpc.go
  src/control/server/ctl_network_rpc_test.go
  src/control/server/server_utils_test.go
  src/tests/ftest/control/config_generate_output.py
  src/tests/ftest/control/config_generate_run.py
  src/tests/ftest/control/config_generate_run.yaml
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: release-2.4, priority, forced-landing

#10877 DAOS-12070 il: comply with fgetws() API
  src/client/dfuse/il/int_posix.c
  src/client/dfuse/il/intercept.h
Labels: release-2.4, priority

#11171 DAOS-9355 doc: mkdocs update
  mkdocs.yml
Labels: release-2.2

#11172 DAOS-9355 doc: mkdocs update
  mkdocs.yml
  src/vos/vos_aggregate.c
Labels: release-2.0

#11159 DAOS-12326 test: fix snapshot_aggregation space check
  src/tests/ftest/container/snapshot_aggregation.py
Labels: forced-landing

#11153 DAOS-12336 control: Relax validation condition on SCM names
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/ipmctl_test.go
Labels: release-2.4, priority, forced-landing

#11143 DAOS-12040 test: Error message has changed (#10807)
  src/tests/ftest/fault_injection/pool.py
Labels: clean-cherry-pick, priority

#11140 DAOS-10681 rebuild: check the global pool map version before rebuild
  src/include/daos_srv/pool.h
  src/pool/srv_pool.c
  src/rebuild/srv.c
Labels: release-2.4, priority

#10999 DAOS-7996 test: Enable two online reintegation test.
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/osa/online_reintegration.yaml
Labels: release-2.2, priority

#11110 DAOS-11678 cart: Handle extra error and early bulk release
  src/cart/crt_iv.c
  src/cart/crt_rpc.c
Labels: release-2.4, priority

#11151 DAOS-12266 cart: Fix swim_dump_updates segfaults (#11048)
  src/cart/crt_swim.c
Labels: clean-cherry-pick, release-2.2

#11132 DAOS-12324 pool: Reset pse_stop in fini_events
  src/pool/srv_pool.c
Labels: forced-landing

#11079 DAOS-11831 test: Add restart after bringing up network interface (#10…
  src/tests/ftest/deployment/network_failure.py
Labels: clean-cherry-pick, priority, forced-landing

#11127 DAOS-10856 test: verify dfuse multi-user chown
  src/tests/ftest/dfuse/mu_perms.py
  src/tests/ftest/dfuse/mu_perms.yaml
Labels: release-2.4, priority, forced-landing

#11173 DAOS-12344 control: nvme and scm cmds run without conf file
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_scm.go
Labels: bug, control-plane, release-2.4, forced-landing

#11148 DAOS-12160 test: reduce debug logs in container/boundary test
  src/tests/ftest/container/boundary.yaml
Labels: forced-landing

#10509 DAOS-11830 test: improve intercept test loggging
  src/tests/ftest/ior/intercept_basic.yaml
  src/tests/ftest/ior/intercept_messages.py
  src/tests/ftest/ior/intercept_messages.yaml
  src/tests/ftest/ior/intercept_multi_client.py
  src/tests/ftest/ior/intercept_multi_client.yaml
  src/tests/ftest/util/ior_intercept_test_base.py
Labels: forced-landing

#11076 DAOS-12247 object: Use correct grp size for enumeration
  src/object/cli_obj.c
  src/object/obj_tx.c
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/daos_extend_simple.c
Labels: release-2.4, priority

#11178 DAOS-12258 test: fix run_dm_activities_with_ior testfile (#11124)
  src/tests/ftest/util/data_mover_test_base.py
Labels: clean-cherry-pick, priority, forced-landing

#11144 DAOS-12332 object: remove wrong assertion in key_query path
  src/object/cli_shard.c
  src/tests/suite/daos_obj.c
Labels: release-2.4, priority, forced-landing

#11166 DAOS-12212 uns: add option to link an existing container in the UNS
  ci/unit/test_nlt_node.sh
  src/client/dfs/duns.c
  src/control/cmd/daos/container.go
  src/control/cmd/daos/pool.go
  src/include/daos_uns.h
  utils/node_local_test.py
Labels: forced-landing

#6307 DAOS-12053 cart: Detect exclusions of self rank
  src/cart/crt_group.c
  src/cart/crt_internal_fns.h
  src/cart/crt_swim.c
  src/control/system/member.go
  src/engine/init.c
  src/pool/srv_pool.c
Labels: forced-landing

#11162 DAOS-12322 test: increase test timeout
  src/tests/ftest/datamover/obj_large_posix.yaml
  src/tests/ftest/datamover/serial_large_posix.yaml
Labels: release-2.2, forced-landing

#10982 DAOS-12210 mercury: Update mercury version to 2.2.0-6 for source builds
  debian/changelog
  debian/control
  utils/build.config
  utils/rpms/daos.spec
Labels: release-2.4, priority

#11183 SRE-415 test: Store Launchable data per stage
  ci/functional/launchable_analysis
Labels: forced-landing

#11182 DAOS-8906 test: Verify and enable the fixes
  src/tests/ftest/scrubber/basic.py
Labels: release-2.4, priority

#11199 DAOS-12322 test: increase test timeout (#11162)
  src/tests/ftest/datamover/obj_large_posix.yaml
  src/tests/ftest/datamover/serial_large_posix.yaml
Labels: clean-cherry-pick, forced-landing

#11136 DAOS-12259 test: reduce dfuse caching perf threshold (#11116)
  src/tests/ftest/dfuse/caching_check.py
  src/tests/ftest/dfuse/caching_check.yaml
Labels: unclean-cherry-pick, priority, forced-landing

#11146 DAOS-10042 control: Don't append to daos_server's $PATH env
  src/control/pbin/exec.go
Labels: release-2.4, priority

#11074 DAOS-11952 rebuild: Do not need migration query/stop for reclaim (#10779)
  src/include/daos/common.h
  src/include/daos_srv/rebuild.h
  src/object/srv_obj_migrate.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/daos_rebuild_simple.c
Labels: release-2.4

#11196 DAOS-12332 object: remove wrong assertion in key_query path (#11144)
  src/object/cli_shard.c
  src/tests/suite/daos_obj.c
Labels: unclean-cherry-pick, release-2.4

#11200 DAOS-12239 control: Check for ErrNotLeader in ResignLeadership (#11163)
  src/control/system/database.go
  src/control/system/database_test.go
  src/control/system/raft.go
Labels: unclean-cherry-pick

#11201 DAOS-11925 test: Error running ../ftest/cart/cart_log test
  src/tests/ftest/launch.py
Labels: priority

#11069 DAOS-12121 test: Bullseye backports from master branch to rel_2.2
  Jenkinsfile
  ci/provisioning/post_provision_config_nodes.sh
  src/tests/ftest/cart/nopmix_launcher/launcher_one_node.py
  src/tests/ftest/launch.py
  src/tests/ftest/scripts/setup_nodes.sh
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/daos_perf_utils.py
  src/tests/ftest/util/daos_racer_utils.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/mdtest_utils.py
  src/tests/ftest/util/pool_security_test_base.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/server_utils_base.py
Labels: priority

#11215 DAOS-12019 cart: Document CRT_CTX_NUM changes
  docs/admin/env_variables.md
  src/cart/README.env
Labels: priority

#11211 DAOS-11550 build: Add SPDK patch to build with glibc 2.36 (#11185)
  utils/build.config
Labels: dependencies, unclean-cherry-pick, release-2.2, priority

#10740 SRE-640 Build: Support Cascade Lake CI VMs
  site_scons/components/__init__.py
  src/vos/tests/vts_common.h
  utils/run_test.sh
Labels: forced-landing

#11195 DAOS-12212 duns: add a clarification on the uns link option
  src/include/daos_uns.h
Labels: forced-landing

#11223 DAOS-12242 test: Fix server info for offline extend. (#11176)
  src/tests/ftest/osa/offline_extend.yaml
Labels: clean-cherry-pick, release-2.2

#11210 DAOS-12214 test: basic IO test for WAL
  src/bio/bio_wal.c
  src/vos/tests/vts_aggregate.c
  src/vos/tests/vts_io.h
  src/vos/tests/vts_wal.c
Labels: release-2.4, priority

#11226 DAOS-12393 bio: Don't log error in LED check if no VMD
  src/bio/bio_device.c
Labels: bug, release-2.4

#11216 DAOS-12019 cart: Change number of maximum contexts (#10765)
  src/cart/crt_init.c
  src/cart/crt_internal_types.h
Labels: unclean-cherry-pick, priority

#11184 DAOS-12324 pool: Reset pse_stop in fini_events (#11132)
  src/pool/srv_pool.c
Labels: clean-cherry-pick

#11218 DAOS-12019 cart: Document CRT_CTX_NUM changes (#11215)
  docs/admin/env_variables.md
  src/cart/README.env
Labels: clean-cherry-pick, priority

#11129 DAOS-10681 object: misc fixes for layout upgrade and rebuild
  src/include/daos/common.h
  src/include/daos_obj.h
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/srv_internal.h
  src/object/srv_obj_migrate.c
  src/rebuild/rebuild_internal.h
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: release-2.4, priority

#11157 DAOS-12209 control: Don't clean up Creating pools on MS step-up
  src/common/tests_dmg_helpers.c
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/lib/control/pool.go
  src/control/server/mgmt_drpc.go
  src/control/server/mgmt_drpc_test.go
  src/control/server/mgmt_pool.go
  src/control/server/server.go
  src/control/system/raft/database.go
  src/include/daos_mgmt.h
  src/mgmt/cli_mgmt.c
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/proto/mgmt/pool.proto
  src/tests/ftest/pool/list_verbose.py
Labels: release-2.4, priority

#11214 DAOS-12373 tools: change dir/file_oclass in daos cont tool to dir/fil…
  src/control/cmd/daos/container.go
  src/tests/ftest/container/auto_oc_selection.py
  src/tests/ftest/util/daos_utils_base.py
  utils/node_local_test.py
Labels: release-2.4, priority, forced-landing

#10546 DAOS-11892 object: add spec shard case in tgts_query
  src/object/cli_obj.c
  src/tests/ftest/ior/hard_rebuild.py
  src/tests/suite/daos_obj_ec.c
  src/vea/tests/vea_stress.c
Labels: unclean-cherry-pick, release-2.4, priority

#11219 DAOS-12383 common: Persist DAV heap statistics
  src/bio/bio_wal.c
  src/common/dav/dav_iface.c
  src/common/dav/stats.c
  src/common/dav/stats.h
  src/common/dav/tx.c
Labels: release-2.4, priority

#11240 DAOS-12402 control: daos_server config generate VMD NVMe scan fix
  docs/admin/deployment.md
  src/control/cmd/daos_server/auto.go
Labels: control-plane, release-2.4

#11236 DAOS-11401 vos: meta flush callbacks
  src/bio/bio_context.c
  src/bio/bio_wal.c
  src/include/daos/mem.h
  src/include/daos_srv/bio.h
  src/vos/vos_internal.h
  src/vos/vos_pool.c
Labels: release-2.4, priority

#11052 DAOS-11390 test: Add NLT/ftest support for control_metadata
  src/control/cmd/dmg/main.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/instance_storage.go
  src/control/server/instance_superblock.go
  src/control/server/storage/metadata/provider.go
  src/tests/ftest/launch.py
  utils/nlt_server.yaml
  utils/node_local_test.py
Labels: release-2.4, priority

#11256 DAOS-12039 test: Fix NVMe recovery tests
  src/bio/bio_monitor.c
  src/tests/suite/daos_nvme_recovery.c
Labels: release-2.4, priority

#11269 DAOS-12373 test: fix dir-oclass / dir_oclass
  src/tests/ftest/container/auto_oc_selection.py
Labels: release-2.4, priority, forced-landing

#11237 DAOS-11551 tools: Update daos cmd output for clone/copy (#11189)
  src/control/cmd/daos/container.go
  src/control/cmd/daos/filesystem.go
  src/control/cmd/daos/util.go
  src/utils/daos_hdlr.c
  src/utils/daos_hdlr.h
  utils/node_local_test.py
Labels: unclean-cherry-pick, priority

#11091 DAOS-11859 control: Add MD-on-SSD bdev tiering to config generate cmds
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/dmg/auto_test.go
  src/control/lib/control/auto.go
  src/control/lib/control/auto_test.go
  src/control/lib/control/mocks.go
  src/control/server/storage/config.go
  src/control/server/storage/config_test.go
Labels: release-2.4, priority, meta-on-ssd

#11238 DAOS-12290 control: Bdev class file should have 0600 perms
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_class.go
  src/control/server/storage/bdev/backend_class_test.go
Labels: release-2.4, priority, forced-landing

#11247 DAOS-623 tools: container hints short conflicts with help
  src/control/cmd/daos/container.go
Labels: forced-landing

#11212 DAOS-12053 cart: Detect exclusions of self rank (#6307)
  src/cart/crt_group.c
  src/cart/crt_internal_fns.h
  src/cart/crt_swim.c
  src/control/system/member.go
  src/engine/init.c
  src/pool/srv_pool.c
Labels: unclean-cherry-pick, priority

#11265 DAOS-623 ci: update GHA action-docker-layer-caching
  .github/workflows/ci2.yml
  .github/workflows/landing-builds.yml
Labels: forced-landing

#11273 DAOS-12012 cart: Segfault in OFI-RXM when using SPDK DAOS bdev module
  src/cart/crt_context.c
  src/cart/crt_hg.c
  src/cart/crt_hg.h
  src/cart/crt_init.c
  src/cart/crt_internal_types.h
  src/tests/ftest/cart/no_pmix_multi_ctx.c
Labels: unclean-cherry-pick

#11152 DAOS-12329 cart: Fix swim suspicion leaks
  src/cart/crt_swim.c
  src/cart/swim/swim.c
  src/include/cart/swim.h
  src/tests/ftest/cart/test_group_np_srv.c
  src/tests/ftest/util/server_utils_params.py
Labels: release-2.4, priority

#5192 DAOS-623 dfs: add a simple DFS program
  src/tests/SConscript
  src/tests/simple_dfs.c
Labels: forced-landing

#11203 DAOS-12227 cart: Fix Coverity CID-840053
  src/cart/crt_rpc.c
Labels: release-2.4, priority

#11165 DAOS-12309 test: Introduce param to toggle log mast for pool create/destroy
  src/tests/ftest/container/boundary.py
  src/tests/ftest/container/boundary.yaml
  src/tests/ftest/pool/create_capacity.py
  src/tests/ftest/pool/create_capacity.yaml
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/test_utils_pool.py
Labels: release-2.4, priority

#11271 DAOS-12100 control: Update admin cert key required perms
  src/control/security/config.go
  src/control/security/config_test.go
  src/control/security/pem.go
  src/control/security/pem_test.go
  src/control/security/signature_test.go
  src/control/security/testdata/certs/agent.key
  src/control/security/testdata/certs/bad.key
  src/control/security/testdata/certs/daosCA.key
  src/control/security/testdata/certs/notkey.crt
  src/control/security/testdata/certs/server.key
  src/control/security/testdata/certs/toomanypem.key
Labels: release-2.4, priority

#11288 DAOS-12290 control: Bdev class file should have 0600 perms (#11238)
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_class.go
  src/control/server/storage/bdev/backend_class_test.go
Labels: control-plane, clean-cherry-pick, release-2.2, release-2.4, priority

#11000 DAOS-11390 control: Add control metadata storage options
  src/control/cmd/daos_server_helper/handler.go
  src/control/cmd/daos_server_helper/handler_test.go
  src/control/cmd/daos_server_helper/main.go
  src/control/cmd/dmg/auto_test.go
  src/control/cmd/dmg/main.go
  src/control/fault/code/codes.go
  src/control/lib/control/mocks.go
  src/control/provider/system/mocks.go
  src/control/provider/system/system_linux.go
  src/control/provider/system/system_linux_test.go
  src/control/server/config/faults.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/ctl_storage.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/ctl_svc_test.go
  src/control/server/engine/config.go
  src/control/server/harness_test.go
  src/control/server/instance_storage.go
  src/control/server/instance_storage_test.go
  src/control/server/instance_superblock.go
  src/control/server/instance_superblock_test.go
  src/control/server/instance_test.go
  src/control/server/mgmt_pool_test.go
  src/control/server/mgmt_system_test.go
  src/control/server/server.go
  src/control/server/server_utils.go
  src/control/server/storage/config.go
  src/control/server/storage/config_test.go
  src/control/server/storage/metadata.go
  src/control/server/storage/metadata/faults.go
  src/control/server/storage/metadata/provider.go
  src/control/server/storage/metadata/provider_test.go
  src/control/server/storage/mocks.go
  src/control/server/storage/mount/provider.go
  src/control/server/storage/provider.go
  src/control/server/storage/provider_test.go
  src/control/server/storage/scm/provider.go
  src/control/server/util_test.go
  src/tests/ftest/launch.py
  utils/config/daos_server.yml
  utils/nlt_server.yaml
  utils/node_local_test.py
Labels: release-2.4, priority

#11284 DAOS-623 ci: update GHA action-docker-layer-caching (#11265)
  .github/workflows/ci2.yml
  .github/workflows/create_release.yml
  .github/workflows/doxygen.yml
  .github/workflows/flake.yml
  .github/workflows/landing-builds.yml
  .github/workflows/spelling.yml
Labels: unclean-cherry-pick

#11280 DAOS-12411 dfs: change file/dir create logic for O_CREAT without O_EX…
  src/client/dfs/dfs.c
Labels: clean-cherry-pick

#11193 DAOS-12354 test: Reduce ior write size to fit all CI clusters
  src/tests/ftest/erasurecode/online_rebuild.yaml
Labels: release-2.4, priority

#11021 DAOS-10690 test: Rectify TestPool.pool_percentage_used method
  src/tests/ftest/util/test_utils_pool.py
Labels: release-2.4, priority

#11283 DAOS-12210 cart: Update 2.2 release to use latest mercury.
  debian/changelog
  debian/control
  utils/build.config
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, release-2.4, priority

#11276 DAOS-12221 test: Update implementation of dmg stop, dmg start in test code.
  src/common/tests_dmg_helpers.c
  src/include/daos/tests_lib.h
  src/tests/suite/daos_test_common.c
Labels: clean-cherry-pick, release-2.2, priority

#11302 DAOS-11418 doc: replace deprecated rf parameter with rd_fac
  docs/user/container.md
  docs/user/filesystem.md
  src/client/dfs/README.md
Labels: release-2.4, priority

#11299 DAOS-12241 test: Moving io/large_file_count.py back to large cluster
  src/tests/ftest/io/large_file_count.py
  src/tests/ftest/io/large_file_count.yaml
Labels: release-2.4, priority

#11204 DAOS-11922 object: fail rebuild during shutdown (#11180)
  src/object/srv_obj_migrate.c
Labels: clean-cherry-pick, release-2.2, release-2.4

#11294 DAOS-12100 control: Update admin cert key required perms (#11271)
  src/control/security/config.go
  src/control/security/config_test.go
  src/control/security/pem.go
  src/control/security/pem_test.go
  src/control/security/signature_test.go
  src/control/security/testdata/certs/agent.key
  src/control/security/testdata/certs/bad.key
  src/control/security/testdata/certs/daosCA.key
  src/control/security/testdata/certs/notkey.crt
  src/control/security/testdata/certs/server.key
  src/control/security/testdata/certs/toomanypem.key
Labels: unclean-cherry-pick, release-2.4

#11298 DAOS-12366 control: Limit reference sharing when updating bdev stats
  src/control/server/ctl_storage.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/ctl_svc_test.go
  src/control/server/harness.go
  src/control/server/instance_drpc.go
  src/control/server/instance_test.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev_test.go
Labels: control-plane, release-2.4, priority

#11306 DAOS-623 build: Improve error message when lmdb is missing
  site_scons/components/__init__.py
  site_scons/prereq_tools/base.py
Labels: meta-on-ssd

#11300 DAOS-10681 rebuild: fix an invalid assertion
  src/rebuild/srv.c
Labels: release-2.4, priority

#11323 DAOS-12441 build: Create 2.4 TB3
  .github/workflows/create_release.yml
  TAG
  VERSION
  debian/changelog
  utils/rpms/daos.spec
Labels: release-2.4, priority

#11311 DAOS-12377 ds3: coverity fixes
  src/client/ds3/bucket.c
  src/client/ds3/pool.c
Labels: release-2.4, priority, forced-landing

#11277 DAOS-12417 security: Add ui.ACLPrincipalFlag type (#11258)
  src/control/cmd/daos/container.go
  src/control/cmd/dmg/cont.go
  src/control/cmd/dmg/cont_test.go
  src/control/cmd/dmg/pool.go
  src/control/drpc/acl.go
  src/control/lib/ui/acl.go
  src/control/lib/ui/acl_test.go
Labels: priority

#11313 DAOS-12241 test: Moving io/large_file_count.py back to large cluster (#11299)
  src/tests/ftest/io/large_file_count.py
  src/tests/ftest/io/large_file_count.yaml
Labels: clean-cherry-pick, release-2.4

#11329 DAOS-12502 test: Fix extra yaml unhandled exception
  src/tests/ftest/launch.py
Labels: forced-landing

#11314 DAOS-12319 test: invoke ior with clush not orterun
  src/tests/ftest/server/metadata.py
Labels: forced-landing
