Repository daos-stack/daos, pull requests merged in 2024-09, with the labels that each got.

#15043 DAOS-16465 vos: fix misused ip_hdl (#15034)
  src/include/daos_srv/vos_types.h
  src/vos/vos_iterator.c
  src/vos/vos_obj.c
Labels: clean-cherry-pick

#15005 DAOS-14544 rsvc: crt tree type usage fix (#14834)
  src/rsvc/srv.c
Labels: clean-cherry-pick

#14996 DAOS-14348 client: GC for pil4dfs dentry cache
  src/client/dfuse/pil4dfs/dfs_dcache.c
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: clean-cherry-pick

#15047 DAOS-16365 client: intercept MPI_Init() to avoid nested call (#14992)
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: clean-cherry-pick, priority, approved-to-merge

#15058 DAOS-16272 dfs: fix get_info returning incorrect oclass (#15048)
  src/client/dfs/obj.c
Labels: clean-cherry-pick

#15042 DAOS-16245 control: Fix dmg cont set-owner (#14945)
  src/container/rpc.c
  src/container/rpc.h
  src/container/srv_container.c
  src/container/srv_internal.h
  src/control/cmd/daos/acl.go
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/cont.go
  src/control/cmd/dmg/cont_test.go
  src/control/cmd/dmg/json_test.go
  src/control/common/proto/mgmt/addons.go
  src/control/common/proto/mgmt/cont.pb.go
  src/control/common/proto/mgmt/mgmt.pb.go
  src/control/common/proto/mgmt/mgmt_grpc.pb.go
  src/control/lib/control/cont.go
  src/control/lib/control/cont_test.go
  src/control/server/mgmt_cont.go
  src/control/server/mgmt_cont_test.go
  src/include/daos_srv/container.h
  src/mgmt/cont.pb-c.c
  src/mgmt/cont.pb-c.h
  src/mgmt/srv_container.c
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/tests/mocks.c
  src/mgmt/tests/mocks.h
  src/mgmt/tests/srv_drpc_tests.c
  src/proto/mgmt/cont.proto
  src/proto/mgmt/mgmt.proto
  src/tests/ftest/security/cont_get_acl.yaml
  src/tests/ftest/security/cont_owner.py
  src/tests/ftest/util/cont_security_test_base.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: clean-cherry-pick, priority, release-2.6.1

#15063 DAOS-16471 test: Reduce targets for ioctl_pool_handles.py
  src/tests/ftest/dfuse/ioctl_pool_handles.yaml
Labels: forced-landing

#15071 DAOS-16471 test: Reduce targets for ioctl_pool_handles.py (#15063)
  src/tests/ftest/dfuse/ioctl_pool_handles.yaml
Labels: clean-cherry-pick, forced-landing

#15055 DAOS-16483 vos: handle empty DTX when vos_tx_end - b26
  src/dtx/dtx_common.c
  src/tests/ftest/util/telemetry_utils.py
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_tls.h
Labels: clean-cherry-pick, forced-landing, release-2.6.1

#15050 DAOS-16484 test: Support mixed speeds when selecting a default interface
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/network_utils.py
Labels: forced-landing

#15077 DAOS-16271 mercury: Add patch to check ep for null in UCX key resolve.
  utils/build.config
Labels: release-2.6.1

#15004 DAOS-16446 test: HDF5-VOL test - Set object class and container prope…
  src/tests/ftest/util/file_count_test_base.py
Labels: forced-landing

#15012 DAOS-16447 test: set D_IL_REPORT per test
  src/tests/ftest/io/large_file_count.yaml
  src/tests/ftest/io/small_file_count.yaml
  src/tests/ftest/ior/small.yaml
  src/tests/ftest/util/file_count_test_base.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#15075 DAOS-16457 test: remove display_memory_info (#15031)
  src/tests/ftest/util/server_utils.py
Labels: clean-cherry-pick, priority

#15054 DAOS-16458 object: fix invalid DRAM access in obj_bulk_transfer - b26
  src/object/srv_coll.c
  src/object/srv_internal.h
  src/object/srv_obj.c
Labels: forced-landing, release-2.6.1

#15080 DAOS-16484 test: Support mixed speeds when selecting a default interf…
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/network_utils.py
Labels: clean-cherry-pick, priority

#15037 DAOS-16467 rebuild: add DAOS_POOL_RF ENV for massive failure case
  docs/admin/env_variables.md
  docs/admin/pool_operations.md
  src/chk/chk_engine.c
  src/common/pool_map.c
  src/container/cli.c
  src/container/srv_container.c
  src/dtx/dtx_coll.c
  src/include/daos/pool_map.h
  src/include/daos_prop.h
  src/object/cli_coll.c
  src/object/srv_coll.c
  src/pool/cli.c
  src/pool/rpc.h
  src/pool/srv.c
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/pool/srv_pool_map.c
  src/pool/srv_util.c
  src/rebuild/srv.c
  src/tests/ftest/util/server_utils_params.py
Labels: forced-landing

#14844 DAOS-14422 control: Update pool query UX for MD-on-SSD phase2
  src/common/dav_v2/dav_iface.c
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool.go
  src/control/server/mgmt_pool.go
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/proto/mgmt/pool.proto
  src/tests/ftest/control/dmg_pool_query_test.py
  src/tests/ftest/control/dmg_pool_query_test.yaml
  src/tests/ftest/pool/list_verbose.py
Labels: control-plane, forced-landing, meta-on-ssd, usability

#14926 SRE-2408 ci: Increase timeout (to 15 minutes) for system restore
  ci/gha_functions.sh
Labels: priority

#15103 DAOS-16515 build: Tag 2.6.1 rc1
  TAG
  VERSION
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#15116 DAOS-16560 test: Improve get_service_file()
  src/tests/ftest/util/systemctl_utils.py
Labels: forced-landing

#15104 DAOS-16540 test: include extra yaml for md on ssd
  src/tests/ftest/soak/soak-extra-mdonssd.yaml
Labels: forced-landing

#15123 DAOS-16560 test: Improve get_service_file() (#15116)
  src/tests/ftest/util/systemctl_utils.py
Labels: clean-cherry-pick

#15100 DAOS-16468 test: ior/small.py - Decrease crt_timeout to 10
  src/tests/ftest/ior/small.yaml
Labels: forced-landing

#15097 DAOS-16480 test: Increase expected range for dirty_pages metric
  src/tests/ftest/telemetry/wal_metrics.py
Labels: forced-landing

#15128 DAOS-16567 test: remove unused IorCommand.log_metrics
  src/tests/ftest/util/ior_utils.py
Labels: forced-landing

#15079 DAOS-15776 test: remove DataMoverTestBase.create_pool
  src/tests/ftest/datamover/copy_procs.py
  src/tests/ftest/datamover/dst_create.py
  src/tests/ftest/datamover/large_dir.py
  src/tests/ftest/datamover/large_file.py
  src/tests/ftest/datamover/negative.py
  src/tests/ftest/datamover/obj_large_posix.py
  src/tests/ftest/datamover/obj_small.py
  src/tests/ftest/datamover/posix_meta_entry.py
  src/tests/ftest/datamover/posix_preserve_props.py
  src/tests/ftest/datamover/posix_subsets.py
  src/tests/ftest/datamover/posix_symlinks.py
  src/tests/ftest/datamover/posix_types.py
  src/tests/ftest/datamover/serial_large_posix.py
  src/tests/ftest/datamover/serial_small.py
  src/tests/ftest/deployment/basic_checkout.py
  src/tests/ftest/util/data_mover_test_base.py
Labels: forced-landing

#13210 DAOS-12859 test: use pool and container labels (pass 3)
  src/tests/ftest/container/rf_enforcement.py
  src/tests/ftest/control/ms_resilience.py
  src/tests/ftest/io/macsio_test.py
  src/tests/ftest/io/parallel_io.py
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/pool/destroy.py
  src/tests/ftest/pool/query_attribute.py
  src/tests/ftest/rebuild/cascading_failures.py
  src/tests/ftest/rebuild/no_cap.py
  src/tests/ftest/rebuild/pool_destroy_race.py
  src/tests/ftest/rebuild/read_array.py
  src/tests/ftest/rebuild/with_io.py
  src/tests/ftest/scrubber/aggregation.py
  src/tests/ftest/scrubber/basic.py
  src/tests/ftest/scrubber/csum_fault.py
  src/tests/ftest/scrubber/frequency.py
  src/tests/ftest/scrubber/rebuild.py
  src/tests/ftest/scrubber/snapshot.py
  src/tests/ftest/scrubber/target_auto_eviction.py
  src/tests/ftest/server/metadata.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/osa_utils.py
  src/tests/ftest/util/rebuild_test_base.py
  src/tests/ftest/util/scrubber_test_base.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/util/vol_test_base.py
Labels: forced-landing

#14584 DAOS-16027 test: Adding daos_test REBUILD31-34 subtests
  src/tests/ftest/daos_test/rebuild.py
  src/tests/ftest/daos_test/rebuild.yaml
Labels: forced-landing

#15109 DAOS-16550 test: use correct stonewall file with mdtest
  src/tests/ftest/deployment/basic_checkout.yaml
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/performance/mdtest_hard.yaml
Labels: forced-landing

#15115 DAOS-16482 control: Increase min hugepages for single tgt count
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/storage/bdev_test.go
Labels: bug, control-plane, forced-landing

#15134 DAOS-16584 test: Support running independent io sys admin steps
  src/tests/ftest/deployment/io_sys_admin.py
  src/tests/ftest/deployment/io_sys_admin.yaml
Labels: forced-landing

#15127 DAOS-16566 test: Update server/multiengine_persocket.py
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/server/multiengine_persocket.yaml
Labels: forced-landing

#15074 DAOS-16487 control: Require hostname for nvme set-faulty & replace
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/json_test.go
  src/control/cmd/dmg/main.go
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/cmd/dmg/telemetry.go
  src/control/cmd/dmg/utils.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/lib/control/server_meta.go
  src/control/lib/control/server_meta_test.go
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/proto/ctl/smd.proto
  src/tests/ftest/control/dmg_storage_query.py
  src/tests/ftest/deployment/disk_failure.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/nvme_utils.py
  src/tests/ftest/vmd/fault_reintegration.py
  src/tests/ftest/vmd/led.py
Labels: control-plane, go, usability

#15094 DAOS-16495 test: Use the test env control config file w/ dmg
  src/tests/ftest/control/config_generate_run.py
  src/tests/ftest/harness/config.yaml
  src/tests/ftest/util/dmg_utils_base.py
Labels: forced-landing

#15073 DAOS-16336 test: bump io test timeout
  src/tests/ftest/daos_test/suite.yaml
Labels: forced-landing

#15106 DAOS-16548 test: add ftest lint check for invalid test_ tag
  src/tests/ftest/daos_test/suite.py
  src/tests/ftest/harness/skip_list.py
  src/tests/ftest/tags.py
Labels: forced-landing

#15139 DAOS-16466 misc: Backport fixes (#15045)
  src/dtx/dtx_rpc.c
  src/engine/server_iv.c
  src/mgmt/cli_mgmt.c
  src/object/cli_ec.c
  src/object/tests/srv_checksum_tests.c
  src/pool/srv_iv.c
  src/utils/ddb/tests/ddb_vos_tests.c
  src/vos/tests/evt_ctl.c
  src/vos/tests/vts_pm.c
Labels: clean-cherry-pick

#15149 DAOS-16495 test: Use the test env control config file w/ dmg (#15094)
  src/tests/ftest/control/config_generate_run.py
  src/tests/ftest/harness/config.yaml
  src/tests/ftest/util/dmg_utils_base.py
Labels: clean-cherry-pick, forced-landing

#14954 DAOS-16346 tests: fix pmemcheck vea errors
  src/vea/tests/vea_ut.c
Labels: forced-landing

#15152 DAOS-16589 test: Add Hardware Medium VMD test stage.
  Jenkinsfile
  src/tests/ftest/tags.py
  src/tests/ftest/vmd/fault_reintegration.py
  src/tests/ftest/vmd/led.py
Labels: forced-landing

#15159 DAOS-16169 test: Skip recovery tests requiring fault injection
  src/tests/suite/daos_cr.c
Labels: forced-landing

#15169 DAOS-16169 test: Skip recovery tests requiring fault injection (#15159)
  src/tests/suite/daos_cr.c
Labels: clean-cherry-pick, forced-landing

#15168 DAOS-16611 java: Bump com.google.protobuf:protobuf-java (#15160)
  src/client/java/daos-java/pom.xml
Labels: clean-cherry-pick, release-2.6.1

#15170 DAOS-16614 build: Tag 2.6.1 rc2
  TAG
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#15165 DAOS-16613 cq: update pylint to 3.3.0
  utils/cq/pylintrc
  utils/cq/requirements.txt
Labels: forced-landing

#15166 DAOS-16589 test: Support Functional Hardware Medium VMD stage
  Jenkinsfile
  src/tests/ftest/harness/basic.py
Labels: forced-landing

#15113 DAOS-16298 test: improve get_clush_command timeout
  src/tests/ftest/recovery/ddb.py
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/util/run_utils.py
Labels: forced-landing
