Repository daos-stack/daos, pull requests merged in 2024-12, with the labels that each got.

#15526 DAOS-16822 client: Add mkdir_p variant to dfs_sys API
  src/client/dfs/common.c
  src/client/dfs/dfs_sys.c
  src/include/daos_fs_sys.h
  src/tests/suite/dfs_sys_unit_test.c
Labels: forced-landing

#15506 DAOS-7485 control: Implement dmg system drain to act on all hosts
  docs/admin/pool_operations.md
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/json_test.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/control/cmd/dmg/pretty/system.go
  src/control/cmd/dmg/pretty/system_test.go
  src/control/cmd/dmg/system.go
  src/control/cmd/dmg/system_test.go
  src/control/common/proto/mgmt/mgmt.pb.go
  src/control/common/proto/mgmt/mgmt_grpc.pb.go
  src/control/common/proto/mgmt/system.pb.go
  src/control/lib/control/pool.go
  src/control/lib/control/response_test.go
  src/control/lib/control/system.go
  src/control/lib/control/system_test.go
  src/control/security/grpc_authorization.go
  src/control/security/grpc_authorization_test.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/mgmt/srv_drpc.c
  src/proto/mgmt/mgmt.proto
  src/proto/mgmt/system.proto
Labels: control-plane, forced-landing, usability

#15531 DAOS-16826 build: Fix compiling issues in gcc 14
  site_scons/site_tools/compiler_setup.py
  src/client/dfuse/dfuse_core.c
  src/gurt/telemetry.c
  src/placement/tests/benchmark_util.h
  src/placement/tests/jump_map_place_obj.c
  src/utils/crt_launch/crt_launch.c
Labels: forced-landing

#15547 DAOS-16843 cq: setup dependabot for requirements.txt
  .github/dependabot.yml
Labels: forced-landing

#15546 DAOS-15645 test: change default cont control_method to daos
  src/tests/ftest/checksum/csum_basic.yaml
  src/tests/ftest/container/api_basic_attribute.yaml
  src/tests/ftest/container/basic_snapshot.yaml
  src/tests/ftest/container/boundary.yaml
  src/tests/ftest/container/query_attribute.yaml
  src/tests/ftest/container/snapshot.yaml
  src/tests/ftest/control/dmg_system_cleanup.yaml
  src/tests/ftest/dtx/basic.yaml
  src/tests/ftest/erasurecode/rank_failure.yaml
  src/tests/ftest/nvme/object.yaml
  src/tests/ftest/object/create_many_dkeys.yaml
  src/tests/ftest/object/fetch_bad_param.yaml
  src/tests/ftest/object/integrity.yaml
  src/tests/ftest/object/open_bad_param.yaml
  src/tests/ftest/object/punch_test.yaml
  src/tests/ftest/object/update_bad_param.yaml
  src/tests/ftest/osa/dmg_negative_test.yaml
  src/tests/ftest/pool/evict.yaml
  src/tests/ftest/rebuild/basic.yaml
  src/tests/ftest/rebuild/cascading_failures.yaml
  src/tests/ftest/rebuild/delete_objects.yaml
  src/tests/ftest/rebuild/read_array.yaml
  src/tests/ftest/telemetry/dkey_akey_enum_punch.yaml
  src/tests/ftest/util/test_utils_base.py
Labels: forced-landing

#15575 DAOS-16865 cq: update flake8 to 7.1.1
  utils/cq/requirements.txt
  utils/githooks/pre-commit.d/71-flake.sh
Labels: forced-landing

#15582 DAOS-16870 test: Fix pool/permission test
  src/tests/ftest/pool/permission.yaml
Labels: forced-landing

#15583 DAOS-16871 cq: add GHA workflows to dependabot
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: forced-landing

#15394 SRE-2525 ci: Fix Trivy scan upload to the Security tab
  .github/workflows/trivy.yml
  README.md
  utils/trivy/trivy.yaml
Labels: clean-cherry-pick, forced-landing, doc-only, release-2.6.3

#15403 DAOS-16350 test: decrease pool size for ior_per_rank (#15183)
  src/tests/ftest/deployment/ior_per_rank.yaml
Labels: clean-cherry-pick, forced-landing, release-2.6.3

#14775 DAOS-16167 test: update soak test to use internal job scheduler
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#15411 DAOS-16096 test: Add retry loop for comparing free pool space (#15289)
  src/tests/ftest/dfuse/root_container.py
Labels: clean-cherry-pick, forced-landing, release-2.6.3

#15540 DAOS-16825 test: Support register cleanup for all Test classes (#15530)
  src/tests/ftest/control/config_generate_run.py
  src/tests/ftest/control/daos_agent_config.py
  src/tests/ftest/network/cart_self_test.py
  src/tests/ftest/util/apricot/apricot/test.py
Labels: clean-cherry-pick, release-2.6.2, release-2.6.3

#15410 DAOS-16709 test: Handle decoding empty json output (#15397)
  src/tests/ftest/util/command_utils.py
Labels: clean-cherry-pick, release-2.6.3

#15253 DAOS-12859 test: use pool and container labels (pass 3) (#13210)
  src/tests/ftest/container/rf_enforcement.py
  src/tests/ftest/control/ms_resilience.py
  src/tests/ftest/io/macsio_test.py
  src/tests/ftest/io/parallel_io.py
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/pool/destroy.py
  src/tests/ftest/pool/query_attribute.py
  src/tests/ftest/rebuild/cascading_failures.py
  src/tests/ftest/rebuild/no_cap.py
  src/tests/ftest/rebuild/pool_destroy_race.py
  src/tests/ftest/rebuild/read_array.py
  src/tests/ftest/rebuild/with_io.py
  src/tests/ftest/scrubber/aggregation.py
  src/tests/ftest/scrubber/basic.py
  src/tests/ftest/scrubber/csum_fault.py
  src/tests/ftest/scrubber/frequency.py
  src/tests/ftest/scrubber/rebuild.py
  src/tests/ftest/scrubber/snapshot.py
  src/tests/ftest/scrubber/target_auto_eviction.py
  src/tests/ftest/server/metadata.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/osa_utils.py
  src/tests/ftest/util/rebuild_test_base.py
  src/tests/ftest/util/scrubber_test_base.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/util/vol_test_base.py
Labels: clean-cherry-pick, priority, forced-landing, release-2.6.3

#15457 DAOS-16670 test: container/multiple_delete.py - Increase SCM leftover…
  src/tests/ftest/container/multiple_delete.py
  src/tests/ftest/container/multiple_delete.yaml
Labels: clean-cherry-pick

#15406 DAOS-16702 rebuild: restart rebuild for a massive failure case
  src/container/container_iv.c
  src/include/daos_srv/rebuild.h
  src/object/cli_obj.c
  src/pool/srv_pool.c
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: clean-cherry-pick

#15595 DAOS-16167 test: update soak test to use internal job scheduler (#14775)
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: clean-cherry-pick, forced-landing, release-2.6.3

#15597 DAOS-16865 cq: update flake8 to 7.1.1 (#15575)
  utils/cq/requirements.txt
  utils/githooks/pre-commit.d/71-flake.sh
Labels: clean-cherry-pick, priority, forced-landing, release-2.6.3

#15496 DAOS-16276 doc: Address engine unavailability (#15456)
  docs/admin/pool_operations.md
  docs/admin/troubleshooting.md
Labels: clean-cherry-pick, doc-only, release-2.6.3

#14547 DAOS-16111 rebuild: uniform identifier in logs part 2 (migrate)
  src/include/daos_srv/rebuild.h
  src/object/srv_obj_migrate.c
  src/rebuild/rebuild_internal.h
  src/rebuild/scan.c
  src/rebuild/srv.c
Labels: forced-landing

#15596 DAOS-15677 cq: fix copyright GHA for landing run
  .github/workflows/linting.yml
  utils/cq/check_update_copyright.sh
Labels: forced-landing

#15584 DAOS-16477 pool: Rename Suspect state to Dead
  docs/admin/pool_operations.md
  src/control/cmd/daos/health.go
  src/control/cmd/daos/pool.go
  src/control/cmd/daos/pretty/health.go
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool.go
  src/control/lib/daos/pool_test.go
  src/include/daos_pool.h
  src/include/daos_srv/pool.h
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_pool.c
  src/mgmt/tests/mocks.c
  src/mgmt/tests/mocks.h
  src/mgmt/tests/srv_drpc_tests.c
  src/pool/srv_cli.c
  src/proto/mgmt/pool.proto
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/ftest/util/test_utils_pool.py
Labels: priority

#15352 DAOS-16572 object: refine sc_ec_agg_active flag setting
  src/container/srv_target.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/rebuild/scan.c
Labels: clean-cherry-pick, priority, forced-landing

#15509 DAOS-16802 tests: properly set fault_injection for CR test
  src/tests/suite/daos_cr.c
Labels: forced-landing

#15600 DAOS-16812 cart: read after free cid 2556737 (#15517)
  src/cart/crt_hg.c
Labels: clean-cherry-pick, priority, forced-landing

#15608 DAOS-16875 cq: fix flake8 xargs usage
  utils/githooks/pre-commit.d/71-flake.sh
Labels: forced-landing

#15614 DAOS-16875 cq: fix flake8 xargs usage (#15608)
  utils/githooks/pre-commit.d/71-flake.sh
Labels: clean-cherry-pick, forced-landing, release-2.6.3

#15255 DAOS-16621 build: Fix Go versions in rpm/deb packaging (#15174)
  debian/changelog
  debian/control
  site_scons/site_tools/go_builder.py
  src/control/go.mod
  utils/docker/Dockerfile.ubuntu
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, priority, forced-landing, release-2.6.3

#15601 DAOS-16873 cq: remove workflows/version-checks.yml
  .github/workflows/version-checks.yml
Labels: forced-landing

#15477 DAOS-16170 cart: do not release completed RPC reference repeatedly - b26
  src/cart/crt_rpc.c
  src/chk/chk_rpc.c
  src/tests/suite/daos_cr.c
Labels: forced-landing, release-2.6.3

#15615 DAOS-16880 client: Address java security scan (#15542)
  src/client/java/daos-java/pom.xml
Labels: clean-cherry-pick, release-2.6.3

#15489 DAOS-16127 tools: Include relevant pool health in container health
  src/control/cmd/daos/pretty/health.go
  src/control/cmd/daos/pretty/health_test.go
Labels: priority

#15610 DAOS-16874 tests: Update expected pool_layout_ver
  src/tests/ftest/control/dmg_pool_query_test.py
Labels: forced-landing

#15563 DAOS-16833 cq: update GHA ubuntu (#15538)
  .github/workflows/ci2.yml
  .github/workflows/landing-builds.yml
  .github/workflows/linting.yml
  .github/workflows/pr-metadata.yml
  .github/workflows/version-checks.yml
  ci/storage/test_main_storage_prepare_node.sh
  ci/unit/test_post_always.sh
  src/tests/ftest/scripts/main.sh
  utils/scripts/helpers/install_maldet.sh
Labels: unclean-cherry-pick, priority, forced-landing

#15511 DAOS-16209 pool: return mem file size on pool query
  src/control/common/proto/logging.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/control/server/util_test.go
  src/include/daos_srv/pool.h
  src/include/daos_srv/vos_types.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_pool.c
  src/mgmt/tests/mocks.c
  src/mgmt/tests/mocks.h
  src/mgmt/tests/srv_drpc_tests.c
  src/pool/cli.c
  src/pool/rpc.c
  src/pool/rpc.h
  src/pool/srv.c
  src/pool/srv_cli.c
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/vos/vos_layout.h
  src/vos/vos_pool.c
  src/vos/vos_space.c
Labels: control-plane, forced-landing

#15598 DAOS-16662 test: update some tests to use unique dfuse mount (#15242)
  src/tests/ftest/deployment/basic_checkout.py
  src/tests/ftest/deployment/basic_checkout.yaml
  src/tests/ftest/dfuse/mu_perms.yaml
  src/tests/ftest/dfuse/simul.yaml
  src/tests/ftest/ior/small.py
  src/tests/ftest/ior/small.yaml
  src/tests/ftest/util/ior_test_base.py
Labels: unclean-cherry-pick, priority, forced-landing, release-2.6.3

#15627 DAOS-16873 cq: remove workflows/version-checks.yml (#15601)
  .github/workflows/version-checks.yml
Labels: clean-cherry-pick, priority, forced-landing, release-2.6.3

#15637 DAOS-16787 utils: Suppress NLT valgrind false positives (#15478)
  src/cart/utils/memcheck-cart.supp
Labels: clean-cherry-pick, priority, forced-landing

#15623 DAOS-13292 build: Don't need UCX libraries … (#15016)
  debian/changelog
  debian/control
  site_scons/prereq_tools/base.py
  utils/rpms/daos.spec
Labels: priority, forced-landing

#15636 DAOS-15677 cq: make copyright GHA required
  .github/workflows/linting.yml
Labels: forced-landing

#15630 DAOS-16887 dfuse: use the inode instead of open handle in pre-read
  src/client/dfuse/dfuse.h
  src/client/dfuse/ops/open.c
  src/client/dfuse/ops/read.c
Labels: forced-landing

#15366 DAOS-16645 cart: Bump file descriptor limit (#15224)
  ci/unit/test_nlt_node.sh
  src/cart/crt_init.c
  utils/ansible/ftest/templates/daos-launch_nlt.sh.j2
  utils/node_local_test.py
Labels: clean-cherry-pick, priority, forced-landing, approved-to-merge

#15641 DAOS-16889 build: fix finding protobuf (#15625)
  src/control/SConscript
Labels: clean-cherry-pick, priority, release-2.6.3

#15639 DAOS-15677 cq: remove required-githooks watermark
  Jenkinsfile
  utils/githooks/commit-msg
  utils/githooks/commit-msg.d/10-watermark.py
  utils/githooks/hook_base.sh
Labels: forced-landing

#15642 DAOS-16263 cq: merge yamllint and clang-format into linting (#14803)
  .github/workflows/clang-format.yml
  .github/workflows/linting.yml
  .github/workflows/yaml.yml
Labels: unclean-cherry-pick, priority, forced-landing, release-2.6.3

#15510 DAOS-16802 tests: properly set fault_injection for CR test - b26
  src/tests/suite/daos_cr.c
Labels: clean-cherry-pick, priority, release-2.6.3

#15335 DAOS-16469 dtx: properly handle DTX partial commit
  src/dtx/dtx_coll.c
  src/dtx/dtx_common.c
  src/dtx/dtx_cos.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/utils/ddb/ddb_vos.c
  src/utils/ddb/tests/ddb_test_driver.c
  src/vos/tests/vts_dtx.c
  src/vos/tests/vts_io.c
  src/vos/tests/vts_mvcc.c
  src/vos/tests/vts_pm.c
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_obj.c
Labels: priority
