Repository daos-stack/daos, pull requests merged in 2024-10, with the labels that each got.

#15187 DAOS-16628 client: reset eq counter to zero after fork() in IL
  src/client/dfuse/il/int_posix.c
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: forced-landing

#15205 DAOS-16634 cart: Test DAOS with Mercury UCX updates.
  utils/build.config
Labels: forced-landing

#15214 DAOS-16634 mercury: Update source build in release 2.6 with ucx patch.
  utils/build.config
Labels: forced-landing

#15182 DAOS-16626 cq: update pylint to 3.3.1
  utils/cq/requirements.txt
Labels: forced-landing

#15138 DAOS-16577 test: remove hw tag from some manual tests
  src/tests/ftest/deployment/disk_failure.py
Labels: forced-landing

#15235 DAOS-9355 doc: DAOS 2.6.1 release notes
  docs/release/release_notes.md
Labels: forced-landing

#15117 DAOS-16445 client: Add function to cycle OIDs non-sequentially (#14999)
  src/client/dfs/dfs_internal.h
  src/client/dfs/mnt.c
  src/include/daos_obj.h
Labels: unclean-cherry-pick, approved-to-merge, release-2.6.2

#15198 DAOS-16566 test: Update server/multiengine_persocket.py (#15127)
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/server/multiengine_persocket.yaml
Labels: clean-cherry-pick, forced-landing

#15136 DAOS-16480 test: Increase expected range for dirty_pages metric (#15097)
  src/tests/ftest/telemetry/wal_metrics.py
Labels: clean-cherry-pick, forced-landing

#15144 DAOS-16590 test: misc ftest/performance updates
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/mdtest_easy.py
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/performance/mdtest_hard.py
  src/tests/ftest/performance/mdtest_hard.yaml
Labels: forced-landing

#15247 DAOS-16577 test: remove hw tag from deployment/disk_failure.py (#15138)
  src/tests/ftest/deployment/disk_failure.py
Labels: clean-cherry-pick, priority, forced-landing

#15254 DAOS-15776 test: remove DataMoverTestBase.create_pool (#15079)
  src/tests/ftest/datamover/copy_procs.py
  src/tests/ftest/datamover/dst_create.py
  src/tests/ftest/datamover/large_dir.py
  src/tests/ftest/datamover/large_file.py
  src/tests/ftest/datamover/negative.py
  src/tests/ftest/datamover/obj_large_posix.py
  src/tests/ftest/datamover/obj_small.py
  src/tests/ftest/datamover/posix_meta_entry.py
  src/tests/ftest/datamover/posix_preserve_props.py
  src/tests/ftest/datamover/posix_subsets.py
  src/tests/ftest/datamover/posix_symlinks.py
  src/tests/ftest/datamover/posix_types.py
  src/tests/ftest/datamover/serial_large_posix.py
  src/tests/ftest/datamover/serial_small.py
  src/tests/ftest/deployment/basic_checkout.py
  src/tests/ftest/util/data_mover_test_base.py
Labels: clean-cherry-pick, priority, forced-landing

#15252 DAOS-16298 test: improve get_clush_command timeout (#15113)
  src/tests/ftest/recovery/ddb.py
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/util/run_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#15249 DAOS-16550 test: use correct stonewall file with mdtest (#15109)
  src/tests/ftest/deployment/basic_checkout.yaml
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/performance/mdtest_hard.yaml
Labels: clean-cherry-pick, priority, forced-landing

#15246 DAOS-16567 test: remove unused IorCommand.log_metrics (#15128)
  src/tests/ftest/util/ior_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#15248 DAOS-16584 test: Support running independent io sys admin steps (#15134)
  src/tests/ftest/deployment/io_sys_admin.py
  src/tests/ftest/deployment/io_sys_admin.yaml
Labels: clean-cherry-pick, priority, forced-landing

#15183 DAOS-16350 test: decrease pool size for ior_per_rank
  src/tests/ftest/deployment/ior_per_rank.yaml
Labels: forced-landing

#15124 DAOS-16540 test: include extra yaml for soak md on ssd (#15104)
  src/tests/ftest/soak/soak-extra-mdonssd.yaml
Labels: forced-landing

#15257 DAOS-16628 client: reset eq counter to zero after fork() in IL (#15187)
  src/client/dfuse/il/int_posix.c
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: priority

#15259 DAOS-16482 control: Increase min hugepages for single tgt count (#15115)
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/storage/bdev_test.go
Labels: bug, control-plane, clean-cherry-pick, priority, forced-landing

#15262 DAOS-15778 test: remove DataMoverTestBase.posix_local_test_paths (#14…
  src/tests/ftest/datamover/negative.py
  src/tests/ftest/util/data_mover_test_base.py
Labels: clean-cherry-pick, priority, forced-landing

#15260 DAOS-16487 control: Require hostname for nvme set-faulty & replace (#…
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/json_test.go
  src/control/cmd/dmg/main.go
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/cmd/dmg/telemetry.go
  src/control/cmd/dmg/utils.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/lib/control/server_meta.go
  src/control/lib/control/server_meta_test.go
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/proto/ctl/smd.proto
  src/tests/ftest/control/dmg_storage_query.py
  src/tests/ftest/deployment/disk_failure.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/nvme_utils.py
  src/tests/ftest/vmd/fault_reintegration.py
  src/tests/ftest/vmd/led.py
Labels: control-plane, clean-cherry-pick, priority, forced-landing

#15256 DAOS-16027 test: Adding daos_test REBUILD31-34 subtests (#14584)
  src/tests/ftest/daos_test/rebuild.py
  src/tests/ftest/daos_test/rebuild.yaml
Labels: clean-cherry-pick, priority, forced-landing

#15261 DAOS-16487 test: fix dmg c helper for set-faulty changes (#15151)
  docs/admin/administration.md
  src/bio/README.md
  src/common/tests_dmg_helpers.c
Labels: clean-cherry-pick, priority, forced-landing

#15251 DAOS-16447 test: set D_IL_REPORT per test (#15012)
  src/tests/ftest/io/large_file_count.yaml
  src/tests/ftest/io/small_file_count.yaml
  src/tests/ftest/ior/small.yaml
  src/tests/ftest/util/file_count_test_base.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#14371 DAOS-14408 common: enable NDCTL for DCPM
  .github/workflows/landing-builds.yml
  debian/changelog
  debian/control
  site_scons/components/__init__.py
  src/control/server/engine/config.go
  src/control/server/engine/config_test.go
  src/control/server/server.go
  src/mgmt/srv_target.c
  utils/build.config
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
  utils/run_utest.py
  utils/scripts/install-el8.sh
  utils/scripts/install-el9.sh
  utils/scripts/install-leap15.sh
  utils/scripts/install-ubuntu.sh
Labels: go, release-2.6.2

#15285 DAOS-16548 test: add ftest lint check for invalid test_ tag (#15106)
  src/tests/ftest/daos_test/suite.py
  src/tests/ftest/harness/skip_list.py
  src/tests/ftest/tags.py
Labels: clean-cherry-pick, forced-landing

#15126 DAOS-16076 test: Automate dmg scale test to be run on Aurora (#14616)
  src/tests/ftest/control/dmg_scale.py
  src/tests/ftest/control/dmg_scale.yaml
Labels: clean-cherry-pick, priority, forced-landing

#15266 DAOS-16590 test: misc ftest/performance updates (#15144)
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/mdtest_easy.py
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/performance/mdtest_hard.py
  src/tests/ftest/performance/mdtest_hard.yaml
Labels: unclean-cherry-pick, priority, forced-landing

#15281 DAOS-16672 control: Move storage_query pretty printers into own file
  src/control/cmd/dmg/pretty/storage.go
  src/control/cmd/dmg/pretty/storage_query.go
  src/control/cmd/dmg/pretty/storage_query_test.go
  src/control/cmd/dmg/pretty/storage_test.go
Labels: control-plane, forced-landing

#15284 DAOS-16673 common: ignore Hadoop 3.4.0 related CVE
  .github/workflows/trivy.yml
  utils/trivy/.trivyignore
  utils/trivy/trivy.yaml
Labels: release-2.6.2, java

#15295 DAOS-16589 test: Support Functional Hardware Medium VMD stage (#15166)
  Jenkinsfile
  src/tests/ftest/harness/basic.py
  src/tests/ftest/tags.py
  src/tests/ftest/vmd/fault_reintegration.py
  src/tests/ftest/vmd/led.py
Labels: clean-cherry-pick, forced-landing

#15272 DAOS-16667 client: bump hadoop-common from 3.3.6 to 3.4.0 (#15194)
  src/client/java/hadoop-daos/pom.xml
Labels: dependencies, clean-cherry-pick, priority, forced-landing

#15304 DAOS-16556 client: call fstat() before mmap() to update file status in kernel
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: clean-cherry-pick, priority

#15098 DAOS-16446 test: HDF5-VOL test - Set object class and container prope…
  src/tests/ftest/util/file_count_test_base.py
Labels: clean-cherry-pick, priority

#15320 DAOS-16673 common: ignore Hadoop 3.4.0 related CVE
  .github/workflows/trivy.yml
  utils/trivy/.trivyignore
  utils/trivy/csv.tpl
  utils/trivy/trivy.yaml
Labels: clean-cherry-pick, priority, forced-landing, release-2.6.2

#15203 DAOS-14408 common: ensure NDCTL not used for storage class `ram`
  .github/workflows/landing-builds.yml
  debian/changelog
  debian/control
  site_scons/components/__init__.py
  src/control/server/engine/config.go
  src/control/server/engine/config_test.go
  src/control/server/server.go
  src/mgmt/srv_target.c
  utils/build.config
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
  utils/run_utest.py
  utils/scripts/install-el8.sh
  utils/scripts/install-el9.sh
  utils/scripts/install-leap15.sh
  utils/scripts/install-ubuntu.sh
Labels: clean-cherry-pick, priority, go, release-2.6.2

#15288 DAOS-16650 control: dmg system exclude, update group version
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
Labels: forced-landing

#15325 DAOS-16621 build: Fix Go versions in rpm/deb packaging (#15174)
  debian/control
  site_scons/site_tools/go_builder.py
  src/control/go.mod
  utils/docker/Dockerfile.ubuntu
  utils/rpms/daos.spec
Labels: priority

#14957 DAOS-16160 control: Update pool create --size % opt for MD-on-SSD p2
  docs/admin/pool_operations.md
  src/bio/bio_context.c
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/control/cmd/dmg/pretty/storage_nvme.go
  src/control/cmd/dmg/utils.go
  src/control/common/proto/ctl/storage_nvme.pb.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/control/storage.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/mgmt_pool.go
  src/control/server/storage/bdev.go
  src/control/server/storage/config.go
  src/proto/ctl/storage_nvme.proto
  src/tests/ftest/control/dmg_pool_query_test.yaml
Labels: control-plane, meta-on-ssd, go, usability

#15020 DAOS-16265 test: Fix erasurecode/rebuild_fio.py out of space
  src/tests/ftest/erasurecode/multiple_failure.yaml
  src/tests/ftest/erasurecode/rebuild_fio.yaml
  src/tests/ftest/util/apricot/apricot/test.py
Labels: forced-landing

#15310 DAOS-16694 dtx: avoid DTX leak during dtx_status_handle
  src/dtx/dtx_resync.c
Labels: forced-landing

#15338 DAOS-16720 cq: pin isort to v1.1.0
  .github/workflows/linting.yml
Labels: forced-landing

#15302 DAOS-16653 pool: Batch crt events (#15230)
  docs/admin/env_variables.md
  src/pool/srv_pool.c
  src/tests/ftest/util/server_utils_params.py
Labels: clean-cherry-pick, priority, approved-to-merge, release-2.6.2

#15339 DAOS-16720 cq: pin isort to v1.1.0 (#15338)
  .github/workflows/linting.yml
Labels: clean-cherry-pick, forced-landing

#15324 DAOS-15852 test: more timing samples for co_op_dup_timing() (#14497)
  src/tests/suite/daos_container.c
Labels: clean-cherry-pick, forced-landing

#15186 DAOS-16572 rebuild: properly assign global_dtx_resync_version in IV - b26
  src/rebuild/rebuild_iv.c
Labels: clean-cherry-pick, release-2.6.2

#15313 DAOS-16696 cart: Fix rc in error path
  src/cart/crt_iv.c
Labels: forced-landing

#15333 DAOS-16160 control: Fix count calcs for MD-on-SSD dev tgt IDs
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/storage/bdev.go
Labels: bug, control-plane, meta-on-ssd

#14985 DAOS-16329 chk: maintenance mode after checking pool with dryrun - b26
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/client/dfs/cont.c
  src/container/srv_container.c
  src/container/srv_target.c
  src/include/daos/container.h
  src/include/daos_cont.h
  src/include/daos_srv/pool.h
  src/include/daos_srv/security.h
  src/mgmt/srv_target.c
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/rebuild/srv.c
  src/security/srv_acl.c
  src/tests/suite/daos_cr.c
Labels: clean-cherry-pick, release-2.6.2

#15340 DAOS-16265 test: Fix erasurecode/rebuild_fio.py out of space (#15020)
  src/tests/ftest/erasurecode/multiple_failure.yaml
  src/tests/ftest/erasurecode/rebuild_fio.yaml
  src/tests/ftest/util/apricot/apricot/test.py
Labels: clean-cherry-pick, forced-landing

#15322 DAOS-16693 telemetry: Avoid race between init/read (#15306)
  src/control/lib/telemetry/counter.go
  src/control/lib/telemetry/duration.go
  src/control/lib/telemetry/gauge.go
  src/control/lib/telemetry/snapshot.go
  src/control/lib/telemetry/telemetry.go
  src/control/lib/telemetry/timestamp.go
  src/gurt/telemetry.c
  src/include/gurt/telemetry_common.h
Labels: bug, clean-cherry-pick, priority, forced-landing, approved-to-merge

#15334 DAOS-16698 control: Bump system_ram_reserved for MD-on-SSD pool create
  src/control/cmd/dmg/auto_test.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm_test.go
  utils/config/daos_server.yml
Labels: bug, control-plane, forced-landing, meta-on-ssd

#15357 DAOS-16696 cart: Fix rc in error path (#15313)
  src/cart/crt_iv.c
Labels: priority

#15221 DAOS-16574 vos: shrink DTX table blob size - b26 (#15220)
  src/vos/vos_dtx.c
Labels: clean-cherry-pick, release-2.6.2

#15355 DAOS-16265 test: Split erasurecode/multiple_failure.py
  src/tests/ftest/erasurecode/multiple_rank_failure.py
  src/tests/ftest/erasurecode/multiple_rank_failure.yaml
  src/tests/ftest/erasurecode/multiple_target_failure.py
  src/tests/ftest/erasurecode/multiple_target_failure.yaml
Labels: priority, forced-landing

#15349 DAOS-16650 control: dmg system exclude, update group version (#15288)
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
Labels: priority, forced-landing

#15269 DAOS-16488 chk: take sd_lock before accessing VOS sys_db - b26
  src/chk/chk_vos.c
  src/common/lru.c
  src/vos/sys_db.c
Labels: priority, release-2.6.2

#14917 DAOS-14262 cart: add ability to select traffic class for SWIM context (#14893)
  src/cart/README.env
  src/cart/crt_hg.c
  src/cart/crt_init.c
  src/cart/crt_internal_types.h
Labels: unclean-cherry-pick

#15388 DAOS-16469 container: Lower log level for cont_aggregate_interval
  src/container/srv_target.c
Labels: priority

#15375 DAOS-16721 object: fix coll RPC for obj with sparse layout
  src/dtx/dtx_coll.c
  src/dtx/dtx_rpc.c
  src/object/cli_coll.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/object/obj_utils.c
  src/object/srv_coll.c
  src/object/srv_obj.c
  src/vos/vos_dtx.c
Labels: priority

#15376 DAOS-16721 object: fix coll RPC for obj with sparse layout - b26
  src/dtx/dtx_coll.c
  src/dtx/dtx_rpc.c
  src/object/cli_coll.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/object/obj_utils.c
  src/object/srv_coll.c
  src/object/srv_obj.c
  src/vos/vos_dtx.c
Labels: priority

#15289 DAOS-16096 test: Add retry loop for comparing free pool space
  src/tests/ftest/dfuse/root_container.py
Labels: forced-landing

#15397 DAOS-16709 test: Handle decoding empty json output
  src/tests/ftest/util/command_utils.py
Labels: forced-landing

#15367 SRE-2329 build: Fix checkout 'null' from version control
  Jenkinsfile
Labels: forced-landing

#15425 DAOS-16685 dfuse: Change eq poll to use NOWAIT.
  src/client/dfuse/dfuse_core.c
Labels: release-2.6.2
