Repository daos-stack/daos, pull requests merged in 2024-06, with the labels that each got.

#14478 DAOS-15076 engine: Fixes and Performance improvements (#14404)
  src/engine/sched.c
  src/engine/srv_internal.h
  src/include/daos/rpc.h
  src/object/cli_shard.c
  src/object/obj_rpc.c
  src/object/srv_mod.c
Labels: clean-cherry-pick

#14477 DAOS-15498 rebuild: reprobe in migrate_obj_iter_cb (#14458)
  src/object/srv_obj_migrate.c
Labels: clean-cherry-pick

#14488 DAOS-15948 test: Include the varaint number in log files
  src/tests/ftest/util/daos_core_base.py
Labels: forced-landing

#14494 DAOS-15498 rebuild: reprobe in migrate_obj_iter_cb (#14458)
  src/object/srv_obj_migrate.c
Labels: priority

#14384 DAOS-623 cq: correct TARGET for merge commits
  utils/githooks/find_base.sh
Labels: forced-landing

#14482 DAOS-14539 client: fix pil4dfs strncmp compile in some envs (#14041)
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: clean-cherry-pick

#14507 DAOS-15959 cart: Add valgrind suppressions for Go runtime
  src/cart/utils/memcheck-cart.supp
Labels: forced-landing

#14480 DAOS-15805 control: Adjust SPDK config entry order to avoid hotplug race
  src/control/server/storage/bdev/backend_class_test.go
  src/control/server/storage/bdev/backend_json.go
  src/control/server/storage/bdev/backend_json_test.go
Labels: control-plane, dependencies, vmd, go

#14513 DAOS-623 build: Update packaging to…
  utils/rpms/packaging/Dockerfile.ubuntu.20.04
Labels: forced-landing

#14350 DAOS-15589 test: Pass the CR tests if contents of mount point are removed on MD-on-SSD cluster
  src/tests/ftest/recovery/pool_list_consolidation.py
  src/tests/ftest/recovery/pool_membership.py
  src/tests/ftest/recovery/pool_membership.yaml
Labels: forced-landing

#14500 DAOS-15948 test: Include the varaint number in log files (#14488)
  src/tests/ftest/util/daos_core_base.py
Labels: clean-cherry-pick, priority, forced-landing

#14487 DAOS-15935 client: search section "[stack]" instead of "[heap]" (#14472)
  src/client/dfuse/pil4dfs/hook.c
  src/tests/ftest/dfuse/bash.py
Labels: clean-cherry-pick, priority, approved-to-merge

#14493 DAOS-15287 test: Add register tearDown steps for job managers (#14245)
  src/tests/ftest/daos_racer/parallel.py
  src/tests/ftest/io/macsio_test.py
  src/tests/ftest/ior/crash.py
  src/tests/ftest/nvme/io_verification.py
  src/tests/ftest/rebuild/mdtest.py
  src/tests/ftest/rebuild/widely_striped.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/daos_perf_base.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/macsio_test_base.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/mpiio_test_base.py
Labels: clean-cherry-pick, forced-landing

#14495 DAOS-15920 object: check modification for CPD RPC - b26
  src/include/daos_srv/container.h
  src/object/obj_internal.h
  src/object/obj_rpc.h
  src/object/obj_tx.c
  src/object/srv_obj.c
Labels: priority

#14512 DAOS-15931 rebuild: fix data corruption caused by partial parity rebuild epoch
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/object/srv_obj_migrate.c
Labels: release-2.6

#14506 DAOS-15963 test: option to disable ULT stack dump on failure
  src/tests/ftest/util/apricot/apricot/test.py
Labels: forced-landing

#14530 DAOS-15991 cq: update pylint to 3.2.3
  utils/cq/requirements.txt
Labels: forced-landing

#14515 DAOS-15972 pool: Address Coverity 2555665,2555666
  src/pool/srv_pool.c
Labels: forced-landing, release-2.6

#14496 DAOS-15801 test: Add aio ioengine to pil4dfs_fio.py functional test
  src/tests/ftest/dfuse/pil4dfs_fio.py
  src/tests/ftest/dfuse/pil4dfs_fio.yaml
  utils/cq/words.dict
Labels: clean-cherry-pick, priority, forced-landing

#14538 DAOS-15963 test: option to disable ULT stack dump on failure (#14506)
  src/tests/ftest/util/apricot/apricot/test.py
Labels: priority, forced-landing

#14520 DAOS-15052 test: Update expected wal checkpoint metrics
  src/tests/ftest/telemetry/wal_metrics.py
Labels: forced-landing

#14501 DAOS-15794 tools: Add --health-only flag to (dmg|daos) pool query (#14297)
  src/control/cmd/daos/pool.go
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/common/proto/mgmt/svc.pb.go
  src/control/common/proto/mgmt/system.pb.go
  src/control/common/proto/srv/srv.pb.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool.go
  src/control/lib/daos/pool_test.go
  src/control/server/mgmt_pool.go
  src/include/daos_pool.h
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/tests/srv_drpc_tests.c
  src/proto/mgmt/pool.proto
  src/tests/ftest/control/dmg_pool_query_test.py
  src/tests/ftest/control/dmg_pool_query_test.yaml
  src/tests/ftest/pool/list_verbose.py
Labels: priority

#14163 DAOS-15617 test: Find mpi4py test in /usr/bin
  src/tests/ftest/mpiio/llnl_mpi4py.py
  src/tests/ftest/mpiio/llnl_mpi4py.yaml
Labels: forced-landing

#14522 DAOS-15805 control: Adjust SPDK config entry order to avoid hotplug r…
  src/control/server/storage/bdev/backend_class_test.go
  src/control/server/storage/bdev/backend_json.go
  src/control/server/storage/bdev/backend_json_test.go
Labels: control-plane, dependencies, clean-cherry-pick, priority, vmd, go, release-2.6

#14508 DAOS-15966 control: Remove dmg storage query device-health
  src/bio/README.md
  src/common/tests_dmg_helpers.c
  src/control/cmd/dmg/json_test.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/lib/support/log.go
  src/control/server/ctl_smd_rpc_test.go
  src/include/daos/tests_lib.h
  src/tests/ftest/checksum/csum_error_logging.py
  src/tests/ftest/nvme/health.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: control-plane

#14527 DAOS-15850 control: Pass up errors when failing to read cert dir (#14475)
  src/control/security/config.go
  src/control/security/config_test.go
  src/control/security/pem_test.go
  src/control/security/testdata/certs/badperms/README
  src/control/security/testdata/certs/goodperms/README
Labels: clean-cherry-pick, priority

#14526 DAOS-15842 control: Reject re-join with different control addr (#14470)
  docs/admin/troubleshooting.md
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/system/errors.go
  src/control/system/membership.go
  src/control/system/membership_test.go
Labels: clean-cherry-pick, priority

#14387 DAOS-15851 ci: Use CI_PR_REPOS parameter if provided
  utils/rpms/packaging/Makefile_packaging.mk
  utils/test_memcheck.supp
Labels: priority, release-2.6

#14497 DAOS-15852 test: more timing samples for co_op_dup_timing()
  src/tests/suite/daos_container.c
Labels: forced-landing

#14540 DAOS-16000 test: fix get_host_log_files ignoring error
  src/tests/ftest/util/server_utils.py
Labels: forced-landing

#14549 DAOS-15602 test: Find mpi4py test in /usr/bin (#14163)
  src/tests/ftest/mpiio/llnl_mpi4py.py
  src/tests/ftest/mpiio/llnl_mpi4py.yaml
Labels: clean-cherry-pick, release-2.6

#14525 DAOS-15589 test: Pass the CR tests if contents of mount point are rem…
  src/tests/ftest/recovery/pool_list_consolidation.py
  src/tests/ftest/recovery/pool_membership.py
  src/tests/ftest/recovery/pool_membership.yaml
Labels: clean-cherry-pick

#14554 DAOS-15968 container: Fix CAPA fetch on NS master (#14511)
  src/container/container_iv.c
Labels: clean-cherry-pick

#14564 DAOS-16011 : Valgrind suppressions due to update Go to 1.22.3
  src/cart/utils/memcheck-cart.supp
  utils/test_memcheck.supp
Labels: priority, forced-landing, go, release-2.6

#14566 DAOS-16011 : Valgrind suppressions due to update Go to 1.22.3
  src/cart/utils/memcheck-cart.supp
Labels: priority, forced-landing, go, release-2.6

#14565 DAOS-15851 ci: Use CI_PR_REPOS parameter if provided
  utils/rpms/packaging/Makefile_packaging.mk
Labels: priority, forced-landing, release-2.6

#14546 DAOS-15913 doc: remove depecated --label flag
  docs/admin/pool_operations.md
  docs/user/container.md
  docs/user/filesystem.md
  docs/user/mpi-io.md
  docs/user/python.md
  docs/user/spark.md
Labels: release-2.6

#14559 DAOS-14630 docs: Document MD-on-SSD configuration
  docs/admin/deployment.md
  src/include/daos/tests_lib.h
Labels: control-plane, doc-only, usability, release-2.6

#14542 DAOS-15391 pool: destroy container during reintegration discard (#13958)
  src/container/srv_target.c
  src/include/daos_srv/container.h
  src/pool/srv_target.c
  src/tests/suite/daos_rebuild.c
Labels: clean-cherry-pick, priority

#14553 DAOS-15052 test: Update expected wal checkpoint metrics (#14520)
  src/tests/ftest/telemetry/wal_metrics.py
Labels: forced-landing

#14523 DAOS-14517 test: Fixing test_daos_vol_bigio
  src/tests/ftest/daos_vol/bigio.yaml
Labels: forced-landing

#14580 DAOS-16034: Valgrind issues related to go 1.22.3
  src/cart/utils/memcheck-cart.supp
Labels: priority, forced-landing, release-2.6

#14574 DAOS-14630 docs: Document MD-on-SSD configuration (#14559)
  docs/admin/deployment.md
Labels: unclean-cherry-pick, doc-only

#14595 DAOS-15913 doc: remove depecated --label flag (#14546)
  docs/admin/pool_operations.md
  docs/user/container.md
  docs/user/filesystem.md
  docs/user/mpi-io.md
  docs/user/python.md
  docs/user/spark.md
Labels: priority, forced-landing, doc-only

#14567 DAOS-16000 test: fix get_host_log_files ignoring error (#14540)
  src/tests/ftest/util/server_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#14541 DAOS-15956 control: Limit race between taking leadership and join
  src/control/server/mgmt_svc.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/system/errors.go
  src/control/system/errors_test.go
  src/control/system/raft/database.go
  src/control/system/raft/mocks.go
  src/control/system/raft/raft.go
  src/control/system/raft/raft_test.go
Labels: forced-landing

#14600 DAOS-16052 test: Skip wal tests if fault injection feature is disabled
  src/cart/utils/memcheck-cart.supp
  src/vos/tests/vts_wal.c
  utils/test_memcheck.supp
Labels: priority, release-2.6

#14605 DAOS-16052 test: Skip wal tests if fault injection feature is disabled
  src/cart/utils/memcheck-cart.supp
  src/vos/tests/vts_wal.c
  utils/test_memcheck.supp
Labels: priority

#14613 DAOS-16017 build: Tag 2.6.0 rc1
  TAG
  VERSION
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#14557 DAOS-16001 placement: fix cases for delay_rebuild
  src/include/daos/pool_map.h
  src/placement/pl_map.h
  src/placement/pl_map_common.c
  src/tests/ftest/rebuild/cascading_failures.py
  src/tests/ftest/util/container_rf_test_base.py
Labels: forced-landing

#14583 DAOS-16021 test: Increase timeout for test_daos_container
  src/tests/ftest/daos_test/suite.yaml
Labels: forced-landing

#14571 DAOS-15738 control: Update required Go build version (#14413)
  src/control/go.mod
Labels: clean-cherry-pick, priority, release-2.6

#14573 DAOS-15966 control: Remove dmg storage query device-health (#14508)
  docs/admin/administration.md
  src/bio/README.md
  src/common/tests_dmg_helpers.c
  src/control/cmd/dmg/json_test.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/lib/support/log.go
  src/control/server/ctl_smd_rpc_test.go
  src/include/daos/tests_lib.h
  src/tests/ftest/checksum/csum_error_logging.py
  src/tests/ftest/nvme/health.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: priority, forced-landing, approved-to-merge, usability, release-2.6

#14578 DAOS-15919 test: wait more time after system restart
  src/tests/suite/daos_cr.c
Labels: forced-landing, approved-to-merge, release-2.6

#14533 DAOS-13994 test: variants for performance pil4dfs
  src/tests/ftest/performance/ior_easy.py
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/ior_hard.py
  src/tests/ftest/performance/ior_hard.yaml
  src/tests/ftest/performance/mdtest_easy.py
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/performance/mdtest_hard.py
  src/tests/ftest/performance/mdtest_hard.yaml
  src/tests/ftest/util/performance_test_base.py
Labels: forced-landing

#14633 DAOS-16087 test: disable dfs pipeline test in release build (#14627)
  src/tests/suite/dfs_unit_test.c
Labels: clean-cherry-pick

#14619 DAOS-16016 test: Coverity 2555785 fix and run test_rebuild_35
  src/tests/ftest/daos_test/rebuild.py
  src/tests/ftest/daos_test/rebuild.yaml
  src/tests/suite/daos_rebuild.c
Labels: forced-landing

#14581 DAOS-15955 test: increase clush fanout for run_remote (#14509)
  src/tests/ftest/util/run_utils.py
  src/tests/ftest/util/soak_test_base.py
Labels: clean-cherry-pick, release-2.6.1

#14585 DAOS-14517 test: Fixing test_daos_vol_bigio (#14523)
  src/tests/ftest/daos_vol/bigio.yaml
Labels: forced-landing

#14642 DAOS-16016 test: Coverity 2555785 fix and run test_rebuild_35 (#14619)
  src/tests/ftest/daos_test/rebuild.py
  src/tests/ftest/daos_test/rebuild.yaml
  src/tests/suite/daos_rebuild.c
Labels: clean-cherry-pick, forced-landing

#14634 DAOS-16084 test: make FI required for pool/cont retry tests
  src/tests/suite/daos_container.c
  src/tests/suite/daos_pool.c
Labels: forced-landing

#14644 DAOS-16084 test: make FI required for pool/cont retry tests
  src/tests/suite/daos_container.c
  src/tests/suite/daos_pool.c
Labels: clean-cherry-pick, forced-landing

#14383 DAOS-16111 rebuild: uniform identifier in logs part 1
  src/include/daos_srv/daos_engine.h
  src/include/daos_srv/object.h
  src/include/daos_srv/rebuild.h
  src/object/srv_obj_migrate.c
  src/pool/srv_target.c
  src/rebuild/scan.c
  src/rebuild/srv.c
  src/tests/ftest/erasurecode/offline_rebuild_single.yaml
  src/tests/ftest/erasurecode/online_rebuild.yaml
  src/tests/ftest/rebuild/cascading_failures.yaml
Labels: forced-landing

#14579 DAOS-15919 chk: rollback generation if failed to start checker
  src/chk/chk_leader.c
Labels: forced-landing

#14609 DAOS-16070 tools: Include BuildInfo field in version output
  src/control/SConscript
  src/control/build/string.go
  src/control/build/variables.go
  src/control/cmd/daos/main.go
  src/control/cmd/daos/util.go
  src/control/cmd/daos_agent/attachinfo.go
  src/control/cmd/daos_agent/main.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/main.go
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/addons.go
  src/control/common/proto/mgmt/svc.pb.go
  src/control/lib/control/network.go
  src/control/server/mgmt_system.go
  src/include/daos_mgmt.h
  src/mgmt/cli_mgmt.c
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/proto/mgmt/svc.proto
Labels: forced-landing

#14630 DAOS-16091 umem: reset rc properly (#14621)
  src/common/mem.c
Labels: clean-cherry-pick, priority

#14601 DAOS-16001 placement: fix cases for delay_rebuild
  src/include/daos/pool_map.h
  src/placement/pl_map.h
  src/placement/pl_map_common.c
  src/tests/ftest/rebuild/cascading_failures.py
  src/tests/ftest/util/container_rf_test_base.py
Labels: clean-cherry-pick

#14647 DAOS-16081 test: Skipping fault injection tests in release builds (#1…
  src/tests/ftest/daos_test/suite.py
  src/tests/ftest/recovery/container_cleanup.py
  src/tests/ftest/recovery/container_list_consolidation.py
  src/tests/ftest/recovery/pool_cleanup.py
  src/tests/ftest/recovery/pool_list_consolidation.py
Labels: forced-landing

#14643 DAOS-13994 test: variants for performance pil4dfs (#14533)
  src/tests/ftest/performance/ior_easy.py
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/ior_hard.py
  src/tests/ftest/performance/ior_hard.yaml
  src/tests/ftest/performance/mdtest_easy.py
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/performance/mdtest_hard.py
  src/tests/ftest/performance/mdtest_hard.yaml
  src/tests/ftest/util/performance_test_base.py
Labels: clean-cherry-pick, priority

#14651 DAOS-16122 test: update pylint to 3.2.4
  utils/cq/requirements.txt
Labels: forced-landing

#14593 DAOS-16039 object: fix EC aggregation wrong peer address
  src/container/srv_target.c
  src/include/daos/common.h
  src/object/srv_ec_aggregate.c
  src/tests/suite/daos_obj_ec.c
Labels: forced-landing
