Repository daos-stack/daos, pull requests merged in 2024-11, with the labels that each got.

#15436 Revert "DAOS-16477 mgmt: return suspect engines for pool healthy query"
  docs/admin/pool_operations.md
  src/control/cmd/daos/health.go
  src/control/cmd/daos/pool.go
  src/control/cmd/daos/pretty/health.go
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool.go
  src/control/lib/daos/pool_test.go
  src/include/daos_pool.h
  src/include/daos_srv/pool.h
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_pool.c
  src/mgmt/tests/mocks.c
  src/mgmt/tests/mocks.h
  src/mgmt/tests/srv_drpc_tests.c
  src/pool/srv_cli.c
  src/proto/mgmt/pool.proto
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/ftest/control/dmg_pool_query_ranks.yaml
  src/tests/ftest/daos_test/suite.yaml
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/server_utils_params.py
  src/tests/ftest/util/test_utils_pool.py
Labels: priority

#15111 DAOS-16508 csum: retry a few times on checksum mismatch on update (#1…
  src/common/checksum.c
  src/object/cli_csum.h
  src/object/cli_obj.c
  src/object/obj_internal.h
Labels: priority, release-2.6.2

#15432 DAOS-16211 vos: Avoid race condition with discard (#15370)
  src/vos/vos_obj_index.c
Labels: unclean-cherry-pick

#15201 SRE-2505 ci: Fix Trivy scan upload to the Security tab
  .github/workflows/trivy.yml
  README.md
  utils/trivy/trivy.yaml
Labels: doc-only, release-2.6.2

#14932 DAOS-16365 client: intercept dlsym() and zeInit() to avoid nested call
  src/client/dfuse/pil4dfs/hook.c
  src/client/dfuse/pil4dfs/hook.h
  src/client/dfuse/pil4dfs/int_dfs.c
  src/client/dfuse/pil4dfs/pil4dfs_int.h
Labels: priority

#15408 DAOS-16721 dtx: handle potential DTX ID reusing trouble
  src/dtx/dtx_coll.c
  src/dtx/dtx_common.c
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos_srv/container.h
  src/object/cli_coll.c
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/object/obj_utils.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/object/srv_obj_remote.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
Labels: priority

#15409 DAOS-16721 dtx: handle potential DTX ID reusing trouble - b26
  src/dtx/dtx_coll.c
  src/dtx/dtx_common.c
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos_srv/container.h
  src/object/cli_coll.c
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/object/obj_utils.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/object/srv_obj_remote.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
Labels: priority

#15446 DAOS-16365 client: intercept dlsym() and zeInit() to avoid nested calls
  src/client/dfuse/pil4dfs/hook.c
  src/client/dfuse/pil4dfs/hook.h
  src/client/dfuse/pil4dfs/int_dfs.c
  src/client/dfuse/pil4dfs/pil4dfs_int.h
Labels: clean-cherry-pick, priority

#15455 DAOS-16784 build: Tag 2.6.2 tb1
  TAG
  VERSION
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#15473 DAOS-16645 cart: Bump file descriptor limit (#15224)
  ci/unit/test_nlt_node.sh
  src/cart/crt_init.c
  utils/ansible/ftest/templates/daos-launch_nlt.sh.j2
  utils/node_local_test.py
Labels: priority

#15479 DAOS-16797 build: Create 2.8 TB1
  TAG
  VERSION
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#15418 DAOS-16327 control: Update dmg storage query usage for MD-on-SSD P2
  docs/admin/pool_operations.md
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/storage_nvme_test.go
  src/control/cmd/dmg/pretty/storage_query.go
  src/control/cmd/dmg/pretty/storage_query_test.go
  src/control/cmd/dmg/storage_query.go
  src/control/cmd/dmg/storage_query_test.go
  src/control/lib/control/auto_test.go
  src/control/lib/control/mocks.go
  src/control/lib/control/pool.go
  src/control/lib/control/server_meta_test.go
  src/control/lib/control/storage.go
  src/control/lib/control/storage_test.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/faults.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend_class.go
  src/control/server/storage/bdev/backend_class_test.go
  src/control/server/storage/bdev/backend_json_test.go
  src/control/server/storage/config.go
  src/control/server/storage/mocks.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm/ipmctl_region.go
  src/control/server/storage/scm/ndctl.go
  utils/config/examples/daos_server_mdonssd.yml
Labels: control-plane, meta-on-ssd

#15463 DAOS-16365 client: use D_ASPRINTF and fix format issues
  src/client/dfuse/pil4dfs/hook.c
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: priority

#15484 DAOS-7203 control: Add histogram support to Prometheus exporter (#5382)
  src/control/cmd/dmg/telemetry.go
  src/control/lib/control/telemetry_test.go
  src/control/lib/daos/telemetry.go
  src/control/lib/daos/telemetry_test.go
  src/control/lib/telemetry/counter.go
  src/control/lib/telemetry/duration.go
  src/control/lib/telemetry/gauge.go
  src/control/lib/telemetry/histogram.go
  src/control/lib/telemetry/promexp/client.go
  src/control/lib/telemetry/promexp/client_test.go
  src/control/lib/telemetry/promexp/collector.go
  src/control/lib/telemetry/promexp/engine_test.go
  src/control/lib/telemetry/promexp/histogram.go
  src/control/lib/telemetry/promexp/source.go
  src/control/lib/telemetry/promexp/util.go
  src/control/lib/telemetry/snapshot.go
  src/control/lib/telemetry/timestamp.go
  src/gurt/telemetry.c
  src/gurt/tests/test_gurt_telem_producer.c
  src/include/gurt/telemetry_common.h
  src/include/gurt/telemetry_producer.h
Labels: clean-cherry-pick

#15459 DAOS-16635 control: Pass meta_sz to pool extend+reintegrate API
  src/control/common/proto/mgmt/pool.pb.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/control/system/pool.go
  src/mgmt/cli_mgmt.c
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/rpc.c
  src/mgmt/rpc.h
  src/mgmt/srv.c
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_pool.c
  src/mgmt/tests/mocks.c
  src/proto/mgmt/pool.proto
Labels: control-plane, meta-on-ssd

#15242 DAOS-16662 test: update some tests to use unique dfuse mount
  src/tests/ftest/deployment/basic_checkout.py
  src/tests/ftest/deployment/basic_checkout.yaml
  src/tests/ftest/dfuse/mu_perms.yaml
  src/tests/ftest/dfuse/simul.yaml
  src/tests/ftest/ior/small.py
  src/tests/ftest/ior/small.yaml
  src/tests/ftest/util/ior_test_base.py
Labels: forced-landing

#15350 DAOS-16572 object: refine sc_ec_agg_active flag setting
  src/container/srv_target.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/rebuild/scan.c
Labels: priority

#15490 DAOS-16328 control: Update dmg pool list for MD-on-SSD
  docs/admin/pool_operations.md
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/lib/control/pool.go
Labels: control-plane, forced-landing, meta-on-ssd

#15513 DAOS-16791 control: Add include_fabric_ifaces to agent config (#15470)
  src/control/cmd/daos_agent/config.go
  src/control/cmd/daos_agent/config_test.go
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/fabric_test.go
  src/control/cmd/daos_agent/infocache.go
  utils/config/daos_agent.yml
Labels: clean-cherry-pick

#15530 DAOS-16825 test: Support register cleanup for all Test classes
  src/tests/ftest/control/config_generate_run.py
  src/tests/ftest/control/daos_agent_config.py
  src/tests/ftest/network/cart_self_test.py
  src/tests/ftest/util/apricot/apricot/test.py
Labels: forced-landing

#15275 DAOS-16100 test: Fix stopping daos_test during timeout
  src/tests/ftest/daos_test/dfs.py
  src/tests/ftest/daos_test/dfuse.py
  src/tests/ftest/harness/basic.py
  src/tests/ftest/harness/cmocka.py
  src/tests/ftest/harness/cmocka.yaml
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/cmocka_utils.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/daos_core_base.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/run_utils.py
Labels: forced-landing

#15503 DAOS-15964 test: verify daos_server_helper on server
  src/tests/ftest/control/daos_server_helper.py
  src/tests/ftest/control/daos_server_helper.yaml
Labels: forced-landing

#15495 DAOS-16757 doc: improve the documentation
  docs/overview/terminology.md
Labels: forced-landing
