Repository daos-stack/daos, pull requests merged in 2024-08, with the labels that each got.

#14840 DAOS-16204 test: remove sudo requirements from io_sys_admin.py (#14732)
  src/tests/ftest/deployment/io_sys_admin.py
  src/tests/ftest/deployment/io_sys_admin.yaml
Labels: clean-cherry-pick, priority, forced-landing

#14862 DAOS-15613 test: build current SHA in daos_build.py (#14796)
  src/tests/ftest/dfuse/daos_build.py
Labels: clean-cherry-pick, priority

#14848 DAOS-16295 test: fix streaming stdout when running launch.py locally
  src/tests/ftest/util/launch_utils.py
Labels: forced-landing

#14859 DAOS-16286 client: intercept fdatasync() (#14835)
  src/client/dfuse/pil4dfs/int_dfs.c
  src/tests/suite/dfuse_test.c
Labels: clean-cherry-pick, priority, forced-landing

#14646 DAOS-16070 tools: Include BuildInfo field in version output
  src/control/SConscript
  src/control/build/string.go
  src/control/build/variables.go
  src/control/cmd/daos/main.go
  src/control/cmd/daos/util.go
  src/control/cmd/daos_agent/attachinfo.go
  src/control/cmd/daos_agent/main.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/main.go
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/addons.go
  src/control/common/proto/mgmt/svc.pb.go
  src/control/lib/control/network.go
  src/control/server/mgmt_system.go
  src/include/daos_mgmt.h
  src/mgmt/cli_mgmt.c
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/proto/mgmt/svc.proto
Labels: clean-cherry-pick, priority, forced-landing

#14707 DAOS-16161 object: should bulk GET for ds_obj_ec_rep_handler
  src/object/srv_obj.c
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/daos_obj_ec.c
Labels: clean-cherry-pick, forced-landing

#14828 DAOS-14679 pool: Backport fixes
  src/include/daos/common.h
  src/include/daos_srv/pool.h
  src/include/daos_srv/rsvc.h
  src/mgmt/rpc.h
  src/mgmt/srv.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_target.c
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/rsvc/srv.c
  src/tests/suite/daos_mgmt.c
Labels: priority, release-2.6.1

#14847 DAOS-16151 cart: add no-sync option to self_test (#14697)
  src/utils/self_test/self_test.c
Labels: unclean-cherry-pick, priority, forced-landing

#14863 DAOS-16238 utils: Add valgrind suppressions for Go runtime (#14823)
  src/cart/utils/memcheck-cart.supp
Labels: unclean-cherry-pick, priority, forced-landing, release-2.6.1

#14837 DAOS-16082 test: Repeatedly query device after SysXS device is set to…
  src/tests/ftest/control/dmg_storage_query.py
Labels: clean-cherry-pick

#14853 DAOS-16038 pool: Enable pool list for clients (#14672)
  src/client/api/init.c
  src/client/api/mgmt.c
  src/control/cmd/daos/pool.go
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/cmd/daos/pretty/ranks.go
  src/control/cmd/daos/pretty/ranks_test.go
  src/control/cmd/daos/util.go
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/cmd/dmg/pretty/ranks.go
  src/control/common/proto/srv/srv.pb.go
  src/control/drpc/modules.go
  src/control/lib/daos/pool.go
  src/control/server/mgmt_drpc.go
  src/engine/drpc_client.c
  src/engine/srv.pb-c.c
  src/engine/srv.pb-c.h
  src/include/daos/drpc.pb-c.h
  src/include/daos/drpc_modules.h
  src/include/daos/mgmt.h
  src/include/daos/task.h
  src/include/daos_mgmt.h
  src/include/daos_srv/daos_engine.h
  src/include/daos_task.h
  src/mgmt/cli_mgmt.c
  src/mgmt/rpc.c
  src/mgmt/rpc.h
  src/mgmt/srv.c
  src/mgmt/srv_internal.h
  src/proto/srv/srv.proto
  src/tests/ftest/pool/list_pools.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/daos_utils_base.py
  src/tests/suite/daos_mgmt.c
Labels: clean-cherry-pick, forced-landing

#14872 DAOS-16013 tools: Query all pool targets by default (#14783)
  src/control/cmd/daos/pool.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
Labels: clean-cherry-pick, priority

#14755 DAOS-16078 common: fix a Coverity issue (release/2.6 catching up with the master)
  src/common/btree.c
Labels: priority

#14751 DAOS-16218 test: Support running agent as user
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/harness/advanced.py
  src/tests/ftest/harness/coverage.py
  src/tests/ftest/harness/coverage.yaml
  src/tests/ftest/util/agent_utils.py
  src/tests/ftest/util/agent_utils_params.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/network_utils.py
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/support_test_base.py
Labels: forced-landing

#14871 DAOS-16250 control: Allow control client version override (#14785)
  src/control/build/context.go
  src/control/build/context_test.go
  src/control/build/errors.go
  src/control/lib/control/interceptors.go
Labels: priority

#14668 DAOS-15930 test: extend_simple add FI required macro call
  src/tests/suite/daos_extend_simple.c
Labels: clean-cherry-pick, forced-landing

#14883 DAOS-15997 build: bump mercury version to 2.4.0rc4 (#14873)
  debian/changelog
  debian/control
  utils/build.config
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, forced-landing

#14889 DAOS-16313 build: Add explicit linker flags to lib/daos/api
  src/control/lib/daos/api/api.go
  src/control/lib/daos/api/system.go
Labels: forced-landing

#14892 DAOS-16316 test: Disable runtime dir creation for test
  src/tests/ftest/control/daos_agent_config.py
  src/tests/ftest/util/agent_utils.py
Labels: forced-landing

#14882 DAOS-16217 test: Use subprocess.run() for run_local()
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/launch_utils.py
  src/tests/ftest/util/run_utils.py
Labels: priority, forced-landing

#14503 DAOS-15960 tests: Improvements for io_sys_admin test
  src/tests/ftest/deployment/io_sys_admin.yaml
  src/tests/ftest/io/large_file_count.yaml
  src/tests/ftest/io/small_file_count.yaml
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/file_count_test_base.py
Labels: forced-landing

#14887 DAOS-15961 cart: Reorganize how envs are handled (#14504)
  src/cart/crt_init.c
  src/cart/crt_internal_types.h
  src/cart/utils/crt_utils.c
  src/cart/utils/crt_utils.h
  src/tests/ftest/cart/utest/utest_portnumber.c
  src/utils/crt_launch/crt_launch.c
  src/utils/self_test/self_test.c
Labels: unclean-cherry-pick, priority, forced-landing

#14885 DAOS-16127 tools: Add daos health check command (#14730)
  src/client/api/SConscript
  src/client/api/version.c
  src/control/build/interop.go
  src/control/build/lib_versions.go
  src/control/build/lib_versions_test.go
  src/control/cmd/daos/container.go
  src/control/cmd/daos/health.go
  src/control/cmd/daos/main.go
  src/control/cmd/daos/pool.go
  src/control/cmd/daos/pretty/health.go
  src/control/cmd/daos/pretty/health_test.go
  src/control/cmd/daos/system.go
  src/control/cmd/daos/util.go
  src/control/cmd/dmg/pool.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/api/api.go
  src/control/lib/daos/api/provider.go
  src/control/lib/daos/api/system.go
  src/control/lib/daos/container.go
  src/control/lib/daos/health.go
  src/control/lib/daos/pool.go
  src/control/lib/daos/pool_test.go
  src/control/lib/daos/status.go
  src/control/lib/daos/status_test.go
  src/control/lib/daos/system.go
  src/control/lib/dlopen/dlopen.go
  src/control/lib/dlopen/dlopen_example.go
  src/control/lib/ranklist/ranklist.go
  src/control/lib/ranklist/ranklist_test.go
  src/control/lib/txtfmt/table.go
  src/control/lib/txtfmt/table_test.go
  src/control/vendor/github.com/jessevdk/go-flags/group.go
  src/include/daos/api.h
  src/include/daos_types.h
  src/mgmt/cli_mgmt.c
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/ftest/control/dmg_pool_query_test.py
  src/tests/ftest/control/dmg_pool_query_test.yaml
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/server_rank_failure.py
  src/tests/ftest/pool/create_query.py
  src/tests/ftest/pool/list_verbose.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/pool_create_all_base.py
Labels: clean-cherry-pick, priority, forced-landing

#14897 DAOS-16288 cart: coverity fixes for 16287,16288,16289 (#14843)
  src/cart/crt_group.c
  src/tests/ftest/cart/test_group_np_cli.c
  src/tests/ftest/cart/test_no_timeout.c
Labels: clean-cherry-pick, priority

#14771 DAOS-16229 test: support dynamic stonewall file
  src/tests/ftest/aggregation/continuous_write.py
  src/tests/ftest/aggregation/space_rb.py
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/basic_checkout.yaml
  src/tests/ftest/deployment/ior_per_rank.yaml
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/server_rank_failure.py
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/ior/hard.yaml
  src/tests/ftest/ior/hard_rebuild.yaml
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/ior_hard.yaml
  src/tests/ftest/rebuild/continues_after_stop.py
  src/tests/ftest/server/metadata.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/mdtest_utils.py
  src/tests/ftest/util/nvme_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#14881 DAOS-16310 test: consolidate il and ioil tags
  src/tests/ftest/dfuse/bash.py
  src/tests/ftest/dfuse/bash_dcache.py
  src/tests/ftest/dfuse/bash_fd.py
  src/tests/ftest/dfuse/daos_build.py
  src/tests/ftest/dfuse/mu_perms.py
  src/tests/ftest/dfuse/pil4dfs_dcache.py
  src/tests/ftest/dfuse/pil4dfs_fio.py
  src/tests/ftest/ior/intercept_messages.py
  src/tests/ftest/ior/intercept_messages_pil4dfs.py
  src/tests/ftest/ior/intercept_multi_client.py
Labels: forced-landing

#14841 DAOS-16035 rebuild: create VOS cont when no record need to be rebuilt…
  src/container/srv_target.c
  src/object/srv_obj_migrate.c
  src/rebuild/scan.c
Labels: clean-cherry-pick, priority, forced-landing

#14899 DAOS-16305 build: Simplify hermetic builds (#14874)
  site_scons/components/__init__.py
  site_scons/prereq_tools/base.py
  utils/build.config
Labels: clean-cherry-pick, priority, forced-landing

#14903 DAOS-15960 tests: Improvements for io_sys_admin test (#14503)
  src/tests/ftest/deployment/io_sys_admin.yaml
  src/tests/ftest/io/large_file_count.yaml
  src/tests/ftest/io/small_file_count.yaml
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/file_count_test_base.py
Labels: clean-cherry-pick

#14898 DAOS-16219 test: Remove sudo usage from fault injection files
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/fault_config_utils.py
Labels: forced-landing

#14622 DAOS-15751 bio: change default bio_max_async_sz to 32k (#14568)
  src/bio/bio_buffer.c
  src/bio/bio_xstream.c
Labels: clean-cherry-pick, forced-landing, release-2.6.1

#14910 DAOS-16301 test: Increase verify_perms.py timeout
  src/tests/ftest/dfuse/mu_perms.yaml
  src/tests/ftest/util/dfuse_utils.py
Labels: forced-landing

#14825 DAOS-15914 dtx: control DTX RPC to reduce network load - b26
  src/cart/crt_context.c
  src/dtx/dtx_coll.c
  src/dtx/dtx_common.c
  src/dtx/dtx_cos.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/cart/api.h
  src/include/daos_srv/dtx_srv.h
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/vos/tests/vts_dtx.c
  src/vos/vos_dtx.c
Labels: clean-cherry-pick, forced-landing

#14683 DAOS-15914 cart: add D_MRECV_BUF env var to control number of multi-recv buffers
  src/cart/README.env
  src/cart/crt_hg.c
  src/cart/crt_hg.h
  src/cart/crt_init.c
  src/cart/crt_internal_types.h
Labels: clean-cherry-pick

#14815 DAOS-16211 vos: Ensure we delete exact entry (#14763)
  src/vos/evtree.c
  src/vos/tests/evt_ctl.sh
  src/vos/vos_aggregate.c
Labels: clean-cherry-pick

#14920 DAOS-16301 test: Increase verify_perms.py timeout (#14910)
  src/tests/ftest/dfuse/mu_perms.yaml
  src/tests/ftest/util/dfuse_utils.py
Labels: clean-cherry-pick, forced-landing

#14919 DAOS-16218 test: Support running agent as user #14751
  src/tests/ftest/control/daos_agent_config.py
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/harness/advanced.py
  src/tests/ftest/harness/coverage.py
  src/tests/ftest/harness/coverage.yaml
  src/tests/ftest/util/agent_utils.py
  src/tests/ftest/util/agent_utils_params.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/network_utils.py
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/support_test_base.py
Labels: clean-cherry-pick, priority, forced-landing

#14915 DAOS-16330 cart: Reduce error logs during timeouts (#14905)
  src/cart/crt_context.c
  src/cart/crt_group.c
  src/cart/crt_init.c
  src/cart/crt_internal.h
  src/cart/crt_internal_fns.h
  src/cart/crt_internal_types.h
Labels: unclean-cherry-pick, forced-landing

#14924 DAOS-16036 bio: bump max WAL tx size to 16MB (#14589)
  src/bio/bio_wal.c
  src/vos/tests/wal_ut.c
Labels: clean-cherry-pick

#14890 DAOS-15946 control: Checker enablement misc fixes (#14700)
  src/control/server/mgmt_check.go
Labels: control-plane, clean-cherry-pick, priority, forced-landing

#14875 DAOS-16307 client: Defer creating network context in child processes
  src/client/dfuse/pil4dfs/int_dfs.c
  src/tests/ftest/dfuse/bash.py
Labels: forced-landing

#14928 DAOS-16219 test: Remove sudo usage from fault injection files (#14898)
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/fault_config_utils.py
Labels: priority

#14938 DAOS-16306 common: Fix Use-After-Free issue in LRU Cache (#14906)
  src/common/lru.c
Labels: clean-cherry-pick, release-2.6.1

#14708 DAOS-16097 vos: assign persistent DTX entry in vos_dtx_prepared
  src/dtx/dtx_rpc.c
  src/object/srv_obj.c
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_ilog.c
  src/vos/vos_internal.h
  src/vos/vos_tree.c
Labels: forced-landing

#14907 DAOS-16317 cart: Simplify crt_get_info_string (#14896)
  src/cart/crt_hg.c
  src/cart/crt_register.c
Labels: clean-cherry-pick

#14927 DAOS-16354 cart: Don't retry URI_LOOKUPs for PROTO_QUERY rpc (#14922)
  src/cart/crt_rpc.c
Labels: clean-cherry-pick

#14961 DAOS-15916 dfs: Seg fault with DFS scanner (#14449)
  src/client/dfs/cont.c
Labels: bug, clean-cherry-pick, priority, approved-to-merge

#14845 DAOS-9247 control,bio: Add PCIe link speed and width to NVMe health s…
  ci/unit/required_packages.sh
  debian/changelog
  debian/control
  docs/admin/administration.md
  src/bio/bio_device.c
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/pretty/storage_nvme.go
  src/control/cmd/dmg/pretty/storage_nvme_test.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/common/env_utils.go
  src/control/common/env_utils_test.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/lib/hardware/hwloc/bindings.go
  src/control/lib/hardware/hwloc/provider.go
  src/control/lib/hardware/hwloc/provider_test.go
  src/control/lib/hardware/hwprov/defaults.go
  src/control/lib/hardware/pci.go
  src/control/lib/hardware/pci_test.go
  src/control/lib/hardware/pciutils/bindings.go
  src/control/lib/hardware/pciutils/bindings_test.go
  src/control/lib/hardware/pretty_test.go
  src/control/lib/hardware/topology.go
  src/control/lib/hardware/topology_test.go
  src/control/pbin/exec.go
  src/control/provider/system/distribution.go
  src/control/server/instance_storage_rpc.go
  src/control/server/instance_storage_rpc_test.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend_vmd.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/mocks.go
  src/include/daos_srv/bio.h
  src/include/daos_srv/control.h
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_query.c
  src/proto/ctl/smd.proto
  utils/ansible/ftest/vars/Rocky8.yml
  utils/rpms/daos.spec
  utils/scripts/install-el8.sh
  utils/scripts/install-el9.sh
  utils/scripts/install-leap15.sh
  utils/scripts/install-ubuntu.sh
Labels: control-plane, unclean-cherry-pick, priority, forced-landing, usability

#14740 DAOS-14422 control: Update pool create UX for MD-on-SSD phase2
  src/common/dav_v2/dav_iface.c
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/fault/code/codes.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool.go
  src/control/server/faults.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/control/server/storage/bdev.go
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_pool.c
  src/mgmt/srv_target.c
  src/proto/mgmt/pool.proto
  src/vos/vos_pool.c
Labels: control-plane, meta-on-ssd, go, usability

#14666 DAOS-15992 client: set st_blksize in ostatx_cb() and add unit test
  src/client/dfs/obj.c
  src/tests/suite/dfs_unit_test.c
Labels: clean-cherry-pick, priority, forced-landing, release-2.6.1

#14921 DAOS-16229 test: support dynamic stonewall file (#14771)
  src/tests/ftest/aggregation/continuous_write.py
  src/tests/ftest/aggregation/space_rb.py
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/basic_checkout.yaml
  src/tests/ftest/deployment/ior_per_rank.yaml
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/server_rank_failure.py
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/ior/hard.yaml
  src/tests/ftest/ior/hard_rebuild.yaml
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/ior_hard.yaml
  src/tests/ftest/rebuild/continues_after_stop.py
  src/tests/ftest/server/metadata.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/mdtest_utils.py
  src/tests/ftest/util/nvme_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: unclean-cherry-pick, priority, forced-landing

#14953 DAOS-16352 control: Handle cases with static ifaces
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/fabric_test.go
  src/control/cmd/daos_agent/infocache.go
  src/control/cmd/daos_agent/infocache_test.go
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
Labels: control-plane, forced-landing

#14964 DAOS-16381 test: Run IOR with HDF5-VOL with multiple object classes
  src/tests/ftest/util/file_count_test_base.py
Labels: forced-landing

#14648 DAOS-16098 doc: Add a guide for setting up DAOS using QEMU
  docs/QSG/qemu-vms.md
Labels: forced-landing

#14979 DAOS-16310 test: consolidate il and ioil tags (#14881)
  src/tests/ftest/dfuse/bash.py
  src/tests/ftest/dfuse/bash_dcache.py
  src/tests/ftest/dfuse/bash_fd.py
  src/tests/ftest/dfuse/daos_build.py
  src/tests/ftest/dfuse/mu_perms.py
  src/tests/ftest/dfuse/pil4dfs_dcache.py
  src/tests/ftest/dfuse/pil4dfs_fio.py
  src/tests/ftest/ior/intercept_messages.py
  src/tests/ftest/ior/intercept_messages_pil4dfs.py
  src/tests/ftest/ior/intercept_multi_client.py
Labels: clean-cherry-pick, priority, forced-landing

#14818 DAOS-16265 test: Add debug for common test dir between variants
  src/tests/ftest/launch.py
  src/tests/ftest/util/apricot/apricot/test.py
Labels: forced-landing

#14966 DAOS-15967 control: Raise RAS event if link speed|width is downgraded…
  docs/admin/administration.md
  src/bio/bio_monitor.c
  src/bio/bio_xstream.c
  src/control/events/ras.go
  src/control/server/ctl_firmware_test.go
  src/control/server/ctl_ranks_rpc_test.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/ctl_svc_test.go
  src/control/server/harness.go
  src/control/server/harness_test.go
  src/control/server/instance.go
  src/control/server/instance_drpc_test.go
  src/control/server/instance_exec_test.go
  src/control/server/instance_storage.go
  src/control/server/instance_storage_rpc.go
  src/control/server/instance_storage_rpc_test.go
  src/control/server/instance_storage_test.go
  src/control/server/instance_superblock_test.go
  src/control/server/instance_test.go
  src/control/server/mgmt_pool_test.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/server/mocks.go
  src/control/server/server.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
  src/control/server/util_test.go
  src/include/daos_srv/ras.h
Labels: control-plane, priority, forced-landing, go, usability

#14976 DAOS-16340 cart: Fix order of finalize in cart_ctl (#14969)
  src/utils/ctl/cart_ctl.c
Labels: clean-cherry-pick

#14949 DAOS-15996 test: enhance output of test_daos_rebuild_ec
  src/tests/suite/daos_rebuild_ec.c
Labels: forced-landing

#14948 DAOS-15137 test: enhance output of test_daos_extend_simple
  src/tests/suite/daos_extend_simple.c
Labels: forced-landing

#14988 DAOS-15439 cart: Support free-form provider specification for UCX.
  src/cart/crt_hg.c
  src/cart/crt_hg.h
  src/cart/crt_init.c
Labels: priority

#14978 DAOS-16391 test: ignore rc from run_local diff
  src/tests/ftest/util/launch_utils.py
Labels: forced-landing

#14960 DAOS-16307 client: Defer creating network context in child processes …
  src/client/dfuse/pil4dfs/int_dfs.c
  src/tests/ftest/dfuse/bash.py
Labels: clean-cherry-pick, priority, forced-landing

#15007 DAOS-16391 test: ignore rc from run_local diff (#14978)
  src/tests/ftest/util/launch_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#15002 DAOS-16407 cart: coverity 2555825 fix (#14994)
  src/cart/crt_hg.c
Labels: clean-cherry-pick, forced-landing

#14963 DAOS-16279 test: bump expected WAL replay time (#14833)
  src/tests/ftest/telemetry/wal_metrics.py
Labels: clean-cherry-pick, forced-landing

#14958 DAOS-16097 vos: assign persistent DTX entry in vos_dtx_prepared - b26
  src/dtx/dtx_rpc.c
  src/object/srv_obj.c
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_ilog.c
  src/vos/vos_internal.h
  src/vos/vos_tree.c
Labels: clean-cherry-pick, release-2.6.1

#14993 DAOS-16406 test: file_count_test_base.py - Don't obtain dfuse mount_d…
  src/tests/ftest/util/file_count_test_base.py
Labels: forced-landing

#14982 DAOS-16381 test: Run IOR with HDF5-VOL with multiple object classes (…
  src/tests/ftest/util/file_count_test_base.py
Labels: clean-cherry-pick, forced-landing

#15022 DAOS-16334 test: Fix permission denied removing temporary test files
  src/tests/ftest/control/config_generate_run.py
Labels: forced-landing

#14944 DAOS-16366 test: Use agent/server config files from test directory
  src/tests/ftest/daos_test/dfuse.py
  src/tests/ftest/launch.py
  src/tests/ftest/pool/destroy.py
  src/tests/ftest/recovery/ddb.py
  src/tests/ftest/util/agent_utils.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/collection_utils.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/fault_config_utils.py
  src/tests/ftest/util/file_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/launch_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/systemctl_utils.py
Labels: forced-landing

#14995 DAOS-14348 client: GC for pil4dfs dentry cache
  src/client/dfuse/pil4dfs/dfs_dcache.c
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: release-2.6

#15006 DAOS-16371 il: do not return unsupported for fputs if ioil is loaded …
  src/client/dfuse/il/int_posix.c
  src/tests/suite/dfuse_test.c
Labels: clean-cherry-pick

#14945 DAOS-16245 control: Fix dmg cont set-owner
  src/container/rpc.c
  src/container/rpc.h
  src/container/srv_container.c
  src/container/srv_internal.h
  src/control/cmd/daos/acl.go
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/cont.go
  src/control/cmd/dmg/cont_test.go
  src/control/cmd/dmg/json_test.go
  src/control/common/proto/mgmt/addons.go
  src/control/common/proto/mgmt/cont.pb.go
  src/control/common/proto/mgmt/mgmt.pb.go
  src/control/common/proto/mgmt/mgmt_grpc.pb.go
  src/control/lib/control/cont.go
  src/control/lib/control/cont_test.go
  src/control/server/mgmt_cont.go
  src/control/server/mgmt_cont_test.go
  src/include/daos_srv/container.h
  src/mgmt/cont.pb-c.c
  src/mgmt/cont.pb-c.h
  src/mgmt/srv_container.c
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/tests/mocks.c
  src/mgmt/tests/mocks.h
  src/mgmt/tests/srv_drpc_tests.c
  src/proto/mgmt/cont.proto
  src/proto/mgmt/mgmt.proto
  src/tests/ftest/security/cont_get_acl.yaml
  src/tests/ftest/security/cont_owner.py
  src/tests/ftest/util/cont_security_test_base.py
  src/tests/ftest/util/daos_utils.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: forced-landing

#14991 DAOS-16352 control: Handle cases with static ifaces (#14953)
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/fabric_test.go
  src/control/cmd/daos_agent/infocache.go
  src/control/cmd/daos_agent/infocache_test.go
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
Labels: unclean-cherry-pick, priority, forced-landing, release-2.6.1

#14992 DAOS-16365 client: intercept MPI_Init() to avoid nested call
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: forced-landing

#15029 DAOS-16462 test: remove server manager srv_timeout
  src/tests/ftest/aggregation/dfuse_space_check.yaml
  src/tests/ftest/dfuse/sparse_file.yaml
  src/tests/ftest/osa/offline_drain.yaml
  src/tests/ftest/osa/offline_parallel_test.yaml
  src/tests/ftest/osa/online_drain.yaml
  src/tests/ftest/util/yaml_utils.py
Labels: forced-landing

#15030 DAOS-16463 test: remove get_host_log_files
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/server_utils.py
Labels: forced-landing

#15031 DAOS-16457 test: remove display_memory_info
  src/tests/ftest/util/server_utils.py
Labels: forced-landing

#15032 DAOS-16334 test: Fix permission denied removing temporary test files (#15022)
  src/tests/ftest/control/config_generate_run.py
Labels: clean-cherry-pick, forced-landing

#15040 DAOS-16463 test: remove get_host_log_files (#15030)
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/server_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#15023 DAOS-16406 test: file_count_test_base.py - Don't obtain dfuse mount_d…
  src/tests/ftest/util/file_count_test_base.py
Labels: clean-cherry-pick, forced-landing

#15033 DAOS-16366 test: Use agent/server config files from test directory (#14944)
  src/tests/ftest/daos_test/dfuse.py
  src/tests/ftest/launch.py
  src/tests/ftest/pool/destroy.py
  src/tests/ftest/recovery/ddb.py
  src/tests/ftest/util/agent_utils.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/collection_utils.py
  src/tests/ftest/util/command_utils.py
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/fault_config_utils.py
  src/tests/ftest/util/file_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/launch_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/systemctl_utils.py
Labels: clean-cherry-pick, forced-landing

#15041 DAOS-16462 test: remove server manager srv_timeout (#15029)
  src/tests/ftest/aggregation/dfuse_space_check.yaml
  src/tests/ftest/dfuse/sparse_file.yaml
  src/tests/ftest/osa/offline_drain.yaml
  src/tests/ftest/osa/offline_parallel_test.yaml
  src/tests/ftest/osa/online_drain.yaml
  src/tests/ftest/util/yaml_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#15049 DAOS-16484 test: Exclude local host in default interface selection
  src/tests/ftest/util/environment_utils.py
Labels: forced-landing

#15039 DAOS-16315 mercury: update to 2.4.0rc5 (#15015)
  utils/build.config
Labels: clean-cherry-pick

#15051 DAOS-16484 test: Exclude local host in default interface selection (#…
  src/tests/ftest/util/environment_utils.py
Labels: clean-cherry-pick, forced-landing
