Repository daos-stack/daos, pull requests merged in 2024-02, with the labels that each got.

#13697 DAOS-15069 dfs: use memcpy instead of snprintf for readdir (#13654)
  src/client/dfs/dfs.c
Labels: clean-cherry-pick

#13701 DAOS-14320 test: remove offline_rebuild_agg test
  src/tests/ftest/erasurecode/offline_rebuild_aggregation.py
Labels: clean-cherry-pick

#13712 DAOS-14626 control: Log failed to take lock msg to notice rather than…
  src/control/system/raft/database.go
Labels: control-plane

#13711 DAOS-9572 control: Indicate list-pools only shows NVMe
  src/control/cmd/dmg/pretty/storage.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/cmd/dmg/storage_query.go
Labels: control-plane

#13665 DAOS-14843 control: Remove user facing info about accel cfg opts (#13…
  src/control/server/config/server_test.go
  utils/config/daos_server.yml
Labels: control-plane, clean-cherry-pick, approved-to-merge

#13554 DAOS-14828 test: Utilizing pool percentage for nvme/fault.py
  src/tests/ftest/nvme/fault.py
  src/tests/ftest/nvme/fault.yaml
Labels: forced-landing

#13219 DAOS-14542 test: replace check_container_info with verify_query
  src/tests/ftest/ior/crash.py
  src/tests/ftest/util/container_rf_test_base.py
  src/tests/ftest/util/rebuild_test_base.py
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#13496 DAOS-14727 pool: Clean orphaned NVMe blobs on create (#13455)
  src/mgmt/srv_target.c
Labels: clean-cherry-pick, priority, approved-to-merge

#13659 DAOS-15055 tools: Add build host/time to JSON version (#13644)
  src/control/SConscript
  src/control/build/string.go
  src/control/build/variables.go
Labels: clean-cherry-pick, priority, approved-to-merge

#13683 DAOS-15031 test: launch.py: exit early if extra yaml is not a file (#…
  src/tests/ftest/launch.py
Labels: clean-cherry-pick, priority

#13684 DAOS-15047 test: harden regex for engine started (#13636)
  src/tests/ftest/util/server_utils_base.py
Labels: clean-cherry-pick, priority, forced-landing

#13685 DAOS-14103 test: remove performance_test_base subprocess (#13601)
  src/tests/ftest/performance/ior_easy.py
  src/tests/ftest/performance/mdtest_easy.py
  src/tests/ftest/rebuild/widely_striped.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/performance_test_base.py
Labels: unclean-cherry-pick, priority

#13571 DAOS-14557 object: collectively query key
  src/dtx/dtx_coll.c
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/include/daos_srv/dtx_srv.h
  src/object/SConscript
  src/object/cli_coll.c
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_ec.h
  src/object/obj_internal.h
  src/object/obj_rpc.c
  src/object/obj_rpc.h
  src/object/obj_tx.c
  src/object/obj_utils.c
  src/object/srv_coll.c
  src/object/srv_internal.h
  src/object/srv_mod.c
  src/object/srv_obj.c
  src/object/srv_obj_remote.c
  src/tests/ftest/util/telemetry_utils.py
  src/tests/suite/daos_obj.c
Labels: priority

#13682 DAOS-14903 container: refine task process in pmap_refresh_cb (#13491)
  src/container/cli.c
  src/include/daos/tse.h
  src/object/obj_tx.c
  src/object/srv_ec_aggregate.c
  src/pool/cli.c
  src/tests/ftest/erasurecode/multiple_failure.yaml
Labels: clean-cherry-pick, priority

#13695 DAOS-15073 pool: avoid deadlock when put last ref on stopped pool
  src/include/daos/lru.h
  src/pool/srv_target.c
  src/vos/vos_obj.h
  src/vos/vos_obj_cache.c
Labels: clean-cherry-pick, release-2.4

#13641 DAOS-14972 pool: Only allow UPIN engine as PS replicas (#13593)
  src/pool/srv_util.c
Labels: release-2.4

#13731 DAOS-623 test: Properly wait for log compression in NLT. (#13726)
  utils/node_local_test.py
Labels: unclean-cherry-pick

#13676 DAOS-14909 test: unit tests for new pool properties
  src/control/lib/daos/pool_property_test.go
Labels: forced-landing

#13716 DAOS-15050 dtx: replace D_INFO with D_DEBUG for debug message (#13643)
  src/dtx/dtx_common.c
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
Labels: clean-cherry-pick, release-2.4

#13754 DAOS-623 ci: Use owners teams for CODEOWNERS (#13721)
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: unclean-cherry-pick

#13747 DAOS-9572 control: Indicate list-pools only shows NVMe (#13711)
  src/control/cmd/dmg/pretty/storage.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/cmd/dmg/storage_query.go
Labels: clean-cherry-pick, priority, approved-to-merge

#13748 DAOS-14626 control: Log failed to take lock msg to notice rather than…
  src/control/system/raft/database.go
Labels: clean-cherry-pick, priority, approved-to-merge

#13735 DAOS-15096 client: poke the scheduler on eq destroy (#13706)
  src/client/api/event.c
Labels: clean-cherry-pick

#13707 DAOS-10942 utils: chmod should ignore unsupported bits (#12949)
  src/control/cmd/daos/filesystem.go
  src/utils/daos_hdlr.c
  src/utils/daos_hdlr.h
Labels: unclean-cherry-pick, priority, forced-landing

#13760 DAOS-15002 test: only kill 2 ranks if we have 2n+1 total
  src/tests/ftest/erasurecode/rebuild_disabled.py
  src/tests/ftest/erasurecode/rebuild_disabled_single.py
Labels: priority, forced-landing

#13758 DAOS-15055 build: Ignore BuildTime in rebuild calculation
  src/control/SConscript
Labels: priority

#13795 DAOS-15206 build: Tag 2.4.2 rc2
  TAG
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#13729 DAOS-10942 utils: use errors.Errorf in go
  src/control/cmd/daos/filesystem.go
Labels: priority

#13800 DAOS-14505 test: enable scrubber in soak
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress.yaml
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#13720 DAOS-15111 cq: update GHA versions
  .github/workflows/ci2.yml
  .github/workflows/clang-format.yml
  .github/workflows/create_release.yml
  .github/workflows/doxygen.yml
  .github/workflows/flake.yml
  .github/workflows/landing-builds.yml
  .github/workflows/linting.yml
  .github/workflows/pr-metadata.yml
  .github/workflows/pylint.yml
  .github/workflows/rpm-build-and-test.yml
  .github/workflows/spelling.yml
  .github/workflows/version-checks.yml
  .github/workflows/yaml.yml
Labels: forced-landing

#13774 DAOS-15163 test: Remove test_array_obj
  src/tests/ftest/object/array.py
  src/tests/ftest/object/array.yaml
Labels: forced-landing

#13615 DAOS-623 build: Various build improvements
  Jenkinsfile
  utils/githooks/find_base.sh
  utils/rpms/packaging/Dockerfile.mockbuild
  utils/rpms/packaging/Makefile_packaging.mk
  utils/rpms/packaging/ccache-stats.patch
  utils/rpms/packaging/get_release_branch
  utils/rpms/packaging/rpm_chrootbuild
Labels: forced-landing

#13819 DAOS-15202 test: Avoid using virtual NVMe in VM test
  src/tests/ftest/control/daos_system_query.yaml
  utils/githooks/find_base.sh
Labels: forced-landing

#13814 DAOS-15225 cq: update yamllint to 1.35.0
  utils/cq/requirements.txt
Labels: forced-landing

#13328 DAOS-14633 doc: fix troubleshooting for daos_agent Failed connect
  docs/admin/troubleshooting.md
Labels: forced-landing

#13638 DAOS-15045 vos: check tls before accessing
  src/mgmt/srv_target.c
Labels: clean-cherry-pick

#13811 DAOS-15085 container: increase capa ULT stack size
  src/container/container_iv.c
Labels: clean-cherry-pick, release-2.4

#13844 DAOS-14456 test: soak - Increase lammps job timeout
  src/tests/ftest/soak/stress.yaml
Labels: forced-landing

#13820 DAOS-15111 cq: fix thollander/actions-comment-pull-request
  .github/workflows/pr-metadata.yml
Labels: forced-landing

#13803 DAOS-15135 object: handle non-continuous ranks array for coll operation
  src/object/cli_coll.c
  src/object/cli_obj.c
Labels: forced-landing

#13853 DAOS-15245 vos: do not ignore failure for DTX commit-on-share
  src/vos/vos_io.c
  src/vos/vos_obj.c
Labels: release-2.4

#13325 DAOS-13936 support: Collect the specific logs and Time range log for support
  src/control/cmd/daos_agent/support.go
  src/control/cmd/daos_server/support.go
  src/control/cmd/dmg/support.go
  src/control/common/proto/ctl/support.pb.go
  src/control/lib/control/support.go
  src/control/lib/support/README.md
  src/control/lib/support/log.go
  src/control/lib/support/log_test.go
  src/control/logging/debug.go
  src/control/logging/logging_test.go
  src/control/server/ctl_support_rpc.go
  src/proto/ctl/support.proto
  src/tests/ftest/control/dmg_support_collect_log.yaml
Labels: forced-landing

#13826 DAOS-15235 test: tag tests with class name
  src/tests/ftest/container/api_basic_attribute.py
  src/tests/ftest/container/auto_oc_selection.py
  src/tests/ftest/container/boundary.py
  src/tests/ftest/container/destroy.py
  src/tests/ftest/container/fill_destroy_loop.py
  src/tests/ftest/container/open.py
  src/tests/ftest/container/query_properties.py
  src/tests/ftest/control/daos_server_support_collect_log.py
  src/tests/ftest/control/dmg_nvme_scan_test.py
  src/tests/ftest/control/super_block_versioning.py
  src/tests/ftest/datamover/large_dir.py
  src/tests/ftest/datamover/obj_small.py
  src/tests/ftest/datamover/posix_subsets.py
  src/tests/ftest/dfuse/container_type.py
  src/tests/ftest/dfuse/find.py
  src/tests/ftest/fault_domain/fault_domain.py
  src/tests/ftest/interoperability/down_grade.py
  src/tests/ftest/interoperability/updown_grade.py
  src/tests/ftest/nvme/fault.py
  src/tests/ftest/object/create_many_dkeys.py
  src/tests/ftest/pool/bad_connect.py
  src/tests/ftest/pool/bad_query.py
  src/tests/ftest/pool/label.py
  src/tests/ftest/pool/list_pools.py
  src/tests/ftest/pool/list_verbose.py
  src/tests/ftest/pool/management_race.py
  src/tests/ftest/pool/pda.py
  src/tests/ftest/pool/permission.py
  src/tests/ftest/pool/query_attribute.py
  src/tests/ftest/pool/target_query.py
  src/tests/ftest/pool/uuid_corner_case.py
  src/tests/ftest/security/pool_connect_init.py
  src/tests/ftest/server/dynamic_start_stop.py
  src/tests/ftest/server/metadata.py
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/soak/faults.py
  src/tests/ftest/soak/smoke.py
  src/tests/ftest/tags.py
  src/tests/ftest/telemetry/dkey_akey_enum_punch.py
Labels: forced-landing

#13796 DAOS-15207 control: Use tab char separator when generating system cmd results
  src/control/cmd/dmg/pretty/printers.go
  src/control/cmd/dmg/pretty/system.go
  src/control/cmd/dmg/pretty/system_test.go
  src/control/cmd/dmg/system_test.go
  src/control/server/mgmt_system.go
  src/control/system/membership.go
  src/control/system/rankgroups.go
  src/control/system/rankgroups_test.go
Labels: bug, control-plane

#13900 DAOS-15207 control: Fix codespell issue
  src/control/cmd/dmg/pretty/system_test.go
Labels: forced-landing
