Repository daos-stack/daos, pull requests merged in 2024-07, with the labels that each got.

#14639 DAOS-16078 common: fix Coverity issue (release/2.6)
  src/common/btree.c
Labels: priority, release-2.6

#14602 DAOS-16039 object: fix EC aggregation wrong peer address
  src/container/srv_target.c
  src/include/daos/common.h
  src/object/srv_ec_aggregate.c
  src/tests/suite/daos_obj_ec.c
Labels: clean-cherry-pick, forced-landing

#14656 DAOS-16103 test: Increase test_ms_failover test timeout
  src/tests/ftest/control/ms_failover.yaml
Labels: forced-landing

#14677 DAOS-16103 test: Increase test_ms_failover test timeout (#14656)
  src/tests/ftest/control/ms_failover.yaml
Labels: clean-cherry-pick, forced-landing

#14638 DAOS-16101 mgmt: enhanced interoperability for MGMT module
  src/mgmt/cli_debug.c
  src/mgmt/cli_mgmt.c
  src/mgmt/cli_query.c
  src/mgmt/rpc.c
  src/mgmt/rpc.h
  src/mgmt/srv.c
Labels: priority, forced-landing, release-2.6

#14649 DAOS-16009 rebuild: fix O_TRUNC file size related handling
  src/client/array/dc_array.c
  src/common/pool_map.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/object/srv_obj_migrate.c
Labels: forced-landing

#14673 DAOS-16009 rebuild: fix O_TRUNC file size related handling
  src/client/array/dc_array.c
  src/common/pool_map.c
  src/object/srv_ec_aggregate.c
  src/object/srv_obj.c
  src/object/srv_obj_migrate.c
Labels: clean-cherry-pick

#14678 DAOS-16101 mgmt: enhanced interoperability for MGMT module (#14638)
  src/mgmt/cli_debug.c
  src/mgmt/cli_mgmt.c
  src/mgmt/cli_query.c
  src/mgmt/rpc.c
  src/mgmt/rpc.h
  src/mgmt/srv.c
Labels: clean-cherry-pick, priority

#14667 DAOS-15930 test: extend_simple add FI required macro call
  src/tests/suite/daos_extend_simple.c
Labels: forced-landing

#14695 DAOS-623 test: update suppressions for NLT
  src/cart/utils/memcheck-cart.supp
Labels: forced-landing

#14694 DAOS-623 test: update suppressions for NLT
  src/cart/utils/memcheck-cart.supp
Labels: forced-landing

#14698 DAOS-16152 build: Tag 2.6.0 rc2
  TAG
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#14684 DAOS-16134 cq: update pylint to 3.2.5
  utils/cq/requirements.txt
Labels: forced-landing

#14590 DAOS-16040 test: Agent failure Aurora support - Use EC object class
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/agent_failure.yaml
Labels: forced-landing

#14703 DAOS-16161 object: should bulk GET for ds_obj_ec_rep_handler
  src/object/srv_obj.c
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/daos_obj_ec.c
Labels: forced-landing

#14616 DAOS-16076 test: Automate dmg scale test to be run on Aurora
  src/tests/ftest/control/dmg_scale.py
  src/tests/ftest/control/dmg_scale.yaml
Labels: forced-landing

#14737 DAOS-16070 tools: Include BuildInfo field in version output
  src/control/SConscript
  src/control/build/string.go
  src/control/build/variables.go
  src/control/cmd/daos/main.go
  src/control/cmd/daos/util.go
  src/control/cmd/daos_agent/attachinfo.go
  src/control/cmd/daos_agent/main.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/main.go
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/addons.go
  src/control/common/proto/mgmt/svc.pb.go
  src/control/lib/control/network.go
  src/control/server/mgmt_system.go
  src/include/daos_mgmt.h
  src/mgmt/cli_mgmt.c
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/proto/mgmt/svc.proto
Labels: priority

#14704 DAOS-16078 common: fix a Coverity issue
  src/common/btree.c
Labels: priority

#14749 Revert "DAOS-16153 nlt: set server nlt tmpfs size to 8g"
  utils/nlt_server.yaml
Labels: priority

#14732 DAOS-16204 test: remove sudo requirements from io_sys_admin.py
  src/tests/ftest/deployment/io_sys_admin.py
  src/tests/ftest/deployment/io_sys_admin.yaml
Labels: forced-landing

#14717 DAOS-16168 build: Ignore scons version deprecation (#14715)
  SConstruct
Labels: clean-cherry-pick

#14762 DAOS-16228 test: update suppressions for NLT again
  src/cart/utils/memcheck-cart.supp
Labels: forced-landing

#14753 DAOS-16037 pool: Fix upgrade for svc_ops
  src/pool/srv_pool.c
Labels: forced-landing

#14768 DAOS-16159 control: Accept UCX full transport names
  src/control/lib/hardware/cart/cart_test.go
  src/control/lib/hardware/cart/ucx.go
  src/control/lib/hardware/cart/ucx_test.go
Labels: forced-landing

#14769 DAOS-16210 vos: Interoperability fix for flat dkey
  src/vos/vos_internal.h
  src/vos/vos_obj.c
  src/vos/vos_tree.c
Labels: forced-landing

#14756 DAOS-14311 pool: add pool warmup RPC + bulk on connect (#14669)
  src/cart/crt_group.c
  src/client/api/init.c
  src/pool/cli.c
  src/pool/rpc.c
  src/pool/rpc.h
  src/pool/srv_internal.h
  src/pool/srv_target.c
Labels: clean-cherry-pick

#14628 DAOS-15825 control: Add NUMA/fabric map to GetAttachInfo payload
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/fabric_test.go
  src/control/cmd/daos_agent/infocache.go
  src/control/cmd/daos_agent/infocache_test.go
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/common/proto/mgmt/svc.pb.go
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/proto/mgmt/svc.proto
Labels: forced-landing

#14734 DAOS-16170 dtx: handle ds_pool_lookup failure when DTX resync
  src/dtx/dtx_resync.c
Labels: forced-landing

#14764 DAOS-15064 mgmt: Show all ranks in daos system query
  src/control/cmd/daos/system.go
  src/include/daos_types.h
  src/mgmt/cli_mgmt.c
  src/tests/ftest/control/daos_system_query.py
  src/tests/ftest/control/daos_system_query.yaml
  src/tests/suite/daos_mgmt.c
Labels: forced-landing

#14781 DAOS-16103 control: Avoid deadlock during leadership change
  src/control/server/mgmt_pool.go
Labels: forced-landing

#14801 DAOS-16261 cq: update pylint to 3.2.6
  utils/cq/requirements.txt
Labels: forced-landing

#14803 DAOS-16263 cq: merge yamllint and clang-format into linting
  .github/workflows/clang-format.yml
  .github/workflows/linting.yml
  .github/workflows/yaml.yml
Labels: forced-landing

#14800 DAOS-13078 test: update ior_per_rank.py to work in CI
  src/tests/ftest/deployment/ior_per_rank.py
  src/tests/ftest/deployment/ior_per_rank.yaml
Labels: forced-landing

#14498 DAOS-15953 test: update online_drain to use config values
  src/tests/ftest/osa/online_drain.py
  src/tests/ftest/osa/online_drain.yaml
Labels: forced-landing

#14796 DAOS-15613 test: build current SHA in daos_build.py
  src/tests/ftest/dfuse/daos_build.py
Labels: forced-landing

#14802 DAOS-15778 test: remove DataMoverTestBase.posix_local_test_paths
  src/tests/ftest/datamover/negative.py
  src/tests/ftest/util/data_mover_test_base.py
Labels: forced-landing

#14795 DAOS-16234 test: add a 10 ms sleep in the dfs time test
  src/tests/suite/dfs_unit_test.c
Labels: clean-cherry-pick

#14700 DAOS-15946 control: Checker enablement misc fixes
  src/control/server/mgmt_check.go
Labels: control-plane, CR

#14823 DAOS-16238 utils: Add valgrind suppressions for Go runtime
  src/cart/utils/memcheck-cart.supp
Labels: forced-landing

#14736 DAOS-16082 test: Repeatedly query device after SysXS device is set to…
  src/tests/ftest/control/dmg_storage_query.py
Labels: forced-landing

#14824 DAOS-16237 control: Add OID to filesystem get-attr (#14774)
  src/client/dfs/obj.c
  src/control/cmd/daos/filesystem.go
  src/control/cmd/daos/object.go
  src/include/daos_fs.h
  src/tests/ftest/util/daos_utils.py
  utils/node_local_test.py
Labels: clean-cherry-pick

#14748 DAOS-16217 test: Update run_local().
  src/tests/ftest/dfuse/pil4dfs_fio.py
  src/tests/ftest/harness/core_files.py
  src/tests/ftest/harness/unit.py
  src/tests/ftest/process_core_files.py
  src/tests/ftest/server/multiengine_persocket.py
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/util/agent_utils.py
  src/tests/ftest/util/collection_utils.py
  src/tests/ftest/util/dfuse_utils.py
  src/tests/ftest/util/fio_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/io_utilities.py
  src/tests/ftest/util/launch_utils.py
  src/tests/ftest/util/package_utils.py
  src/tests/ftest/util/run_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/slurm_utils.py
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/user_utils.py
  src/tests/ftest/verify_perms.py
Labels: forced-landing

#14830 DAOS-16103 control: Avoid deadlock during leadership change (#14781)
  src/control/server/mgmt_pool.go
Labels: clean-cherry-pick, priority, forced-landing, release-2.6.1

#14798 DAOS-16008 cart: cart_ctl fixes (#14686)
  src/cart/utils/crt_utils.c
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/cart_ctl_utils.py
  src/utils/ctl/cart_ctl.c
Labels: unclean-cherry-pick, forced-landing

#14636 DAOS-15956 control: Limit race between taking leadership and join (#1…
  src/control/server/mgmt_svc.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/system/errors.go
  src/control/system/errors_test.go
  src/control/system/raft/database.go
  src/control/system/raft/mocks.go
  src/control/system/raft/raft.go
  src/control/system/raft/raft_test.go
Labels: clean-cherry-pick, priority, release-2.6.1

#14839 DAOS-16223 control: Config generate to not output auto values (#14778)
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/dmg/auto_test.go
  src/control/lib/control/auto.go
  src/control/lib/control/auto_test.go
  src/control/server/config/server_test.go
  src/tests/ftest/control/config_generate_output.py
Labels: control-plane, clean-cherry-pick, forced-landing

#14842 DAOS-16159 control: Accept UCX full transport names (#14768)
  src/control/lib/hardware/cart/cart_test.go
  src/control/lib/hardware/cart/ucx.go
  src/control/lib/hardware/cart/ucx_test.go
Labels: clean-cherry-pick, priority, forced-landing, release-2.6.1

#14851 DAOS-16228 test: update suppressions for NLT again (#14762)
  src/cart/utils/memcheck-cart.supp
Labels: clean-cherry-pick, forced-landing

#14791 DAOS-15825 control: Improve GetAttachInfo NUMA fabric map
  src/control/cmd/daos_agent/fabric.go
  src/control/cmd/daos_agent/fabric_test.go
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/common/proto/mgmt/svc.pb.go
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/proto/mgmt/svc.proto
Labels: forced-landing

#14846 DAOS-16226 cart: URI_LOOKUP rpc to inherit the original RPC timeout
  src/cart/crt_rpc.c
Labels: clean-cherry-pick, priority, forced-landing
