Repository daos-stack/daos, pull requests merged in 2024-01, with the labels that each got.

#13508 DAOS-14443 pool: Fix pool create performance (#13003)
  src/common/rsvc.c
  src/gurt/misc.c
  src/include/gurt/common.h
  src/pool/rpc.h
  src/pool/srv_pool.c
  src/rsvc/srv.c
Labels: unclean-cherry-pick

#13385 DAOS-14181 control: Remove bdev scan cache
  src/control/cmd/dmg/pretty/storage_nvme.go
  src/control/cmd/dmg/pretty/storage_nvme_test.go
  src/control/common/proto/mocks.go
  src/control/common/proto/types_test.go
  src/control/lib/control/mocks.go
  src/control/lib/control/pool.go
  src/control/lib/control/storage.go
  src/control/server/ctl_ranks_rpc.go
  src/control/server/ctl_storage.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/ctl_svc_test.go
  src/control/server/harness.go
  src/control/server/instance.go
  src/control/server/instance_drpc.go
  src/control/server/instance_storage.go
  src/control/server/instance_storage_rpc.go
  src/control/server/instance_storage_rpc_test.go
  src/control/server/instance_test.go
  src/control/server/server.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
  src/control/server/storage/bdev/backend_vmd.go
  src/control/server/storage/bdev/backend_vmd_test.go
  src/control/server/storage/bdev_test.go
  src/control/server/storage/mocks.go
  src/control/server/storage/provider.go
  src/control/server/storage/provider_test.go
  src/control/server/util_test.go
  src/mgmt/srv_query.c
Labels: control-plane

#13146 DAOS-14480 test: Extend Python code to support UCX with ud_x.
  Jenkinsfile
  src/tests/ftest/util/network_utils.py
Labels: forced-landing

#13568 DAOS-14480 test: Extend Python code to support UCX with ud_x
  Jenkinsfile
  src/tests/ftest/util/network_utils.py
Labels: forced-landing

#13547 DAOS-14352 object: recover migrate with correct epoch
  src/object/srv_obj_migrate.c
  src/tests/suite/daos_rebuild_ec.c
Labels: priority

#13494 DAOS-330 pool: Consider FDs in PS placement
  src/pool/srv_internal.h
  src/pool/srv_pool.c
  src/pool/srv_util.c
  src/rdb/rdb_raft.c
  src/tests/ftest/daos_test/rebuild.yaml
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/daos_rebuild.c
  src/tests/suite/daos_test.h
  src/tests/suite/daos_test_common.c
Labels: forced-landing

#13346 DAOS-14654 test: simplify ior_per_rank.py
  src/tests/ftest/deployment/ior_per_rank.py
  src/tests/ftest/deployment/ior_per_rank.yaml
Labels: forced-landing

#13464 DAOS-14735 test: simplify write_hostfile
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/nvme/pool_exclude.py
  src/tests/ftest/nvme/pool_extend.py
  src/tests/ftest/osa/offline_drain.py
  src/tests/ftest/osa/offline_reintegration.py
  src/tests/ftest/osa/online_drain.py
  src/tests/ftest/osa/online_extend.py
  src/tests/ftest/osa/online_parallel_test.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/util/write_host_file.py
Labels: forced-landing

#13559 DAOS-14843 control: Remove user facing info about accel cfg opts
  src/control/server/config/server_test.go
  utils/config/daos_server.yml
Labels: control-plane, forced-landing

#13594 DAOS-14852 test: Fix JSON key lookup in NVMe space usage query
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/pool_create_all_base.py
Labels: bug

#13591 DAOS-14966 cart: Fix incorrect opc logging
  src/cart/crt_rpc.c
Labels: forced-landing

#13600 DAOS-14965 tests: using correct rd_fac in online_rebuild_single
  src/tests/ftest/erasurecode/online_rebuild_single.yaml
Labels: forced-landing

#13608 DAOS-14440 build: Update distro versions in GHA
  .github/workflows/rpm-build-and-test.yml
  ci/functional/test_main.sh
Labels: priority, forced-landing

#13551 DAOS-14831 test: use scm and nvme for ior/hard_rebuild
  src/tests/ftest/ior/hard_rebuild.yaml
Labels: forced-landing

#13560 DAOS-14718 test: Fix reading of DAOS_TEST_INSECURE_MODE envar (#13441)
  src/tests/ftest/control/config_generate_run.yaml
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/environment_utils.py
Labels: clean-cherry-pick, priority

#13619 DAOS-13252 tests: set svcn for multiple_failure test
  src/tests/ftest/erasurecode/multiple_failure.yaml
Labels: forced-landing

#13622 DAOS-14981 gurt: restore d_getenv_int undefined symbol
  src/gurt/misc.c
  src/include/gurt/common.h
Labels: forced-landing

#13576 DAOS-14886 test: Add default nvme arg for UCX provider stage
  Jenkinsfile
Labels: forced-landing

#13578 DAOS-13584 tests: limit pool query test time (#12451)
  src/tests/suite/daos_md_replication.c
Labels: clean-cherry-pick, forced-landing

#13180 DAOS-14443 rdb: Improve rdb_campaign error
  src/rdb/rdb.c
  src/rdb/rdb_raft.c
Labels: forced-landing

#13516 DAOS-13560 common: Optimize single child B+Tree
  src/common/btree.c
  src/common/tests/btree.c
  src/common/tests/btree.sh
  src/common/tests/btree_direct.c
  src/include/daos/btree.h
  src/include/daos_srv/vos_types.h
  src/vos/vos_layout.h
  src/vos/vos_tree.c
  utils/utest.yaml
Labels: forced-landing

#13463 DAOS-13228 control: List BDEV role assignments in scan/format display
  src/bio/bio_device.c
  src/bio/smd.pb-c.c
  src/bio/smd.pb-c.h
  src/control/cmd/dmg/pretty/storage.go
  src/control/cmd/dmg/pretty/storage_nvme.go
  src/control/cmd/dmg/pretty/storage_nvme_test.go
  src/control/cmd/dmg/pretty/storage_scm.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/cmd/dmg/storage.go
  src/control/cmd/dmg/storage_test.go
  src/control/common/proto/ctl/smd.pb.go
  src/control/common/proto/ctl/storage_nvme.pb.go
  src/control/lib/control/auto_test.go
  src/control/lib/control/mocks.go
  src/control/lib/control/storage.go
  src/control/lib/spdk/nvme.go
  src/control/lib/spdk/nvme_default.go
  src/control/lib/spdk/src/nvme_control_common.c
  src/control/server/ctl_storage.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/harness.go
  src/control/server/instance.go
  src/control/server/instance_storage.go
  src/control/server/instance_storage_rpc.go
  src/control/server/instance_storage_rpc_test.go
  src/control/server/instance_superblock.go
  src/control/server/instance_test.go
  src/control/server/storage/bdev.go
  src/control/server/storage/config.go
  src/control/server/storage/config_test.go
  src/control/server/storage/provider.go
  src/mgmt/smd.pb-c.c
  src/mgmt/smd.pb-c.h
  src/mgmt/srv_query.c
  src/proto/ctl/smd.proto
  src/proto/ctl/storage_nvme.proto
  src/tests/ftest/control/dmg_storage_query.py
Labels: control-plane, meta-on-ssd

#13602 DAOS-14976 object: properly select collective punch leader for resend
  src/object/cli_obj.c
Labels: forced-landing

#13580 DAOS-14856 packaging: Move ld.so.conf.d file…
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#13647 DAOS-14781 test: expect more containers before rdb nospace
  src/tests/ftest/server/metadata.py
  src/tests/ftest/server/metadata.yaml
Labels: forced-landing

#13650 DAOS-14654 test: simplify ior_per_rank.py (#13346)
  src/tests/ftest/deployment/ior_per_rank.py
  src/tests/ftest/deployment/ior_per_rank.yaml
Labels: clean-cherry-pick, priority

#13546 DAOS-14793 control: Fail if VMD has no backing storage (#13503)
  src/control/server/server_utils_test.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
  src/control/server/storage/bdev/firmware.go
  src/control/server/storage/bdev/firmware_test.go
  src/control/server/storage/faults.go
Labels: control-plane, clean-cherry-pick, forced-landing

#13169 DAOS-14225 control: Ignore duplicate call to SetRank
  docs/admin/deployment.md
  src/control/cmd/daos/main.go
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/daos_server/main.go
  src/control/server/instance.go
  src/tests/ftest/pool/create_capacity.py
  src/tests/ftest/pool/create_capacity.yaml
  src/tests/ftest/util/test_utils_pool.py
Labels: bug, control-plane

#13614 DAOS-14985 bio: Handle NVMe unplugged in list devs
  src/bio/bio_device.c
  src/control/common/proto/ctl/addons.go
  src/control/server/ctl_smd_rpc_test.go
  src/control/server/instance_storage_rpc.go
  src/control/server/instance_storage_rpc_test.go
  src/mgmt/srv_drpc.c
  src/mgmt/srv_query.c
Labels: bug, forced-landing, hotplug

#13652 DAOS-14831 test: use scm and nvme for ior/hard_rebuild (#13551)
  src/tests/ftest/ior/hard_rebuild.yaml
Labels: clean-cherry-pick, priority

#13651 DAOS-14735 test: simplify write_hostfile (#13464)
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/nvme/pool_exclude.py
  src/tests/ftest/nvme/pool_extend.py
  src/tests/ftest/osa/offline_drain.py
  src/tests/ftest/osa/offline_reintegration.py
  src/tests/ftest/osa/online_drain.py
  src/tests/ftest/osa/online_extend.py
  src/tests/ftest/osa/online_parallel_test.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/util/write_host_file.py
Labels: clean-cherry-pick, priority, forced-landing

#13433 DAOS-14650 test: replace mpirun bind-to and map-by with args (#13392)
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/performance/ior_easy.yaml
  src/tests/ftest/performance/ior_hard.yaml
  src/tests/ftest/performance/mdtest_easy.yaml
  src/tests/ftest/performance/mdtest_hard.yaml
  src/tests/ftest/telemetry/pool_space_metrics.yaml
  src/tests/ftest/util/data_mover_utils.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/mdtest_test_base.py
Labels: unclean-cherry-pick, priority, forced-landing

#13475 DAOS-12425 control: Add opt to auto-format on server start-up (#13074)
  src/control/cmd/daos_server/start.go
  src/control/server/config/server.go
  src/control/server/server.go
Labels: clean-cherry-pick, priority

#13636 DAOS-15047 test: harden regex for engine started
  src/tests/ftest/util/server_utils_base.py
Labels: forced-landing

#13445 DAOS-14541 test: remove redundant write_objects_wo_failon (#13218)
  src/tests/ftest/container/fill_destroy_loop.py
  src/tests/ftest/control/dmg_system_cleanup.py
  src/tests/ftest/pool/evict.py
  src/tests/ftest/rebuild/container_create_race.py
  src/tests/ftest/util/container_rf_test_base.py
  src/tests/ftest/util/test_utils_container.py
  src/tests/ftest/util/test_utils_pool.py
Labels: unclean-cherry-pick, priority

#13646 DAOS-14474,14219,14476,15049 dfs: dfs bug fixes
  src/client/dfs/dfs.c
  src/client/dfs/duns.c
  src/control/cmd/daos/filesystem.go
  src/tests/suite/dfs_unit_test.c
  utils/node_local_test.py
Labels: unclean-cherry-pick

#13532 DAOS-14826 client: reserve low fds
  src/client/dfuse/pil4dfs/int_dfs.c
  src/tests/ftest/daos_test/dfuse.py
  src/tests/suite/dfuse_test.c
Labels: forced-landing

#13672 DAOS-14985 test: Address unit test failure due to merge
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/instance_storage_rpc.go
  src/control/server/instance_storage_rpc_test.go
Labels: bug, control-plane

#13653 DAOS-14594 test: fix dfs_parallel xml generation (#13312)
  src/tests/suite/dfs_test.c
Labels: unclean-cherry-pick, priority, forced-landing

#13630 DAOS-15038 test: Parsing NVMe controller details from SMD info JSON is failing
  src/common/tests_dmg_helpers.c
  src/tests/suite/daos_nvme_recovery.c
Labels: bug, forced-landing

#13598 DAOS-12209 pool: force destroy ignore evict errors
  src/control/server/ctl_smd_rpc_test.go
  src/control/server/mgmt_cont_test.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
Labels: release-2.4, priority, forced-landing

#13668 DAOS-14837 container: don't pause EC aggregation (#13539)
  src/container/srv_container.c
  src/container/srv_target.c
  src/object/srv_ec_aggregate.c
Labels: clean-cherry-pick, forced-landing

#13490 DAOS-14635 control: Remove agent default log path
  src/control/cmd/daos_agent/config.go
  src/control/cmd/daos_agent/config_test.go
  src/control/cmd/daos_agent/main.go
  src/control/cmd/daos_server/start.go
  src/control/common/cmdutil/logging.go
Labels: control-plane

#13605 DAOS-14550 control: Prevent SPDK calls if disable_hugepages true in cfg
  src/control/cmd/dmg/pretty/storage.go
  src/control/cmd/dmg/pretty/storage_nvme.go
  src/control/cmd/dmg/pretty/storage_scm.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/fault/code/codes.go
  src/control/server/config/faults.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/faults.go
  src/control/server/instance_storage_rpc.go
  src/control/server/instance_storage_rpc_test.go
  src/control/server/server_utils.go
Labels: control-plane

#13673 Revert "DAOS-14969 test: Increase crt_timeout for test_daos_oid_allocator"
  src/tests/ftest/daos_test/suite.yaml
  src/tests/ftest/util/daos_core_base.py
Labels: priority, forced-landing

#13658 DAOS-14781 test: expect more containers before rdb nospace (#13647)
  src/tests/ftest/server/metadata.py
  src/tests/ftest/server/metadata.yaml
Labels: unclean-cherry-pick, priority, forced-landing

#13401 DAOS-14690 control: Fix TestSecurity_DomainInfo_String
  src/control/cmd/dmg/auto_test.go
  src/control/security/domain_info_test.go
Labels: clean-cherry-pick, priority, approved-to-merge

#13703 DAOS-15037 client: Pass vectorized write to dfs (#13628)
  src/client/dfuse/il/int_read.c
  src/client/dfuse/il/int_write.c
Labels: clean-cherry-pick, release-2.4, approved-to-merge

#13369 DAOS-14561 vos: Add garbage collection metrics (#13244)
  site_scons/site_tools/go_builder.py
  src/vos/tests/vts_gc.c
  src/vos/vos_aggregate.c
  src/vos/vos_common.c
  src/vos/vos_gc.c
  src/vos/vos_internal.h
  src/vos/vos_pool.c
  src/vos/vos_space.c
Labels: clean-cherry-pick, priority, forced-landing, approved-to-merge
