Repository daos-stack/daos, pull requests merged in 2024-05, with the labels that each got.

#14067 DAOS-14529 control: Fix config usage in daos_server cmds
  src/control/cmd/daos_server/auto.go
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/daos_server/config.go
  src/control/cmd/daos_server/json_test.go
  src/control/cmd/daos_server/main.go
  src/control/cmd/daos_server/ms_recovery_test.go
  src/control/cmd/daos_server/network_test.go
  src/control/cmd/daos_server/start_test.go
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/cmd/daos_server/storage_scm.go
  src/control/cmd/daos_server/storage_scm_test.go
  src/control/cmd/daos_server/storage_utils.go
  src/control/cmd/daos_server/support_test.go
  src/control/logging/defaults.go
  src/control/server/config/server.go
  src/control/server/ctl_svc.go
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/server_utils_base.py
  utils/node_local_test.py
Labels: control-plane, go

#14248 DAOS-15748 dfuse: Have pre read work with out-of-order I/O
  src/client/dfuse/dfuse.h
  src/client/dfuse/ops/read.c
  src/tests/ftest/dfuse/read.py
Labels: forced-landing

#14279 DAOS-15728 test: Fix coverity issue 2555526
  src/common/tests_dmg_helpers.c
Labels: forced-landing

#14282 DAOS-623 ci: fix landing-builds trigger
  .github/workflows/landing-builds.yml
Labels: forced-landing

#14213 DAOS-15651 control: fail fast on invalid rank for integrate
  src/control/logging/syslog_test.go
  src/control/server/mgmt_pool.go
Labels: forced-landing

#14285 DAOS-15774 test: fix nvme/enospace.py container destroy
  src/tests/ftest/nvme/enospace.yaml
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#14302 DAOS-15798 test: fix pool/verify_space.py
  src/tests/ftest/pool/verify_space.py
Labels: forced-landing

#14230 DAOS-15508 control: Simplify NVMe set-faulty and replace API response
  src/control/cmd/dmg/pretty/printers.go
  src/control/cmd/dmg/pretty/printers_test.go
  src/control/cmd/dmg/pretty/server.go
  src/control/cmd/dmg/pretty/storage.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/cmd/dmg/server.go
  src/control/cmd/dmg/storage_query.go
  src/control/lib/control/response.go
  src/control/lib/control/server_meta.go
  src/control/lib/control/server_meta_test.go
  src/control/lib/control/storage.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_smd_rpc_test.go
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/vmd/fault_reintegration.py
Labels: control-plane, go

#14266 DAOS-15670 doc: update comment for .to_rec_update()
  src/include/daos/btree.h
Labels: forced-landing

#14317 DAOS-15807 test: fix container register_cleanup
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#14247 DAOS-13757 test: Update csum_logging.yaml to pass test args.
  src/tests/ftest/checksum/csum_error_logging.yaml
Labels: forced-landing

#14215 DAOS-15643 test: Enable dfuse register cleanup model
  src/tests/ftest/aggregation/dfuse_space_check.py
  src/tests/ftest/daos_test/dfuse.py
  src/tests/ftest/datamover/negative.py
  src/tests/ftest/datamover/posix_meta_entry.py
  src/tests/ftest/datamover/posix_subsets.py
  src/tests/ftest/datamover/posix_symlinks.py
  src/tests/ftest/datamover/posix_types.py
  src/tests/ftest/datamover/serial_large_posix.py
  src/tests/ftest/dbench/dbench.py
  src/tests/ftest/dfuse/bash.py
  src/tests/ftest/dfuse/bash_dcache.py
  src/tests/ftest/dfuse/bash_fd.py
  src/tests/ftest/dfuse/container_type.py
  src/tests/ftest/dfuse/daos_build.py
  src/tests/ftest/dfuse/enospace.py
  src/tests/ftest/dfuse/fio_pil4dfs_small.py
  src/tests/ftest/dfuse/fio_small.py
  src/tests/ftest/dfuse/mu_mount.py
  src/tests/ftest/dfuse/mu_perms.py
  src/tests/ftest/dfuse/pil4dfs_dcache.py
  src/tests/ftest/dfuse/pil4dfs_fio.py
  src/tests/ftest/dfuse/read.py
  src/tests/ftest/dfuse/root_container.py
  src/tests/ftest/dfuse/simul.py
  src/tests/ftest/dfuse/sparse_file.py
  src/tests/ftest/erasurecode/rebuild_fio.py
  src/tests/ftest/erasurecode/truncate.py
  src/tests/ftest/fault_injection/ec.py
  src/tests/ftest/io/macsio_test.py
  src/tests/ftest/io/parallel_io.py
  src/tests/ftest/server/replay.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/dfuse_test_base.py
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/fio_test_base.py
  src/tests/ftest/util/fio_utils.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/performance_test_base.py
  src/tests/ftest/util/vol_test_base.py
Labels: forced-landing

#14087 DAOS-15477 test: Fix tests using the execute_cont_rf_test method
  src/tests/ftest/datamover/obj_small.py
  src/tests/ftest/datamover/serial_small.py
  src/tests/ftest/util/container_rf_test_base.py
Labels: forced-landing

#14235 DAOS-15715 pool: Fix reconf_arg leak in check mode
  src/pool/srv_pool.c
Labels: forced-landing

#14301 DAOS-15797 test: fix nvme/object.py read_an_array
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#14325 DAOS-15814 test: Fix build parameter for HW test stages
  Jenkinsfile
Labels: forced-landing

#14214 DAOS-623 cq: simplify githook output
  utils/githooks/hook_base.sh
  utils/githooks/pre-commit.d/10-update-copyright
  utils/githooks/pre-commit.d/20-codespell.sh
  utils/githooks/pre-commit.d/30-Jenkinsfile
  utils/githooks/pre-commit.d/40-yamllint.sh
  utils/githooks/pre-commit.d/50-clang-format
  utils/githooks/pre-commit.d/60-gofmt.sh
  utils/githooks/pre-commit.d/70-isort.sh
  utils/githooks/pre-commit.d/71-flake.sh
  utils/githooks/pre-commit.d/72-pylint.sh
Labels: forced-landing

#14326 DAOS-15814 test: Fix build parameter for HW test stages
  Jenkinsfile
Labels: forced-landing

#14308 DAOS-15780 test: Modifying namespace in test.py
  src/tests/ftest/util/apricot/apricot/test.py
Labels: forced-landing

#14346 DAOS-15617 test: Fix mpiio/llnl_mpi4py.py on EL9
  src/tests/ftest/mpiio/llnl_mpi4py.py
Labels: forced-landing

#14321 DAOS-15770 test: Increase lammps job timeout; add ior 4k job
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress.yaml
Labels: forced-landing

#14294 DAOS-15633 control: Remove support for legacy storage syntax from config
  docs/admin/common_tasks.md
  docs/admin/deployment.md
  src/control/cmd/daos_server/start.go
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/server/README.md
  src/control/server/config/faults.go
  src/control/server/config/server.go
  src/control/server/config/server_legacy.go
  src/control/server/config/server_test.go
  src/control/server/engine/config.go
  src/control/server/engine/config_legacy.go
  src/control/server/faults.go
  src/control/server/storage/config.go
  src/tests/ftest/util/server_utils_base.py
  utils/config/examples/daos_server_local.yml
  utils/config/examples/daos_server_unittests.yml
  utils/node_local_test.py
Labels: control-plane, go, usability

#14218 DAOS-15670 rdb: Do MC updates first in log_offer
  src/include/daos_srv/rdb.h
  src/rdb/rdb_internal.h
  src/rdb/rdb_raft.c
  src/rdb/rdb_tx.c
  src/rdb/rdb_util.c
  src/rdb/tests/rdb_test.c
Labels: forced-landing

#14193 DAOS-14834 control: Enable parallel server->engine dRPCs
  src/control/cmd/daos_agent/security_rpc_test.go
  src/control/drpc/drpc_client.go
  src/control/drpc/drpc_client_test.go
  src/control/server/ctl_ranks_rpc_test.go
  src/control/server/ctl_smd_rpc_test.go
  src/control/server/ctl_svc_test.go
  src/control/server/harness_test.go
  src/control/server/instance.go
  src/control/server/instance_drpc.go
  src/control/server/instance_drpc_test.go
  src/control/server/mgmt_check_test.go
  src/control/server/mgmt_cont_test.go
  src/control/server/mgmt_pool_test.go
  src/control/server/mgmt_system_test.go
  src/control/server/util_test.go
Labels: forced-landing

#14352 DAOS-15830 cq: update pylint to 3.1.1
  utils/cq/requirements.txt
Labels: forced-landing

#14362 DAOS-15835 test: remove invalid argument
  src/tests/ftest/erasurecode/restart.py
Labels: forced-landing

#14269 DAOS-15769 chk: restart PS with full functionality after check
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_internal.h
  src/chk/chk_iv.c
  src/chk/chk_leader.c
  src/chk/chk_rpc.c
  src/container/srv_target.c
  src/include/daos_srv/container.h
  src/include/daos_srv/daos_chk.h
  src/include/daos_srv/pool.h
  src/mgmt/srv_pool.c
  src/mgmt/srv_target.c
  src/pool/srv_pool.c
  src/pool/srv_target.c
  src/pool/srv_util.c
  src/tests/ftest/recovery/pool_membership.py
  src/tests/suite/daos_cr.c
Labels: forced-landing

#14293 DAOS-15685 control: Make failure clear when mountpt goes missing
  src/control/fault/code/codes.go
  src/control/server/instance_storage.go
  src/control/server/instance_storage_test.go
  src/control/server/storage/faults.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm/provider.go
  src/control/server/storage/scm/provider_test.go
Labels: control-plane, go, usability

#14348 DAOS-15746 test: Fix pool/verify_space.py for MD on SSD
  src/tests/ftest/pool/verify_space.py
  src/tests/ftest/pool/verify_space.yaml
Labels: forced-landing

#14334 DAOS-15762 test: add githook for ftest changes
  .github/workflows/linting.yml
  src/tests/ftest/tags.py
  utils/githooks/pre-commit.d/73-ftest.sh
Labels: forced-landing

#14366 DAOS-623 cq: speedup get_release_branch
  utils/rpms/packaging/get_release_branch
Labels: forced-landing

#14336 DAOS-623 cq: aggregate GHA linting summary
  .github/workflows/linting.yml
Labels: forced-landing

#14309 DAOS-15228 test: add more unit tests for tags.py
  src/tests/ftest/tags.py
Labels: forced-landing

#14365 DAOS-15830 cq: update pylint to 3.2.0
  src/tests/ftest/deployment/critical_integration.py
  src/tests/ftest/dfuse/simul.py
  src/tests/ftest/pool/bad_query.py
  src/tests/ftest/util/configuration_utils.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/file_count_test_base.py
  src/tests/ftest/util/nvme_utils.py
  src/tests/ftest/util/osa_utils.py
  src/tests/ftest/util/pool_create_all_base.py
  src/tests/ftest/util/pool_security_test_base.py
  utils/cq/daos_pylint.py
  utils/cq/requirements.txt
Labels: forced-landing

#14376 DAOS-15848 test: Add module use to soak job scripts for aurora
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#14370 DAOS-15828 container: properly init ds_cont_child under check mode
  src/container/srv_target.c
  src/dtx/dtx_common.c
  src/pool/srv_target.c
  src/rebuild/srv.c
Labels: priority

#14397 DAOS-623 cq: skip ftest githook for missing deps
  utils/githooks/pre-commit.d/73-ftest.sh
Labels: forced-landing

#14388 DAOS-15779 control: Explicitly link to libgurt in cgo
  src/control/lib/hardware/cart/bindings.go
Labels: forced-landing

#14379 DAOS-15841 control: Improve coverage and fs mocking in storage packages
  src/control/provider/system/mocks.go
  src/control/provider/system/system_linux.go
  src/control/provider/system/system_linux_test.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/instance_storage.go
  src/control/server/instance_storage_test.go
  src/control/server/instance_superblock.go
  src/control/server/instance_superblock_test.go
  src/control/server/instance_test.go
  src/control/server/storage/metadata/provider.go
  src/control/server/storage/metadata/provider_test.go
  src/control/server/storage/mount/provider.go
  src/control/server/storage/mount/provider_test.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm/mocks.go
  src/control/server/storage/scm/provider.go
  src/control/server/storage/scm/provider_test.go
Labels: control-plane, go

#14295 DAOS-15615 test: Clear existing tmpfs mount points before running tests
  src/tests/ftest/launch.py
  src/tests/ftest/scripts/setup_nodes.sh
  src/tests/ftest/util/launch_utils.py
Labels: forced-landing

#14410 DAOS-15859 test: Updates for release/2.6
  src/tests/ftest/util/apricot/apricot/test.py
Labels: forced-landing

#14406 DAOS-15860 cq: update pylint to 3.2.2
  utils/cq/requirements.txt
Labels: forced-landing

#14416 DAOS-15873 test: Fix wal checkpoint metric test
  src/tests/ftest/telemetry/wal_metrics.py
Labels: forced-landing

#14426 DAOS-15859 test: Fix next_version
  Jenkinsfile
Labels: forced-landing

#14411 DAOS-15858 test: Increase timeout for test_lost_majority_ps_replicas
  src/tests/ftest/recovery/pool_list_consolidation.yaml
Labels: forced-landing

#14439 DAOS-15915 cq: fix codespell errors
  ci/codespell.ignores
  pyproject.toml
  src/bio/bio_wal.c
  src/client/array/dc_array.c
  src/client/dfuse/ops/readdir.c
  src/engine/module.c
  src/include/daos/tse.h
  src/include/daos_api.h
  src/include/daos_errno.h
  src/include/daos_srv/bio.h
  src/include/daos_srv/dtx_srv.h
  src/object/cli_shard.c
  src/object/srv_coll.c
  src/object/srv_obj.c
  src/placement/tests/jump_map_place_obj.c
  src/tests/ftest/util/pool_security_test_base.py
  src/tests/suite/daos_base_tx.c
  src/tests/suite/daos_pipeline.c
  src/vos/vos_layout.h
Labels: forced-landing

#14449 DAOS-15916 dfs: Seg fault with DFS scanner
  src/client/dfs/cont.c
Labels: bug

#14440 DAOS-15808 test: Fix test_dmg_storage_query_device_state
  src/tests/ftest/control/dmg_storage_query.py
Labels: forced-landing

#14463 DAOS-15808 test: Fix test_dmg_storage_query_device_state (#14440)
  src/tests/ftest/control/dmg_storage_query.py
Labels: priority, forced-landing

#14462 DAOS-15858 test: Increase test timeout for test_lost_majority_ps_repl…
  src/tests/ftest/recovery/pool_list_consolidation.yaml
Labels: priority, forced-landing

#14459 DAOS-15915 cq: fix codespell errors (#14439)
  ci/codespell.ignores
  pyproject.toml
  src/bio/bio_wal.c
  src/client/array/dc_array.c
  src/client/dfuse/ops/readdir.c
  src/engine/module.c
  src/include/daos/tse.h
  src/include/daos_api.h
  src/include/daos_errno.h
  src/include/daos_srv/bio.h
  src/include/daos_srv/dtx_srv.h
  src/object/cli_shard.c
  src/object/srv_coll.c
  src/object/srv_obj.c
  src/placement/tests/jump_map_place_obj.c
  src/tests/ftest/util/pool_security_test_base.py
  src/tests/suite/daos_base_tx.c
  src/tests/suite/daos_pipeline.c
  src/vos/vos_layout.h
Labels: clean-cherry-pick, priority, forced-landing

#14461 DAOS-15856 test: speedup rebuild/basic (#14398)
  src/tests/ftest/rebuild/basic.yaml
Labels: clean-cherry-pick, priority, forced-landing

#14465 DAOS-15862 client: declare num_fd_dup2ed atomic and lock_fd_dup2ed as rwlock
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: clean-cherry-pick, priority, approved-to-merge

#14464 DAOS-15834 client: disable interception before exec() (#14405)
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: clean-cherry-pick, priority, approved-to-merge

#14245 DAOS-15287 test: Add register tearDown steps for job managers
  src/tests/ftest/daos_racer/parallel.py
  src/tests/ftest/io/macsio_test.py
  src/tests/ftest/ior/crash.py
  src/tests/ftest/nvme/io_verification.py
  src/tests/ftest/rebuild/mdtest.py
  src/tests/ftest/rebuild/widely_striped.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/daos_perf_base.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/macsio_test_base.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/mpiio_test_base.py
Labels: forced-landing
