Repository daos-stack/daos, pull requests merged in 2024-04, with the labels that each got.

#14011 DAOS-14264 test: Include IntelMPI in soak testing
  src/tests/ftest/soak/soak-extra-intelmpi.yaml
  src/tests/ftest/soak/soak-extra-suse.yaml
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#14062 DAOS-15495: Fix libipmctl init failure
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/ipmctl_dimm_test.go
  src/control/server/storage/scm/ipmctl_firmware.go
  src/control/server/storage/scm/ipmctl_firmware_test.go
  src/control/server/storage/scm/ipmctl_region_test.go
  src/control/server/storage/scm/ipmctl_test.go
  src/control/server/storage/scm/ndctl_test.go
Labels: control-plane

#14035 DAOS-15493 cart: Cleanup of deprecated envariables
  src/cart/crt_init.c
  src/cart/utils/crt_utils.c
  src/client/api/tests/eq_tests.c
  src/common/misc.c
  src/control/cmd/daos_agent/README.md
  src/control/cmd/daos_agent/mgmt_rpc.go
  src/control/cmd/daos_server/README.md
  src/control/common/proto/mgmt/svc.pb.go
  src/control/server/engine/config.go
  src/control/server/engine/config_test.go
  src/control/server/engine/exec_test.go
  src/control/server/server_utils.go
  src/mgmt/cli_mgmt.c
  src/mgmt/svc.pb-c.h
  src/proto/mgmt/svc.proto
  src/tests/ftest/cart/corpc/corpc_five_node.yaml
  src/tests/ftest/cart/corpc/corpc_one_node.yaml
  src/tests/ftest/cart/corpc/corpc_two_node.yaml
  src/tests/ftest/cart/ctl/ctl_five_node.yaml
  src/tests/ftest/cart/ctl/ctl_one_node.yaml
  src/tests/ftest/cart/ghost_rank_rpc/ghost_rank_rpc_one_node.yaml
  src/tests/ftest/cart/group_test/group_test.yaml
  src/tests/ftest/cart/iv/iv_one_node.yaml
  src/tests/ftest/cart/iv/iv_two_node.yaml
  src/tests/ftest/cart/no_pmix/multictx_one_node.yaml
  src/tests/ftest/cart/no_pmix_multi_ctx.c
  src/tests/ftest/cart/nopmix_launcher/launcher_one_node.yaml
  src/tests/ftest/cart/rpc/multisend_one_node.yaml
  src/tests/ftest/cart/rpc/rpc_one_node.yaml
  src/tests/ftest/cart/rpc/rpc_two_node.yaml
  src/tests/ftest/cart/rpc/swim_notification.yaml
  src/tests/ftest/cart/selftest/selftest_three_node.yaml
  src/tests/ftest/cart/utest/test_linkage.cpp
  src/tests/ftest/cart/utest/utest_portnumber.c
  src/tests/ftest/cart/utest/utest_swim.c
  src/tests/ftest/cart/util/cart_utils.py
  src/tests/ftest/network/cart_self_test.py
  src/tests/ftest/network/cart_self_test.yaml
  src/tests/ftest/scripts/main.sh
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/server_utils_params.py
  src/utils/crt_launch/crt_launch.c
  src/utils/self_test/self_test.c
  utils/node_local_test.py
Labels: forced-landing

#14093 DAOS-15552 doc: update UCX rpm documentation (#14083)
  docs/admin/ucx.md
Labels: unclean-cherry-pick, priority

#14027 DAOS-15480 object: do not support conditional punch object
  src/object/cli_obj.c
  src/vos/vos_ilog.c
Labels: forced-landing

#14085 DAOS-15551 test: Lower vos_wal_replay_time expected value
  src/tests/ftest/telemetry/wal_metrics.py
Labels: forced-landing

#14098 DAOS-15002 test: fix rebuild/container_create_race
  src/tests/ftest/rebuild/container_create_race.yaml
Labels: priority, forced-landing

#14123 DAOS-15611 test: fix dfuse/daos_build.py requirements
  docs/QSG/build_from_scratch.md
  src/tests/ftest/dfuse/daos_build.py
Labels: forced-landing

#14132 SRE-2145 Warnings-ng 11.2.2 modified API (#14111)
  Jenkinsfile
Labels: forced-landing

#14014 DAOS-15322 common: fix untrusted loop bound
  src/common/btree.c
  src/vos/vos_tree.c
Labels: forced-landing

#14121 DAOS-623 cq: skip jenkinsfile hook if URL not accessible
  utils/githooks/pre-commit.d/20-Jenkinsfile
Labels: forced-landing

#14095 DAOS-15124 rebuild: allow retry fetch if hit -DER_CSUM or -DER_NVME_IO
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/obj_internal.h
  src/rebuild/srv.c
  src/tests/suite/daos_test_common.c
  src/vos/vos_pool_scrub.c
Labels: forced-landing

#14046 DAOS-14022 test: new container test co_op_dup_timing
  src/control/lib/daos/pool_property_test.go
  src/include/daos_prop.h
  src/tests/ftest/daos_test/suite.yaml
  src/tests/suite/daos_container.c
  src/tests/suite/daos_test.h
  src/tests/suite/daos_test_common.c
Labels: forced-landing

#14086 DAOS-14672 test: agent cache expiration for timeout avoidance
  src/tests/ftest/rebuild/widely_striped.yaml
  src/tests/ftest/rebuild/with_ior.yaml
  src/tests/ftest/util/agent_utils_params.py
Labels: forced-landing

#14118 DAOS-15522 test: daos_test fi always for potential dmg retry
  src/tests/suite/daos_pool.c
Labels: forced-landing

#13801 DAOS-15197 test: rebuild with 1 million files
  src/tests/ftest/rebuild/mdtest.py
  src/tests/ftest/rebuild/mdtest.yaml
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/osa_utils.py
Labels: forced-landing

#13954 DAOS-15398 dfuse: fix build issue with strtok_r
  src/client/dfuse/dfuse_main.c
Labels: forced-landing

#14099 DAOS-623 ci: Add a workflow for OSSF Scorecard
  .github/actions/provision-cluster/action.yml
  .github/workflows/bash_unit_testing.yml
  .github/workflows/ci2.yml
  .github/workflows/clang-format.yml
  .github/workflows/create_release.yml
  .github/workflows/doxygen.yml
  .github/workflows/flake.yml
  .github/workflows/landing-builds.yml
  .github/workflows/linting.yml
  .github/workflows/ossf-scorecard.yml
  .github/workflows/pr-metadata.yml
  .github/workflows/pylint.yml
  .github/workflows/rpm-build-and-test-report.yml
  .github/workflows/rpm-build-and-test.yml
  .github/workflows/spelling.yml
  .github/workflows/version-checks.yml
  .github/workflows/yaml.yml
  utils/githooks/pre-commit.d/20-flake.sh
Labels: forced-landing

#14115 DAOS-15606 control: Remove daos_server storage legacy subcommand syntax
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
  docs/admin/troubleshooting.md
  docs/admin/vmd.md
  src/control/cmd/daos_server/main.go
  src/control/cmd/daos_server/storage_legacy.go
  src/control/cmd/daos_server/storage_legacy_test.go
  src/tests/ftest/util/collection_utils.py
  src/tests/ftest/util/server_utils_base.py
Labels: control-plane, forced-landing, go

#14153 DAOS-15477 test: remove unnecessary pool disconnect
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#14088 DAOS-15541 control: Fix tgt count in config generate API
  src/control/cmd/daos_server/auto_test.go
  src/control/lib/control/auto.go
  src/control/lib/control/auto_test.go
Labels: control-plane

#14056 DAOS-14821 test: fix daos_nvme_recovery test
  src/tests/suite/daos_nvme_recovery.c
Labels: forced-landing

#14066 DAOS-7611 test: Add unexpected reboot to soak harassers
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#14142 DAOS-15629 test: Remove 16 ppn from soak datamover
  src/tests/ftest/soak/stress.yaml
Labels: forced-landing

#14140 DAOS-15535 test: Add crt_timeout to offline_rebuild.py test.
  src/tests/ftest/container/per_server_fault_domain.yaml
  src/tests/ftest/erasurecode/cell_size_property.yaml
  src/tests/ftest/erasurecode/offline_rebuild.yaml
  src/tests/ftest/rebuild/container_create_race.yaml
Labels: forced-landing

#13848 DAOS-15208 test: Update rebuild_disabled_single.py container with rf:1
  src/tests/ftest/erasurecode/rebuild_disabled_single.yaml
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#13865 DAOS-15269 cq: merge GHA lint checks into linting.yml
  .github/workflows/doxygen.yml
  .github/workflows/flake.yml
  .github/workflows/linting.yml
  .github/workflows/pylint.yml
  .github/workflows/spelling.yml
Labels: forced-landing

#14187 DAOS-13880 doc: remove outdated datamover restriction
  docs/user/datamover.md
Labels: forced-landing, doc-only

#14161 DAOS-15638 tests: move cat_recovery test from pr to daily test
  src/tests/ftest/daos_test/suite.py
  src/tests/ftest/daos_test/suite.yaml
  src/tests/ftest/recovery/cat_recov_core.py
  src/tests/ftest/recovery/cat_recov_core.yaml
  src/tests/ftest/recovery/container_cleanup.py
  src/tests/ftest/recovery/container_cleanup.yaml
  src/tests/ftest/recovery/container_list_consolidation.py
  src/tests/ftest/recovery/container_list_consolidation.yaml
  src/tests/ftest/recovery/ms_membership.py
  src/tests/ftest/recovery/pool_cleanup.py
  src/tests/ftest/recovery/pool_cleanup.yaml
  src/tests/ftest/recovery/pool_list_consolidation.py
  src/tests/ftest/recovery/pool_membership.py
Labels: forced-landing

#14155 DAOS-15614 tests: more wait when exclude rank during CR test
  src/tests/suite/daos_cr.c
Labels: forced-landing

#13962 DAOS-15388 tools: daos fs copy: error when src is dst
  src/tests/ftest/datamover/negative.py
  src/tests/ftest/util/data_mover_test_base.py
  src/utils/daos_hdlr.c
Labels: forced-landing

#14171 DAOS-15658 test: harasser test need rf2 containers
  src/tests/ftest/soak/harassers.yaml
Labels: forced-landing

#14183 DAOS-15672 rebuild: Fix pool destroy hangs
  src/object/srv_obj_migrate.c
Labels: forced-landing

#14181 DAOS-15667 cart: Set individual rpc timeouts
  src/tests/ftest/cart/test_group_np_cli.c
Labels: forced-landing

#13994 DAOS-15385 control: Add JSON output support to daos_server cmds
  src/control/cmd/daos_server/auto.go
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/daos_server/config.go
  src/control/cmd/daos_server/json_test.go
  src/control/cmd/daos_server/main.go
  src/control/cmd/daos_server/ms_recovery_test.go
  src/control/cmd/daos_server/network.go
  src/control/cmd/daos_server/network_test.go
  src/control/cmd/daos_server/start_test.go
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/cmd/daos_server/storage_scm.go
  src/control/cmd/daos_server/storage_scm_test.go
  src/control/cmd/daos_server/storage_utils.go
  src/control/cmd/daos_server/support_test.go
  src/control/lib/control/mocks.go
  src/control/lib/control/network_test.go
  src/control/lib/control/server_meta_test.go
  src/control/lib/hardware/fabric.go
  src/control/lib/hardware/fabric_test.go
  src/control/server/ctl_network_rpc.go
  src/control/server/ctl_smd_rpc.go
  src/control/server/ctl_svc.go
Labels: control-plane, forced-landing

#14208 DAOS-12891 control: Make -o daos_server option subcommand specific
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/daos_server/config.go
  src/control/cmd/daos_server/main.go
  src/control/cmd/daos_server/ms_recovery_test.go
  src/control/cmd/daos_server/network_test.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/cmd/daos_server/storage_scm_test.go
Labels: control-plane, usability

#14211 DAOS-15686 gurt: Accept ERROR as a log mask string
  src/gurt/dlog.c
Labels: forced-landing

#14126 DAOS-12974 test: nvme/pool_capacity.py - Use threads to create contai…
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/nvme/pool_capacity.yaml
Labels: forced-landing

#13262 DAOS-14571 dfuse: Increase pre-read buffer size.
  src/client/dfuse/dfuse.h
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/dfuse_fuseops.c
  src/client/dfuse/ops/open.c
  src/client/dfuse/ops/read.c
  src/tests/ftest/dfuse/read.py
  src/tests/ftest/dfuse/read.yaml
  src/tests/ftest/util/dfuse_utils.py
Labels: forced-landing

#14227 DAOS-623 cq: update actions/upload-artifact version
  .github/workflows/ossf-scorecard.yml
Labels: forced-landing

#14190 DAOS-15646 test: update target_query.py to use get_space_per_target
  src/client/pydaos/raw/daos_api.py
  src/client/pydaos/raw/daos_cref.py
  src/tests/ftest/pool/target_query.py
Labels: forced-landing

#14233 DAOS-15648 test: Avoid failures with virtual NVMe
  src/tests/ftest/recovery/ddb.yaml
Labels: forced-landing

#14159 DAOS-15642 test: Implement TestContainer register cleanup
  src/tests/ftest/checksum/csum_basic.py
  src/tests/ftest/container/basic_snapshot.py
  src/tests/ftest/container/full_pool_container_create.py
  src/tests/ftest/container/list.py
  src/tests/ftest/container/list.yaml
  src/tests/ftest/container/query_properties.py
  src/tests/ftest/container/snapshot.py
  src/tests/ftest/control/dmg_storage_query.py
  src/tests/ftest/datamover/dst_create.py
  src/tests/ftest/datamover/obj_small.py
  src/tests/ftest/datamover/posix_preserve_props.py
  src/tests/ftest/datamover/serial_small.py
  src/tests/ftest/dfuse/mu_perms.py
  src/tests/ftest/dtx/basic.py
  src/tests/ftest/object/create_many_dkeys.py
  src/tests/ftest/object/fetch_bad_param.py
  src/tests/ftest/object/integrity.py
  src/tests/ftest/object/open_bad_param.py
  src/tests/ftest/object/punch_test.py
  src/tests/ftest/object/update_bad_param.py
  src/tests/ftest/pool/destroy.py
  src/tests/ftest/pool/evict.py
  src/tests/ftest/pool/permission.py
  src/tests/ftest/rebuild/container_rf.yaml
  src/tests/ftest/rebuild/no_cap.py
  src/tests/ftest/rebuild/pool_destroy_race.py
  src/tests/ftest/rebuild/pool_destroy_race.yaml
  src/tests/ftest/security/cont_acl.py
  src/tests/ftest/server/daos_server_restart.py
  src/tests/ftest/server/metadata.py
  src/tests/ftest/telemetry/dkey_akey_enum_punch.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/ec_utils.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/osa_utils.py
  src/tests/ftest/util/pool_security_test_base.py
  src/tests/ftest/util/soak_utils.py
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#14110 DAOS-15595 cart: Remove SEP setting
  src/cart/README.env
  src/cart/crt_init.c
  src/cart/utils/crt_utils.c
  src/control/cmd/daos_agent/README.md
  src/control/common/proto/mgmt/svc.pb.go
  src/control/lib/control/network.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/engine/config.go
  src/control/server/engine/config_test.go
  src/control/server/engine/exec_test.go
  src/control/server/mgmt_system_test.go
  src/control/server/server.go
  src/include/cart/types.h
  src/include/daos/mgmt.h
  src/mgmt/cli_mgmt.c
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/pool/cli.c
  src/proto/mgmt/svc.proto
  src/tests/ftest/cart/corpc/corpc_five_node.yaml
  src/tests/ftest/cart/corpc/corpc_one_node.yaml
  src/tests/ftest/cart/corpc/corpc_two_node.yaml
  src/tests/ftest/cart/ctl/ctl_five_node.yaml
  src/tests/ftest/cart/ctl/ctl_one_node.yaml
  src/tests/ftest/cart/ghost_rank_rpc/ghost_rank_rpc_one_node.yaml
  src/tests/ftest/cart/iv/iv_one_node.yaml
  src/tests/ftest/cart/iv/iv_two_node.yaml
  src/tests/ftest/cart/no_pmix/multictx_one_node.yaml
  src/tests/ftest/cart/rpc/multisend_one_node.yaml
  src/tests/ftest/cart/rpc/rpc_one_node.yaml
  src/tests/ftest/cart/rpc/rpc_two_node.yaml
  src/tests/ftest/cart/rpc/swim_notification.yaml
  src/tests/ftest/cart/selftest/selftest_three_node.yaml
  src/tests/ftest/cart/util/cart_utils.py
  src/tests/ftest/daos_test/suite.single_host.yaml
  src/tests/ftest/daos_test/suite.yaml
  src/tests/ftest/util/daos_core_base.py
  src/tests/ftest/util/environment_utils.py
  src/tests/ftest/util/server_utils_params.py
  src/utils/self_test/self_test.c
  utils/config/daos_server.yml
  utils/config/examples/daos_server_unittests.yml
  utils/nlt_server.yaml
Labels: forced-landing

#14168 DAOS-15654 control: Ignore NEW state NVMe devices when processing spa…
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
Labels: bug, control-plane, go

#14249 DAOS-15750 test: Missing dfuse/mu_perms.py execution
  src/tests/ftest/dfuse/ioctl_pool_handles.py
  src/tests/ftest/dfuse/mu_mount.py
  src/tests/ftest/dfuse/mu_perms.py
Labels: forced-landing

#14246 DAOS-15747 test: Quote filenames when creating stack traces
  src/tests/ftest/process_core_files.py
Labels: forced-landing

#14180 DAOS-15622 test: enhance co_op_dup_timing() predictability
  src/common/tests_dmg_helpers.c
  src/include/daos/tests_lib.h
  src/tests/suite/daos_container.c
Labels: forced-landing

#14250 DAOS-15749 test: Don't destroy an orphaned contianer
  src/tests/ftest/recovery/container_list_consolidation.py
Labels: forced-landing

#14264 DAOS-15768 test: skip cont cleanup in dmg_system_cleanup
  src/tests/ftest/control/dmg_system_cleanup.py
Labels: forced-landing

#14239 DAOS-15048 control: Display NSID only when populated in storage query
  src/control/cmd/dmg/pretty/storage.go
  src/control/cmd/dmg/pretty/storage_test.go
Labels: control-plane, go, usability

#13797 DAOS-14657 test: ftest for libpil4dfs with fio
  src/tests/ftest/dfuse/pil4dfs_fio.py
  src/tests/ftest/dfuse/pil4dfs_fio.yaml
  src/tests/ftest/util/cpu_utils.py
  src/tests/ftest/util/fio_utils.py
  utils/cq/words.dict
Labels: forced-landing

#14256 DAOS-15745 dfuse: Add the pre_read metrics whilst holding reference.
  src/client/dfuse/ops/read.c
Labels: forced-landing

#14243 DAOS-15628 test: Verify maximum containers create with and without dup metadata ops
  src/tests/ftest/server/metadata.py
  src/tests/ftest/server/metadata.yaml
Labels: forced-landing

#13050 DAOS-13520 control: Fix UUID filter for dmg check query
  src/control/server/mgmt_check.go
  src/control/server/mgmt_check_test.go
Labels: CR

#14173 DAOS-15659 test: fix local ftest prefix
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/environment_utils.py
Labels: forced-landing

#14242 DAOS-15713 chk: fix kinds of coverity issues
  src/chk/chk_common.c
  src/chk/chk_engine.c
  src/chk/chk_leader.c
  src/chk/chk_upcall.c
  src/include/daos_srv/daos_chk.h
  src/mgmt/srv_drpc.c
  src/tests/suite/daos_cr.c
Labels: priority, forced-landing

#14222 DAOS-15661 object: set correct map version for layout create
  src/object/cli_obj.c
Labels: forced-landing

#14262 DAOS-15616 test: Update dfuse/find.py to work in a python venv
  src/tests/ftest/dfuse/find.py
  src/tests/ftest/directory_tree.py
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/io_utilities.py
  src/tests/ftest/util/mpiio_utils.py
  src/tests/ftest/util/profiler_utils.py
Labels: forced-landing

#14201 DAOS-15655 test: stop passing server group
  src/tests/ftest/aggregation/continuous_write.py
  src/tests/ftest/aggregation/multiple_pool_cont.py
  src/tests/ftest/aggregation/space_rb.py
  src/tests/ftest/container/multiple_delete.py
  src/tests/ftest/container/per_server_fault_domain.py
  src/tests/ftest/control/dmg_telemetry_io_latency.py
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/server_rank_failure.py
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/erasurecode/space_usage.py
  src/tests/ftest/io/parallel_io.py
  src/tests/ftest/ior/crash.py
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/nvme/fragmentation.py
  src/tests/ftest/nvme/io.py
  src/tests/ftest/nvme/io_verification.py
  src/tests/ftest/nvme/pool_capacity.py
  src/tests/ftest/nvme/pool_exclude.py
  src/tests/ftest/pool/verify_space.py
  src/tests/ftest/recovery/pool_membership.py
  src/tests/ftest/server/metadata.py
  src/tests/ftest/util/data_mover_test_base.py
  src/tests/ftest/util/ior_test_base.py
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/mdtest_test_base.py
  src/tests/ftest/util/mdtest_utils.py
  src/tests/ftest/util/nvme_utils.py
  src/tests/ftest/util/osa_utils.py
  src/tests/ftest/util/soak_utils.py
  src/tests/ftest/vmd/fault_reintegration.py
Labels: forced-landing

#14284 DAOS-15774 test: fix pool_acl and pool_groups
  src/tests/ftest/util/pool_security_test_base.py
Labels: forced-landing

#14117 DAOS-8331 client: Telemetry dump should go to unique file paths
  src/cart/README.env
  src/cart/crt_init.c
  src/client/api/metrics.c
  src/include/daos/metrics.h
Labels: forced-landing

#14271 DAOS-15767 test: Increase soak job pool size
  src/tests/ftest/soak/harassers.yaml
  src/tests/ftest/soak/smoke.yaml
  src/tests/ftest/soak/stress.yaml
Labels: forced-landing

#14276 DAOS-15650 test: Update soak cleanup with new dfuse mounts
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing
