Repository daos-stack/daos, pull requests merged in 2024-03, with the labels that each got.

#13875 DAOS-15007 object: fix EC aggregation's ap_min_unagg_eph set
  src/container/srv_container.c
  src/object/srv_ec_aggregate.c
Labels: forced-landing

#13906 DAOS-15324 test: fix CID 1971004 memset size argument
  src/tests/suite/daos_container.c
Labels: forced-landing

#13746 DAOS-12701 doc: Modify Build from scratch file under QSG
  docs/QSG/build_from_scratch.md
Labels: forced-landing, doc-only

#13883 DAOS-15286 cq: update pylint to 3.1.0
  src/tests/ftest/cart/util/cart_logtest.py
  utils/cq/daos_pylint.py
  utils/cq/requirements.txt
  utils/node_local_test.py
Labels: forced-landing

#13859 DAOS-15263 test: speedup datamover/negative_space.py
  src/tests/ftest/datamover/negative_space.py
  src/tests/ftest/datamover/negative_space.yaml
  src/tests/ftest/util/data_mover_test_base.py
Labels: forced-landing

#13902 DAOS-15250 test: fix multi proc writing same cmocka xml
  src/tests/suite/daos_test.c
Labels: forced-landing

#13903 DAOS-14574 test: Query the pool to detect whether the pool is destroyed
  src/tests/ftest/pool/create_all_hw.yaml
  src/tests/ftest/util/pool_create_all_base.py
Labels: forced-landing

#13874 DAOS-14242 test: Use 8 targets for deployment/network_failure.yaml an…
  src/tests/ftest/deployment/network_failure.yaml
  src/tests/ftest/deployment/server_rank_failure.yaml
Labels: forced-landing

#13930 DAOS-623 cq: quiet githook output
  utils/rpms/packaging/get_release_branch
Labels: forced-landing

#13944 DAOS-15306 gurt: Fix Coverity message for unchecked return value.
  src/gurt/dlog.c
Labels: forced-landing

#13925 SRE-471 test: Adding elapsed time to log steps
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/collection_utils.py
  src/tests/ftest/util/launch_utils.py
Labels: forced-landing

#13868 DAOS-14023 test: update md space tests for larger rdb
  src/tests/ftest/server/metadata.py
  src/tests/ftest/server/metadata.yaml
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#13519 DAOS-14539 client: intercept execve() and it variants
  docs/user/filesystem.md
  src/client/dfuse/SConscript
  src/client/dfuse/pil4dfs/hook.c
  src/client/dfuse/pil4dfs/hook.h
  src/client/dfuse/pil4dfs/int_dfs.c
  src/gurt/dlog.c
  src/include/gurt/dlog.h
  src/tests/ftest/daos_test/dfuse.py
  src/tests/suite/dfuse_test.c
Labels: forced-landing

#13941 DAOS-623 ci: Parameters are in the params namespace
  .gitignore
  Jenkinsfile
Labels: forced-landing

#13960 DAOS-14023 test: fix pylint issue
  src/tests/ftest/server/metadata.py
Labels: forced-landing

#13953 DAOS-15310 vos: Fix Coverity issue for uninitialized pointer read.
  src/vos/vos_obj.c
Labels: forced-landing

#13931 DAOS-15315 bio: Fix CID-1958030 Resource leak
  src/bio/bio_config.c
Labels: forced-landing

#13791 DAOS-14889 control: Discover PMem details via XML cli
  src/control/cmd/daos_server/storage_legacy.go
  src/control/cmd/daos_server/storage_legacy_test.go
  src/control/cmd/dmg/pretty/storage_scm.go
  src/control/cmd/dmg/pretty/storage_test.go
  src/control/common/proto/ctl/storage_scm.pb.go
  src/control/lib/ipmctl/nvm.go
  src/control/server/storage/mocks.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/ipmctl_dimm.go
  src/control/server/storage/scm/ipmctl_dimm_test.go
  src/control/server/storage/scm/ipmctl_region.go
  src/control/server/storage/scm/ipmctl_region_test.go
  src/control/server/storage/scm/ipmctl_test.go
  src/control/server/storage/scm/mocks.go
  src/control/server/storage/scm/ndctl.go
  src/control/server/storage/scm/ndctl_test.go
  src/control/server/storage/scm/provider_test.go
  src/proto/ctl/storage_scm.proto
Labels: bug, control-plane

#13971 DAOS-15415 control: Enforce no more than 3 bdev tiers in MD-on-SSD
  src/control/server/storage/config.go
Labels: control-plane, forced-landing, meta-on-ssd

#13937 DAOS-13881 control: Clean associated handles on agent start
  src/control/cmd/daos_agent/config.go
  src/control/cmd/daos_agent/procmon.go
  src/control/cmd/daos_agent/start.go
  src/control/lib/control/system.go
  src/control/security/auth/auth_sys.go
  src/control/security/grpc_authorization.go
  src/control/security/grpc_authorization_test.go
  src/control/server/mgmt_system.go
  utils/config/daos_agent.yml
Labels: control-plane, forced-landing

#13951 DAOS-14630 doc: Improve MD-on-SSD example config and validate with test
  src/control/server/config/server_test.go
  utils/config/examples/daos_server_mdonssd.yml
Labels: control-plane, forced-landing

#13918 DAOS-15262 vos: Fix probe issue in vos iterator
  src/vos/vos_iterator.c
Labels: forced-landing

#13878 DAOS-15133 test: Disable logging raw dmg output by default
  src/common/tests_dmg_helpers.c
Labels: forced-landing

#13662 DAOS-14799 container: interoperability fix for OIT OID KVS (#13634)
  src/container/srv_container.c
Labels: unclean-cherry-pick, priority

#13739 DAOS-14640 rebuild: rpt ref leak in rebuild_iv_ent_refresh() (#13348)
  src/rebuild/rebuild_iv.c
Labels: clean-cherry-pick, priority

#13952 DAOS-15397 test: Rebuild TO updates are needed on 2.4
  src/tests/ftest/soak/harassers.yaml
Labels: release-2.4

#13418 DAOS-14702 test: Updates to soak for aurora
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/soak/stress.py
  src/tests/ftest/soak/stress.yaml
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#13926 DAOS-13982 rdb: increase noappend bytes in test for nospace (#13866)
  src/rdb/rdb_internal.h
  src/rdb/rdb_raft.c
Labels: clean-cherry-pick

#13897 DAOS-623 ci: Modify githooks to allow skip (#13885)
  utils/githooks/commit-msg
  utils/githooks/commit-msg.d/10-watermark.py
  utils/githooks/hook_base.sh
  utils/githooks/pre-commit
  utils/githooks/prepare-commit-msg
Labels: clean-cherry-pick

#13751 DAOS-623 object: potential mem leak in EC aggregation (#13688)
  src/object/srv_ec_aggregate.c
Labels: clean-cherry-pick

#13669 DAOS-14838 gc: run in tight mode under space pressure (#13544)
  src/container/srv_target.c
  src/pool/srv_target.c
Labels: unclean-cherry-pick, priority

#13983 DAOS-14126 pool: Fix a pool destroy timeout
  src/include/daos_srv/pool.h
  src/pool/srv_target.c
Labels: priority, forced-landing

#13979 DAOS-15426 telemetry: Export missing stats metrics
  src/control/lib/telemetry/duration_test.go
  src/control/lib/telemetry/gauge_test.go
  src/control/lib/telemetry/promexp/collector.go
  src/control/lib/telemetry/promexp/collector_test.go
  src/control/lib/telemetry/telemetry.go
  src/control/lib/telemetry/test_helpers.go
  src/gurt/telemetry.c
  src/tests/ftest/util/telemetry_utils.py
Labels: forced-landing

#13945 DAOS-14574 test: Query the pool to detect whether the pool is destroy…
  src/tests/ftest/pool/create_all_hw.yaml
  src/tests/ftest/util/pool_create_all_base.py
Labels: unclean-cherry-pick, forced-landing

#13905 DAOS-15316 object: fix some coverity issues
  src/dtx/dtx_common.c
  src/object/srv_obj.c
Labels: forced-landing

#14010 SRE-2105 cq: Add permissions metatdata for GHA files.
  .github/workflows/unit-testing.yml
Labels: forced-landing

#13995 DAOS-14542 test: replace check_container_info with verify_query (#13219)
  src/tests/ftest/ior/crash.py
  src/tests/ftest/util/container_rf_test_base.py
  src/tests/ftest/util/rebuild_test_base.py
  src/tests/ftest/util/test_utils_container.py
Labels: clean-cherry-pick, priority

#13996 DAOS-15263 test: speedup datamover/negative_space.py (#13859)
  src/tests/ftest/datamover/negative_space.py
  src/tests/ftest/datamover/negative_space.yaml
  src/tests/ftest/util/data_mover_test_base.py
Labels: clean-cherry-pick, priority

#13699 DAOS-13079 test: ftest to use fusermount3 (#13010)
  src/tests/ftest/util/dfuse_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#13757 DAOS-15121 test: do not check errno after rewind() (#13743)
  src/tests/ftest/util/run_utils.py
  src/tests/suite/dfuse_test.c
Labels: clean-cherry-pick, priority

#14025 DAOS-15402 test: Increase dfuse/mu_perms.py timeout
  src/tests/ftest/dfuse/mu_perms.yaml
Labels: forced-landing

#14003 DAOS-14702 test: Updates to soak for aurora (#13418)
  src/tests/ftest/slurm_setup.py
  src/tests/ftest/soak/stress.py
  src/tests/ftest/soak/stress.yaml
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: clean-cherry-pick, forced-landing

#14006 DAOS-15277 cart: Strengthen incoming tag checks (#13934)
  src/cart/crt_rpc.c
Labels: clean-cherry-pick

#14033 DAOS-15492 build: Add minimum go version (#14031)
  debian/control
Labels: clean-cherry-pick

#13759 DAOS-15055 build: Ignore BuildTime in rebuild calculation
  src/control/SConscript
Labels: priority, forced-landing

#13495 DAOS-11404 dtx: Introduce local transactions
  debian/changelog
  debian/daos-server-tests.install
  src/dtx/SConscript
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/tests/SConscript
  src/dtx/tests/dts_local.c
  src/dtx/tests/dts_local_rdb.c
  src/dtx/tests/dts_structs.c
  src/dtx/tests/dts_utils.c
  src/dtx/tests/dts_utils.h
  src/dtx/tests/dtx_tests.c
  src/dtx/tests/pl_map_mock.c
  src/dtx/tests/sched_mock.c
  src/dtx/tests/srv_mock.c
  src/dtx/tests/ult_mock.c
  src/include/daos_srv/dtx_srv.h
  src/include/daos_srv/vos.h
  src/tests/ftest/util/telemetry_utils.py
  src/vos/tests/SConscript
  src/vos/vos_aggregate.c
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_ilog.c
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_obj.c
  src/vos/vos_ts.c
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
  utils/utest.yaml
Labels: meta-on-ssd

#14029 DAOS-15399 test: Adding elapsed time to log steps (#13925)
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/collection_utils.py
  src/tests/ftest/util/launch_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#13998 DAOS-12950 test: add ftest tag linter (#13642)
  .github/workflows/linting.yml
  src/tests/ftest/aggregation/checksum.py
  src/tests/ftest/daos_test/dfs.py
  src/tests/ftest/datamover/posix_preserve_props.py
  src/tests/ftest/erasurecode/ior_smoke.py
  src/tests/ftest/erasurecode/mdtest_smoke.py
  src/tests/ftest/erasurecode/online_rebuild.py
  src/tests/ftest/erasurecode/online_rebuild_mdtest.py
  src/tests/ftest/network/cart_self_test.py
  src/tests/ftest/nvme/object.py
  src/tests/ftest/pool/info.py
  src/tests/ftest/rebuild/pool_destroy_race.py
  src/tests/ftest/scrubber/basic.py
  src/tests/ftest/security/cont_overwrite_acl.py
  src/tests/ftest/tags.py
  utils/cq/words.dict
  utils/rpms/daos.spec
  utils/utest.yaml
Labels: unclean-cherry-pick, priority

#14001 DAOS-15225 cq: update yamllint to 1.35.1 (#13821)
  utils/cq/requirements.txt
Labels: unclean-cherry-pick, priority

#14008 DAOS-14748 bio: race in stopping health monitor (#13500)
  src/bio/bio_internal.h
  src/bio/bio_monitor.c
  src/bio/bio_xstream.c
Labels: clean-cherry-pick, priority

#14047 DAOS-15145 test: add mock functions for dtx_tests
  src/dtx/tests/ult_mock.c
Labels: forced-landing

#13745 DAOS-14894 test: Bump system_ram_reserved for dfuse/daos_build.py (#1…
  src/tests/ftest/dfuse/daos_build.yaml
Labels: clean-cherry-pick, priority, approved-to-merge

#14019 DAOS-14126 pool: Fix a pool destroy timeout (#13983) (#12889)
  src/include/daos_srv/pool.h
  src/pool/srv_target.c
Labels: unclean-cherry-pick, priority

#13933 DAOS-15339 sched: suppress unnecessary warn message
  src/engine/sched.c
Labels: forced-landing

#14052 DAOS-14780 rebuild: fix a bug with mpt_inflight_size
  src/object/srv_obj_migrate.c
Labels: priority

#14039 DAOS-15104 doc: Improve set-logmasks documentation in admin guide (#1…
  docs/admin/administration.md
Labels: priority

#14068 DAOS-15533 test: Reduce release/2.4 timed build frequency
  Jenkinsfile
Labels: forced-landing

#13763 DAOS-14631 test: Adding WAL/Meta SSD fault/reintegration tests
  src/tests/ftest/control/dmg_storage_query.py
  src/tests/ftest/nvme/fault.py
  src/tests/ftest/nvme/fault.yaml
  src/tests/ftest/nvme/health.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/nvme_utils.py
  src/tests/ftest/vmd/led.py
Labels: forced-landing

#14069 DAOS-15468 test: Automating testing IL with large number of targets
  src/tests/ftest/dfuse/ioctl_pool_handles.py
  src/tests/ftest/dfuse/ioctl_pool_handles.yaml
  src/tests/ftest/util/ior_utils.py
  src/tests/ftest/util/telemetry_utils.py
Labels: forced-landing
