Repository daos-stack/daos, pull requests merged in 2025-06, with the labels that each got.

#16370 DAOS-17148 common: disable BTR_FEAT_SKIP_LEAF_REBAL
  src/common/btree.c
  src/include/daos/btree.h
  src/vos/vos_dtx.c
Labels: forced-landing

#16372 DAOS-17148 common: disable BTR_FEAT_SKIP_LEAF_REBAL - b26
  src/common/btree.c
  src/include/daos/btree.h
  src/vos/vos_dtx.c
Labels: clean-cherry-pick, release-2.6.4

#16459 DAOS-17598 vos: keep dae_need_release flag for partial commit
  src/vos/vos_dtx.c
Labels: priority

#16460 DAOS-17598 vos: keep dae_need_release flag for partial commit - b26
  src/vos/vos_dtx.c
Labels: priority, release-2.6.4

#16310 DAOS-17432 test: Update suppressions for Go runtime
  src/cart/utils/memcheck-cart.supp
Labels: forced-landing

#16485 DAOS-17651 test: Increase timeout for recovery/pool_list_consolidatio…
  src/tests/ftest/recovery/pool_list_consolidation.yaml
Labels: forced-landing

#16507 DAOS-17432 test: Update suppressions for Go runtime (#16310)
  src/cart/utils/memcheck-cart.supp
Labels: forced-landing

#16305 DAOS-17049 control: Allow graceful shutdown for specific ranks
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
Labels: forced-landing

#16498 DAOS-17653 test: Resolve daos_build.py ofi failed to build
  src/tests/ftest/dfuse/daos_build.py
  utils/scripts/install-el8.sh
  utils/scripts/install-el9.sh
  utils/scripts/install-leap15.sh
  utils/scripts/install-ubuntu.sh
Labels: forced-landing

#16389 DAOS-17560 vos: maintain DTX statistical info correctly
  src/vos/vos_container.c
  src/vos/vos_dtx.c
Labels: priority

#16532 SRE-3149 test: Skip gpg check for lua-lmod install (#16531)
  ci/provisioning/post_provision_config_nodes_LEAP_15.sh
Labels: clean-cherry-pick, forced-landing

#16411 DAOS-17179 test: Fix stop commands with trailing space (#15993)
  src/tests/ftest/util/daos_core_base.py
Labels: priority, forced-landing

#16387 DAOS-17562 test: Add missing EL 8 debuginfo packages
  src/tests/ftest/process_core_files.py
Labels: forced-landing

#16504 DAOS-17534 dtx: race between DTX aggregation and container close
  src/dtx/dtx_common.c
  src/dtx/tests/sched_mock.c
  src/engine/sched.c
  src/include/daos_srv/daos_engine.h
Labels: priority

#16542 DAOS-17731 test: erasurecode/online_rebuild_mdtest.py - wait_for_rebu…
  src/tests/ftest/erasurecode/online_rebuild_mdtest.py
Labels: forced-landing

#16505 DAOS-17534 dtx: race between DTX aggregation and container close - b26
  src/dtx/dtx_common.c
  src/dtx/tests/sched_mock.c
  src/engine/sched.c
  src/include/daos_srv/daos_engine.h
Labels: priority

#16181 DAOS-17341 control: Remove spdk lockfiles on engine exit
  src/control/cmd/daos_server/storage_nvme.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/common/file_utils.go
  src/control/common/test/utils.go
  src/control/fault/code/codes.go
  src/control/lib/spdk/mocks.go
  src/control/lib/spdk/nvme.go
  src/control/lib/spdk/nvme_default.go
  src/control/lib/spdk/nvme_stubs.go
  src/control/lib/spdk/nvme_test.go
  src/control/lib/spdk/spdk.go
  src/control/run_go_tests.sh
  src/control/server/config/faults.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/faults.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_test.go
  src/control/server/storage/faults.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm.go
  src/engine/init.c
Labels: control-plane, forced-landing

#16291 DAOS-17339 control: Avoid starting AdminExcluded ranks (#16249)
  src/control/cmd/dmg/system.go
  src/control/cmd/dmg/system_test.go
  src/control/common/proto/mgmt/system.pb.go
  src/control/fault/code/codes.go
  src/control/lib/control/mocks.go
  src/control/lib/control/system.go
  src/control/server/faults.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/system/errors.go
  src/control/system/membership.go
  src/control/system/membership_test.go
  src/proto/mgmt/system.proto
  src/tests/ftest/control/dmg_system_start.py
  src/tests/ftest/control/dmg_system_start.yaml
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: unclean-cherry-pick, priority, release-2.6.4
