Repository daos-stack/daos, pull requests merged in 2025-07, with the labels that each got.

#16289 DAOS-9217 pool: allow rd_fac to be modified
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/pool/srv_cli.c
Labels: release-2.2, priority

#16345 DAOS-17513 control: Update meminfo to include per-numa stats
  src/control/cmd/daos_server/auto.go
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/daos_server/storage_nvme_test.go
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/pretty/storage.go
  src/control/common/meminfo.go
  src/control/common/meminfo_test.go
  src/control/common/proto/ctl/storage.pb.go
  src/control/common/proto/mocks.go
  src/control/common/testdata/meminfo
  src/control/common/testdata/meminfo_0
  src/control/common/testdata/meminfo_1
  src/control/lib/control/auto.go
  src/control/lib/control/auto_test.go
  src/control/lib/control/mocks.go
  src/control/lib/control/storage.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/ctl_storage.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/engine/config_test.go
  src/control/server/mocks.go
  src/control/server/server.go
  src/control/server/server_utils.go
  src/control/server/server_utils_test.go
  src/control/server/storage/bdev_test.go
  src/proto/ctl/storage.proto
Labels: control-plane, go

#16552 DAOS-17745 test: nvme/io.py - Reduce block size to 800MiB
  src/tests/ftest/nvme/io.yaml
Labels: forced-landing

#16558 DAOS-9217 pool: allow rd_fac to be modified (#16289)
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/pool/srv_cli.c
Labels: release-2.2, forced-landing

#16487 DAOS-17499 client: support FIOCLEX in ioctl() in libpil4dfs
  src/client/dfuse/pil4dfs/int_dfs.c
Labels: priority

#16403 DAOS-17550 object: refine dc_array_set_size processing
  src/client/array/dc_array.c
  src/object/cli_obj.c
Labels: priority

#16268 DAOS-17338 object: optimize sgl handling to reduce iov buffer count
  src/object/cli_mod.c
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/srv_mod.c
  src/tests/suite/daos_obj_array.c
Labels: priority

#16564 DAOS-17769 test: Fix spdk paths in run_go_tests.sh
  src/control/run_go_tests.sh
Labels: forced-landing

#16444 DAOS-17532 test: Remove local host client use from functional tests
  src/tests/ftest/container/api_basic_attribute.yaml
  src/tests/ftest/container/auto_oc_selection.yaml
  src/tests/ftest/container/basic_snapshot.yaml
  src/tests/ftest/container/boundary.py
  src/tests/ftest/container/boundary.yaml
  src/tests/ftest/container/destroy.yaml
  src/tests/ftest/container/fill_destroy_loop.yaml
  src/tests/ftest/container/label.yaml
  src/tests/ftest/container/list.yaml
  src/tests/ftest/container/open.yaml
  src/tests/ftest/container/per_server_fault_domain.py
  src/tests/ftest/container/per_server_fault_domain.yaml
  src/tests/ftest/container/query_attribute.yaml
  src/tests/ftest/container/query_properties.yaml
  src/tests/ftest/container/snapshot.yaml
  src/tests/ftest/control/daos_object_query.yaml
  src/tests/ftest/control/daos_snapshot.yaml
  src/tests/ftest/control/dmg_system_cleanup.py
  src/tests/ftest/control/dmg_system_cleanup.yaml
  src/tests/ftest/dfuse/bash.yaml
  src/tests/ftest/dfuse/bash_dcache.yaml
  src/tests/ftest/dfuse/bash_fd.yaml
  src/tests/ftest/dfuse/enospace.yaml
  src/tests/ftest/dfuse/il_whitelist.yaml
  src/tests/ftest/dfuse/root_container.yaml
  src/tests/ftest/dtx/basic.yaml
  src/tests/ftest/object/create_many_dkeys.yaml
  src/tests/ftest/object/fetch_bad_param.yaml
  src/tests/ftest/object/integrity.yaml
  src/tests/ftest/object/open_bad_param.yaml
  src/tests/ftest/object/punch_test.yaml
  src/tests/ftest/object/same_key_different_value.yaml
  src/tests/ftest/object/update_bad_param.yaml
  src/tests/ftest/pool/evict.yaml
  src/tests/ftest/pool/pda.yaml
  src/tests/ftest/pool/permission.yaml
  src/tests/ftest/rebuild/basic.yaml
  src/tests/ftest/rebuild/with_io.yaml
  src/tests/ftest/recovery/container_cleanup.yaml
  src/tests/ftest/recovery/container_list_consolidation.yaml
  src/tests/ftest/recovery/ddb.yaml
  src/tests/ftest/recovery/pool_list_consolidation.yaml
  src/tests/ftest/recovery/pool_membership.yaml
  src/tests/ftest/security/cont_create_acl.yaml
  src/tests/ftest/telemetry/dkey_akey_enum_punch.yaml
Labels: forced-landing

#16562 DAOS-17761 cq: bump python package versions (#16530)
  utils/cq/pylintrc
  utils/cq/requirements.txt
Labels: unclean-cherry-pick, priority, forced-landing

#16569 DAOS-17656 object: several fix for EC object fetch processing
  src/object/cli_csum.c
  src/object/cli_csum.h
  src/object/cli_ec.c
  src/object/cli_obj.c
  src/object/cli_shard.c
  src/object/srv_obj.c
  src/object/tests/cli_checksum_tests.c
  src/tests/suite/daos_obj_ec.c
  src/tests/suite/daos_test.h
Labels: clean-cherry-pick

#16302 DAOS-17002 test: fix rebuild_fio aggregation detection (#15817)
  src/tests/ftest/erasurecode/rebuild_fio.py
  src/tests/ftest/erasurecode/rebuild_fio.yaml
Labels: clean-cherry-pick, priority, forced-landing

#16572 DAOS-17612 build: Bump golang.org/x/net from 0.37.0 to 0.38.0 in /src/control (#16272)
  src/control/go.mod
  src/control/go.sum
  src/control/vendor/golang.org/x/net/http2/frame.go
  src/control/vendor/golang.org/x/net/http2/server.go
  src/control/vendor/modules.txt
Labels: clean-cherry-pick, priority, release-2.6.4

#16264 DAOS-17113 control: Enable hotplug in config by default
  src/control/cmd/dmg/auto_test.go
  src/control/fault/code/codes.go
  src/control/lib/control/mocks.go
  src/control/server/config/faults.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  utils/config/daos_server.yml
Labels: control-plane

#16534 DAOS-17736 rebuild: exit the whole rebuild when one obj rebuild failed
  src/object/srv_obj_migrate.c
  src/pool/srv_pool.c
Labels: forced-landing

#16457 DAOS-17472 build: Enable new RPM builds
  Jenkinsfile
  ci/provisioning/post_provision_config_common_functions.sh
  ci/rpm/build_success.sh
  ci/rpm/gen_rpms.sh
  src/control/build/config.go
  src/control/build/config_test.go
  src/control/build/variables.go
  src/control/cmd/daos_agent/main.go
  src/control/cmd/daos_server/config.go
  src/control/lib/control/config.go
  src/control/lib/control/config_test.go
  utils/rpms/argobots.sh
  utils/rpms/daos.sh
  utils/rpms/fpm_common.sh
  utils/rpms/isa-l.sh
  utils/rpms/isa-l_crypto.sh
  utils/rpms/libfabric.sh
  utils/rpms/mercury.sh
  utils/rpms/package_names.sh
  utils/rpms/pmdk.sh
  utils/scripts/install-el8.sh
  utils/scripts/install-el9.sh
  utils/scripts/install-leap15.sh
Labels: forced-landing

#16624 DAOS-17822 chk: filter out repeated pools in the check list
  src/chk/chk_common.c
Labels: priority, forced-landing

#16539 DAOS-17738 client: reset DTX base UUID after fork
  src/client/api/event.c
  src/client/api/init.c
  src/common/misc.c
  src/vos/vos_dtx.c
Labels: priority, forced-landing

#16540 DAOS-17738 client: reset DTX base UUID after fork - b26
  src/client/api/event.c
  src/client/dfuse/il/int_posix.c
  src/client/dfuse/pil4dfs/int_dfs.c
  src/common/misc.c
  src/vos/vos_dtx.c
Labels: unclean-cherry-pick, priority

#16599 DAOS-17712 cart: race in test_multisend_server
  src/cart/utils/crt_utils.c
  src/cart/utils/crt_utils.h
  src/tests/ftest/cart/test_ep_cred_server.c
  src/tests/ftest/cart/test_group_np_srv.c
  src/tests/ftest/cart/test_multisend_server.c
  src/tests/ftest/cart/test_proto_server.c
  src/tests/ftest/cart/test_rpc_to_ghost_rank.c
Labels: forced-landing

#16617 DAOS-17748 control: Add verification to raft-db Add/Remove wrappers (…
  src/control/system/membership.go
  src/control/system/raft/database_members.go
  src/control/system/raft/database_members_test.go
  src/control/system/raft/database_test.go
  src/control/system/raft/raft.go
Labels: bug, control-plane, priority, forced-landing

#16620 DAOS-17818 test: CR Automate Test - dmg check start --failout
  src/tests/ftest/recovery/check_start_options.py
  src/tests/ftest/recovery/check_start_options.yaml
  src/tests/ftest/util/recovery_test_base.py
Labels: forced-landing

#16475 DAOS-17643 control: Disallow most transitions from Excluded
  src/control/system/member.go
  src/control/system/member_internal_test.go
Labels: forced-landing

#16577 DAOS-17776 client: bump hadoop-common from 3.4.0 to 3.4.1
  src/client/java/hadoop-daos/pom.xml
  utils/trivy/.trivyignore
  utils/trivy/trivy.yaml
Labels: forced-landing

#16600 DAOS-17547 rebuild: error on stopped ds_pool_child (#16382)
  src/object/srv_obj_migrate.c
  src/rebuild/srv.c
Labels: clean-cherry-pick, forced-landing

#16466 DAOS-17631 cart: Print self_uri on context create
  src/cart/crt_context.c
Labels: forced-landing

#16665 DAOS-17492 control: Ensure updated members can become voters (#16392)
  src/control/system/raft/database.go
  src/control/system/raft/database_test.go
  src/control/system/raft/mocks.go
  src/control/system/raft/raft.go
  src/control/system/raft/raft_test.go
Labels: unclean-cherry-pick, priority, release-2.6.4

#16658 DAOS-17819 test: CR Automate Test - Check start options --find-orphans
  src/tests/ftest/recovery/check_start_options.py
  src/tests/ftest/recovery/check_start_options.yaml
Labels: forced-landing

#16675 SRE-3236 LUA-LMOD hack fix for Leap 15.6
  ci/provisioning/post_provision_config_nodes_LEAP.sh
Labels: forced-landing

#16683 DAOS-17835 doc: Document how to add/remove MS replica (#16651)
  docs/admin/administration.md
  src/control/system/raft/database_test.go
Labels: clean-cherry-pick, priority, forced-landing, release-2.6.4

#16669 DAOS-17534 dtx: not add cont to batched commit list if being stopped - b26
  src/dtx/dtx_common.c
  src/engine/srv.c
  src/include/daos_srv/daos_engine.h
Labels: priority
