Repository daos-stack/daos, pull requests merged in 2025-04, with the labels that each got.

#16079 DAOS-17200 tests: avoid data corruption across all replicas (#16047)
  src/tests/suite/daos_rebuild_simple.c
Labels: forced-landing, release-2.6.4

#16189 DAOS-17224 object: fix anchor split listing (#16056)
  src/client/api/object.c
  src/client/dfs/pipeline.c
  src/tests/ftest/daos_test/dfs.yaml
  src/tests/suite/dfs_unit_test.c
Labels: priority

#15998 DAOS-16620 vos: exit scrub earlier during container destruction (#15957)
  src/container/srv_target.c
  src/vos/vos_pool_scrub.c
Labels: release-2.6.4

#16140 DAOS-16767 doc: improve documentation for daos cont set-prop
  docs/user/container.md
Labels: doc-only

#16127 DAOS-17253 build: Fix client only build (#16059)
  debian/changelog
  debian/control
  debian/daos-client-tests.install
  debian/daos-server-tests.install
  debian/daos-server.dirs
  debian/daos-server.install
  debian/daos-server.postinst
  debian/daos-server.preinst
  debian/rules
  site_scons/prereq_tools/base.py
  src/common/SConscript
  src/common/tests/SConscript
  src/security/SConscript
  src/tests/SConscript
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, approved-to-merge

#16176 DAOS-17350 build: Search in user environment for Go binary
  site_scons/site_tools/go_builder.py
Labels: forced-landing

#16153 DAOS-17296 object: ensure retry-able error on SSD faulty
  src/bio/bio_buffer.c
  src/container/srv_target.c
  src/dtx/dtx_common.c
  src/include/daos_srv/container.h
  src/include/daos_srv/dtx_srv.h
  src/object/srv_coll.c
  src/object/srv_internal.h
  src/object/srv_obj.c
Labels: clean-cherry-pick

#16190 DAOS-16925,16578,17016,17149,17331 cart: Suppress NLT Go valgrind errors
  src/cart/utils/memcheck-cart.supp
Labels: unclean-cherry-pick

#16187 DAOS-16845 test: update tests to use check_free_space (#15553)
  src/tests/ftest/aggregation/dfuse_space_check.py
  src/tests/ftest/aggregation/dfuse_space_check.yaml
  src/tests/ftest/container/multiple_delete.py
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/nvme/enospace.yaml
  src/tests/ftest/util/test_utils_pool.py
Labels: unclean-cherry-pick, priority, forced-landing

#16206 DAOS-17115 object: Avoid logging non-SSD errors (#15906)
  src/object/srv_obj.c
Labels: clean-cherry-pick, priority, approved-to-merge

#16213 DAOS-16620 container: demote lifecycle errors to debug (#16193)
  src/container/srv_target.c
Labels: clean-cherry-pick, release-2.6.4

#16205 DAOS-16922 dfuse: Avoid assertion on shutdown (#15972)
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/dfuse_main.c
Labels: unclean-cherry-pick, priority, approved-to-merge

#16217 DAOS-17376 tests: enable local flock in dfuse for io_sys_admin
  src/tests/ftest/deployment/io_sys_admin.yaml
Labels: forced-landing

#16220 DAOS-17052 test: update expected msg for critical_integration (#15855)
  src/tests/ftest/deployment/critical_integration.py
Labels: clean-cherry-pick, priority

#15987 DAOS-10028 client: Refactor container properties for Go
  src/control/cmd/daos/acl.go
  src/control/cmd/daos/container.go
  src/control/cmd/daos/pretty/container.go
  src/control/cmd/daos/property.go
  src/control/cmd/daos/property_flags.go
  src/control/cmd/daos/property_test.go
  src/control/cmd/daos/util.go
  src/control/lib/daos/api/container.go
  src/control/lib/daos/api/container_test.go
  src/control/lib/daos/api/libdaos.go
  src/control/lib/daos/api/libdaos_cont_stubs.go
  src/control/lib/daos/cont_prop.go
  src/control/lib/daos/container.go
  src/control/lib/daos/container_property.go
  src/control/lib/daos/container_property_test.go
  src/control/lib/daos/object.go
  src/control/lib/daos/object_test.go
  src/control/lib/daos/pool.go
  src/control/lib/daos/pool_cont_prop.go
  src/control/lib/daos/pool_cont_prop_test.go
  src/control/lib/daos/pool_property.go
  src/control/lib/daos/pool_property_test.go
  src/control/lib/daos/property.go
  src/control/lib/daos/property_test.go
  src/control/lib/daos/test_stubs.go
  src/control/lib/daos/util.go
  src/utils/daos_hdlr.h
  utils/node_local_test.py
Labels: forced-landing

#16233 DAOS-17131 dfs: Possible missing string termination after strncpy function call
  src/client/dfs/cont.c
  src/client/dfs/obj.c
  src/client/dfuse/ops/lookup.c
  src/tests/obj_ctl.c
Labels: unclean-cherry-pick, priority, release-2.6.4

#16139 SRE-2832 build: unblock Build, Unit tests, Functional test (EL8) stages in FC Lab
  Jenkinsfile
  ci/functional/launchable_analysis
  ci/provisioning/post_provision_config.sh
  ci/provisioning/post_provision_config_nodes.sh
  ci/unit/test_nlt.sh
  ci/unit/test_nlt_node.sh
  ftest.sh
  utils/githooks/pre-commit.d/30-Jenkinsfile.sh
  utils/node_local_test.py
Labels: priority

#16201 DAOS-17343 control: Validate SPDK config on engine start
  src/control/cmd/daos_server_helper/handler.go
  src/control/cmd/daos_server_helper/main.go
  src/control/fault/code/codes.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/instance_storage.go
  src/control/server/storage/bdev.go
  src/control/server/storage/bdev/backend.go
  src/control/server/storage/bdev/backend_class.go
  src/control/server/storage/bdev/backend_class_test.go
  src/control/server/storage/bdev/backend_json.go
  src/control/server/storage/bdev/backend_json_test.go
  src/control/server/storage/bdev/backend_test.go
  src/control/server/storage/bdev/mocks.go
  src/control/server/storage/bdev/provider.go
  src/control/server/storage/faults.go
  src/control/server/storage/mocks.go
  src/control/server/storage/provider.go
  src/control/server/storage/provider_test.go
Labels: forced-landing

#16236 DAOS-16927 pool: Fix upgrade DER_NOTSUPPORTEDs (#15873)
  src/pool/srv_pool.c
Labels: clean-cherry-pick, priority

#16113 DAOS-17178 cart: Implement D_QUOTA_BULKS (#16088)
  src/bio/bio_internal.h
  src/cart/README.env
  src/cart/crt_bulk.c
  src/cart/crt_context.c
  src/cart/crt_hg.c
  src/cart/crt_hg.h
  src/cart/crt_hg_proc.c
  src/cart/crt_init.c
  src/cart/crt_internal_fns.h
  src/cart/crt_internal_types.h
  src/cart/crt_rpc.h
  src/include/cart/types.h
Labels: unclean-cherry-pick, priority

#16208 DAOS-17287 build: Remove separate rpm build for raft (#16094)
  debian/changelog
  utils/rpms/Makefile
  utils/rpms/archive.sh
  utils/rpms/daos.spec
Labels: unclean-cherry-pick, approved-to-merge

#16244 DAOS-17406 cq: use cancel-in-progress for more workflows
  .github/workflows/bash_unit_testing.yml
  .github/workflows/bullseye-coverage.yml
  .github/workflows/ci2.yml
  .github/workflows/landing-builds.yml
  .github/workflows/linting.yml
  .github/workflows/rpm-build-and-test.yml
  .github/workflows/unit-testing.yml
Labels: forced-landing

#16243 SRE-2832 build: unblock Build, Unit tests, Functional test (EL8) stages in FC Lab (#16139)
  Jenkinsfile
  ci/functional/launchable_analysis
  ci/provisioning/post_provision_config.sh
  ci/provisioning/post_provision_config_nodes.sh
  ci/unit/test_nlt.sh
  ci/unit/test_nlt_node.sh
  ftest.sh
  utils/githooks/pre-commit.d/30-Jenkinsfile.sh
  utils/node_local_test.py
Labels: priority

#16223 DAOS-15630 test: tags.py filter tests by tags (#15705)
  src/tests/ftest/tags.py
  utils/githooks/pre-commit.d/73-ftest.sh
Labels: clean-cherry-pick, priority, forced-landing

#16262 DAOS-17423 test: disable test_dfuse_find_perf in CI
  src/tests/ftest/dfuse/find.py
Labels: forced-landing

#16239 DAOS-17147 dfs: set dfs chunk size to a multiple of full stripe acces…
  src/client/dfs/cont.c
  src/include/daos/object.h
  src/object/obj_class.c
Labels: clean-cherry-pick, priority

#16173 DAOS-17347 dtx: retry DTX resync for recoverable network failure
  src/dtx/dtx_internal.h
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
Labels: priority

#16267 DAOS-17423 test: disable test_dfuse_find_perf in CI (#16262)
  src/tests/ftest/dfuse/find.py
Labels: clean-cherry-pick, priority, forced-landing

#16250 DAOS-15947 control: Unit test for PoolRanksReq type conversion
  src/control/lib/control/pool_test.go
Labels: control-plane, priority, forced-landing

#16265 DAOS-17120 test: replace pcmd with run_remote (#15915)
  src/tests/ftest/control/dmg_storage_scan_scm.py
  src/tests/ftest/control/log_entry.py
  src/tests/ftest/control/ssd_socket.py
  src/tests/ftest/control/super_block_versioning.py
  src/tests/ftest/control/version.py
  src/tests/ftest/daos_racer/parallel.py
  src/tests/ftest/deployment/agent_failure.py
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/dfuse/posix_stat.py
  src/tests/ftest/erasurecode/truncate.py
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/recovery/container_list_consolidation.py
  src/tests/ftest/recovery/ddb.py
  src/tests/ftest/server/cpu_usage.py
  src/tests/ftest/server/daos_server_dump.py
  src/tests/ftest/util/agent_utils.py
  src/tests/ftest/util/cpu_utils.py
  src/tests/ftest/util/daos_racer_utils.py
  src/tests/ftest/util/ddb_utils.py
  src/tests/ftest/util/general_utils.py
  src/tests/ftest/util/job_manager_utils.py
  src/tests/ftest/util/macsio_util.py
  src/tests/ftest/util/performance_test_base.py
  src/tests/ftest/util/run_utils.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/soak_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#16108 DAOS-17151 object: yield if too many in-flight bulk transfer - b26
  src/object/srv_obj.c
Labels: clean-cherry-pick, release-2.6.4

#16005 DAOS-13700 test: use self.random in most cases
  src/tests/ftest/container/boundary.py
  src/tests/ftest/deployment/disk_failure.py
  src/tests/ftest/dfuse/find.py
  src/tests/ftest/harness/config.py
  src/tests/ftest/harness/config.yaml
  src/tests/ftest/nvme/pool_exclude.py
  src/tests/ftest/osa/offline_drain.py
  src/tests/ftest/osa/offline_parallel_test.py
  src/tests/ftest/osa/offline_reintegration.py
  src/tests/ftest/osa/online_parallel_test.py
  src/tests/ftest/osa/online_reintegration.py
  src/tests/ftest/pool/create_all_vm.py
  src/tests/ftest/pool/management_race.py
  src/tests/ftest/rebuild/mdtest.py
  src/tests/ftest/server/replay.py
  src/tests/ftest/util/apricot/apricot/test.py
  src/tests/ftest/util/daos_io_conf.py
  src/tests/ftest/util/pool_security_test_base.py
  src/tests/ftest/util/server_utils.py
  src/tests/ftest/util/slurm_utils.py
  src/tests/ftest/util/soak_test_base.py
  src/tests/ftest/util/soak_utils.py
Labels: forced-landing

#16185 DAOS-17353 object: reduce noisy warning for DTX refresh - b26
  src/object/cli_obj.c
  src/object/obj_internal.h
  src/object/obj_rpc.h
  src/object/obj_tx.c
  src/object/srv_obj.c
Labels: forced-landing, release-2.6.4

#16280 DAOS-17278 build: Update golang.org/x/net to v0.37.0 (#16128)
  site_scons/site_tools/go_builder.py
  src/control/go.mod
  src/control/go.sum
  src/control/run_go_tests.sh
  src/control/vendor/golang.org/x/net/context/context.go
  src/control/vendor/golang.org/x/net/context/go17.go
  src/control/vendor/golang.org/x/net/context/go19.go
  src/control/vendor/golang.org/x/net/context/pre_go17.go
  src/control/vendor/golang.org/x/net/context/pre_go19.go
  src/control/vendor/golang.org/x/net/http2/config.go
  src/control/vendor/golang.org/x/net/http2/config_go124.go
  src/control/vendor/golang.org/x/net/http2/http2.go
  src/control/vendor/golang.org/x/net/http2/server.go
  src/control/vendor/golang.org/x/net/http2/transport.go
  src/control/vendor/golang.org/x/net/http2/write.go
  src/control/vendor/golang.org/x/net/internal/httpcommon/ascii.go
  src/control/vendor/golang.org/x/net/internal/httpcommon/headermap.go
  src/control/vendor/golang.org/x/net/internal/httpcommon/request.go
  src/control/vendor/golang.org/x/sys/unix/auxv.go
  src/control/vendor/golang.org/x/sys/unix/auxv_unsupported.go
  src/control/vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  src/control/vendor/golang.org/x/sys/unix/syscall_solaris.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  src/control/vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  src/control/vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  src/control/vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  src/control/vendor/golang.org/x/sys/unix/ztypes_linux.go
  src/control/vendor/golang.org/x/sys/windows/dll_windows.go
  src/control/vendor/modules.txt
  utils/cq/words.dict
Labels: forced-landing

#16249 DAOS-17339 control: Avoid starting AdminExcluded ranks
  src/control/cmd/dmg/system.go
  src/control/cmd/dmg/system_test.go
  src/control/common/proto/mgmt/system.pb.go
  src/control/fault/code/codes.go
  src/control/lib/control/mocks.go
  src/control/lib/control/system.go
  src/control/server/faults.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/system/errors.go
  src/control/system/membership.go
  src/control/system/membership_test.go
  src/proto/mgmt/system.proto
  src/tests/ftest/control/dmg_system_start.py
  src/tests/ftest/control/dmg_system_start.yaml
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
Labels: forced-landing

#16282 DAOS-17404 ci: Enable plugin for finding branches (#16234)
  utils/githooks/branches.default
  utils/githooks/find_base.sh
  utils/githooks/get_branch
Labels: clean-cherry-pick, priority, forced-landing, approved-to-merge

#16278 DAOS-17106 cart: Fix floods of swim debug messages
  src/cart/crt_swim.c
Labels: forced-landing

#16175 DAOS-17347 dtx: retry DTX resync for recoverable network failure - b26
  src/dtx/dtx_internal.h
  src/dtx/dtx_resync.c
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
Labels: priority, release-2.6.4

#16288 DAOS-10039 doc: add pool rename and improve pool creation
  docs/admin/pool_operations.md
Labels: release-2.2, priority

#16261 DAOS-15947 docs: Update admin guide dmg system command syntax
  docs/admin/administration.md
  docs/admin/pool_operations.md
Labels: control-plane, priority, doc-only

#16306 DAOS-17461 cq: speedup githook submodule check
  utils/githooks/prepare-commit-msg.d/10-submodule-update-check.py
Labels: forced-landing
