Repository daos-stack/daos, pull requests merged in 2025-09, with the labels that each got.

#16786 DAOS-17942 control: Fix ftest ControlLogEntry by printing updates
  src/pool/srv_pool.c
Labels: forced-landing

#16779 DAOS-17939 common: make pool recreation easily reusable by utilities
  src/include/daos_srv/daos_mgmt_srv.h
  src/include/daos_srv/mgmt_tgt_common.h
  src/mgmt/SConscript
  src/mgmt/mgmt_common.c
  src/mgmt/srv_target.c
  src/pool/srv_pool.c
  src/pool/srv_pool_check.c
  src/pool/srv_target.c
Labels: CR, forced-landing

#16371 DAOS-17345 vos: cap reserved space
  src/vos/vos_space.c
Labels: priority

#16799 DAOS-17950 test: Fix dfuse/daos_build.py test
  src/tests/ftest/dfuse/daos_build.yaml
Labels: forced-landing

#16613 DAOS-17591 object: refresh DTX MBS for case being changed - b26
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/vos/vos_dtx.c
Labels: release-2.6.4

#16761 DAOS-17814 control: Improve dmg storage query usage with no PMem
  src/control/cmd/daos_server/storage_scm.go
  src/control/cmd/daos_server_helper/handler_test.go
  src/control/cmd/dmg/pretty/storage_query.go
  src/control/cmd/dmg/pretty/storage_query_test.go
  src/control/common/proto/mocks.go
  src/control/lib/control/mocks.go
  src/control/server/config/server.go
  src/control/server/config/server_test.go
  src/control/server/ctl_storage.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/ctl_storage_test.go
  src/control/server/instance_storage_rpc.go
  src/control/server/storage/mocks.go
  src/control/server/storage/provider.go
  src/control/server/storage/scm.go
  src/control/server/storage/scm/provider.go
  src/control/server/storage/scm/provider_test.go
Labels: control-plane, forced-landing, go

#16768 DAOS-17472 build: Enable new RPM builds
  .github/workflows/ci2.yml
  Jenkinsfile
  ci/provisioning/post_provision_config_common_functions.sh
  ci/rpm/build_deps.sh
  ci/rpm/build_success.sh
  ci/rpm/gen_rpms.sh
  ci/rpm/install_deps.sh
  ci/unit/required_packages.sh
  docs/dev/development.md
  site_scons/components/__init__.py
  site_scons/prereq_tools/base.py
  src/control/SConscript
  src/control/build/config.go
  src/control/build/config_test.go
  src/control/build/variables.go
  src/control/cmd/daos_agent/main.go
  src/control/cmd/daos_server/config.go
  src/control/lib/control/config.go
  src/control/lib/control/config_test.go
  utils/build.config
  utils/docker/Dockerfile.el.8
  utils/docker/Dockerfile.el.9
  utils/docker/Dockerfile.leap.15
  utils/docker/Dockerfile.ubuntu
  utils/rpms/argobots.sh
  utils/rpms/build_packages.sh
  utils/rpms/create_local_repo.sh
  utils/rpms/daos.sh
  utils/rpms/daos.spec
  utils/rpms/fpm_common.sh
  utils/rpms/fused.sh
  utils/rpms/isa-l.sh
  utils/rpms/isa-l_crypto.sh
  utils/rpms/libfabric.sh
  utils/rpms/mercury.sh
  utils/rpms/package_info.sh
  utils/rpms/package_version.sh
  utils/rpms/pmdk.sh
  utils/rpms/spdk.sh
  utils/scripts/create_spdk_pkgconfig.sh
  utils/scripts/install-el8.sh
  utils/scripts/install-el9.sh
  utils/scripts/install-leap15.sh
  utils/sl/setup_local.sh
Labels: forced-landing

#16854 DAOS-17472 build: Fix leap package name
  utils/rpms/daos.spec
  utils/rpms/package_info.sh
Labels: forced-landing

#16740 DAOS-17905 object: fixes excessive waiting time in system xstream dur…
  src/object/srv_obj_migrate.c
Labels: priority

#16870 DAOS-17758 test: add some sleep in dfuse mtime check to accomodate CI…
  src/tests/suite/dfuse_test.c
Labels: clean-cherry-pick

#16686 DAOS-17831 control: Add dmg pool rebuild start|stop cmds
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/json_test.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/control/common/proto/mgmt/addons.go
  src/control/common/proto/mgmt/mgmt.pb.go
  src/control/common/proto/mgmt/mgmt_grpc.pb.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/drpc.go
  src/control/security/grpc_authorization.go
  src/control/security/grpc_authorization_test.go
  src/control/server/mgmt_pool.go
  src/include/daos/drpc_modules.h
  src/mgmt/drpc_internal.h
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv.c
  src/mgmt/srv_drpc.c
  src/mgmt/tests/mocks.c
  src/mgmt/tests/mocks.h
  src/mgmt/tests/srv_drpc_tests.c
  src/proto/mgmt/mgmt.proto
  src/proto/mgmt/pool.proto
Labels: control-plane, CR, forced-landing

#16860 DAOS-17820 test: CR Automate Test - Check start corner cases - Single…
  src/tests/ftest/recovery/check_start_corner_case.py
  src/tests/ftest/recovery/check_start_corner_case.yaml
Labels: forced-landing

#16863 DAOS-17982 cq: update GHA ubuntu to Noble
  .github/workflows/ci2.yml
  .github/workflows/landing-builds.yml
Labels: priority, forced-landing

#16873 DAOS-17988 client: Include padding space during memory allocation
  src/gurt/shm_dict.c
Labels: forced-landing

#16583 SRE-3150 test: Add device verification and test summary to launch
  src/tests/ftest/launch.py
  src/tests/ftest/pool/create_all_hw.yaml
  src/tests/ftest/server/storage_tiers.py
  src/tests/ftest/server/storage_tiers.yaml
  src/tests/ftest/util/collection_utils.py
  src/tests/ftest/util/command_utils_base.py
  src/tests/ftest/util/launch_utils.py
  src/tests/ftest/util/server_utils_params.py
Labels: forced-landing

#16887 DAOS-17997 cq: Update hadoop from 3.4.1 to 3.4.2
  .gitignore
  src/client/java/daos-java/pom.xml
  src/client/java/hadoop-daos/pom.xml
  utils/trivy/.trivyignore
  utils/trivy/trivy.yaml
Labels: priority, forced-landing

#16878 DAOS-17990 cart: Fix deadlines
  src/cart/crt_hg.c
  src/cart/crt_hg_proc.c
  src/cart/crt_rpc.c
  src/cart/crt_rpc.h
Labels: forced-landing

#16857 DAOS-17981 build: Fix CI_BUILD_PACKAGES_ONLY use
  Jenkinsfile
Labels: forced-landing

#16897 DAOS-17497 test: Adjust CR tests for md-on-ssd mode 1
  src/tests/ftest/recovery/check_policy.py
  src/tests/ftest/recovery/check_policy.yaml
  src/tests/ftest/recovery/check_repair.py
  src/tests/ftest/recovery/check_repair.yaml
  src/tests/ftest/recovery/check_start_options.py
  src/tests/ftest/recovery/check_start_options.yaml
  src/tests/ftest/recovery/check_stop.py
  src/tests/ftest/recovery/check_stop.yaml
Labels: forced-landing

#16745 DAOS-17322 ddb: DTX aggregation with ddb
  src/control/cmd/ddb/commands_wrapper.go
  src/control/cmd/ddb/ddb_commands.go
  src/dtx/tests/SConscript
  src/dtx/tests/dts_count.c
  src/dtx/tests/dtx_ut.c
  src/include/daos_srv/vos.h
  src/utils/ddb/ddb.c
  src/utils/ddb/ddb.h
  src/utils/ddb/ddb_commands.c
  src/utils/ddb/ddb_parse.c
  src/utils/ddb/ddb_parse.h
  src/utils/ddb/tests/SConscript
  src/utils/ddb/tests/ddb_cmd_options_tests.c
  src/utils/ddb/tests/ddb_cmocka.h
  src/utils/ddb/tests/ddb_commands_tests.c
  src/utils/ddb/tests/ddb_parse_tests.c
  src/utils/ddb/tests/ddb_test_driver.h
  src/vos/tests/vts_dtx.c
  src/vos/vos_dtx.c
Labels: CR

#16785 DAOS-17823 client: implement LRU cache in shared memory
  src/gurt/SConscript
  src/gurt/shm_alloc.c
  src/gurt/shm_internal.h
  src/gurt/shm_lru.c
  src/gurt/tests/SConscript
  src/gurt/tests/test_shm.c
  src/include/gurt/shm_utils.h
  src/tests/ftest/cart/utest/SConscript
Labels: forced-landing

#16932 Revert "SRE-3150 test: Fix running server storage verification"
  src/tests/ftest/util/collection_utils.py
Labels: forced-landing
