Repository daos-stack/daos, pull requests merged in 2025-05, with the labels that each got.

#16369 DAOS-17541 control: Reduce minimum Go toolchain version (#16365)
  src/control/go.mod
Labels: clean-cherry-pick, priority, release-2.6

#15993 DAOS-17179 test: Fix stop commands with trailing space
  src/tests/ftest/util/daos_core_base.py
Labels: forced-landing

#16399 DAOS-17577 test: Temporarily skip some functional tests by default
  Jenkinsfile
Labels: priority, forced-landing

#16343 DAOS-15947 docs: Update admin guide dmg pool command advice
  docs/admin/administration.md
  docs/admin/pool_operations.md
Labels: priority, forced-landing

#16323 DAOS-15947 docs: Update admin guide dmg system command syntax (#16261)
  docs/admin/administration.md
  docs/admin/pool_operations.md
Labels: forced-landing

#16438 SRE-3035 ci: Set scm param for recordIssues (#16437)
  Jenkinsfile
Labels: forced-landing

#16446 DAOS-16817 test: add some sleep in dfs mtime check to accomodate CI (…
  src/tests/suite/dfs_unit_test.c
Labels: clean-cherry-pick
