Repository daos-stack/daos, pull requests merged in 2025-08, with the labels that each got.

#16451 DAOS-6344 build: move daemon logfiles from /tmp to /var/log/daos
  debian/changelog
  debian/rules
  docs/QSG/qemu-vms.md
  docs/QSG/setup_rhel.md
  docs/QSG/setup_suse.md
  docs/admin/administration.md
  docs/admin/deployment.md
  docs/admin/troubleshooting.md
  src/control/cmd/daos_server/auto_test.go
  src/control/cmd/dmg/auto_test.go
  src/control/lib/control/auto.go
  src/control/server/config/server_test.go
  src/tests/ftest/util/agent_utils_params.py
  utils/config/daos_agent.yml
  utils/config/daos_server.yml
  utils/config/examples/daos_server_local.yml
  utils/config/examples/daos_server_mdonssd.yml
  utils/config/examples/daos_server_tcp.yml
  utils/config/examples/daos_server_ucx.yml
  utils/config/examples/daos_server_verbs.yml
  utils/docker/examples/daos-agent/el8/daos_agent.yml.example
  utils/docker/examples/daos-server/el8/daos_server.yml.example
  utils/docker/vcluster/daos-client/el8/daos_agent.yml.in
  utils/docker/vcluster/daos-server/el8/daos_server.yml.in
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
Labels: forced-landing

#16705 DAOS-17872 build: Tag 2.6.4 rc2
  TAG
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#16711 DAOS-17659 control: Sort dmg pool get-prop output
  src/control/lib/control/pool.go
Labels: forced-landing

#16725 DAOS-17534 dtx: avoid repeatedly adding item into batched commit list
  src/dtx/dtx_common.c
Labels: priority

#16726 DAOS-17534 dtx: avoid repeatedly adding item into batched commit list - b26
  src/dtx/dtx_common.c
Labels: priority, release-2.6.4

#16722 DAOS-17877 cq: give create_release.yml write permission (#16708)
  .github/actions/make_release/entrypoint.sh
  .github/workflows/create_release.yml
Labels: clean-cherry-pick, priority, forced-landing, release-2.6.4

#16736 DAOS-17890 test: condense rebuild/basic.py
  src/tests/ftest/rebuild/basic.py
  src/tests/ftest/rebuild/basic.yaml
Labels: forced-landing

#16744 DAOS-17895 control: Fix TestPoolCommands failures
  src/control/lib/control/pool.go
Labels: forced-landing

#16776 Revert "DAOS-17868 common: Reclaim empty slabs under memory pressure …
  src/common/dav_v2/heap.c
  src/vos/tests/vts_wal.c
Labels: priority, forced-landing
