Repository daos-stack/daos, pull requests merged in 2025-02, with the labels that each got.

#15824 DAOS-16257 mercury: Update build.config to include ep flush patch.
  utils/build.config
Labels: release-2.6.3

#15811 DAOS-16312 control: Always use --force for dmg system stop
  src/control/cmd/dmg/system.go
  src/control/cmd/dmg/system_test.go
  src/control/lib/control/system.go
  src/control/lib/control/system_test.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/tests/ftest/control/log_entry.py
  utils/node_local_test.py
Labels: control-plane, unclean-cherry-pick, forced-landing, usability, release-2.6.3

#15833 DAOS-16990 cart: workaround to CXI init errors with retrying HG init
  src/cart/README.env
  src/cart/crt_hg.c
  src/cart/crt_init.c
  src/cart/crt_internal_types.h
Labels: forced-landing

#15837 DAOS-16990 cart: workaround to CXI init errors with retrying HG init …
  src/cart/README.env
  src/cart/crt_hg.c
  src/cart/crt_init.c
  src/cart/crt_internal_types.h
Labels: forced-landing

#15832 DAOS-16768 pool: larger ABT ULT stack sizes
  src/container/srv_target.c
  src/pool/srv_target.c
Labels: unclean-cherry-pick

#15829 DAOS-16362 pydaos: increase torch ftest timeout
  src/tests/ftest/pytorch/dataset.yaml
Labels: forced-landing

#15779 DAOS-16969 test: Reduce cleanup operations for metadata.py test
  src/tests/ftest/server/metadata.py
  src/tests/ftest/server/metadata.yaml
  src/tests/ftest/util/command_utils.py
Labels: forced-landing

#15752 DAOS-16951 dtx: add invalid records discard capability
  debian/changelog
  debian/daos-server-tests.install
  src/control/cmd/ddb/commands_wrapper.go
  src/control/cmd/ddb/ddb_commands.go
  src/dtx/tests/SConscript
  src/dtx/tests/dts_discard_invalid.c
  src/dtx/tests/dts_structs.c
  src/dtx/tests/dtx_tests.c
  src/dtx/tests/dtx_ut.c
  src/dtx/tests/sched_mock.c
  src/include/daos_srv/evtree.h
  src/include/daos_srv/vos.h
  src/utils/ddb/ddb.c
  src/utils/ddb/ddb.h
  src/utils/ddb/ddb_commands.c
  src/utils/ddb/ddb_vos.c
  src/utils/ddb/ddb_vos.h
  src/utils/ddb/tests/SConscript
  src/utils/ddb/tests/ddb_cmd_options_tests.c
  src/utils/ddb/tests/ddb_commands_tests.c
  src/utils/ddb/tests/ddb_ut.c
  src/utils/ddb/tests/ddb_vos_ut.c
  src/vos/evtree.c
  src/vos/ilog.c
  src/vos/ilog.h
  src/vos/ilog_internal.h
  src/vos/tests/SConscript
  src/vos/tests/vos_tests.c
  src/vos/tests/vts_common.h
  src/vos/tests/vts_evtree.c
  src/vos/tests/vts_ilog.c
  src/vos/tests/vts_tree.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
  src/vos/vos_tree.c
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
  utils/utest.yaml
Labels: CR, release-2.6.3

#15847 DAOS-623 ci: enable dependabot for GHA on branch 2.6
  .github/dependabot.yml
Labels: forced-landing

#15868 DAOS-17090 cq: dependabot ignore avocado
  .github/dependabot.yml
Labels: forced-landing

#15857 DAOS-16876 vos: remove DTX record after partial commit
  src/dtx/dtx_resync.c
  src/vos/vos_dtx.c
Labels: priority

#15858 DAOS-16876 vos: remove DTX record after partial commit - b26
  src/dtx/dtx_resync.c
  src/vos/vos_dtx.c
Labels: priority, release-2.6.3

#15882 DAOS-16876 vos: skip DTX record when load partial committed DTX - b26
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
Labels: priority, release-2.6.3

#15879 DAOS-17055 client: add a soft limit of 4k to nr ranges for list-io
  src/client/api/init.c
  src/client/array/dc_array.c
  src/include/daos/array.h
  src/include/daos/common.h
  src/include/daos_array.h
  src/include/daos_fs.h
  src/tests/suite/dfs_unit_test.c
Labels: clean-cherry-pick

#15855 DAOS-17052 test: update expected msg for critical_integration
  src/tests/ftest/deployment/critical_integration.py
Labels: forced-landing

#15889 DAOS-17108 common: suppress io.netty 4.1.115 CVE
  utils/trivy/.trivyignore
Labels: forced-landing

#15890 DAOS-17108 common: suppress io.netty 4.1.115 CVE (#15889)
  utils/trivy/.trivyignore
Labels: priority, approved-to-merge, release-2.6.3

#15874 DAOS-16408 coverity: 2555831 Unused value
  src/vos/vos_obj_cache.c
Labels: forced-landing

#15875 DAOS-16813 test: bump checkpoint duraion
  src/tests/ftest/telemetry/wal_metrics.py
Labels: forced-landing

#15884 DAOS-17045 bio: drain inflight health collecting on teardown
  src/bio/bio_recovery.c
Labels: forced-landing

#15898 DAOS-16733 test: Fix enospace.py ftest limits
  src/tests/ftest/nvme/enospace.yaml
Labels: forced-landing

#15817 DAOS-17002 test: fix rebuild_fio aggregation detection
  src/tests/ftest/erasurecode/rebuild_fio.py
  src/tests/ftest/erasurecode/rebuild_fio.yaml
Labels: forced-landing

#15815 DAOS-16954 common: fix how the embedded value is deleted
  src/common/btree.c
Labels: forced-landing

#15865 DAOS-17087 cart: fix crt_bulk_create() not accepting CRT_BULK_WO
  src/cart/crt_bulk.c
  src/cart/crt_hg.c
Labels: forced-landing

#15568 DAOS-15645 test: create cont with daos instead of API
  src/tests/ftest/checksum/csum_basic.py
  src/tests/ftest/checksum/csum_basic.yaml
  src/tests/ftest/container/api_basic_attribute.py
  src/tests/ftest/container/api_basic_attribute.yaml
  src/tests/ftest/container/basic_snapshot.yaml
  src/tests/ftest/container/destroy.yaml
  src/tests/ftest/container/query_attribute.yaml
  src/tests/ftest/container/query_properties.py
  src/tests/ftest/container/query_properties.yaml
  src/tests/ftest/container/snapshot.yaml
  src/tests/ftest/control/dmg_system_cleanup.yaml
  src/tests/ftest/datamover/obj_small.yaml
  src/tests/ftest/datamover/serial_small.yaml
  src/tests/ftest/dtx/basic.yaml
  src/tests/ftest/erasurecode/offline_rebuild_single.yaml
  src/tests/ftest/erasurecode/online_rebuild_single.yaml
  src/tests/ftest/erasurecode/rank_failure.yaml
  src/tests/ftest/nvme/object.yaml
  src/tests/ftest/object/create_many_dkeys.yaml
  src/tests/ftest/object/fetch_bad_param.yaml
  src/tests/ftest/object/integrity.yaml
  src/tests/ftest/object/open_bad_param.yaml
  src/tests/ftest/object/punch_test.yaml
  src/tests/ftest/object/update_bad_param.yaml
  src/tests/ftest/osa/dmg_negative_test.yaml
  src/tests/ftest/pool/evict.yaml
  src/tests/ftest/rebuild/basic.yaml
  src/tests/ftest/rebuild/cascading_failures.yaml
  src/tests/ftest/rebuild/delete_objects.yaml
  src/tests/ftest/rebuild/read_array.yaml
  src/tests/ftest/recovery/ddb.yaml
  src/tests/ftest/telemetry/dkey_akey_enum_punch.yaml
  src/tests/ftest/util/test_utils_container.py
Labels: forced-landing

#15747 DAOS-16876 vos: Improve error reporting on corruption crash
  src/tests/ftest/util/telemetry_utils.py
  src/vos/evt_priv.h
  src/vos/ilog.c
  src/vos/tests/vts_ilog.c
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_ilog.c
  src/vos/vos_internal.h
  src/vos/vos_obj_index.c
  src/vos/vos_tls.h
Labels: priority

#15901 DAOS-16876 vos: discard invalid DTX when commit or abort - b26
  src/include/daos_srv/evtree.h
  src/tests/ftest/util/telemetry_utils.py
  src/vos/evt_priv.h
  src/vos/evtree.c
  src/vos/ilog.c
  src/vos/tests/vts_ilog.c
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_ilog.c
  src/vos/vos_internal.h
  src/vos/vos_obj_index.c
  src/vos/vos_tls.h
  src/vos/vos_tree.c
Labels: priority, release-2.6.4

#15922 DAOS-17045 bio: drain inflight health collecting on teardown (#15884)
  src/bio/bio_recovery.c
Labels: clean-cherry-pick

#15938 DAOS-16978 vos: fix issue in VOS pool recreation on faulty device rep…
  src/bio/bio_context.c
  src/bio/smd/smd_pool.c
  src/bio/smd/tests/smd_ut.c
  src/include/daos_srv/bio.h
  src/include/daos_srv/smd.h
  src/include/daos_srv/vos_types.h
  src/pool/srv_target.c
  src/utils/ddb/ddb_vos.c
  src/vos/vos_pool.c
Labels: clean-cherry-pick, priority

#15778 DAOS-16111 rebuild: enhance leader update_and_warn_for_slow_engines()
  src/rebuild/rebuild_internal.h
  src/rebuild/srv.c
  src/tests/ftest/cart/util/daos_sys_logscan.py
  src/tests/ftest/daos_test/rebuild.py
  src/tests/ftest/daos_test/rebuild.yaml
  src/tests/suite/daos_rebuild.c
Labels: forced-landing

#15807 DAOS-16464 test: improve online_rebuild_mdtest.py (#15108)
  src/tests/ftest/erasurecode/online_rebuild_mdtest.py
  src/tests/ftest/erasurecode/online_rebuild_mdtest.yaml
  src/tests/ftest/util/ec_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#15931 DAOS-17111 swim: do not trust dead node (#15894)
  src/cart/swim/swim.c
Labels: clean-cherry-pick

#15942 DAOS-16876 dtx: misc fixes for DTX related logic
  src/dtx/dtx_common.c
  src/vos/lru_array.h
  src/vos/vos_dtx.c
Labels: priority

#15941 DAOS-16876 dtx: misc fixes for DTX related logic - b26
  src/dtx/dtx_common.c
  src/vos/lru_array.h
  src/vos/vos_dtx.c
Labels: priority

#15893 DAOS-16824 cart: lower error messages to warn level (#15529)
  src/cart/crt_context.c
  src/cart/crt_hg.c
  src/cart/crt_hg_proc.c
  src/cart/crt_internal.h
  src/cart/crt_register.c
  src/cart/crt_rpc.c
Labels: clean-cherry-pick, release-2.6.3, release-2.6.4

#15966 DAOS-17160 test: conditionally depend on libtest
  src/client/pydaos/raw/daos_api.py
Labels: forced-landing

#15705 DAOS-15630 test: tags.py dump tests associated with tags
  src/tests/ftest/tags.py
  utils/githooks/pre-commit.d/73-ftest.sh
Labels: forced-landing

#15741 DAOS-14426 test: Refactor aggregation/dfuse_space_check.py
  src/tests/ftest/aggregation/dfuse_space_check.py
  src/tests/ftest/aggregation/dfuse_space_check.yaml
Labels: forced-landing

#15974 DAOS-623 cq: CODEOWNERS put pydaos/raw under ftest owners
  .github/CODEOWNERS
Labels: forced-landing

#15972 DAOS-16922 dfuse: Avoid assertion on shutdown
  src/client/dfuse/dfuse_core.c
  src/client/dfuse/dfuse_main.c
Labels: forced-landing
