Repository daos-stack/daos, pull requests merged in 2025-03, with the labels that each got.

#15731 DAOS-6611 control: Enable dmg pool exclude,drain,reint on multiple ranks
  src/common/tests_dmg_helpers.c
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/json_test.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pool_test.go
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/cmd/dmg/pretty/system.go
  src/control/cmd/dmg/pretty/system_test.go
  src/control/cmd/dmg/system.go
  src/control/common/proto/mgmt/system.pb.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/control/system.go
  src/control/lib/control/system_test.go
  src/control/server/faults.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/control/server/mgmt_svc.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/proto/mgmt/system.proto
  src/tests/ftest/deployment/network_failure.py
  src/tests/ftest/deployment/server_rank_failure.py
  src/tests/ftest/deployment/target_failure.py
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#15982 DAOS-10028 test: Update unit test helper
  src/control/cmd/daos_agent/mgmt_rpc_test.go
  src/control/common/test/utils.go
  src/control/lib/daos/api/container_test.go
  src/control/lib/daos/api/pool_test.go
  src/control/lib/daos/api/selftest_test.go
  src/control/lib/daos/api/util.go
  src/control/lib/telemetry/promexp/client_test.go
  src/control/lib/telemetry/telemetry_test.go
  src/control/server/mgmt_system_test.go
Labels: forced-landing

#15970 DAOS-17151 engine: RPC credits for IO chore task
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/dtx/tests/ult_mock.c
  src/engine/srv.c
  src/engine/srv_internal.h
  src/engine/ult.c
  src/include/daos_srv/daos_engine.h
  src/include/daos_srv/dtx_srv.h
  src/tests/ftest/util/telemetry_utils.py
  src/vos/vos_common.c
  src/vos/vos_dtx.c
Labels: priority, forced-landing

#14345 DAOS-15817 test: raise exception for clush job_manager failure
  src/tests/ftest/server/metadata.py
  src/tests/ftest/server/metadata.yaml
  src/tests/ftest/util/job_manager_utils.py
Labels: forced-landing

#15951 DAOS-17137 doc: Complete self_test doc
  docs/admin/performance_tuning.md
Labels: forced-landing, doc-only

#15961 DAOS-17151 engine: RPC credits for IO chore task - b26
  src/dtx/dtx_common.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/dtx/tests/ult_mock.c
  src/engine/srv.c
  src/engine/srv_internal.h
  src/engine/ult.c
  src/include/daos_srv/daos_engine.h
  src/include/daos_srv/dtx_srv.h
  src/tests/ftest/util/telemetry_utils.py
  src/vos/vos_common.c
  src/vos/vos_dtx.c
Labels: priority, release-2.6.3

#15991 DAOS-17153 il: library should populate fstype (#15953)
  src/client/dfuse/pil4dfs/int_dfs.c
  src/include/daos_fs.h
Labels: clean-cherry-pick

#16027 DAOS-17209 test: Handle non-persistent PMEM naming
  src/tests/ftest/util/storage_utils.py
Labels: forced-landing

#16042 DAOS-17209 test: Handle non-persistent PMEM naming (#16027)
  src/tests/ftest/util/storage_utils.py
Labels: clean-cherry-pick, forced-landing

#16049 DAOS-17094 test: auto storage config for daos_server_restart
  src/tests/ftest/server/daos_server_restart.yaml
Labels: forced-landing

#16050 DAOS-17094 test: auto storage config for daos_server_restart
  src/tests/ftest/server/daos_server_restart.yaml
Labels: unclean-cherry-pick, forced-landing

#16003 DAOS-17205 ci: Fix python bandit check
  src/tests/ftest/util/apricot/apricot/test.py
  utils/rpms/daos.spec
Labels: forced-landing

#16020 DAOS-623 ci: Simplify the pull request template (#15969)
  .github/pull_request_template.md
Labels: forced-landing

#16046 DAOS-17094 pool: deep stack size for IV ULT - b26
  src/pool/srv_iv.c
Labels: clean-cherry-pick, release-2.6.3

#16053 DAOS-17106 swim: Never change self_id
  src/cart/crt_swim.c
  src/cart/swim/swim.c
  src/tests/ftest/cart/test_swim_emu.c
Labels: clean-cherry-pick

#15553 DAOS-16845 test: update tests to use check_free_space
  src/tests/ftest/aggregation/dfuse_space_check.py
  src/tests/ftest/container/multiple_delete.py
  src/tests/ftest/nvme/enospace.py
  src/tests/ftest/nvme/enospace.yaml
  src/tests/ftest/util/test_utils_pool.py
Labels: forced-landing

#16047 DAOS-17200 tests: avoid data corruption across all replicas
  src/tests/suite/daos_rebuild_simple.c
Labels: forced-landing

#15979 DAOS-16936 dtx: rank range based DTX hints for coll_punch
  src/dtx/dtx_coll.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos/dtx.h
  src/include/daos_srv/dtx_srv.h
  src/object/obj_rpc.c
  src/object/srv_coll.c
Labels: priority

#16081 DAOS-17271 pool: Fix handle_event -DER_NONEXISTs
  src/pool/srv_pool.c
Labels: forced-landing

#15934 DAOS-17134 client: Add delay for retrying IO
  src/object/cli_obj.c
Labels: forced-landing

#15892 DAOS-16898 cq: support user bash in githooks (#15648)
  utils/cq/check_update_copyright.sh
  utils/githooks/find_base.sh
  utils/githooks/git-version.sh
  utils/githooks/hook_base.sh
  utils/githooks/pre-commit
  utils/githooks/pre-commit.d/10-update-copyright.sh
  utils/githooks/pre-commit.d/20-codespell.sh
  utils/githooks/pre-commit.d/30-Jenkinsfile.sh
  utils/githooks/pre-commit.d/40-yamllint.sh
  utils/githooks/pre-commit.d/50-clang-format.sh
  utils/githooks/pre-commit.d/60-gofmt.sh
  utils/githooks/pre-commit.d/70-isort.sh
  utils/githooks/pre-commit.d/71-flake.sh
  utils/githooks/pre-commit.d/72-pylint.sh
  utils/githooks/pre-commit.d/73-ftest.sh
  utils/githooks/prepare-commit-msg
  utils/rpms/packaging/get_release_branch
Labels: unclean-cherry-pick, priority, forced-landing

#15975 DAOS-16936 dtx: rank range based DTX hints for coll_punch - b26
  src/dtx/dtx_coll.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos/dtx.h
  src/include/daos_srv/dtx_srv.h
  src/object/cli_mod.c
  src/object/obj_rpc.c
  src/object/srv_coll.c
Labels: priority, release-2.6.3

#16090 DAOS-17271 pool: Fix handle_event -DER_NONEXISTs (#16081)
  src/pool/srv_pool.c
Labels: clean-cherry-pick, priority

#15799 DAOS-16312 control: Always use --force for dmg system stop
  src/control/cmd/dmg/system.go
  src/control/cmd/dmg/system_test.go
  src/control/lib/control/system.go
  src/control/lib/control/system_test.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/tests/ftest/control/log_entry.py
  utils/node_local_test.py
Labels: control-plane, usability

#16129 DAOS-17167 build: Tag 2.6.3 rc4
  TAG
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#16116 DAOS-17111 cart: Use only swim ctx for outage (#15924)
  src/cart/crt_hg_proc.c
  src/cart/crt_internal_types.h
  src/cart/crt_swim.c
Labels: clean-cherry-pick

#16126 DAOS-17317 control: Quiet misleading server error
  src/control/server/mgmt_check.go
Labels: forced-landing

#16048 DAOS-15947 control: Enable replacement of rank after loss of metadata
  src/control/cmd/dmg/storage.go
  src/control/common/proto/ctl/storage.pb.go
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/svc.pb.go
  src/control/fault/code/codes.go
  src/control/lib/control/storage.go
  src/control/lib/control/system.go
  src/control/lib/hostlist/numericlist.go
  src/control/lib/hostlist/numericlist_test.go
  src/control/lib/ranklist/ranklist.go
  src/control/lib/ranklist/ranklist_test.go
  src/control/server/ctl_storage_rpc.go
  src/control/server/ctl_storage_rpc_test.go
  src/control/server/faults.go
  src/control/server/harness.go
  src/control/server/instance.go
  src/control/server/instance_storage.go
  src/control/server/instance_test.go
  src/control/server/mgmt_pool_test.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/control/system/faults.go
  src/control/system/membership.go
  src/control/system/membership_test.go
  src/control/system/mocks.go
  src/control/system/pool.go
  src/control/system/raft/database_test.go
  src/control/system/raft/raft_recovery_test.go
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/proto/ctl/storage.proto
  src/proto/mgmt/svc.proto
Labels: control-plane, usability
