Repository daos-stack/daos, pull requests merged in 2025-01, with the labels that each got.

#15678 DAOS-16917 cq: update copyright for HPE
  utils/cq/check_update_copyright.sh
Labels: forced-landing

#15632 DAOS-16881 control: Fix daos_server scm prep for single missing ns
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/ipmctl_test.go
  src/control/server/storage/scm/mocks.go
  src/control/server/storage/scm/ndctl.go
Labels: bug, control-plane

#15688 DAOS-16500 build: Move to Leap 15.6 (#15561)
  Jenkinsfile
  ci/parse_ci_envs.sh
  utils/rpms/daos.rpmlintrc
  utils/rpms/daos.spec
  utils/rpms/packaging/Makefile_distro_vars.mk
  utils/scripts/helpers/repo-helper-leap15.sh
Labels: unclean-cherry-pick, priority, forced-landing

#15684 DAOS-16500 test: Update Functional on Leap 15.6 stage
  Jenkinsfile
Labels: priority

#15655 DAOS-15677 cq: add copyright GHA and remove required-githooks (#15552)
  .github/workflows/linting.yml
  Jenkinsfile
  utils/cq/check_update_copyright.sh
  utils/githooks/commit-msg
  utils/githooks/commit-msg.d/10-watermark.py
  utils/githooks/find_base.sh
  utils/githooks/hook_base.sh
  utils/githooks/pre-commit.d/10-update-copyright
  utils/githooks/pre-commit.d/10-update-copyright.sh
  utils/githooks/pre-commit.d/30-Jenkinsfile.sh
  utils/githooks/pre-commit.d/50-clang-format.sh
  utils/githooks/pre-commit.d/71-flake.sh
  utils/githooks/pre-commit.d/72-pylint.sh
  utils/githooks/pre-commit.d/73-ftest.sh
Labels: unclean-cherry-pick, priority, forced-landing, release-2.6.3

#15686 DAOS-16917 cq: update copyright for HPE (#15678)
  utils/cq/check_update_copyright.sh
Labels: clean-cherry-pick, priority, forced-landing

#15658 DAOS-16876 vos: set cont parameter when deregister modification from DTX - b26
  src/vos/tests/vts_aggregate.c
  src/vos/vos_dtx.c
  src/vos/vos_gc.c
  src/vos/vos_obj.c
  src/vos/vos_obj_index.c
Labels: unclean-cherry-pick, release-2.6.3

#15512 DAOS-16477 mgmt: return suspect engines for pool healthy query (#15458)
  docs/admin/pool_operations.md
  src/control/cmd/daos/health.go
  src/control/cmd/daos/pool.go
  src/control/cmd/daos/pretty/health.go
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/common/proto/ctl/storage_nvme.pb.go
  src/control/common/proto/ctl/support.pb.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/common/proto/mgmt/svc.pb.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool.go
  src/control/lib/daos/pool_test.go
  src/include/daos_pool.h
  src/include/daos_srv/pool.h
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_pool.c
  src/mgmt/svc.pb-c.c
  src/mgmt/svc.pb-c.h
  src/mgmt/tests/mocks.c
  src/mgmt/tests/mocks.h
  src/mgmt/tests/srv_drpc_tests.c
  src/pool/srv_cli.c
  src/proto/mgmt/pool.proto
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/ftest/control/dmg_pool_query_ranks.yaml
  src/tests/ftest/util/dmg_utils.py
  src/tests/ftest/util/dmg_utils_base.py
  src/tests/ftest/util/server_utils_params.py
  src/tests/ftest/util/test_utils_pool.py
Labels: priority

#15692 DAOS-16830 pool: Allow setting DAOS_POOL_RF to 0 (#15564)
  docs/admin/env_variables.md
  src/pool/srv.c
Labels: clean-cherry-pick, priority, forced-landing, approved-to-merge

#15701 DAOS-16881 control: Fix daos_server scm prep for single missing ns (#…
  src/control/server/storage/scm/ipmctl.go
  src/control/server/storage/scm/ipmctl_test.go
  src/control/server/storage/scm/mocks.go
  src/control/server/storage/scm/ndctl.go
Labels: control-plane, unclean-cherry-pick, priority, forced-landing

#15681 DAOS-16639 object: fix assertion (#15329)
  src/object/srv_ec_aggregate.c
Labels: priority

#15474 DAOS-16386 utils: Add DDB Feature and RM_POOL Support (#15062)
  src/bio/bio_xstream.c
  src/control/cmd/ddb/command_completers.go
  src/control/cmd/ddb/commands_wrapper.go
  src/control/cmd/ddb/ddb_commands.go
  src/control/cmd/ddb/main.go
  src/dtx/dtx_resync.c
  src/include/daos_srv/pool.h
  src/include/daos_srv/vos.h
  src/include/daos_srv/vos_types.h
  src/pool/srv_target.c
  src/utils/ddb/ddb.c
  src/utils/ddb/ddb.h
  src/utils/ddb/ddb_commands.c
  src/utils/ddb/ddb_main.c
  src/utils/ddb/ddb_printer.c
  src/utils/ddb/ddb_vos.c
  src/utils/ddb/ddb_vos.h
  src/utils/ddb/tests/ddb_commands_tests.c
  src/utils/ddb/tests/ddb_main_tests.c
  src/utils/ddb/tests/ddb_parse_tests.c
  src/utils/ddb/tests/ddb_test_driver.c
  src/utils/ddb/tests/ddb_test_driver.h
  src/utils/ddb/tests/ddb_vos_tests.c
  src/vos/vos_pool.c
Labels: unclean-cherry-pick, priority, forced-landing, release-2.6.2

#15715 DAOS-16925 cart: Add memcheck suppression for tsan::MemoryAccessRange
  src/cart/utils/memcheck-cart.supp
Labels: forced-landing

#15693 DAOS-16872 cq: Bump GHA versions
  .github/workflows/bullseye-coverage.yml
  .github/workflows/ci2.yml
  .github/workflows/landing-builds.yml
  .github/workflows/linting.yml
  .github/workflows/ossf-scorecard.yml
  .github/workflows/pr-metadata.yml
  .github/workflows/rpm-build-and-test-report.yml
  .github/workflows/rpm-build-and-test.yml
  .github/workflows/trivy.yml
Labels: unclean-cherry-pick, priority, forced-landing

#15716 DAOS-16477 pool: Rename Suspect state to Dead
  docs/admin/pool_operations.md
  docs/admin/troubleshooting.md
  src/control/cmd/daos/health.go
  src/control/cmd/daos/pool.go
  src/control/cmd/daos/pretty/health.go
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/common/proto/logging.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool.go
  src/control/lib/daos/pool_test.go
  src/include/daos_pool.h
  src/include/daos_srv/pool.h
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/srv_internal.h
  src/mgmt/srv_pool.c
  src/mgmt/tests/mocks.c
  src/mgmt/tests/mocks.h
  src/mgmt/tests/srv_drpc_tests.c
  src/pool/srv_cli.c
  src/proto/mgmt/pool.proto
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/ftest/util/test_utils_pool.py
Labels: unclean-cherry-pick, priority

#15649 DAOS-16897 object: add N+3 EC object class
  src/include/daos_obj_class.h
  src/object/obj_class_def.c
  src/object/obj_internal.h
  src/tests/ftest/erasurecode/aggregation.yaml
  src/tests/ftest/erasurecode/cell_size.yaml
  src/tests/ftest/erasurecode/ior_smoke.yaml
  src/tests/ftest/erasurecode/mdtest_smoke.yaml
  src/tests/ftest/erasurecode/multiple_rank_failure.yaml
  src/tests/ftest/erasurecode/multiple_target_failure.yaml
  src/tests/ftest/erasurecode/offline_rebuild.yaml
  src/tests/ftest/erasurecode/online_rebuild.yaml
  src/tests/ftest/erasurecode/online_rebuild_mdtest.yaml
  src/tests/ftest/ior/hard.yaml
  src/tests/ftest/ior/hard_rebuild.yaml
Labels: priority

#15399 DAOS-16469 dtx: properly handle DTX partial commit - b26
  src/dtx/dtx_coll.c
  src/dtx/dtx_common.c
  src/dtx/dtx_cos.c
  src/dtx/dtx_internal.h
  src/dtx/dtx_rpc.c
  src/dtx/dtx_srv.c
  src/include/daos_srv/vos.h
  src/object/srv_obj.c
  src/utils/ddb/ddb_vos.c
  src/utils/ddb/tests/ddb_test_driver.c
  src/vos/tests/vts_dtx.c
  src/vos/tests/vts_io.c
  src/vos/tests/vts_mvcc.c
  src/vos/tests/vts_pm.c
  src/vos/vos_common.c
  src/vos/vos_dtx.c
  src/vos/vos_internal.h
  src/vos/vos_io.c
  src/vos/vos_obj.c
Labels: priority

#15551 DAOS-7485 control: Implement system reint to act on all pools
  src/control/cmd/dmg/command_test.go
  src/control/cmd/dmg/json_test.go
  src/control/cmd/dmg/pool.go
  src/control/cmd/dmg/pretty/system.go
  src/control/cmd/dmg/pretty/system_test.go
  src/control/cmd/dmg/system.go
  src/control/cmd/dmg/system_test.go
  src/control/common/proto/mgmt/addons.go
  src/control/common/proto/mgmt/mgmt.pb.go
  src/control/common/proto/mgmt/mgmt_grpc.pb.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/common/proto/mgmt/system.pb.go
  src/control/drpc/modules.go
  src/control/lib/control/pool.go
  src/control/lib/control/system.go
  src/control/lib/control/system_test.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/control/server/mgmt_svc.go
  src/control/server/mgmt_system.go
  src/control/server/mgmt_system_test.go
  src/include/daos/drpc_modules.h
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv.c
  src/mgmt/srv_drpc.c
  src/mgmt/tests/srv_drpc_tests.c
  src/proto/mgmt/mgmt.proto
  src/proto/mgmt/pool.proto
  src/proto/mgmt/system.proto
Labels: control-plane, forced-landing

#15733 DAOS-16868 bio: Skip LED reset on absent bdev (#15718)
  src/bio/bio_device.c
Labels: bug, clean-cherry-pick, forced-landing

#15730 DAOS-16897 object: add N+3 EC object class (#15649)
  src/include/daos_obj_class.h
  src/object/obj_class_def.c
  src/object/obj_internal.h
  src/tests/ftest/erasurecode/aggregation.yaml
  src/tests/ftest/erasurecode/cell_size.yaml
  src/tests/ftest/erasurecode/ior_smoke.yaml
  src/tests/ftest/erasurecode/mdtest_smoke.yaml
  src/tests/ftest/erasurecode/multiple_rank_failure.yaml
  src/tests/ftest/erasurecode/multiple_target_failure.yaml
  src/tests/ftest/erasurecode/offline_rebuild.yaml
  src/tests/ftest/erasurecode/online_rebuild.yaml
  src/tests/ftest/erasurecode/online_rebuild_mdtest.yaml
  src/tests/ftest/ior/hard.yaml
  src/tests/ftest/ior/hard_rebuild.yaml
Labels: clean-cherry-pick, priority

#15739 DAOS-16958 ci: increase timeout for Unit Test with memcheck
  Jenkinsfile
Labels: forced-landing

#15665 DAOS-16878 pool: Reduce unexpected DER_NO_SERVICEs
  src/pool/srv_pool.c
Labels: forced-landing

#15729 DAOS-16943 rebuild: check DAOS_REBUILD ENV for restart
  src/pool/srv_pool.c
  src/rebuild/srv.c
Labels: clean-cherry-pick

#15764 DAOS-16973 cq: fix codespell warnings
  src/control/server/mgmt_system.go
  src/dtx/tests/dts_local_rdb.c
  src/gurt/examples/telem_producer_example.c
  src/vea/vea_internal.h
Labels: forced-landing

#15755 DAOS-15698 test: Update the reset faulty device logic for nvme_utils.…
  src/tests/ftest/util/nvme_utils.py
Labels: clean-cherry-pick, priority, forced-landing

#15765 DAOS-16973 cq: fix codespell warnings (#15764)
  src/control/server/mgmt_system.go
  src/dtx/tests/dts_local_rdb.c
  src/gurt/examples/telem_producer_example.c
  src/vea/vea_internal.h
Labels: unclean-cherry-pick, forced-landing, approved-to-merge

#15695 DAOS-16209 control: Add MD-on-SSD resp flag for display mode
  src/bio/SConscript
  src/control/cmd/daos/pretty/pool.go
  src/control/cmd/daos/pretty/pool_test.go
  src/control/cmd/dmg/pretty/pool.go
  src/control/cmd/dmg/pretty/pool_test.go
  src/control/common/proto/mgmt/mgmt.pb.go
  src/control/common/proto/mgmt/mgmt_grpc.pb.go
  src/control/common/proto/mgmt/pool.pb.go
  src/control/common/proto/mgmt/system.pb.go
  src/control/lib/control/pool.go
  src/control/lib/control/pool_test.go
  src/control/lib/daos/pool.go
  src/control/server/mgmt_pool.go
  src/control/server/mgmt_pool_test.go
  src/mgmt/pool.pb-c.c
  src/mgmt/pool.pb-c.h
  src/mgmt/srv_drpc.c
  src/mgmt/tests/SConscript
  src/proto/mgmt/pool.proto
  src/tests/ftest/control/dmg_pool_query_test.py
  src/tests/ftest/pool/list_verbose.py
  src/tests/ftest/util/dmg_utils.py
Labels: control-plane, forced-landing, meta-on-ssd

#15775 DAOS-16878 pool: Reduce unexpected DER_NO_SERVICEs (#15665)
  src/pool/srv_pool.c
Labels: clean-cherry-pick

#15787 DAOS-16989 build: tag 2.6.3-rc1
  TAG
  VERSION
  debian/changelog
  utils/rpms/daos.spec
Labels: forced-landing

#15757 DAOS-15136 client: Switch to using libfused (#14077)
  debian/control
  site_scons/components/__init__.py
  site_scons/prereq_tools/base.py
  src/client/dfuse/SConscript
  src/client/dfuse/dfuse.h
  src/client/dfuse/dfuse_fuseops.c
  src/client/dfuse/dfuse_main.c
  src/client/dfuse/dfuse_thread.c
  utils/build.config
  utils/cq/words.dict
  utils/rpms/daos.spec
Labels: unclean-cherry-pick

#15727 DAOS-16931 container: fix the oid iv check for same request
  src/container/oid_iv.c
  src/container/srv_internal.h
Labels: priority

#15720 DAOS-16931 container: fix oid iv race with using invalid on update pt…
  src/container/oid_iv.c
  src/container/srv_internal.h
Labels: clean-cherry-pick, priority

#15801 DAOS-16931 iv: fix the copyright from previous PR
  src/container/oid_iv.c
Labels: priority

#15802 DAOS-16931 iv: fix the copyright from previous PR
  src/container/oid_iv.c
  src/container/srv_internal.h
Labels: priority

#15708 DAOS-15268 test: handle errors in add_del_user
  src/tests/ftest/security/cont_acl.py
  src/tests/ftest/security/cont_acl.yaml
  src/tests/ftest/util/launch_utils.py
  src/tests/ftest/util/pool_security_test_base.py
  src/tests/ftest/util/security_test_base.py
  src/tests/ftest/util/user_utils.py
  utils/cq/words.dict
Labels: forced-landing

#15756 DAOS-13938 dfuse: adjust offset in readdir cache entry list (#15190)
  src/client/dfuse/ops/readdir.c
Labels: priority

#15784 DAOS-16807 client: intercept io_queue_init in libpil4dfs
  src/client/dfuse/pil4dfs/aio.c
Labels: clean-cherry-pick, priority, approved-to-merge

#15770 DAOS-16968 test: Fix pool query tests
  src/tests/ftest/control/dmg_pool_query_ranks.py
  src/tests/ftest/control/dmg_pool_query_test.py
  src/tests/ftest/pool/list_verbose.py
Labels: forced-landing

#15776 DAOS-15604 test: Address intermittent scrubber aggregation test failure. (#15696)
  src/tests/ftest/util/scrubber_test_base.py
Labels: clean-cherry-pick, forced-landing

#15691 DAOS-16362: pydaos.torch checkpointing
  docs/user/pytorch.md
  mkdocs.yml
  requirements-ftest.txt
  src/client/pydaos/torch/Readme.md
  src/client/pydaos/torch/__init__.py
  src/client/pydaos/torch/torch_api.py
  src/client/pydaos/torch/torch_shim.c
  src/tests/ftest/SConscript
  src/tests/ftest/directory_tree.py
  src/tests/ftest/pytorch/checkpoint.py
  src/tests/ftest/pytorch/checkpoint.yaml
  src/tests/ftest/pytorch/dataset.py
  src/tests/ftest/pytorch/dataset.yaml
  src/tests/ftest/util/io_utilities.py
  utils/cq/check_update_copyright.sh
  utils/cq/words.dict
  utils/node_local_test.py
Labels: forced-landing

#15258 DAOS-16153 test: Do not run NLT fi tests for release builds. (#15171)
  Jenkinsfile
  utils/node_local_test.py
Labels: clean-cherry-pick, priority
